### ISSUE TITLE
Font selection dialog in Print Composer failing

### ISSUE THREAD

**Issue by garrettdashnelson** [OSGeo/homebrew-osgeo4mac#100]
Using the UI font dialog box in the Print Composer is failing without changing the font. The "Sample" field does not update with font choice change (font, style, or size), and upon choosing "OK" returns to Print Composer without actuating change. QGIS 2.8.0, Qt 4.8.7., OS X 10.10.4. Here's the relevant console log:

```
7/30/15 4:06:50.436 PM QGIS[89990]: modalSession has been exited prematurely - check for a reentrant call to endModalSession:
```

Font selection on layer appearances in map view is unaffected.

**Comment by dakcarto** [comment]
Hi @garrettdashnelson,

Thanks for reporting. This is unrelated to the Homebrew packaging done in this tap, and is an upstream bug that should be filed via http://issues.qgis.org

**Comment by dakcarto** [comment]
Also, you may want to try and rebuild with the latest `qgis-28` changes, which include a bump to 2.8.3.

**Comment by garrettdashnelson** [comment]
2.8.3 bump fixes the problem. Thanks!
