### ISSUE TITLE
osgeo-gdal bottle missing

### ISSUE THREAD

**Issue by nextstopsun** [OSGeo/homebrew-osgeo4mac#1000]
I'm trying to install osgeo-gdal and I get an error during download:
```
Downloading https://dl.bintray.com/homebrew-osgeo/osgeo-bottles/osgeo-gdal-2.4.1.mojave.bottle.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "osgeo-gdal"
```

**Comment by fjperini** [comment]
@nextstopsun Yes, Bintray is not working due to limitations in the account.
We will migrate the bottles to OSGeo.

**Comment by nextstopsun** [comment]
Meanwhile is there a hack to download this archive to homebrew cache from somewhere?

**Comment by fjperini** [comment]
Could not generate that bottle because those of some dependencies were missing.

**Comment by fjperini** [comment]
You can join to be in more contact: https://join.slack.com/t/homebrew-osgeo4mac/shared_invite/enQtNTY2NjcxOTg4Nzg5LTJjZGIxMGY0MWU5OGEyOTJhYzViNzJiYzJlZGEwZTRiMDc4MzkyY2IzZTA2MDljNDlhM2M5ZGE2OWM0MGQ3Y2I

**Comment by fjperini** [comment]
solved!
