### ISSUE TITLE
Make qgis require osgeo-proj instead of proj

### ISSUE THREAD

**Issue by nextstopsun** [OSGeo/homebrew-osgeo4mac#1001]
I wonder why does `qgis` formula require `proj` and not `osgeo-proj`?

**Comment by fjperini** [comment]
@nextstopsun This will be resolved when we start uploading the new changes.

**Comment by nextstopsun** [comment]
@fjperini sounds promising :) 
Looks like i've broken my install with all that naming changes.

**Comment by fjperini** [comment]
we will try to solve this throughout the day.

you can rename them manually (and link them) and create links to the libraries, as a temporary solution.

**Comment by PeterPetrik** [comment]
https://github.com/OSGeo/homebrew-osgeo4mac/pull/999

**Comment by fjperini** [comment]
I have already built qgis on my machine, I just need to fix something in orfeo. Later I apply all the changes.
![Captura de Pantalla 2019-03-31 a la(s) 12 16 04](https://user-images.githubusercontent.com/21315242/55292646-c0ce8980-53c3-11e9-838f-6a854f252f9b.png)

**Comment by fjperini** [comment]
@nextstopsun the bottles for qgis are ready!
