### ISSUE TITLE
Error: Too many open files @ rb_sysopen

### ISSUE THREAD

**Issue by peteWT** [OSGeo/homebrew-osgeo4mac#1017]
**Please answers the following**

I've... 
- I read
	- [X] the [reporting issues](https://github.com/OSGeo/homebrew-osgeo4mac/docs/reporting-issues)
	- [X] the [troubleshooting](https://github.com/OSGeo/homebrew-osgeo4mac/docs/troubleshooting)
- [X] I checked the documentation and found no answer
- [X] I tried to install after following the suggestions
- [X] I am running the latest version (`brew update` twice?)
- [X] I checked to make sure that this issue has not already been filed
- [X] I uploaded logs: [https://gist.github.com/5875465306c48ce930bcc37e59eb64fb](https://gist.github.com/5875465306c48ce930bcc37e59eb64fb) 

**Describe the bug**

After many package updates and system updates `brew install qgis` fails consistently with the following error:

```$ brew install qgis
Updating Homebrew...
==> Auto-updated Homebrew!
Updated Homebrew from f20e362f5 to 9dc19e832.
Updated 1 tap (osgeo/osgeo4mac).
No changes to formulae.

==> Installing qgis from osgeo/osgeo4mac
Error: Too many open files @ rb_sysopen - /usr/local/var/homebrew/locks/cython.formula.lock
```

**To Reproduce**

`$ brew install qgis`

**Expected behavior**

Install `qgis` formula

**Screenshots**

**Additional context**

Recently updated to OSX Mojave 10.14.4 (18E226)

`brew doctor` output: 

```shell
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have the following deprecated, official taps tapped:
  Homebrew/homebrew-science
  Homebrew/homebrew-versions
Untap them with `brew untap`.

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/extension-functions.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/fakemysql.h
  /usr/local/include/fakepq.h
  /usr/local/include/fakesql.h
  /usr/local/include/itcl.h
  /usr/local/include/itcl2TclOO.h
  /usr/local/include/itclDecls.h
  /usr/local/include/itclInt.h
  /usr/local/include/itclIntDecls.h
  /usr/local/include/itclMigrate2TclCore.h
  /usr/local/include/itclTclIntStubsFcn.h
  /usr/local/include/mysqlStubs.h
  /usr/local/include/odbcStubs.h
  /usr/local/include/pqStubs.h
  /usr/local/include/tcl.h
  /usr/local/include/tclDecls.h
  /usr/local/include/tclOO.h
  /usr/local/include/tclOODecls.h
  /usr/local/include/tclPlatDecls.h
  /usr/local/include/tclThread.h
  /usr/local/include/tclTomMath.h
  /usr/local/include/tclTomMathDecls.h
  /usr/local/include/tdbc.h
  /usr/local/include/tdbcDecls.h
  /usr/local/include/tdbcInt.h
  /usr/local/include/tk.h
  /usr/local/include/tkDecls.h
  /usr/local/include/tkPlatDecls.h

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
  /usr/local/lib/pkgconfig/tcl.pc
  /usr/local/lib/pkgconfig/tk.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libtclstub8.6.a
  /usr/local/lib/libtkstub8.6.a

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  osgeo-insighttoolkit
  proj
  osgeo-vtk
  postgresql
  osgeo-pcl
  pyqt-qt4
  osgeo-pdal
  osgeo-matplotlib
  gdal
  libgeotiff
  ipython
  r
  grass-64
  libspatialite
  osgeo-sip
  sshfs
  osgeo-six
  numpy
  gdal-20
  osgeo-pyqt
  postgis
  osgeo-lastools
  netcdf
  osgeo-qscintilla2
  sip-qt4
  scipy
  qscintilla2-qt4

```

**Logs**

[https://gist.github.com/5875465306c48ce930bcc37e59eb64fb](https://gist.github.com/5875465306c48ce930bcc37e59eb64fb)

**Comment by fjperini** [comment]
@peteWT You need to do `ulimit -n 1024`

Keep in mind that we are working on the tap, in a few hours everything will work normally.

**Comment by peteWT** [comment]
Thanks @fjperini that seems to have solved the file limit issue. It seems though, that the .app cant find proj:

```
$ qgis
dyld: Library not loaded: /usr/local/opt/proj/lib/libproj.13.dylib
  Referenced from: /usr/local/opt/qgis/QGIS.app/Contents/MacOS/QGIS
  Reason: image not found
/usr/local/bin/qgis: line 20: 35837 Abort trap: 6           /usr/local/opt/qgis/QGIS.app/Contents/MacOS/QGIS "$@"
```
Any suggestions? 

Thank you for your quick reply to my last question and for your work on osgeo4mac!

**Comment by fjperini** [comment]
@peteWT I will update qgis! #1063

**Comment by fjperini** [comment]
@peteWT If problems arise, we will solve it: `brew install osgeoqgis`

**Comment by peteWT** [comment]
Thanks @fjperini the app now loads from command line!!  but linking to Applications fails:

```
$ ln -Fs `find $(brew --prefix) -name "QGIS.app"` /Applications/QGIS.app
ln: /Applications/QGIS.app: No such file or directory 
```

**Comment by fjperini** [comment]
this is more advisable

```
qgis_location=$(find $(brew --prefix)/Cellar/osgeo-qgis/ -name "3.*" -print -quit)/QGIS.app

osascript -e 'tell application "Finder"' -e 'make new alias to file (posix file "'$qgis_location'") at (posix file "/Applications")' -e 'end tell'
```

I'll check the other.

**Comment by fjperini** [comment]
@peteWT I hope you serve the above. we close this issue

**Comment by songololo** [comment]
Just an FYI that I'm running into the same issue on the latest / current formula.

Fixed with `ulimit -n 1024`, though I'm curious if this will be necessary for future installs?

**Comment by mattfack** [comment]
Agree with songololo

**Comment by peteWT** [comment]
Also re: linking the QGIS.app
Running @fjperini  [script](https://github.com/OSGeo/homebrew-osgeo4mac/issues/1017#issuecomment-479600353) 

```
$ osascript -e 'tell application "Finder"' -e 'make new alias to file (posix file "'$qgis_location'") at (posix file "/Applications")' -e 'end tell'

24:143: execution error: Not authorized to send Apple events to Finder. (-1743)
```

**Comment by eldang** [comment]
I ran into this again today with osgeo-qgis-ltr, and none of the workarounds I could find with ulimit or sysctl worked.  osgeo-qgis was able to install without the too many files message.

**Comment by zbeekman** [comment]
I opened #1198 with a few additional details. `ulimit -n 1024` seems to have fixed it. The formula is very complicated, and uses some deprecated functionality. A `brew audit qgis3` would probably yield some good advice that may resolve this issue.

**Comment by mikebeaton** [comment]
I've just hit this issue when installing `qemu` (to get version 8) from scratch, as the first package installed by `brew`, with all its dependencies. Same problem on both Fedora and Ubuntu. In this case re-running the install picks up where it stopped and completes without needing `ulimit -n 1024`.
