### ISSUE TITLE
mapnik not found proj4

### ISSUE THREAD

**Issue by winsento** [OSGeo/homebrew-osgeo4mac#1022]
Mapnik can't find Proj4
`brew install osgeo-mapnik` 
and `mapnik-config --proj-lib`  is empty.

osgeo-proj installed and linked, brew-doctor is empty.

**Steps to reproduce the behavior:**
If install in interactive mode `brew install osgeo-mapnik -i` i can see what mapnik could not find PROJ4

![image](https://user-images.githubusercontent.com/2316328/55195880-eccced80-51be-11e9-8d3d-d2ba7b1da8c0.png)

**Comment by fjperini** [comment]
@winsento I will update this in a few hours.

**Comment by fjperini** [comment]
I will add `-DACCEPT_USE_OF_DEPRECATED_PROJ_API_H=1` to CFLAGS to avoid a compilation error, but we must wait for a mapnik update.

https://github.com/mapnik/mapnik/issues/4036

**Comment by fjperini** [comment]
it will be used pro j5 for a time.
The problem in HS is external to this tap.
