### ISSUE TITLE
osgeo-postgis without osgeo-postgresql

### ISSUE THREAD

**Issue by alazarolop** [OSGeo/homebrew-osgeo4mac#1028]
Hi,

This is not a proper bug, but a question about `osgeo-postgis` and `osgeo-postgresql`. I tried to upgrade PostGIS as I saw it was a bump in a minor version, but then I got a message about uninstalling `postgresql` core version in favour of `osgeo-postgresql` among other packages. 

```shell
osgeo/osgeo4mac/osgeo-postgis 2.5.2_1 -> 2.5.2_5
osgeo-proj: You have other linked versions!

Unlink with brew unlink proj or remove with brew uninstall --ignore-dependencies proj

osgeo-libgeotiff: You have other linked versions!

Unlink with brew unlink libgeotiff or remove with brew uninstall --ignore-dependencies libgeotiff

osgeo-libspatialite: You have other linked versions!

Unlink with brew unlink libspatialite or remove with brew uninstall --ignore-dependencies libspatialite

osgeo-netcdf: You have other linked versions!

Unlink with brew unlink netcdf or remove with brew uninstall --ignore-dependencies netcdf

osgeo-postgresql: You have other linked versions!

Unlink with brew unlink postgresql or remove with brew uninstall --ignore-dependencies postgresql

Error: osgeo-postgis: Unsatisfied requirements failed this build.
```

I understand you are doing a lot of under the hood changes, so I was wondering if there is any advantage in this new formula over core version.
Thank you

**Comment by fjperini** [comment]
@alazarolop For two reasons, core formulas do not work to perform a migration and, since they are common dependencies in most formulas ... we will have more control over when to update.

**Comment by alazarolop** [comment]
@fjperini So would you recommend to proceed and unlink core and link new OSGeo formula? Do the new formula respect the `/usr/local/var/postgres` directory structure? I mean, would we need to take any extra configuration step? 

I once tested a tap that let you run several PostgreSQL versions at the same time (as in Ubuntu), but it then used another directory structure.

**Comment by fjperini** [comment]
@alazarolop I kept the structure for / var, in case something already existed there.

Of course, for example ... we were doing tests to migrate from v10 to v11, and from Postgis v2.4 to v2.5 and it turned out well. We will publish a section on this already.

**Comment by alazarolop** [comment]
@fjperini Perfect! That makes things easier. 

By the way, I took a look at the github.io page and it's quite helpful. I was wondering what kind of help do you need for the support and see if I could fit into it. 
Thank you

**Comment by fjperini** [comment]
@alazarolop I'll write you for the last thing you told me, I just need to update you before.

**Comment by alazarolop** [comment]
Cool! I will keep an eye on your message then. I closed the issue to not to clutter the page now that the main question is clear.
