### ISSUE TITLE
Add formula qgis-210

### ISSUE THREAD

**Issue by Ylannl** [OSGeo/homebrew-osgeo4mac#103]
Would be nice to have a formula for the latest QGIS 2.10 release.

**Comment by pjduplooy** [comment]
Hi 
If you look in the pull requests here and https://github.com/christianurich/homebrew-osgeo4mac/commit/f4358cbe1834a0acd9e704bf1b6cdd50e74b3f1c , there is one

**Comment by Ylannl** [comment]
True, totally missed that.
