### ISSUE TITLE
Horao viewer

### ISSUE THREAD

**Issue by pjduplooy** [OSGeo/homebrew-osgeo4mac#105]
Hi
Anyone want to take a stab at creating a formula for Oslandia's Horao viewer and plugin for QGIS?
Git page is https://github.com/Oslandia/horao

Description and dependencies for ubuntu are at https://github.com/Oslandia/workshop-3d

Deps are cmake, open-scene-graph, boost, lwgeom from postgis, pyqt4, pyqt4-sql, gdal and proj.

Install procedure is also at https://github.com/Oslandia/workshop-3d under Horao

**Comment by nickrobison** [comment]
Unfortunately, it looks like the horao project no longer exists on Github, so I don't think we'll be able to add this to the osgeo tap. Apologies.
