### ISSUE TITLE
QGIS head install fails

### ISSUE THREAD

**Issue by jctull** [OSGeo/homebrew-osgeo4mac#106]
QGIS builds but fails to install when building trunk. I was able to build, install and run QGIS head using homebrew dependencies manually. My QGIS truncated build log is available here:
https://gist.github.com/jctull/6261d7788e5218753cfb

**Comment by jctull** [comment]
Ok, yesterday's updates seemed to have cured this. Sorry for the bandwidth.

**Comment by jctull** [comment]
Oops, jumped the gun. I see now that the changes yesterday force HEAD to build release 2.8. So we're not building trunk. Is there another formula for that?

**Comment by dakcarto** [comment]
Hi @jctull !

Yeah, the `qgis-28` now builds that branch's latest commits for HEAD (which is appropriate). I am formulating (oh look, a pun) a new `qgis-210` formula that will be out soon. That will have master as HEAD-built branch, as per norm.

Your error seems to be an error introduced upstream, and not related to the formula; but, I may be incorrect, as I have not built HEAD yet.

**Comment by jctull** [comment]
Thanks. I was able to build the trunk source code locally. Perhaps a missing option that did not hit an upstream issue, but trunk built and installed otherwise.

**Comment by davenquinn** [comment]
Hi @jctull, did you ever find a fix for this? I am getting a similar error trying to update the formula to QGIS 2.14.

**Comment by jctull** [comment]
No, I have been building from source locally using homebrew for all the dependencies. I have not attempted to build the formula in a while.
