### ISSUE TITLE
grass70 fails to load GUI after brew install grass-70

### ISSUE THREAD

**Issue by TAKeanice** [OSGeo/homebrew-osgeo4mac#107]
```
$ grass70
Starting GRASS GIS...
ERROR: wxGUI requires wxPython. No module named wxversion
Error in GUI startup. If necessary, please report this error to the GRASS developers.
Switching to text mode now.

Hit RETURN to continue...
```

Although wxPython is installed by the grass-70.rb formula, something seems to be failing at startup.
Additionally, there is the following error after hitting RETURN a couple of times (after the same error as above re-appears when hitting enter):
```
Unable to create temporary directory <grass7-xxxx-53115>! Exiting.
```
where xxxx stands for my username.

Can you help me to figure out the cause of the problem?
Thank you!

**Comment by rkrug** [comment]
Tassilo Karge <notifications@github.com> writes:

> ```
> $ grass70
> Starting GRASS GIS...
> ERROR: wxGUI requires wxPython. No module named wxversion
> Error in GUI startup. If necessary, please report this error to the GRASS developers.
> Switching to text mode now.
>
> Hit RETURN to continue...
> ```
>
> Although wxPython is installed by the grass-70.rb formula, something seems to be failing at startup.
> Additionally, there is the following error after hitting RETURN a
> couple of times (after the same error as above re-appears when hitting
> enter):
> ```
> Unable to create temporary directory <grass7-xxxx-53115>! Exiting.
> ```
> where xxxx stands for my username.
>
> Can you help me to figure out the cause of the problem?
> Thank you!

Hm - works for me.

I just checked and I have wxmac also installed -make sure that it is
installed and working (maybe the command wx-config helps you?)

Cheers,

Rainer

>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/OSGeo/homebrew-osgeo4mac/issues/107

-- 
Rainer M. Krug, PhD (Conservation Ecology, SUN), MSc (Conservation Biology, UCT), Dipl. Phys. (Germany)

Centre of Excellence for Invasion Biology
Stellenbosch University
South Africa

Tel :       +33 - (0)9 53 10 27 44
Cell:       +33 - (0)6 85 62 59 98
Fax :       +33 - (0)9 58 10 27 44

Fax (D):    +49 - (0)3 21 21 25 22 44

email:      Rainer@krugs.de

Skype:      RMkrug

PGP: 0x0F52F982

**Comment by dakcarto** [comment]
Hi @TAKeanice,

Make sure that the Homebrew `site-packages` is discoverable, if you are using the system Python, as opposed to Homebrew's, e.g.:

```sh
export PYTHONPATH=${HOMEBREW_PREFIX}/lib/python2.7/site-packages:$PYTHONPATH
```

A better method is to add a `homebrew.pth` file as indicated on some Python-specific formulae:

```
Your default Python does not recognize the Homebrew site-packages
directory as a special site-packages directory, which means that .pth
files will not be followed. This means you will not be able to import
some modules after installing them with Homebrew, like wxpython. To fix
this for the current user, you can run:

  mkdir -p ~/Library/Python/2.7/lib/python/site-packages
  echo 'import site; site.addsitedir("${HOMEBREW_PREFIX}/lib/python2.7/site-packages")' >> ~/Library/Python/2.7/lib/python/site-packages/homebrew.pth
```

That ensures other .pth files will be treated properly.

Also, if using Homebrew's Python, make sure that your Homebrew `bin` directory is available on PATH, e.g. (it obviously looks that way since you are just typing `grass-70`, but may not be the case if you are running that from it directory):

```sh
export PATH=${HOMEBREW_PREFIX}/bin:$PATH
```

Note above HOMEBREW_PREFIX variable would be the same as `brew --prefix`.

**Comment by dakcarto** [comment]
Also, note that the formula has been updated to v7.0.1 recently.

**Comment by TAKeanice** [comment]
Thanks for your hints :) I have installed Python through Homebrew, I will check again if that is really used. But I suppose it is, since in my bash_profile I am adding /usr/local/bin and /usr/local/sbin (where /usr/local is the brew --prefix) to the PATH _before_ every other entry.

**Comment by TAKeanice** [comment]
the `brew upgrade grass-7ß` installs the dependencies `jbig2dec` and `ghostscript`, and builds from source, as opposed to the previous version which was already bottled.

**Comment by dakcarto** [comment]
Yes, the new formula does not have bottles built yet.

Looks like the version of your OS (10.10.5) is too new to be recognized by the build setup. Will update my Yosemite build bot and test.

**Comment by TAKeanice** [comment]
Thank you! I will report you the result as soon as you notify me

**Comment by TAKeanice** [comment]
@dakcarto have you already updated and tested? (I just want to ask for the status, not annoy or push you)

**Comment by dakcarto** [comment]
Hi @TAKeanice,

Sorry, I forgot to mention that I updated the bottles a week ago. I did not run into the error you saw. Please try upgrading to the latest, which should pull a bottle: `grass-70-7.0.1.yosemite.bottle.tar.gz`

**Comment by dakcarto** [comment]
Closing. Try latest `grass-70` formula. Please reopen if necessary.

**Comment by RoxFonseca** [comment]
Hello everyone! I found this post bc I have the same problem when in my terminal I try to open Grass... but I don't understand how to fix it... I am new using Grass and Python... I hope you can help me with that bc I need to use Grass in my class in the university... 

Thanks..

**Comment by rkrug** [comment]
just reinstalled grass-70 fromm bottle and it works.

**Comment by RoxFonseca** [comment]
Thanks for the help... I installed linuxbrew and I write in the terminal `brew install grass-70` and it is not work for me... this is the error...

`Error: No available formula with the name "grass-70" 
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: Broken pipe
`
thanks :) for your help again...

**Comment by RoxFonseca** [comment]
Hello again... 

Before my error I was intalled anaconda bc I need to install iphyton notebook (now is jupyter)... so after that I try to open grass and appear the error... so today I try many ways to my grass work and finally I try removing anaconda and iphyton notebook... and WOALA!!! my grass work perfectly :) so... I don't know how did wrong when I installed anaconda and iphyton notebook...

Thanks @rkrug for all :)

Rox

**Comment by dheerajchand** [comment]
Hey everyone, 

I am getting this error, as well, after following the [instructions on installing GRASS 7.2](https://grasswiki.osgeo.org/wiki/Compiling_on_MacOSX_using_homebrew#GRASS_7.2).

```
╰─ grass72
Cleaning up temporary files...
ERROR: MAPSET dheerajchand not found at
       /Users/dheerajchand/Documents/Professional/grassdata/US
Starting GRASS GIS...
ERROR: wxGUI requires wxPython. No module named wxversion
ERROR: Error in GUI startup. See messages above (if any) and if necessary, please report this error to the GRASS developers.
On systems with package manager, make sure you have the right GUI package, probably named grass-gui, installed.
To run GRASS GIS in text mode use the -text flag.
Use '--help' for further options
     grass72 --help
See also: https://grass.osgeo.org/grass72/manuals/helptext.html
Exiting...
╭─ ✘  OSX  L 2.28  ~    
```

I'm not sure what's wrong, I have wxpython and wxmac installed correctly via Homebrew. Any suggestions?

**Comment by kandread** [comment]
Had same issue and setting the GRASS Python to the Homebrew-installed Python fixed it for me.

`export GRASS_PYTHON=/usr/local/bin/python2`
`export GRASS_PYTHONWX=/usr/local/bin/pythonw2`

**Comment by chris338** [comment]
Setting Grass to Python 2.7 in "=/usr/bin/python2.7" fixed it for me. I put in both of these statements:
:~$ export GRASS_PYTHON=/usr/bin/python2.7
:~$ export GRASS_PYTHONWX=/usr/bin/python2.7
