### ISSUE TITLE
qtkeychain can't be migrated to new osgeo-keychain

### ISSUE THREAD

**Issue by alazarolop** [OSGeo/homebrew-osgeo4mac#1074]
After updating homebrew, I'm getting this message:
```
osgeo-qtkeychain from osgeo/osgeo4mac is given, but old name qtkeychain was installed from homebrew/core.
 Please try to use qtkeychain to refer the formula.
To force migrate use `brew migrate --force qtkeychain`.
```
And then, when I try to run the suggested code, what I get is:

```
Error: qtkeychain doesn't replace any formula.
```

Shall I try another command to fix it?

**Comment by fjperini** [comment]
You can uninstall `qtkeychain` and install `osgeo-qtkeychain`.

Later I will update `qgis-ltr` to use this new dependency.

**Comment by alazarolop** [comment]
@fjperini I uninstalled de package when I read your email (I needed to force it) and QGIS is working. 

I think it was installed along with some older version of QGIS because when I tried to uninstall it, it said it was used by `osgeo-qgis`, that's why I needed to force the uninstall. I thought it was weird.

**Comment by fjperini** [comment]
@alazarolop if you use it for `osgeo-qgis`, you will not have problems. it will be enough if you delete `qtkeychain` and install `osgeo-qtkeychain`. already solved?

**Comment by alazarolop** [comment]
Yes, solved!
