### ISSUE TITLE
osgeo-postgresql services doesn't start properly

### ISSUE THREAD

**Issue by alazarolop** [OSGeo/homebrew-osgeo4mac#1075]
Since I upgraded from core `postgresql` formula to `osgeo-postgresql`, I have realised that every time I restart the OS, the server (or the cluster) is not properly started.

I think it could be related to the path configured on the service for the cluster. In the info of the formula at least, it's suggested the following path:
``` 
$ pg_ctl start -D /usr/local/var/postgresql 
```
When in my case, with a cluster created with the core formula, would be:
``` 
$ pg_ctl start -D /usr/local/var/postgres
```

So I can manually start the cluster with the second statement, but the services isn't functioning as expected at the end. Could it be fix in the formula? Or shall I modify a local file manually? I tried to manually edit the .plist file into the cellar directory of `osgeo-postgresql` and restart the service and the OS, but it doesn't work.

Thank you.

**Comment by fjperini** [comment]
To use brew service you must use the name of the formula:
`brew services start osgeo-postgresql`
and to start it with `pg_ctl`, just use the path that you require.

**Comment by alazarolop** [comment]
Sorry I didn't explain it well.

After the installation, I run and I got:
```
$ brew services start osgeo-postgresql
Successfully started `osgeo-postgresql` (label: homebrew.mxcl.osgeo-postgresql)
```
So, I understand it's working with no issues. But then, when I try to use `psql`:
```
psql: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
```
That's why I think that the cluster hasn't been properly started and I stopped and started the service again with the same result.
```
$ brew services start osgeo-postgresql
Successfully started `osgeo-postgresql` (label: homebrew.mxcl.osgeo-postgresql)
$ brew services stop osgeo-postgresql
Successfully stopped `osgeo-postgresql` (label: homebrew.mxcl.osgeo-postgresql)
```
I decided to manually start the cluster with:
```
$ pg_ctl -D /usr/local/var/postgres start
waiting for server to start....2019-04-03 18:32:03.186 WEST [7006] LOG:  listening on IPv6 address "::", port 5432
2019-04-03 18:32:03.186 WEST [7006] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2019-04-03 18:32:03.187 WEST [7006] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2019-04-03 18:32:03.306 WEST [7007] LOG:  database system was shut down at 2019-04-03 14:04:32 WEST
2019-04-03 18:32:03.316 WEST [7006] LOG:  database system is ready to accept connections
 done
server started
```
And it worked. After this command is run, I can use `psql` correctly:
```
psql (11.2)
Type "help" for help.

postgres=# 
```
What's more, after running `pg_ctl`, it doesn't matter if I stop the service again, the cluster is still running and I can connect to it.

So, I understand that service isn't working as before. I noticed too that the directory which is mentioned in the info of the formula ends with `postgresql` instead of `postgres` (as it's in the core formula), which I thought it could be related to the issue.

**Comment by fjperini** [comment]
try to stop all postgresql processes

```
sudo lsof -i :5432
kill PID
```

https://github.com/OSGeo/homebrew-osgeo4mac/blob/a0faa31cdacaba2f08c7f07353f5c4f2bfb08ce3/Formula/osgeo-postgresql.rb#L270

and use `/usr/local/var/postgresql`

Maybe the problem is due to a previous configuration.


you can join, we were working on this with @miguelangelperg

https://join.slack.com/t/homebrew-osgeo4mac/shared_invite/enQtNjAwMjc5OTc2MTUxLTNmNjM2MGZhZWM1ZTFlMWZlNzFjYzE4OWIzMDMwMmZjNzdlNTRlYjFhYTNhM2RjOGM2MTliM2QyZjljYzYyOWE

**Comment by alazarolop** [comment]
I used initdb as suggested in the info and it's happening the same, but I remembered to check the log and this is what I get, and I think it's the problem:
```
2019-04-03 19:40:34.198 WEST [6818] LOG:  listening on IPv6 address "::", port 5432
2019-04-03 19:40:34.198 WEST [6818] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2019-04-03 19:40:34.199 WEST [6818] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2019-04-03 19:40:34.336 WEST [6818] FATAL:  postmaster became multithreaded during startup
2019-04-03 19:40:34.336 WEST [6818] HINT:  Set the LC_ALL environment variable to a valid locale.
```
How could I fix the problem with the "valid locale"?

**Comment by ivorbosloper** [comment]
I run into the same problem after upgrading `osgeo/osgeo4mac/osgeo-postgresql 11.2_1 -> 11.2_2`

After moving the cluster from /usr/local/var/postgres to /usr/local/var/postgresql , `pg_ctl` works but `brew services start` fails. It seems like the `brew services` process has the wrong environment to launch postgresql. If I modify my `~/Library/LaunchAgents/homebrew.mxcl.osgeo-postgresql.plist` launch file to include an environment variable (see https://serverfault.com/questions/111391/use-an-environment-variable-in-a-launchd-script), then after running `brew services restart osgeo-postgresql` the file is reverted to the original file. How to fix this?

`pg_ctl -D /usr/local/var/postgresql -l logfile start` works fine
`brew services start osgeo-postgresql` fails with the FATAL error

**Comment by alazarolop** [comment]
As far as I understand, every time  you run `brew services`,  it's copying the .plist file from the `/usr/locarl/Cellar/<formula>/`, so any changes made on the "LaunchAgents" folder is lost. You can modify the plist in the cellar and then you will find the change in the LaunchAgents.

BTW, which environmental are you trying to use?

**Comment by ivorbosloper** [comment]
@alazarolop thanks for the hint! I didn't expect the copying-part but now fixed the problem.

I've added the following part to `/usr/local/Cellar/osgeo-postgresql/11.2_2/homebrew.mxcl.osgeo-postgresql.plist` and now I can start/stop with `brew services restart osgeo-postgresql`.

```
  <key>EnvironmentVariables</key>
  <dict>
    <key>LC_ALL</key>
    <string>en_US.UTF-8</string>
  </dict>
```

I'm not sure if this is a general fix (then a pull-request would make sense), e.g. is 'en_US.UTF-8' the right locale for everybody? Or does the `brew services` command inherit some other/default environment I should configure instead of patching the .plist file?

**Comment by alazarolop** [comment]
Wow! It works like a charm! When I was trying to fix it I knew the environmental variable was the problem, but the method I used to add it to the plist didn't work. This solved it.

I think it could be a general fix, as the suggested step to create the cluster enforce to use this specific locale:
```
initdb /usr/local/var/postgresql -E utf8 --locale=en_US.UTF-8
```

**Comment by alazarolop** [comment]
@fjperini what do you think about this fix? It's eventually solved the issue we had.

**Comment by miguelangelperg** [comment]
**About postgresql**

Sometimes postgresql, postgres, server, cluster are terms that can be confused. It may be useful to keep in mind the difference between the database server and the data directory or database cluster.

The **server** is the program that allows us to manage our databases. In other words, the program in charge of offering the **postgres service**. ***postgres*** is the name with which it is agreed to name this service and so it can be found by any application that wants to use it. *It is not up to the user's criteria*. In our case, ***osgeo-postgresql*** is the application that is responsible for installing and offering the postgres service.

The **data directory** or **database cluster** is the place where our databases are stored physically. Usually the data directory is called *postgresql* by the current version. But the user can use any name. For example, ***jhondatabase***.

You can also start with any locale.

** Start the service**

To use the service it is necessary to **start** it and indicate the data directory that you should use. In the example, it would be:

`pg_ctl -D /usr/local/var/jhondatabase  start`

We can stop it manually:

`pg_ctl -D /usr/local/var/jhondatabase stop`

If you use plist you must modify line 13 and change `<string>/usr/local/var/postgresql</string>`
by `<string>/usr/local/var/jhondatabase</string>`

### If you need to Kill a process

If you need to kill a process, by example, postgres. In terminal:

Find the process
 `echo "$(ps -ceo pid=,comm= | awk '/postgres/ { print $1; exit }')"`

It will return a number

2 And them

`kill -9 <number>`

**Comment by alazarolop** [comment]
@miguelangelperg thanks for your detailed explanation. 

The manual method you mentioned to start the postgres service (and to get the cluster running) is what I've been using since the home-brew service to automatically do it when SO start up wasn't working for me (and some of us). The log of postgres suggested that there was an issue with ¿a mix of locale setups? and the manual method worked for me as long as I had a "LC_ALL" environmental variable defined in my .bash_profile.

I understand that the method suggested by @ivorbosloper solved the problem of the automation of triggering the `postgres` service , supplying the environmental variable to the plist. The manual method to start the service is have been always working at least for me.

**Comment by miguelangelperg** [comment]
I have the same problem with brew services. My locales: es_ES.UTF-8.

I start the service in the following way:
`pg_ctl start -D /usr/local/var/otropostgresql`
I do not need to indicate the locales to use

Maybe the problem with plist is another

**Comment by fjperini** [comment]
tomorrow I will sit down to solve everything!

**Comment by fjperini** [comment]
@alazarolop @miguelangelperg I will update PostgreSQL!
You could add the proposal by @ivorbosloper to solve the problem you are having.

**Comment by alazarolop** [comment]
@fjperini cool! Do you mean just to the latest version? 
I already did it and saved the method for new upgraded versions in case the .plist isn’t modified in the formula 👌🏼

**Comment by fjperini** [comment]
@alazarolop I'll update PostgreSQL to its latest version and add what luis suggests to `caveats` so that it looks like formula information.

Since it is a solution for certain cases, for example, in my installation I have not had this problem.

**Comment by alazarolop** [comment]
Cool! So I'm closing the issue then. 
Thank you all!
