### ISSUE TITLE
Bad boot screen for qgis-ltr

### ISSUE THREAD

**Issue by Emic37** [OSGeo/homebrew-osgeo4mac#1080]
I found a little error : 
When we open qgis-ltr `3.4.6`, the boot screen displayed is that of qgis `3.6 Noosa`. It should be that of qgis-ltr `3.4 Madeira`.

Or else, no other problem for the moment. All seems work for the moment. Thanks for your hard work.

**Comment by dd-a** [comment]
It seems that the boot screen displayed is the one of the version previously executed.

**Comment by Emic37** [comment]
Surprising. If it's right, reboot qgis-ltr should solve this problem no ? I rebooted qgis-ltr some times and it always displays the qgis 3.6 boot screen.

**Comment by dd-a** [comment]
Strange.  I’ve tested it by starting 3.6.1 and 3.4.6 alternatively, and also the same successively, and I always got the splash screen of the previous one.  But I have also other older versions installed from lutraconsulting and kyngchaos.

**Comment by fjperini** [comment]
It is not a problem, I had uploaded the 3.6 image, I will replace it with the 3.4 image.

**Comment by Emic37** [comment]
@fjperini yes just a small mistake. Thanks so much.

**Comment by fjperini** [comment]
I'll change it in the next revision
