### ISSUE TITLE
curl-openssl for osgeo-gdal ? need curl build with nghttp2 

### ISSUE THREAD

**Issue by vincentsarago** [OSGeo/homebrew-osgeo4mac#1085]
Since version 2.3, GDAL built agains libcurl+nghttp2 is able to merge GET requests ref: https://github.com/vincentsarago/gdal-http2-benchmark#benchmark

The new `curl` formula doesn't include nghttp2 thus we end up having GDAL missing this nice feature. I see that https://github.com/Homebrew/homebrew-core/blob/master/Formula/curl-openssl.rb is build against nghttp2 so maybe we could just replace `curl` by `curl-openssl` ? 

second solution will be to ship a new `osgeo-curl` maybe ?

**Comment by fjperini** [comment]
@vincentsarago we could replace it with `curl-openssl`.

Although first there will be to review these changes

```
--- curl.rb
+++ curl-openssl.rb

   depends_on "pkg-config" => :build
+  depends_on "brotli"
+  depends_on "c-ares"
+  depends_on "libidn"
+  depends_on "libmetalink"
+  depends_on "libssh2"
+  depends_on "nghttp2"
+  depends_on "openldap"
+  depends_on "openssl"
+  depends_on "rtmpdump"
 

       --disable-dependency-tracking
       --disable-silent-rules
       --prefix=#{prefix}
-      --with-darwinssl
-      --without-ca-bundle
-      --without-ca-path
+      --enable-ares=#{Formula["c-ares"].opt_prefix}
+      --with-ca-bundle=#{etc}/openssl/cert.pem
+      --with-ca-path=#{etc}/openssl/certs
+      --with-gssapi
+      --with-libidn2
+      --with-libmetalink
+      --with-librtmp
+      --with-libssh2
+      --with-ssl=#{Formula["openssl"].opt_prefix}
     ]
 
     system "./configure", *args
     system "make", "install"
-    system "make", "install", "-C", "scripts"
     libexec.install "lib/mk-ca-bundle.pl"
   end
```
I think there will be no problems in replacing it.

**Comment by fjperini** [comment]
@vincentsarago I will apply this changes with other required ones.

**Comment by fjperini** [comment]
@vincentsarago I will apply this change. we can close this issue
thanks for the contribution!
