### ISSUE TITLE
hdf file not supported in gdal

### ISSUE THREAD

**Issue by dschneiderch** [OSGeo/homebrew-osgeo4mac#109]
I have gdal brewed using --with-complete --with-libkml
hdf5 was also brewed:
Khione:/Volumes/hydroData/WestUS_Data/MOD17A_NPP $ gdalinfo --format HDF5
Format Details:
  Short Name: HDF5
  Long Name: Hierarchical Data Format Release 5
  Extension: hdf5
  Help Topic: frmt_hdf5.html
  Supports: Subdatasets

but when I try gdalinfo somefile.hdf I get:
Khione:/Volumes/hydroData/WestUS_Data/MOD17A_NPP $ gdalinfo raw_8day/MOD17A2.A2000049.h09v05.005.2006333225721.hdf
ERROR 4: `raw_8day/MOD17A2.A2000049.h09v05.005.2006333225721.hdf' not recognised as a supported file format.

gdalinfo failed - unable to open 'raw_8day/MOD17A2.A2000049.h09v05.005.2006333225721.hdf'.

However, gdalinfo on a geotif works fine.
fwiw, I haven't been able to brew gdal --with-python so I don't know if thats related (issue https://github.com/Homebrew/homebrew/issues/36744)

suggestions?

**Comment by dakcarto** [comment]
Hi @dschneiderch,

Did you try using the `.hdf5` extension as indicated by the driver `--format HDF5 ` output?

**Comment by dschneiderch** [comment]
Hi,
I hadn't, but just did and it did not help. I tried both .HDF5 and .hdf5
Dominik

Dominik Schneider
o 303.735.6296 | c 518.956.3978

**Comment by rashadkm** [comment]
i think extension is .h5

**Comment by dschneiderch** [comment]
.h5 doesn't work either.
if anyone wants to try it, the file is here:
ftp://snowserver.colorado.edu/pub/fromDominik/test.h5
I couldn't get it to work on my imac or macbook.


Dominik Schneider
o 303.735.6296 | c 518.956.3978

**Comment by dakcarto** [comment]
Hi Dominik,

Using [HDFView](https://www.hdfgroup.org/products/java/hdfview/) or any of the utilities in `HOMEBREW_PREFIX/opt/hdf5/bin` fails to open your file.

Using some of the [files in the basic tutorial](https://www.hdfgroup.org/ftp/HDF5/examples/files/tutorial/) seem to work fine, though, including via `gdalinfo`. You file is invalid maybe?

**Comment by dschneiderch** [comment]
my apologies. the tutorial files work fine. I will redownload.

Dominik Schneider
o 303.735.6296 | c 518.956.3978

**Comment by dschneiderch** [comment]
Sorry to reopen, I've dug into this deeper and am still having problems. The files from the basic tutorial work as indicated but every file i've tried from http://e4ftl01.cr.usgs.gov/MOLT/MOD09GA.005 hasn't. I've emailed the ldaac help and will update with a response but could there be an issue with either recent hdf5.rb or something else that's changed?
 i'm using hdf5 1.8.15 on os 10.9.5 and have the same problem on another computer running 10.11.1

skipping gdal i also get this error:
```bash
> h5debug ~/Downloads/MOD09GA.A2015266.h08v04.005.2015268104518.hdf
HDF5-DIAG: Error detected in HDF5 (1.8.15-patch1) thread 0:
  #000: H5F.c line 604 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 1085 in H5F_open(): unable to read superblock
    major: File accessibilty
    minor: Read failed
  #002: H5Fsuper.c line 277 in H5F_super_read(): file signature not found
    major: File accessibilty
    minor: Not an HDF5 file
cannot open file
```

**Comment by esagara** [comment]
MODIS is hdf4. I believe I had to pass some flags during my install.
```
brew install gdal --with-libkml --with-hdf4
```

**Comment by dschneiderch** [comment]
Thanks Eric! 
homebrew doesn't consider hdf4 current anymore so based on [a post on the r-sig-geo list](http://r-sig-geo.2731867.n2.nabble.com/OSX-rgdal-GDAL-drivers-and-HDF4-td7588400.html)  I will do:
(note --with-complete and --with-unsupported instead of --complete and --enable-unsupported)

```bash
brew install homebrew/versions/hdf4 
#brew link --overwrite hdf4   # prefer hdf4 links over NetCDF ?
brew install gdal --with-complete --with-unsupported --with-hdf4 
```
before I continue, I have a question though.
The poster said to prefer hdf4 links over netcdf links but i'm not sure this is such a great idea. The only link is `ncgen` that would be overwritten. netcdf4 is backwards compatible with netcdf3 but hdf5 is not backwards compatible with hdf4 so I presume I would lose compatibility with netcdf4 files. netcdf3 is based on hdf4, netcdf4 is based on hdf5. 
Does anyone know if my intuition is correct?

**Comment by dschneiderch** [comment]
well I tried both and you have to overwrite the links for hdf4 to get picked up by gdal. However it seems I can still read my netcdf files which I am **pretty** sure are nc4.

It seems, given the major differences between hdf4 and hdf5 and the fact that hdf4 files will be around for a long time, that hdf4 should not be in homebrew/versions but rather offered as a parallel install within homebrew/osgeo4mac.

**Comment by nickrobison** [comment]
@dschneiderch We've added an hdf4 formula and linked it into `gdal2`, everything should be working now. Feel free to open another ticket it something's amiss.

Thanks!

**Comment by ankitrao22** [comment]
@nickrobison i have installed gdal2 using homebrew but could not able to get hdf4 compilation. 

I will be thankful to you if you could suggest me a way to install. 

Thank you 

Ankit
