### ISSUE TITLE
State of the tap?

### ISSUE THREAD

**Issue by christianbraun** [OSGeo/homebrew-osgeo4mac#1092]
Hi guys,
what is the state of the tap and the refactoring? I am a bit afraid of updating my installation of QGIS because I need it in production.

Can you give some hints please.

Best,
Christian

**Comment by fjperini** [comment]
@christianbraun if you will use QGIS 3, you can update. All that remains is to review those that respect QGIS 2.

My advice is that you perform a clean installation.
