### ISSUE TITLE
allow osgeo-qgis to install with only postgresql@10

### ISSUE THREAD

**Issue by drewda** [OSGeo/homebrew-osgeo4mac#1096]
Currently running `brew install osgeo-qgis --with-pg10` appears to require installing **both** osgeo-postgresql and osgeo-postgresql@10.

I tried to trace it to a particular dependency that does not allow you to specify the `--with-pg10` flag. I see that there is no option in https://github.com/OSGeo/homebrew-osgeo4mac/blob/master/Formula/osgeo-vtk.rb#L70

It would be nice to be able to decide to only use osgeo-postgresql@10 with osgeo-qgis.

(A general note: thanks to the maintainers for these formulas--by far my favorite way of installing QGIS.)

**Comment by fjperini** [comment]
@drewda Thanks for your comment. I'll check this!

**Comment by fjperini** [comment]
@drewda this has already been fixed. You can write me if you need me to review something else.

as a separate fact: we are making some corrections to use proj5 and gdal2, QGIS is not prepared for proj6 and gdal3. Wait a few hours, it is advisable not to update until completing the process.

We close this issue by the moment.

Thanks for the contribution!

**Comment by drewda** [comment]
@fjperini thanks. I will try `brew install osgeo-qgis --with-pg10` again

**Comment by fjperini** [comment]
@drewda Wait a few hours. We are applying other changes.

**Comment by drewda** [comment]
O.K. For what it's worth, installing the qgis with pg10 specified still wants to install both postgres formulas:

```sh
==> Installing osgeo-qgis from osgeo/osgeo4mac
==> Installing dependencies for osgeo/osgeo4mac/osgeo-qgis: cmake, six, osgeo-sip, libpq, arpack, superlu, armadillo, ant, osgeo-proj, osgeo-libgeotiff, osgeo-libspatialite, osgeo-libkml, osgeo-netcdf, osgeo-hdf4, osgeo-postgresql@10, osgeo-gdal, osgeo-gdal-python, osgeo-pyqt, osgeo-qscintilla2, qca, osgeo-qt-webkit, osgeo-pyqt-webkit, osgeo-qtkeychain, qwt, freetds, osgeo-postgresql, osgeo-psqlodbc, osgeo-postgis, exiv2, osgeo-laszip@2, osgeo-liblas, osgeo-laz-perf, netpbm, scipy, pygobject, libomp, imagemagick, osgeo-matplotlib, tbb, osgeo-vtk, mysql, osgeo-pcl, osgeo-hexer, osgeo-pdal, nss, librsvg, gdal2-python, llvm, osgeo-qgis-res, fftw, utf8proc, osgeo-grass, osgeo-pyspatialite, osgeo-qt-psql, osgeo-qt-odbc, osgeo-qt-mysql, osgeo-muparserx, opencv, mesa, osgeo-opencollada, osgeo-openscenegraph, osgeo-ossim, osgeo-insighttoolkit, osgeo-orfeo, osgeo-saga-lts, osgeo-whitebox-tools, osgeo-lastools and osgeo-taudem
```

**Comment by fjperini** [comment]
Yes, we still need to update several formulas.
