### ISSUE TITLE
Can't build saga-gis

### ISSUE THREAD

**Issue by alazarolop** [OSGeo/homebrew-osgeo4mac#1104]
Hi, 

I needed to upgrade `saga-gis` formula when opencv dependency get updated.

```
==> Reinstalling 3 broken dependents from source:
osgeo/osgeo4mac/osgeo-liblas, osgeo/osgeo4mac/osgeo-openscenegraph, osgeo/osgeo4mac/saga-gis
```

But I'm getting stuck during the building process
```
==> Reinstalling osgeo/osgeo4mac/saga-gis --with-app
==> Downloading https://downloads.sourceforge.net/project/saga-gis/SAGA%20-%207/SAGA%20-%207.1
==> Downloading from https://netix.dl.sourceforge.net/project/saga-gis/SAGA%20-%207/SAGA%20-%2
######################################################################## 100.0%
==> autoreconf -i
==> ./configure --prefix=/usr/local/Cellar/saga-gis/7.1.1 --disable-openmp --disable-libfire -
==> make install
Last 15 lines from /Users/alazaro/Library/Logs/Homebrew/saga-gis/03.make:
         ^~~~~~~~~~~~~
1 error generated.
In file included from opencv_ml.cpp:61:
./opencv_ml.h:72:10: fatal error: 'opencv2/core/version.hpp' file not found
#include "opencv2/core/version.hpp"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
1 error generated.
make[4]: *** [opencv_fourier.lo] Error 1
make[4]: *** [opencv_ml.lo] Error 1
make[4]: *** [MLB_Interface.lo] Error 1
make[3]: *** [install-recursive] Error 1
make[2]: *** [install-recursive] Error 1
make[1]: *** [install-recursive] Error 1
make: *** [install-recursive] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/osgeo/homebrew-osgeo4mac/issues
```

Then I installed the bottle version without the --with-app flag, and as far as I've tested, it's working again from CMD (at least some processes). But I usually use the GUI application, so I was wondering if there is a fix for this problem.

Thank you

**Comment by fjperini** [comment]
@alazarolop I'll check this!

**Comment by alazarolop** [comment]
@fjperini do you think the formula could be updated along the way to its latest version?

**Comment by fjperini** [comment]
@alazarolop we are analyzing using proj5 and gdal2 for a while due to problems with proj6 and gdal3 in qgis.

With this we will also restore `osgeo-saga-lts`.

**Comment by alazarolop** [comment]
Great! I actually didn't know about gdal3. Do you mean just `osgeo-saga-lts` or both `osgeo-saga-lts` and `saga-gis`?

**Comment by fjperini** [comment]
@alazarolop Both! Is almost decided, we will use gdal 2.4.1 and proj 5.0.0.
Just wait until I apply all the changes.

**Comment by alazarolop** [comment]
@fjperini Cool! Thanks for the information. Besides your reason, to be honest I would also prefer to keep gdal2, regarding compatibility with some R packages that I I’m not sure if they’ve already been update.

**Comment by fjperini** [comment]
@alazarolop I will update `osgeo-saga`. we close this issue.
