### ISSUE TITLE
Simple click sometimes doesn't work

### ISSUE THREAD

**Issue by Emic37** [OSGeo/homebrew-osgeo4mac#1106]
Sorry to open a new potential issue. The problem with sip broke my homebrew qgis installation, so I tried Qgis builed by [lutraconsulting](https://lutraconsulting.github.io/qgis-mac-packager/). This is only one big `.app` which contains all dependencies. 

I don't find (like with qgis from here) this little "bug" that you may have already noticed : when we click to select a tool, sometimes, the button become grey but tool is not selected. You have to click a second time to really select the tool and use it.

So maybe, it's a problem from this build ? I believe it happens when I use touchpad touch in particular and a window is opened. 
For example : I identify an entity. Qgis opens the form. If I want edit this entity, I click to switch to edit mode. The first click doesn't work and the button becomes grey but edit mode is not activated. The second clic activates edit mode.

If I use  the "hard click", everything seems to work properly. Has anyone ever noticed this problem ?

**Comment by fjperini** [comment]
@Emic37 Share some images about this.

In general, the problems that may arise are due to some problem in the user's Homebrew installation.

**Comment by Emic37** [comment]
Ok thanks. What should I check ? I uninstall qgis and all dependencies waiting you finish all modifications in the tap. `brew doctor` command returns that my system is ready to brew.

**Comment by fjperini** [comment]
@Emic37 Creating the new bottle for `osgeo-qgis-ltr`.

When you update, check again and report the result.

A screenshot will help.

Thank you!
