### ISSUE TITLE
update orfeo toolbox to 5.0

### ISSUE THREAD

**Issue by rashadkm** [OSGeo/homebrew-osgeo4mac#111]
OTB 5.0.0 is out since Aug 1st. the current version in the homebrew is 4.2.0. Is there any recent plan to upgrade to 5.0?

**Comment by rashadkm** [comment]
also there are sub projects. Ice, monteverdi2

**Comment by dmwelch** [comment]
@dakcarto This issue can be closed, yes?

**Comment by dakcarto** [comment]
Indeed, thanks

**Comment by dakcarto** [comment]
Note, I will be working on `ice` and `monteverdi3` updates, too.

**Comment by rashadkm** [comment]
FYI, since OTB 5.6, ice is a yet another otb module. if you wait for next release 5.8, so will be monteverdi. With that you don't need to maintain three otb projects. just one project: OTB

**Comment by dakcarto** [comment]
@rashadkm thank you for the update. Unfortunately, as evidenced by my lack of recent OTB-related commits here, I have not been able to keep up on all the different projects. This is why I am now devoting considerable amount of time focusing on migrating all these formulae to the homebrew/geospatial tap. I will try to update the OTB-related formulae first, though we generally can't (or don't need to) utilize the benefit of the SuperBuild dependencies as easily in the Homebrew package environ.

Any review of the last (upcoming) updates to the OTB-related formulae will be greatly appreciated.

**Comment by rashadkm** [comment]
sure. I would be glad to look into the updates in otb formulae. you can go without superbuild. even so what I mentioned was the projects are fused under single name otb.

instead of monteverdi 3.6.0 you will have Monteverdi - OTB 5.8.

feel free to add me in cc when the formulae is ready.
