### ISSUE TITLE
gdal2 ? 

### ISSUE THREAD

**Issue by vincentsarago** [OSGeo/homebrew-osgeo4mac#1121]
👋 
with gdal being updated to a major version `3.0.0` I think it could be great to add a `osgeo-gdal2` formula.

To be honest I'd love this because gdal3 is breaking some application I'm using. 😬

**Comment by fjperini** [comment]
@vincentsarago Yes, we are working on this.
we are likely to use gdal2 and proj5 for a while.

**Comment by vincentsarago** [comment]
that's sounds great @fjperini

**Comment by fjperini** [comment]
@vincentsarago is almost decided, we will use gdal 2.4.1 and proj 5.0.0.
Just wait until I apply all the changes.

**Comment by vincentsarago** [comment]
🙏

**Comment by fjperini** [comment]
@vincentsarago We are already using GDAL v2.4.1. Just wait to rebuild all the bottles that depend on this library.  We close this issue.

**Comment by fjperini** [comment]
@vincentsarago Keep in mind that for `osgeo-proj`, `osgeo-gdal`, `osgeo-gdal-*` and `osgeo-libgeotiff` you will have to de-install and re-install. And then continue with the other updates.
