### ISSUE TITLE
saga-his points to outdated libhpdf library

### ISSUE THREAD

**Issue by cbertelli** [OSGeo/homebrew-osgeo4mac#113]
It's easy to overcome problems
ln -s /usr/local/lib/libhpdf-2.3.0.dylib /usr/local/lib/libhpdf-2.2.1.dylib
but it's better to correct the formula.

**Comment by turboladen** [comment]
I'm on the El Capitan GM and don't seem to get that.

```
ll /usr/local/lib/libhpdf*
lrwxr-xr-x  1 sloveless  admin  47 Oct  4 11:23 /usr/local/lib/libhpdf-2.3.0.dylib -> ../Cellar/libharu/2.3.0/lib/libhpdf-2.3.0.dylib
lrwxr-xr-x  1 sloveless  admin  37 Oct  4 11:23 /usr/local/lib/libhpdf.a -> ../Cellar/libharu/2.3.0/lib/libhpdf.a
lrwxr-xr-x  1 sloveless  admin  41 Oct  4 11:23 /usr/local/lib/libhpdf.dylib -> ../Cellar/libharu/2.3.0/lib/libhpdf.dylib
```

**Comment by dakcarto** [comment]
Hi, thanks for reporting!

The current formula is source-build-only. Try again and verify. If it is still an issue, reopen this ticket.
