### ISSUE TITLE
Referenced from: /usr/local/bin/spatiaLite   Reason: Incompatible library version: spatiaLite requires version 11.0.0 or later, but libproj.9.dylib provides version 10.0.0 Trace/BPT trap: 5

### ISSUE THREAD

**Issue by pngimbwa** [OSGeo/homebrew-osgeo4mac#117]
Hi all,

Am getting this error when i type spatiaLite on my terminal.

The error:
Referenced from: /usr/local/bin/spatiaLite
 Reason: Incompatible library version: spatiaLite requires version 11.0.0 or later, but libproj.9.dylib provides version 10.0.0
Trace/BPT trap: 5

Am using Max OS X  El Capitan (10.11)
Help would be much appreciated.
Thank you.

Peter

**Comment by dakcarto** [comment]
Hi, thanks for reporting!

The `spatialite` formula is not supported in this repo. It is a core Homebrew formula. You probably just need to rebuild it.
