### ISSUE TITLE
Mapnik Not a directory @ rb_file_s_rename

### ISSUE THREAD

**Issue by winsento** [OSGeo/homebrew-osgeo4mac#1176]
`brew install --HEAD osgeo-mapnik`

Result:
```
...
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at c83a2ab std::ostream operator<< overloads
Error: An exception occurred within a child process:
  Errno::ENOTDIR: Not a directory @ rb_file_s_rename - (/private/tmp/osgeo-mapnik--geometry-20190521-26118-1umb3f6/.git, /private/tmp/osgeo-mapnik-20190521-26118-46txmz/deps/mapbox/geometry/.git)
```

**Comment by fjperini** [comment]
@winsento I will update this formula.

**Comment by fjperini** [comment]
@winsento we recommend not using the master branch.

PROJ5 will be used for a time. 

The problem in HS is external to this tap, the Sierra bottle will be used. In Mojave build correctly.

**Comment by fjperini** [comment]
@winsento the bottle was already generated, it works correctly. we close this issue
