### ISSUE TITLE
GDAL Java bindings work incorrect

### ISSUE THREAD

**Issue by aalukin** [OSGeo/homebrew-osgeo4mac#1196]
**Please answers the following**

I've... 
- I read
	- [x] the [reporting issues](https://github.com/OSGeo/homebrew-osgeo4mac/docs/reporting-issues)
	- [x] the [troubleshooting](https://github.com/OSGeo/homebrew-osgeo4mac/docs/troubleshooting)
- [x] I checked the documentation and found no answer
- [x] I tried to install after following the suggestions
- [x] I am running the latest version (`brew update` twice?)
- [x] I checked to make sure that this issue has not already been filed

**Describe the bug**

After updating `osgeo-qgis` Java bindings from `osgeo-gdal` formula start to produce empty rasters and vectors with the same code and inputs as before the `libproj` bug.
For example, gdal reporejct, crop and polygonize commands give empty tiffs or shape files outputs.
But execution of those commands from console gives correct output.

Also, the `lib` directory, which contains jars and dll files don't update last time and have the creation time:

`drwxr-xr-x  10 artur  staff   320 May 24 06:04 .`
 `drwxr-xr-x   3  artur  staff    96 May 23 21:34 ..`
 `drwxr-xr-x   3  artur  staff    96 Mar 15 15:05 .bottle`
 `drwxr-xr-x   3  artur  staff    96 Mar 15 15:05 .brew`
  `-rw-r--r--    1   artur  staff  4345 May 24 06:04 INSTALL_RECEIPT.json`
 ` -rw-r--r--   1    artur  staff  1568 Mar 15 15:05 README.md`
  `drwxr-xr-x  27  artur  staff   864 May 23 21:34 bin`
  `drwxr-xr-x  71  artur  staff  2272 May 23 21:34 include`
 ` drwxr-xr-x   9   artur  staff   288 Mar 15 15:05 lib`
  `drwxr-xr-x   3   artur  staff    96 Mar 15 15:05 share`

Can these need some swig's error, or it need recompile to work as before update?

**To Reproduce**

1. Create simple java application
2. Add libs from `/usr/local/opt/osgeo-gdal/lib`
3. Add simple GDAL java bindings code, for example translate jp2k to geotiff
```
        ogr.RegisterAll();
        gdal.AllRegister();

        String[] args = new String[]{file.getAbsolutePath()};
        args = gdal.GeneralCmdLineProcessor(args);
        Dataset hDataSet = gdal.Open(args[0], gdalconstConstants.GA_ReadOnly);
        if (hDataSet == null) {
            log.error("Error reading prj from {}", file.getPath());
            throw new IllegalArgumentException("");
        }
        String base = FilenameUtils.removeExtension(file.getAbsolutePath());
        Vector<String> optionsVector = new Vector<>();
        optionsVector.add("-of");
        optionsVector.add("GTiff");
        TranslateOptions options = new TranslateOptions(optionsVector);
        gdal.Translate(base + GEO_TIFF_EXTENSION, hDataSet, options);
```

4. Start app with goal libs in arguments: `-Djava.library.path=/usr/local/opt/osgeo-gdal/lib`

**Expected behavior**

This code should convert formats from jp2k to geotiff (but bug reproduces with any others commands from gdal with java bindings).
Code doesn't have any errors, because before updating it worked correct. The input data are the same as before.

`brew doctor` output: 

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  osgeo-insighttoolkit
  numpy
  scipy
```

**Comment by fjperini** [comment]
@aalukin I'll check this!
