### ISSUE TITLE
qgis3: Error: Too many open files @ rb_sysopen

### ISSUE THREAD

**Issue by zbeekman** [OSGeo/homebrew-osgeo4mac#1198]
**Please answers the following**

I've... 
- I read
	- [ ] the [reporting issues](https://github.com/OSGeo/homebrew-osgeo4mac/docs/reporting-issues) Nope, since the link 404s
	- [ ] the [troubleshooting](https://github.com/OSGeo/homebrew-osgeo4mac/docs/troubleshooting) Nope, since the link 404s
- [x] I checked the documentation and found no answer
- [x] I tried to install after following the suggestions
- [x] I am running the latest version (`brew update` twice?)
- [x] I checked to make sure that this issue has not already been filed
      Yes, #1017 was reported but it was prematurely closed.
- [ ] I uploaded logs: `brew gist-logs formula`: `Error: No logs.`

**Describe the bug**

```
$ brew install qgis3
==> Installing osgeo-qgis from osgeo/osgeo4mac
Error: Too many open files @ rb_sysopen - /usr/local/var/homebrew/locks/gnu-getopt.formula.lock
```

**To Reproduce**

I was following this tutorial: https://gis4wrf.github.io/installation/#macos

**Expected behavior**

The formula does not trigger a ruby error using outdated methods/techniques

**Screenshots**

Detailed backtrace:
```
...
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gdcm.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/osgeo-vigra.rb
Error: Too many open files @ rb_sysopen - /usr/local/var/homebrew/locks/gnu-getopt.formula.lock
/usr/local/Homebrew/Library/Homebrew/lock_file.rb:41:in `initialize'
/usr/local/Homebrew/Library/Homebrew/lock_file.rb:41:in `open'
/usr/local/Homebrew/Library/Homebrew/lock_file.rb:41:in `open'
/usr/local/Homebrew/Library/Homebrew/lock_file.rb:41:in `create_lockfile'
/usr/local/Homebrew/Library/Homebrew/lock_file.rb:16:in `lock'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1147:in `lock'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:1015:in `each'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:1015:in `lock'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:142:in `prelude'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:331:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:264:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:262:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:262:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

The formula appears to be trying to load too many formulae at once without closing them.

**Additional context**

`brew doctor` output: 

```shell
Warning: The filesystem on / appears to be case-sensitive.
The default macOS filesystem is case-insensitive. Please report any apparent problems.

Warning: You have installed Bitdefender. The "Traffic Scan" option interferes with
Homebrew's ability to download packages. See: # But it's disabled
  https://github.com/Homebrew/brew/issues/5558

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  postgresql # qgis3 asked to unlink
  markdown
  metis
  open-mpi
  netcdf # qgis3 asked to unlink
  intel-parallel-studio
  sip # qgis3 asked to unlink
  pyqt # qgis3 asked to unlink
```

**Logs**

Ruby error while running the formula, no logs

```
$ brew config
HOMEBREW_VERSION: 2.1.5-13-g755123d
ORIGIN: https://github.com/Homebrew/brew
HEAD: 755123d2c813cb9172fc823ea38ca13488c15a54
Last commit: 4 hours ago
Core tap ORIGIN: git@github.com:Homebrew/homebrew-core.git
Core tap HEAD: b2f0b10b876634224d0b22b66262a6423b37a195
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BINTRAY_KEY: set
HOMEBREW_BINTRAY_USER: zbeekman
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MIANTAINER: 1
HOMEBREW_VISUAL: emacs
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1001
Git: 2.22.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 12.0.1, 12, 11.0.2, 10.0.2, 1.8.0_202, 1.8.0_152
macOS: 10.14.5-x86_64
CLT: 10.2.1.0.1.1554506761
Xcode: 10.2.1
XQuartz: 2.7.11 => /opt/X11
```

**Comment by jonathanmccormack** [comment]
I too am encountering this issue -- fixed with `ulimit -n 1024` but a more permanent solution would be ideal.

**Comment by fjperini** [comment]
@jonathanmccormack It is necessary for the amount of files. We close this issue.

**Comment by zbeekman** [comment]
But there's no reason you should be simultaneously opening every. single. homebrew. formula. :thinking:

**Comment by jonathanmccormack** [comment]
Agreed, and I strongly disagree with closing this issue. Even if the documentation were updated to inform new users that they need to run `ulimit -n 1024` in order to get osgeo-qgis to install correctly, this strikes me as a temporary workaround to a very real bug in the formula.

**Comment by fjperini** [comment]
Yes, you are right. It can be useful, although always remember to look in the issues so there are no duplicates.

**Comment by zbeekman** [comment]
Might be stale, but probably shouldn't be closed until resolved...

**Comment by zbeekman** [comment]
Is there not a label you can add to prevent stalebot from closing this?

**Comment by resistor4u** [comment]
or at least put a caveat in the `brew options` part of the formula?

**Comment by richard-rasch** [comment]
I gave up getting qgis-ltr@2 running on my Mac (was working then broke with brew upgrade) now I can't install qgis3 because of the 'too many open files' error. Is there a simpler way to run qgis on my mac?
