### ISSUE TITLE
Znzibar still uses Noosa splash image

### ISSUE THREAD

**Issue by nextstopsun** [OSGeo/homebrew-osgeo4mac#1209]
That confused me at first after upgrading

**Comment by fjperini** [comment]
@nextstopsun Yes, it is necessary to update the splash 😅

**Comment by nextstopsun** [comment]
@fjperini Can I help you with that so you can concentrate on more important things?

**Comment by fjperini** [comment]
@nextstopsun It's something you can do, but before applying the changes you have to wait for some updates that we are analyzing.

**Comment by fjperini** [comment]
solved!
