### ISSUE TITLE
failure to brew install QGIS - Failed to download resource "osgeo-qgis-ltr"

### ISSUE THREAD

**Issue by BC14w** [OSGeo/homebrew-osgeo4mac#1211]
I've been trying to install QGIS my Mac through brew. but so far, I've run into a few issues. I was able to brew instal through the dependencies by limiting using ulimit -n 1024. I had to run brew install qgis 3 times to get to the end of all dependencies.
Now that all dependencies are dowloaded, it tries to download the tar file from GitHub but gives me this error with not much explanation:
`brew install osgeo/osgeo4mac/osgeo-qgis-ltr
==> Installing osgeo-qgis-ltr from osgeo/osgeo4mac
==> Downloading https://github.com/qgis/QGIS/archive/final-3_4_9.tar.gz
Error: An exception occurred within a child process:                          
  DownloadError: Failed to download resource "osgeo-qgis-ltr"
Download failed: https://github.com/qgis/QGIS/archive/final-3_4_9.tar.gz`

**Comment by fjperini** [comment]
@BC14w You may have just had a connection problem, try again.
I have tried it recently and it installs correctly.

```
$ brew install osgeo-qgis-ltr
==> Installing osgeo-qgis-ltr from osgeo/osgeo4mac
==> Downloading https://bottle.download.osgeo.org/osgeo-qgis-ltr-3.4.9.mojave.bottle.tar.gz
######################################################################## 100.0%
==> Pouring osgeo-qgis-ltr-3.4.9.mojave.bottle.tar.gz
.
.
.
==> Summary
🍺  /usr/local/Cellar/osgeo-qgis-ltr/3.4.9: 6,073 files, 253.4MB
```
