### ISSUE TITLE
cannot compile QGIS due to missing libssh

### ISSUE THREAD

**Issue by 3nids** [OSGeo/homebrew-osgeo4mac#1212]
I am trying to build QGIS right now (using a custom setup) and am getting this error:

    /usr/local/opt/exiv2/include/exiv2/ssh.hpp:27:10: fatal error: 'libssh/libssh.h' file not found
    #include <libssh/libssh.h>
             ^~~~~~~~~~~~~~~~~
    1 error generated.

Does someone know how to handle this?

**Comment by fjperini** [comment]
@3nids I will revise this when rebuilding `osgeo-qgis`.
