### ISSUE TITLE
qgis-28 fails due to 404 on fcgi

### ISSUE THREAD

**Issue by matthewhanson** [OSGeo/homebrew-osgeo4mac#124]
brew and osgeo4mac up to date.

Tried installing 
brew install qgis-28

and get

```
una:~ $ brew install qgis-28
==> Installing qgis-28 from osgeo/osgeo4mac
==> Installing dependencies for osgeo/osgeo4mac/qgis-28: fcgi, postgresql
==> Installing osgeo/osgeo4mac/qgis-28 dependency: fcgi
==> Downloading http://www.fastcgi.com/dist/fcgi-2.4.0.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "fcgi"
Download failed: http://www.fastcgi.com/dist/fcgi-2.4.0.tar.gz
```

**Comment by dakcarto** [comment]
Hi,

Thanks for reporting. This error is unrelated to the `qgis-28` formula. Its dependency `fcgi` appears to have its hosted project site either taken down, someone forgot to pay a bill, the project's been shuttered, etc.: http://www.fastcgi.com/

Not sure if there is another download site (didn't find a reputable one).

In the meantime, you can download it from here:
http://qgis.dakotacarto.com/osgeo4mac/fcgi-2.4.0.tar.gz

Then place the archive in your Homebrew cache (e.g. `/Library/Caches/Homebrew/` by default). Then try and build `qgis-28` again and it will use the cached archive and verify its hash as per usual.

**Comment by dakcarto** [comment]
This is now fixed [upstream at Homebrew](https://github.com/Homebrew/homebrew/commit/3540ee9).
