### ISSUE TITLE
Update to proj 6.1 and gdal 3

### ISSUE THREAD

**Issue by PeterPetrik** [OSGeo/homebrew-osgeo4mac#1240]
please see https://github.com/qgis/QGIS-Mac-Packager/issues/12#issuecomment-515712483

**Comment by fjperini** [comment]
I will start updating everything.

Just one doubt, SAGA LTS still without support for PROJ 6 AND GDAL 3?

We can use https://github.com/north-road/qgis-processing-saga-nextgen to use the latest version of SAGA. @nyalldawson v7.3?

**Comment by fjperini** [comment]
We must also make sure we have a version of GRASS working with these updates.

**Comment by PeterPetrik** [comment]
@fjperini what is the state for transition to proj 6.1.. ?

**Comment by fjperini** [comment]
@PeterPetrik i will start updating!

**Comment by pat-s** [comment]
> Just one doubt, SAGA LTS still without support for PROJ 6 AND GDAL 3?

SAGA LTS (v2.x) won't support PROJ 6. There is an official statement to this in the SAGA dev forum.

**Comment by jctull** [comment]
> @PeterPetrik i will start updating!

Any progress on this? I believe the updates to PROJ6 and GDAL3 are needed to get GeoPDF export capabilities as well.

**Comment by neteler** [comment]
Update: GRASS GIS 7.8.1 with support for Python 3, PROJ 6 and GDAL 3 has been released:

- https://github.com/OSGeo/grass/releases/tag/7.8.1
- https://trac.osgeo.org/grass/wiki/Release/7.8.1-News

**Comment by neteler** [comment]
FWIW:

Update: GRASS GIS 7.8.2 with important fixes for Python 3, PROJ 6 and GDAL 3 support has been released:

    https://github.com/OSGeo/grass/releases/tag/7.8.2
    https://trac.osgeo.org/grass/wiki/Release/7.8.2-News
