### ISSUE TITLE
invalid option for gdal2

### ISSUE THREAD

**Issue by JorjGaidin** [OSGeo/homebrew-osgeo4mac#1241]
I'm following documentation from https://grasswiki.osgeo.org/wiki/Compiling_on_MacOSX_using_homebrew

to install grass7 using home-brew.

When executing  

brew install gdal2 --with-complete --with-unsupported 

I receive error "invalid option: --with-complete"

I cannot find any corrections to the syntax in the release notes.  I'm sure it's a simple thing but I'm just not finding it.  Can anyone assist?

**Comment by jctull** [comment]
You should be able to install by simply doing
`brew install osgeo-grass`
