### ISSUE TITLE
R/RStudio installed via homebrew crashes when running functions from raster library (may not be a brew issue)

### ISSUE THREAD

**Issue by 808zoid** [OSGeo/homebrew-osgeo4mac#1242]
Greetings all, 

Platform: Sierra. 10.12.6

I'm running into this issue (crash/core dump) via R/RStudio (cask) installed via homebrew. Note, it could be a problem related to R itself, however, it appears more likely that the problem is related to my installation of R, than R itself, given that the function is commonly used by 'others' without a problem. 

Please forgive in advance if the reporting of this "bug" is inappropriate in the context of this forum

Installation 
++++++++
$ brew cask install r
and
$ brew cask install rstudio 

Problem
++++++
Commands in R that causes the problem (this may be meaningless to many - sorry!)
>setwd("/users/my-home-dir/work/GIS/R-and-QGIS/SPATIAL_ANALYSIS/")
>dem=raster("vie_dem_srtm.tif") #elevation in meters
>plot(dem, zlim=c(1000,3000)) #areas where elevation is between 1000m-3000m

###Calculate slope
>slope=**terrain**(dem,opt='slope',unit='degrees') # Problem command 

^^^ the above command results in the following->:
*** caught segfault ***
address 0x131965ff8, cause 'memory not mapped'

Traceback:
 1: .terrain(as.double(v), as.integer(c(tr$nrows[i] + 2, nc)), rs,     un, nopt, lonlat, y)
 2: terrain(dem, opt = "slope", unit = "degrees")

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
Selection?: 
++++++

Questions:
+++++++
1) Is there an osgeo (tapped) formula for RStudio or R? 
2) Give that I'm downloading binaries for R/RStudio, could there be a problem with precompiled-dynamic libraries compiled on my platform  - i.e. has anyone else encountered this  (or a similar) issue with R installed via brew? 
3) I've included the output from "brew doctor" below: note: one of the issues, I've noted repeatedly is this warning from homebrew:
=====================
_**Pouring osgeo-liblas-1.8.1_6.sierra.bottle.tar.gz
Warning: osgeo/osgeo4mac/osgeo-liblas dependency gcc was built with a different C++ standard
library (libstdc++ from clang). This may cause problems at runtime.**_
=====================
4) How do I resolve #3 (of course it may not be the problem)

Output from 'brew doctor' (**note* the unlinked libs are superseded by analogous packages from osgeo)**
++++++++++++++++++++++++++
my-home-dir:bin $ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Library/Frameworks/Python.framework/Versions/3.6/bin/python3-config
  /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6-config
  /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6m-config

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libtcl8.6.dylib
  /usr/local/lib/libtk8.6.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/fakemysql.h
  /usr/local/include/fakepq.h
  /usr/local/include/fakesql.h
  /usr/local/include/itcl.h
  /usr/local/include/itcl2TclOO.h
  /usr/local/include/itclDecls.h
  /usr/local/include/itclInt.h
  /usr/local/include/itclIntDecls.h
  /usr/local/include/itclMigrate2TclCore.h
  /usr/local/include/itclTclIntStubsFcn.h
  /usr/local/include/mysqlStubs.h
  /usr/local/include/odbcStubs.h
  /usr/local/include/pqStubs.h
  /usr/local/include/tcl.h
  /usr/local/include/tclDecls.h
  /usr/local/include/tclOO.h
  /usr/local/include/tclOODecls.h
  /usr/local/include/tclPlatDecls.h
  /usr/local/include/tclThread.h
  /usr/local/include/tclTomMath.h
  /usr/local/include/tclTomMathDecls.h
  /usr/local/include/tdbc.h
  /usr/local/include/tdbcDecls.h
  /usr/local/include/tdbcInt.h
  /usr/local/include/tk.h
  /usr/local/include/tkDecls.h
  /usr/local/include/tkPlatDecls.h

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
  /usr/local/lib/pkgconfig/tcl.pc
  /usr/local/lib/pkgconfig/tk.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libtclstub8.6.a
  /usr/local/lib/libtkstub8.6.a

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  gdal
  libgeotiff
  libspatialite
  netcdf
  postgis
  postgresql
  proj

Warning: Some installed formulae are not readable:
  r-gui: unknown version :snow_leopard
+++++++++++++++++++++++++++++

Thank you in advance, and please delete this "issue" if it's not appropriate for this forum.

**Comment by luispuerto** [comment]
osgeo tap doesn't install RStudio and the R formula that installs comes from core. So you should open this issue in the [Homebrew/homebrew-core](https://github.com/Homebrew/homebrew-core/issues) tap.

**Comment by mparish1** [comment]
I had the same problem. If you change the neighbors to 4 (I think the default is 8...so 4 is inferior), then it worked for me. 

so change you slope calculation to:

slope=terrain(dem,opt='slope',unit='degrees', neighbors=4)
