### ISSUE TITLE
Can't run GRASS GIS gui because wxpython error

### ISSUE THREAD

**Issue by alazarolop** [OSGeo/homebrew-osgeo4mac#1246]
Hi,

Last week I upgraded QGIS and GRASS GIS. With QGIS I run in an issue I could solve (https://github.com/OSGeo/homebrew-osgeo4mac/issues/1245), but then I tried to run GRASS GIS gui I got stuck. GRASS GIS itself run and can be manage, but when I try to run the gui I get:
```
Launching <wxpython> GUI in the background, please wait...
ERROR: wxGUI requires wxPython. No module named _core_
You can still use GRASS GIS modules in the command line or in Python.
```
This issue had been described before (https://github.com/OSGeo/homebrew-osgeo4mac/issues/228#issuecomment-506730879), but I couldn't successfully apply the solution.

I have some issues with unlinked formulas in `brew doctor` and my path is:
```
/usr/local/opt/sqlite/bin:/usr/local/sbin:/usr/local/opt/gdal2/bin:/Users/alazaro/.jenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/MacGPG2/bin:/usr/local/share/dotnet:/opt/X11/bin
```
I didn't try to build it from source though. Could it be an issue from the formula? Thank you in advance.

**Comment by neteler** [comment]
The formula still uses GRASS GIS 7.6.x with Python 2:

https://github.com/OSGeo/homebrew-osgeo4mac/blob/master/Formula/osgeo-grass.rb#L16

It might be worthwhile to update to GRASS GIS 7.8 with Python 3 support.

**Comment by jasonrwang** [comment]
My Python 2 (in /usr/local/bin/python2) didn't have wxpython installed, so a simple `python2 -m pip install wxpython` got this to work for me!

**Comment by neteler** [comment]
FYI: We are close to GRASS GIS 7.8.1, as of today:

https://github.com/OSGeo/grass/releases/tag/7.8.1RC2

**Comment by pat-s** [comment]
Running into the same issue even though `wxPython` is installed for python2 and added to `$PATH`.
Even if GRASS >= 7.8 solves this, there should be backward comp available for older versions.

Right now, I cannot get any GRASS formula to start on 10.14.6 (Mojave). :/

**Comment by neteler** [comment]
> Right now, I cannot get any GRASS formula to start on 10.14.6 (Mojave). :/

Do you have any error messages to look at?

**Comment by pat-s** [comment]
Just the already reported 

> ERROR: wxGUI requires wxPython. No module named wxversion

Maybe I missed something but adding the python2 packages to $PATH should actually work when there is a complain about missing py modules.

(Also it is confusing to me why some formulas in this repo have the `osgeo` prefix and some not. Even though this is off-topic.)

**Comment by neteler** [comment]
Could maybe efforts in this repo help? https://github.com/qgis/QGIS-Mac-Packager

**Comment by pat-s** [comment]
Thanks but "uff" - another parallel attempt to get spatial stuff working.
I'd much prefer having everything in one place, i.e. `osgeo4mac`.
If I wouldnt' have to teach tmrw using GRASS I'd probably contribute to getting GRASS 7.8.x working right now.

**Comment by pat-s** [comment]
@neteler Do you have permissions to invite me to the Slack group?

(We can hide this comment later by marking is as off-topic)

**Comment by neteler** [comment]
Sorry, I'm not involved in the other project, please ask there...

**Comment by pat-s** [comment]
@geo-ninja @fjperini Could you invite me to the Slack group?

You can delete this comment afterwards.

Also I think there should be a "less disturbing" way to ask for the invitation. I haven't found one based on the instructions given at https://osgeo.github.io/homebrew-osgeo4mac/ though...

**Comment by alazarolop** [comment]
@pat-s , you should have an invitation in your inbox. Have you tried to just enter your credentials in the Slack sign-in page though. As far as I remember, you didn't need a proper invitation.

**Comment by neteler** [comment]
Did anyone try with Python 3?

**Comment by fjperini** [comment]
@alazarolop @neteler @jasonrwang @pat-s. Check #1366 Working!

**Comment by pat-s** [comment]
Works for me after installing `wxpython` via `pip3`.

**Comment by fjperini** [comment]
@pat-s Yes, I also had to do the same. For some reason, the `wx` module when installing `wxpython` does not appear in `/usr/local/lib/python3.7/site-packages`, but if it appears for @alazarolop, then it must be something of each machine.
I can have `wxpython` installed in `/usr/local/Cellar/osgeo-grass/7.8.2/libexec/vendor/lib/python3.7/site-packages/`.

**Comment by alazarolop** [comment]
@fjperini how can we install `wxpython` in this location https://github.com/OSGeo/homebrew-osgeo4mac/issues/1246#issuecomment-587167964?

**Comment by neteler** [comment]
New upstream ticket: https://github.com/OSGeo/grass/issues/457
