### ISSUE TITLE
Unable to import pyGRASS: grass_gis.7.0.3 not found.

### ISSUE THREAD

**Issue by mankoff** [OSGeo/homebrew-osgeo4mac#126]
I'm running grass 7.0.3 installed via homebrew. Everything seems to work, including the GUI, but I see the following message at the console:

````
> g.gui.psmap
Unable to import pyGRASS: grass_gis.7.0.3 not found.
Some functionality will be not accessible
```

When I search `/usr/local` for anything grass and python related (`$ find . -name "*grass*.py"`), nothing shows up. Should I be adjusting my `$PYTHONPATH` to something for grass?

**Comment by mankoff** [comment]
OK I've found the python scripts and made some progress, but still not fully working.

The python scripts can be added to `PYTHONPATH` by adding `/usr/local/opt/grass-70/grass-base/etc/python`.

Then, in Python, `import grass.lib` works, but `import grass.script` crashes with:

```
>>> import grass.script
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/opt/grass-70/grass-base/etc/python/grass/script/__init__.py", line 4, in <module>
    from core   import *
  File "/usr/local/opt/grass-70/grass-base/etc/python/grass/script/core.py", line 36, in <module>
    gettext.install('grasslibs', os.path.join(os.getenv("GISBASE"), 'locale'))
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 70, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'
```

Note that it appears to be looking for `GISBASE`, but `grass70 --help` shows only `GISDBASE` (note the **D**). Is this a typo? Or are these two different variables?

Anyway, setting GISBASE to *anything* fixes the above problem:

```
$ export GISBASE=
$ python
>>> import grass.script # no error
```

However, now that `GISBASE` is set, `grass70` won't start. I can set it to the actual grass DB root rather than empty as above, and it still doesn't work.

**Comment by mankoff** [comment]
I figured out difference between `GISBASE` and `GISDBASE`. `GISBASE` should be `/usr/local/Cellar/grass-70/7.0.3`. `GISDBASE` is the *user database*. Either way, I'm still getting Python import errors from `g.gui.psmap`.

**Comment by bolliger32** [comment]
I have a similar problem except that the `grass_gis.7.0.3` library is nowhere to be found. I just installed grass 7.0.3 via homebrew after [this](https://github.com/OSGeo/homebrew-osgeo4mac/issues/118#issuecomment-200278686) update. `GISBASE` and `PYTHONPATH` are set to `/usr/local/Cellar/grass-70/7.0.3/grass-7.0.3` and `/usr/local/Cellar/grass-70/7.0.3/grass-7.0.3/etc/python` respectively.

Where is this `grass_gis.7.0.3` library supposed to be?

**Comment by dakcarto** [comment]
Hi,

After reviewing the GRASS Python Wiki ([here](http://grasswiki.osgeo.org/wiki/GRASS_and_Python#Linux) and [here](http://grasswiki.osgeo.org/wiki/Working_with_GRASS_without_starting_it_explicitly)), I've created a `grass_python.env` to source into a bash session:

```bash
export GISBASE="$(grass70 --config path)"
export PATH="$PATH:$GISBASE/bin:$GISBASE/scripts"
export DYLD_LIBRARY_PATH="$LD_LIBRARY_PATH:$GISBASE/lib"
# for parallel session management, we use process ID (PID) as lock file number:
export GIS_LOCK=$$
# path to GRASS settings file
export GISRC="$HOME/.grass7/rc"
export PYTHONPATH="$PYTHONPATH:$GISBASE/etc/python"
```

Sourcing this, I get:

```
$> g.gui.psmap --help

Description:
 Tool for creating hardcopy map outputs.

Keywords:
 general, GUI, printing

Usage:
 g.gui.psmap [file=name] [--help] [--verbose] [--quiet] [--ui]

Flags:
 --h   Print usage summary
 --v   Verbose module output
 --q   Quiet module output
 --ui  Force launching GUI dialog

Parameters:
  file   File containing mapping instructions to load
          See ps.map manual for details
```

Not sure on the `GIS_LOCK=$$` bit on OS X, but this is a start. You will need Homebrew's `python` and `grass70` on your PATH as well. There is also the concern of `DYLD_LIBRARY_PATH` being ignored (stripped) on OS X 10.11. Any binary utility linking should work without that env var, since everything has been fixed up using `install_name_tool`; but, if you get errors about dylibs not being found, we'll probably have to find a workaround.

Also, review `grass70` startup script for other session init methodology.

Not sure on the best place to put this in the `grass-70` install dir. Maybe in:
```
#{prefix}/environ/grass_python.env
```
?

**Comment by mankoff** [comment]
So... although I see the following error:

```
Unable to import pyGRASS: grass_gis.7.0.3 not found.
Some functionality will be not accessible
```

with `g.gui.psmap` or `g.gui.mapswipe`, everything appears to work fine. I can't find any issues with the gui tools.

**Comment by ShakyaKiran** [comment]
Hello, I am new to grass and want to implement it for atmospheric correction with python.  I have regular python 2.7 and have installed grass gis 7.0.4 in windiws 10.  I want to use pygrass but got lost in configuration and environment variable setup.  I will be very helpful if someone can help me on this.
