### ISSUE TITLE
Third-party binary links broken (MrSID and ECW/JP2)

### ISSUE THREAD

**Issue by jctull** [OSGeo/homebrew-osgeo4mac#1263]
Trying to install osgeo-mrsid-sdk results in an error. I suspect it may be due to outdated links to archives on the old/nonexistent lizardtech server. The current available archives are at:
https://www.extensis.com/support/developers

brew install osgeo-mrsid-sdk
==> Installing osgeo-mrsid-sdk from osgeo/osgeo4mac
Error: Formula expects to locate the following archive:
  MrSID_DSDK-9.5.1.4427-darwin14.universal.clang60.tar.gz

in the HOMEBREW_CACHE directory:
  /Users/xxx/Library/Caches/Homebrew

Copy archive to cache or create a symlink in cache to archive:
  ln -sf /path/to/archive $(brew --cache)/
Error: An exception occurred within a child process:
  SystemExit: exit

**Comment by jctull** [comment]
A similar issues occurs for erdas ecw/jp2:

brew install osgeo-ecwjp2-sdk
==> Installing osgeo-ecwjp2-sdk from osgeo/osgeo4mac
osgeo-ecwjp2-sdk: ERDAS ECW/JP2 SDK was not found at:
  /Hexagon/ERDASEcwJpeg2000SDK5.4.0/Desktop_Read-Only

Download SDK and install 'Desktop Read-Only' to default location from:
  http://download.intergraph.com/?ProductName=ERDAS%20ECW/JPEG2000%20SDK
Error: An unsatisfied requirement failed this build.

**Comment by alazarolop** [comment]
Hi @jctull , a lot of issues are rising because of the upgrading process of formulas. But I'm not sure about this one (https://github.com/OSGeo/homebrew-osgeo4mac/issues/1263#issuecomment-532776818). 

Have your tried to actually install the SDK?. It's a manual process as described:
```
Download SDK and install 'Desktop Read-Only' to default location from:
http://download.intergraph.com/?ProductName=ERDAS%20ECW/JPEG2000%20SDK
```
After that, you will be able to install the formula. I'm not sure about the first problem though.

**Comment by jctull** [comment]
I was able to manually install the SDK. When I run, e.g., 'gdalinfo --formats', I get this error:

ERROR 1: dlopen(/usr/local/lib/gdalplugins/3.0/gdal_ECW_JP2ECW.dylib, 1): Symbol not found: __ZN14GDALPamDataset7SetGCPsEiPK8GDAL_GCPPKc
  Referenced from: /usr/local/lib/gdalplugins/3.0/gdal_ECW_JP2ECW.dylib
  Expected in: flat namespace
 in /usr/local/lib/gdalplugins/3.0/gdal_ECW_JP2ECW.dylib
ERROR 1: dlopen(/usr/local/lib/gdalplugins/3.0/gdal_ECW_JP2ECW.dylib, 1): Symbol not found: __ZN14GDALPamDataset7SetGCPsEiPK8GDAL_GCPPKc
  Referenced from: /usr/local/lib/gdalplugins/3.0/gdal_ECW_JP2ECW.dylib
  Expected in: flat namespace
 in /usr/local/lib/gdalplugins/3.0/gdal_ECW_JP2ECW.dylib
Supported Formats:
...

**Comment by roblabs** [comment]
Regarding the `erdas ecw/jp2` issue —

### **Is the right fix to upgrade to ERDAS 5.5?**

The link in the error log that points `Intergraph.com` is broken.  I was able to find this link to download the image for version 5.5.  (Which doesn't work on Catalina, _different issue_)

* https://download.hexagongeospatial.com/downloads/ecw/erdas-ecw-jp2-sdk-v5-5-macos?result=true


But the source requires 5.4 which does not seem to be available from Hexagon (at least the link that I guessed at)

https://github.com/OSGeo/homebrew-osgeo4mac/blob/master/Formula/osgeo-ecwjp2-sdk.rb#L3-L15

**Comment by songololo** [comment]
@roblabs do you know if the above issues affect QGIS formula installation on Catalina?

New issue created to track Catalina stability for QGIS formula:
https://github.com/OSGeo/homebrew-osgeo4mac/issues/1268

**Comment by alazarolop** [comment]
This should be easily fixed editing the directory in your local formula `osgeo-ecwjp2-sdk` until it's changed in the tap:
```
ECWJP2_SDK = "/Hexagon/ERDASEcwJpeg2000SDK5.4.0/Desktop_Read-Only".freeze
```
to the correct one, probably:
```
ECWJP2_SDK = "/Hexagon/ERDASEcwJpeg2000SDK5.5.0/Desktop_Read-Only".freeze
```
About MacOS Catalina issue, I guess it's related to the read-only system volume. Should you unlock it during the installation and lock in down again? I'm not sure how to do it though. Maybe with this [link](https://www.reddit.com/r/MacOS/comments/caiue5/macos_catalina_readonly_file_system_with_sip/et94g0e/)?
