### ISSUE TITLE
osgeo-grass r dependency

### ISSUE THREAD

**Issue by rkrug** [OSGeo/homebrew-osgeo4mac#1264]
I've... 
- I **not** read 
	- [ ] the [reporting issues](https://github.com/OSGeo/homebrew-osgeo4mac/docs/reporting-issues)
	- [ ] the [troubleshooting](https://github.com/OSGeo/homebrew-osgeo4mac/docs/troubleshooting)
 **as the links are dead**

- [X] I checked the documentation and found no answer
- [X] I tried to install after following the suggestions
- [x] I am running the latest version (`brew update` twice?)
- [x] I checked to make sure that this issue has not already been filed
- [ ] I uploaded logs: `brew gist-logs formula`

**Describe the bug**
I have `sethrfore/r-srf`s R installed and would like to keep it, but the formula for grass gives me the following error:

```
Error: r is already installed from sethrfore/r-srf!
Please `brew uninstall r` first."
```

As far as know, R is not e dependency of grass, wherefore the dependency of r which is here
https://github.com/OSGeo/homebrew-osgeo4mac/blob/e3b64237d09f180abe3d2860da71161d1027134d/Formula/osgeo-grass.rb#L94 should be made optional?

as additional info, all other dependencies are installed:
```
13:54 $ brew info osgeo-grass
osgeo/osgeo4mac/osgeo-grass: stable 7.6.1 (bottled), HEAD
Geographic Resources Analysis Support System
https://grass.osgeo.org/
Not installed
From: https://github.com/osgeo/homebrew-osgeo4mac/blob/master/Formula/osgeo-grass.rb
==> Dependencies
Build: autoconf ✔, automake ✔, pkg-config ✔
Required: python@2 ✔, boost ✔, libiconv ✔, bison ✔, cairo ✔, flex ✔, freetype ✔, gettext ✔, ghostscript ✔, libtiff ✔, libpng ✔, sqlite ✔, regex-opt ✔, geos ✔, readline ✔, lapack ✔, openblas ✔, bzip2 ✔, zlib ✔, unixodbc ✔, wxmac ✔, wxpython ✔, zstd ✔, lbzip2 ✔, xz ✔, byacc ✔, subversion ✔, openjpeg ✔, osgeo-netcdf ✔, osgeo-proj ✔, osgeo-gdal ✔, osgeo-gdal-python ✔, osgeo-libgeotiff ✔, py3cairo ✔, pygobject3 ✔, pygobject ✔, osgeo-pyqt ✔, numpy ✔, scipy ✔, osgeo-matplotlib ✔, osgeo-liblas ✔, mysql ✔, r ✘, osgeo-postgresql ✔
Recommended: fftw ✔, tcl-tk ✔
Optional: avce00 ✘
==> Requirements
Required: x11 ✔
==> Options
--with-app
	Build GRASS.app Package
--with-aqua
	Build with experimental Aqua GUI backend
--with-avce00
	Build with AVCE00 support: Make Arc/Info (binary) Vector Coverages appear as E00
--with-others
	Build with other optional dependencies
--with-pg10
	Build with PostgreSQL 10 client
--without-fftw
	Build without fftw support
--without-gui
	Build without WxPython interface. Command line tools still available
--without-tcl-tk
	Build without tcl-tk support
--HEAD
	Install HEAD version
==> Caveats

If it is the case that you can change the shebang at the beginning of
the script to enforce Python 2 usage.

  #!/usr/bin/env python

Should be changed into

  #!/usr/bin/env python2

✔ ~
13:58 $
```

**Comment by alazarolop** [comment]
Hi @jctull , not sure why your links are dead. This is [the OSgeo4mac website](https://osgeo.github.io/homebrew-osgeo4mac/docs/installing-QGIS-3/) which contains the info about the R dependency installation. I hope it can help you.

**Comment by rkrug** [comment]
@alazarolop Thanks -that should help. 

But I am trying to install grass, and I do not think that R is a requirement to run grass. So R should be an optional dependency.

**Comment by jctull** [comment]
> Hi @jctull , not sure why your links are dead. This is [the OSgeo4mac website](https://osgeo.github.io/homebrew-osgeo4mac/docs/installing-QGIS-3/) which contains the info about the R dependency installation. I hope it can help you.

Hi @alazarolop but this was not my issue.

@rkrug You can try to build osgeo-grass from source without the R dependency. As noted in the link above, osgeo will not work with the version of R you have installed.

`brew install --build-from-source --without-r osgeo-grass`

**Comment by rkrug** [comment]
This option does not exist in `osgeo-grass`, only in QGIS.

So - I think it should be added to osgeo-grass, as grass does not need R, even though without doubt, very useful.

**Comment by alazarolop** [comment]
@rkrug I reckon the reason why the R dependency is there is because you can launch a R session from within GRASS. Could you solve the issue with the guide? 

I do agree it should be added a flag option as long as there is no conflict with other formulas.

**Comment by rkrug** [comment]
@alazarolop if you are referring to this guide [this QGIS Guide](https://osgeo.github.io/homebrew-osgeo4mac/docs/installing-QGIS-3/), than it surely will help, but I did not try it, as I would prefer not to play around at that level if not necessary (which it is not at the moment)

Ao yes - please add the flag option `--without-R` in the grass formula! If there is a formula which depends on GRASS installing R, that there is a problem in that formula, as R should be optional for grass.

**Comment by rkrug** [comment]
and the links are still dead.
