### ISSUE TITLE
Can't build GDAL with head

### ISSUE THREAD

**Issue by palmerj** [OSGeo/homebrew-osgeo4mac#1267]
I read:
- [x] the [reporting issues](https://github.com/OSGeo/homebrew-osgeo4mac/docs/reporting-issues)
- [x] the [troubleshooting](https://github.com/OSGeo/homebrew-osgeo4mac/docs/troubleshooting)
- [x] I checked the documentation and found no answer
- [x] I tried to install after following the suggestions
- [x] I am running the latest version (`brew update` twice?)
- [x] I checked to make sure that this issue has not already been filed
- [ ] I uploaded logs: `brew gist-logs formula`

**Describe the bug**

Since https://github.com/OSGeo/homebrew-osgeo4mac/pull/1252 I can not build gdal with `--head`. I get a ruby error during the build process:

```
Errno::ENOENT: No such file or directory @ rb_sysopen - configure
```

I think it's because the change directory code has been commented out: https://github.com/OSGeo/homebrew-osgeo4mac/blob/master/Formula/osgeo-gdal.rb#L296

**To Reproduce**

Run `brew install osgeo-gdal install --head --env=std`

Using MacOS Catalina 10.15 (19A602)
CLT: 1100.0.33.8
Xcode: 11.1

**Comment by palmerj** [comment]
I hacked the osgeo-gdal.rb build script to try and build, but now I get another error during the gdal make:

```
/bin/sh: sphinx-build: command not found
```

**Comment by palmerj** [comment]
`brew install sphinx-doc` to get past the sphinx-build issue.

Note I'm having random clang crashes while trying to compile the source code. Somethings clang hangs while trying to compile one source file, other times clang crashes with a error report. Is clang on Catalina stable?

**Comment by songololo** [comment]
@palmerj were you able to get the QGIS formula working on Catalina?

New issue created to track Catalina stability:
https://github.com/OSGeo/homebrew-osgeo4mac/issues/1268

**Comment by palmerj** [comment]
> @palmerj do you know if the above issues affect QGIS formula installation on Catalina?

Sorry I haven't had time to test that
