### ISSUE TITLE
Is QGIS stable for Catalina Mac OS?

### ISSUE THREAD

**Issue by songololo** [OSGeo/homebrew-osgeo4mac#1268]
Is the QGIS formula stable for systems running Catalina OS?

I have searched issues for bugs with Catalina and three separate issues came up, though perusing these does not give a clear indication on whether these issues may have been resolved:
- https://github.com/OSGeo/homebrew-osgeo4mac/issues/1267
- https://github.com/OSGeo/homebrew-osgeo4mac/issues/1263
- https://github.com/OSGeo/homebrew-osgeo4mac/issues/1245

Would it be possible for QGIS formula users that have upgraded to Catalina to report / link issues to this issue and whether they have been resolved so that we can track when it might be safe to upgrade Mac OS to Catalina?

**Comment by alazarolop** [comment]
`osgeo-qgis` is hardly working in previous macOS releases as there are some misalignment in dependencies within the tap. As for now you may easily use the cask version `brew cask install qgis` until everything is fixed with GDAL 3 and Proj 6.

**Comment by songololo** [comment]
I've been able to upgrade, I did a brew uninstall and clean install.

QGIS is a bit of a mission to install because dependencies are constantly changing / breaking.

I had to follow the instructions in https://github.com/OSGeo/homebrew-osgeo4mac/issues/1261 to get the new installation working, though I believe this is not Catalina related.
