### ISSUE TITLE
qgis-214 build fails on El Captain

### ISSUE THREAD

**Issue by mbalcilar** [OSGeo/homebrew-osgeo4mac#129]
The build fails around 53% with following message:

/usr/local/opt/sqlite/lib/libsqlite3.dylib /usr/local/lib/libspatialite.dylib
[ 53%] Built target qgis_gui
make: *** [all] Error 2

I have freshly build all dependencies. Here is the gist log:
https://gist.github.com/d594f0fc3d3c626b08b522b5bb3d2535

OS X 10.11.4 with newest Xcode.

Any workaround?

**Comment by dakcarto** [comment]
Hi. Thanks for reporting! 

The error is actually related to C++ conversion mapping in the Python bindings via `sip`:

```
/tmp/qgis-21420160415-2030-1ea6c67/QGIS-final-2_14_1/python/core/conversions.sip:735:7: error: member reference type 'QMap<qint64, QMap<int, QVariant> > *' (aka 'QMap<long long, QMap<int, QVariant> > *') is a pointer; did you mean to use '->'?
    qm.insert(k, *t);
    ~~^
      ->
/tmp/qgis-21420160415-2030-1ea6c67/QGIS-final-2_14_1/python/core/conversions.sip:735:18: error: no viable conversion from 'QVariant' to 'const QMap<int, QVariant>'
    qm.insert(k, *t);
                 ^~
/usr/local/Cellar/qt/4.8.7_2/lib/QtCore.framework/Headers/qmap.h:183:12: note: candidate constructor not viable: no known conversion from 'QVariant' to 'const QMap<int, QVariant> &' for 1st argument
    inline QMap(const QMap<Key, T> &other) : d(other.d)
           ^
/usr/local/Cellar/qt/4.8.7_2/lib/QtCore.framework/Headers/qmap.h:398:46: note: passing argument to parameter 'value' here
    iterator insert(const Key &key, const T &value);
```
The `sip` formula was just upgraded to 2.1.8, so maybe it has caused a build failure. Doing a build here with upgraded formulae to test.

Did you do a `brew update` right be fore building `qgis-214`?

**Comment by dakcarto** [comment]
Confirmed build issue with latest sip, at least on my dev build for `release-2_14` branch, which built fine last week. Looking into a fix.

**Comment by dakcarto** [comment]
Ok, everything should be fixed with latest commits. Builds fine on 10.11.4 now, with `sip` 4.18 installed.

Please test when you have the time.

**Comment by mbalcilar** [comment]
Thanks for quick fix. Builds fine now.
