### ISSUE TITLE
Recent upgrade to GDAL 3 breaks the gdal2 installation

### ISSUE THREAD

**Issue by thclark** [OSGeo/homebrew-osgeo4mac#1290]
**Please answers the following**

I've... 
- I read
	- [ ] the [reporting issues](https://github.com/OSGeo/homebrew-osgeo4mac/docs/reporting-issues) **not read because link is broken**
	- [ ] the [troubleshooting](https://github.com/OSGeo/homebrew-osgeo4mac/docs/troubleshooting) **not read because link is broken**
- [x] I checked the documentation and found no answer
- [x] I tried to install after following the suggestions
- [x] I am running the latest version (`brew update` twice?)
- [x] I checked to make sure that this issue has not already been filed
- [x] I uploaded logs: `brew gist-logs formula`

**Describe the bug**

[This commit](https://github.com/OSGeo/homebrew-osgeo4mac/commit/d7cfceb2fa6b3b429da8305640fff7910b1e6f5e) does a major version update of GDAL, which is fine (it's expected to be latest), but I believe the `gdal2` keg is aliased to `osgeo-gdal` and is therefore now installing the incorrect version.

**To Reproduce**

```
brew tap osgeo/osgeo4mac && brew tap --repair
brew install gdal2
==> Installing osgeo-gdal from osgeo/osgeo4mac
==> Downloading https://github.com/OSGeo/gdal/releases/download/v3.0.2/gdal-3.0.2.tar.gz
```
**Expected behavior**

That `brew install gdal2` would install gdal 2, not gdal 3

**Additional context**
99% sure this is irrelevant, but since the template asks for it... `brew doctor` output: 

```shellWarning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/thc29/.pyenv/shims/python3.6m-config
  /Users/thc29/.pyenv/shims/python-config
  /Users/thc29/.pyenv/shims/python3-config
  /Users/thc29/.pyenv/shims/python3.6-config

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  proj
  postgresql
  libgeotiff
  libspatialite
  netcdf

Warning: Some installed formulae are missing dependencies.
You should `brew install` the missing dependencies:
  brew install gdal
**NB this is missing because I've obviously not installed gdal yet!**
```

**Logs**
https://gist.github.com/beeb62a4fadda2f7b41876b14ad65455

**Comment by thclark** [comment]
Update: It might be worth considering using homebrew's @ version notation system for this in the same way that (for example) node's major versions are managed on homebrew:

eg node latest:

https://github.com/Homebrew/homebrew-core/blob/master/Formula/node@10.rb

**Comment by thclark** [comment]
No, stalebot! Just because nobody has commented doesn't mean it's no longer an issue!

**Comment by thclark** [comment]
No, stalebot! Just because nobody has commented doesn't mean it's no longer an issue!

**Comment by fjperini** [comment]
@tbonfort All tools are already using GDAL 3. Do you need GDAL 2?

**Comment by timo-piirmann** [comment]
There is an up-to-date GDAL 3 in the core brew. I also expected to get GDAL 2 version from here as the name suggests. And depending on the software project there are still stuff that expects GDAL < 3 to work.

**Comment by ReadMost** [comment]
I have the same problem
Why does it install version3 when I show explicitly version? Does it stupid as this stalebot?
