### ISSUE TITLE
No PostgreSQL driver in osgeo-gdal

### ISSUE THREAD

**Issue by peteWT** [OSGeo/homebrew-osgeo4mac#1291]
**Please answers the following**

I've... 
- I read
	- [x] the [reporting issues](https://github.com/OSGeo/homebrew-osgeo4mac/docs/reporting-issues)
	- [x] the [troubleshooting](https://github.com/OSGeo/homebrew-osgeo4mac/docs/troubleshooting)
- [x] I checked the documentation and found no answer
- [x] I tried to install after following the suggestions
- [x] I am running the latest version (`brew update` twice?)
- [x] I checked to make sure that this issue has not already been filed
- [x] I uploaded logs: `brew gist-logs formula`

**Describe the bug**
Somehow  to PostgreSQL driver is absent from gdal

**To Reproduce**

ogrinfo --formats

**Expected behavior**

PostgreSQL in the list of formats available

**Screenshots**

**Additional context**

`brew doctor` output: 

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/pete/.pyenv/shims/python2-config
  /Users/pete/.pyenv/shims/python3.7-config
  /Users/pete/.pyenv/shims/python2.7-config
  /Users/pete/.pyenv/shims/python3.7m-config
  /Users/pete/.pyenv/shims/python-config
  /Users/pete/.pyenv/shims/python3-config
  /Users/pete/.pyenv/shims/python3.8-config

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libwkhtmltox.0.12.5.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/wkhtmltox/image.h
  /usr/local/include/wkhtmltox/pdf.h

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  proj
  postgresql
  libgeotiff
  libspatialite
  netcdf

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.zshrc
```

**Logs**

**Comment by sagadave** [comment]
Confirming the PostgreSQL driver is missing from osgeo-gdal. 

Tried 
`brew install osgeo-gdal --with-pg`
but that didn't install the driver.  

dave$ ogrinfo --formats 
Supported Formats:
  PCIDSK -raster,vector- (rw+v): PCIDSK Database File
  netCDF -raster,vector- (rw+s): Network Common Data Format
  PDS4 -raster,vector- (rw+vs): NASA Planetary Data System 4
  JP2OpenJPEG -raster,vector- (rwv): JPEG-2000 driver based on OpenJPEG library
  JPEG2000 -raster,vector- (rwv): JPEG-2000 part 1 (ISO/IEC 15444-1), based on Jasper library
  PDF -raster,vector- (w+): Geospatial PDF
  MBTiles -raster,vector- (rw+v): MBTiles
  EEDA -vector- (ro): Earth Engine Data API
  ESRI Shapefile -vector- (rw+v): ESRI Shapefile
  MapInfo File -vector- (rw+v): MapInfo File
  UK .NTF -vector- (rov): UK .NTF
  OGR_SDTS -vector- (rov): SDTS
  S57 -vector- (rw+v): IHO S-57 (ENC)
  DGN -vector- (rw+v): Microstation DGN
  OGR_VRT -vector- (rov): VRT - Virtual Datasource
  REC -vector- (ro): EPIInfo .REC 
  Memory -vector- (rw+): Memory
  BNA -vector- (rw+v): Atlas BNA
  CSV -vector- (rw+v): Comma Separated Value (.csv)
  NAS -vector- (rov): NAS - ALKIS
  GML -vector- (rw+v): Geography Markup Language (GML)
  GPX -vector- (rw+v): GPX
  LIBKML -vector- (rw+v): Keyhole Markup Language (LIBKML)
  KML -vector- (rw+v): Keyhole Markup Language (KML)
  GeoJSON -vector- (rw+v): GeoJSON
  GeoJSONSeq -vector- (rw+v): GeoJSON Sequence
  ESRIJSON -vector- (rov): ESRIJSON
  TopoJSON -vector- (rov): TopoJSON
  Interlis 1 -vector- (rw+v): Interlis 1
  Interlis 2 -vector- (rw+v): Interlis 2
  OGR_GMT -vector- (rw+v): GMT ASCII Vectors (.gmt)
  GPKG -raster,vector- (rw+vs): GeoPackage
  SQLite -vector- (rw+v): SQLite / Spatialite
  OGR_DODS -vector- (ro): OGR_DODS
  ODBC -vector- (rw+): ODBC
  WAsP -vector- (rw+v): WAsP .map format
  PGeo -vector- (ro): ESRI Personal GeoDatabase
  MSSQLSpatial -vector- (rw+): Microsoft SQL Server Spatial Database
  OpenFileGDB -vector- (rov): ESRI FileGDB
  XPlane -vector- (rov): X-Plane/Flightgear aeronautical data
  DXF -vector- (rw+v): AutoCAD DXF
  CAD -raster,vector- (rovs): AutoCAD Driver
  Geoconcept -vector- (rw+v): Geoconcept
  GeoRSS -vector- (rw+v): GeoRSS
  GPSTrackMaker -vector- (rw+v): GPSTrackMaker
  VFK -vector- (ro): Czech Cadastral Exchange Data Format
  PGDUMP -vector- (w+v): PostgreSQL SQL dump
  OSM -vector- (rov): OpenStreetMap XML and PBF
  GPSBabel -vector- (rw+): GPSBabel
  SUA -vector- (rov): Tim Newport-Peace's Special Use Airspace Format
  OpenAir -vector- (rov): OpenAir
  OGR_PDS -vector- (rov): Planetary Data Systems TABLE
  WFS -vector- (rov): OGC WFS (Web Feature Service)
  WFS3 -vector- (ro): OGC WFS 3 client (Web Feature Service)
  HTF -vector- (rov): Hydrographic Transfer Vector
  AeronavFAA -vector- (rov): Aeronav FAA
  Geomedia -vector- (ro): Geomedia .mdb
  EDIGEO -vector- (rov): French EDIGEO exchange format
  GFT -vector- (rw+): Google Fusion Tables
  SVG -vector- (rov): Scalable Vector Graphics
  CouchDB -vector- (rw+): CouchDB / GeoCouch
  Cloudant -vector- (rw+): Cloudant / CouchDB
  Idrisi -vector- (rov): Idrisi Vector (.vct)
  ARCGEN -vector- (rov): Arc/Info Generate
  SEGUKOOA -vector- (rov): SEG-P1 / UKOOA P1/90
  SEGY -vector- (rov): SEG-Y
  XLS -vector- (ro): MS Excel format
  ODS -vector- (rw+v): Open Document/ LibreOffice / OpenOffice Spreadsheet 
  XLSX -vector- (rw+v): MS Office Open XML spreadsheet
  ElasticSearch -vector- (rw+): Elastic Search
  Walk -vector- (ro): Walk
  Carto -vector- (rw+): Carto
  AmigoCloud -vector- (rw+): AmigoCloud
  SXF -vector- (rov): Storage and eXchange Format
  Selafin -vector- (rw+v): Selafin
  JML -vector- (rw+v): OpenJUMP JML
  PLSCENES -raster,vector- (ro): Planet Labs Scenes API
  CSW -vector- (ro): OGC CSW (Catalog  Service for the Web)
  VDV -vector- (rw+v): VDV-451/VDV-452/INTREST Data Format
  GMLAS -vector- (rwv): Geography Markup Language (GML) driven by application schemas
  MVT -vector- (rw+v): Mapbox Vector Tiles
  TIGER -vector- (rw+v): U.S. Census TIGER/Line
  AVCBin -vector- (rov): Arc/Info Binary Coverage
  AVCE00 -vector- (rov): Arc/Info E00 (ASCII) Coverage
  NGW -raster,vector- (rw+s): NextGIS Web
  HTTP -raster,vector- (ro): HTTP Fetching Wrapper

**Comment by kristfal** [comment]
2nd this. @sagadave did you find any workarounds or alternatives to installing gdal with postgresql > 3.0.0 ?

**Comment by kristfal** [comment]
Ok, for those in need of GDAL with a working PG12 + PostGIS environment on Mac OS, here is what I did to make it work:

0. Delete any previous installation of postgresql (installed binary, via homebrew, etc.)

1. Download and install Postgresql12 with postgis using Postgresapp or whatever preferred method you have to get Postgresql with Postgis running.

2. Temporarily set up Postgresapp to your PATH:

```
sudo mkdir -p /etc/paths.d &&
echo /Applications/Postgres.app/Contents/Versions/latest/bin | sudo tee /etc/paths.d/postgresapp
```

After this, close and reopen your Terminal.

3. Clone gdal from source github and install all dependencies required to compile from source via `brew install [follow the readme of gdal..]`

4. Install libpq with development headers via `brew install libpq`

5. Export `libpq` to your path by following the install suggestion printed at the end of the brew install command. Ex: `export PKG_CONFIG_PATH=/path/to/libpq`

6. Configure gdal from `<root>/gdal` using `./configure --with-threads --with-pg=YES --disable-static` and verify that it prints `PostgreSQL=yes`

7. Compile with `sudo make & sudo make install`

8. Remove the Postgresapp PATH reference with `sudo rm /etc/paths.d/postgresapp`

9. Verify installation by `which ogr2ogr && ogr2ogr --version`. It should print something like:

```
/usr/local/bin/ogr2ogr
GDAL 3.1.0dev, released 2019/99/99
```

10. Verify postgresql driver persence by `ogrinfo --formats | grep PostgreSQL` which should print:

```
PostgreSQL -vector- (rw+): PostgreSQL/PostGIS
PGDUMP -vector- (w+v): PostgreSQL SQL dump
```

11. Note: Due to a bug with current version of Gdal, we'll need to use `export PGGSSENCMODE=disable` whenever we use ogr2ogr postgresql bindings.

**Comment by tbussmann** [comment]
the issue here lies likely in https://github.com/OSGeo/homebrew-osgeo4mac/blob/ad92804e65a819d1c9c839cd2705bb3e0a2222e8/Formula/osgeo-gdal.rb#L315-L319 with GDAL 3.0.x the configure option `--with-pg` has changed and https://github.com/OSGeo/homebrew-osgeo4mac/commit/d7cfceb2fa6b3b429da8305640fff7910b1e6f5e missed to adopt to that. Passing a path to `pg_config` is no longer supported, only `yes` or `no`, see https://github.com/OSGeo/gdal/commit/45e06386d9099cbbe4f8eb7b4c2b8edca09ed144

**Comment by bahoo** [comment]
☝️ Can confirm!

**Comment by jparish3** [comment]
/usr/local/Cellar/osgeo-gdal/3.0.2: 222 files, 53.6MB  still gets: Unable to find driver `PostgreSQL'.

**Comment by jparish3** [comment]
now getting a basic install issue: dyld: Library not loaded: /usr/local/opt/cfitsio/lib/libcfitsio.7.dylib
  Referenced from: /usr/local/bin/ogr2ogr
  Reason: image not found

**Comment by stranljip** [comment]
> now getting a basic install issue: dyld: Library not loaded: /usr/local/opt/cfitsio/lib/libcfitsio.7.dylib
> Referenced from: /usr/local/bin/ogr2ogr
> Reason: image not found

This seems to be a wrong dependency. The current installed version from Homebrew is libcfitsio.8.dylib

**Comment by tbussmann** [comment]
@jparish3: as far as I see there have not been any attempts to solve the issue in this repo, yet. One of the maintainers would need to take care of it. @bahoo did quickfix it in his fork with the information provided (thus still not properly handle the `--with-pg10` flag. If that is flag is still needed the pkg-config search would need to be influenced likely by setting PKG_CONFIG_PATH or the like - I don't know much about homebrew dependency handling and release politics of this tap) Thanks to the patch I've landed in gdal upstream a `--head` install of this formula should now error out to make the need for changes obvious.

**Comment by fjperini** [comment]
I will review this!

**Comment by alazarolop** [comment]
It should be fixed with the latest release, could you confirm @peteWT?
