### ISSUE TITLE
Cannot install QGIS — missing pygtk dependency

### ISSUE THREAD

**Issue by warpedgeoid** [OSGeo/homebrew-osgeo4mac#1293]
The pygtk dependency appears to now be missing, completely breaking QGIS installation on a new machine.

`➜ brew install osgeo-qgis-ltr
==> Installing osgeo-qgis-ltr from osgeo/osgeo4mac
Error: No available formula with the name "pygtk" (dependency of osgeo/osgeo4mac/osgeo-qgis-ltr)
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.`

**Comment by gsdali** [comment]
I have also run into this issue.

**Comment by chrisn-au** [comment]
as do I

**Comment by rdornas** [comment]
Me too.

**Comment by warpedgeoid** [comment]
This appears to be happening with both the LTR and non-LTR version of this formula.

**Comment by markegge** [comment]
Same here.

**Comment by jakobjassmann** [comment]
Same problem here. The reason seems to be the recent removal of the pygtk formula from  homebrew/core. Looks like the team maintining the core formulae has decided pgtk is"deprecated" and removed it. 

I guess a long term solution will have to be found to remove the dependency for pygtk from the osgeo-qgis and osgeo-qgis-ltr fromulae. 

If you are in an urgent rush (like me), you can install the relevant missing packages by retrieving the formula via git, saving them as local formulae and then installing them with brew (see below).

```
# Retrieve old pygtk formula and save as temporary file in active folder
git -C "$(brew --repo homebrew/core)" show 6258719db^:Formula/pygtk.rb > pygtk.rb
# Retrieve old pygobject formula (pygtk dependency) 
git -C "$(brew --repo homebrew/core)" show fcfa254fc^:Formula/pygobject.rb > pygobject.rb
# install local formulae form files
brew install pygobject.rb pygtk.rb
# remove temporary formulae files (if needed)
rm pygobject.rb pygtk.rb
```

Just as a warning: Messing around with package mangers in unorthodox ways is never a good idea! So unless you're happy to take that risk, I would recommend waiting for a proper fix. 

After that brew install osgeo/osgeo4mac/osgeo-qgis-ltr or brew install osgeo/osgeo4mac/osgeo-qgis should work like before.

**Comment by gsdali** [comment]
To be fair pygtk is part of python 2 which hasn't been updated since 2011 and ceased to be maintained on Jan 1 this year. There hopefully shouldn't be any dependency on it in QGIS (although I've run into some plugins that make python 2 calls).

I just got caught out because I delayed moving from Macports to brew (post Catalina upgrade) to this nice quiet period in January. I might have to go back to MacPorts

**Comment by fjperini** [comment]
@warmerdam  @gsdali @chrisn-au @rdornas @markegge @jakobjassmann We are working in another branch, so as not to break the dependencies in the future.
For the new version of QGIS, everything will be updated.

**Comment by mcandre** [comment]
`brew install` no longer finds such local files :/

```console
$ git -C "$(brew --repo homebrew/core)" show 6258719db^:Formula/pygtk.rb > pygtk.rb

$ cat pygtk.rb 
class Pygtk < Formula
  desc "GTK+ bindings for Python"
  homepage "http://www.pygtk.org/"
  url "https://download.gnome.org/sources/pygtk/2.24/pygtk-2.24.0.tar.bz2"
  sha256 "cd1c1ea265bd63ff669e92a2d3c2a88eb26bcd9e5363e0f82c896e649f206912"
  revision 3

  bottle do
    cellar :any
    rebuild 2
    sha256 "12bab3d76587659b38e56867c9b359941803275716896e2936cd3e8029cf5f3f" => :catalina
    sha256 "87f89d246e3a779381ec2efdee7ee2b69fda464f38a59dd8e14304435d759419" => :mojave
    sha256 "969cef803e110b2767c6d3ade304b92d7f23a02ff7eb4030772b69b52df7c3b2" => :high_sierra
  end

  depends_on "pkg-config" => :build
  depends_on "atk"
  depends_on "glib"
  depends_on "gtk+"
  depends_on "libglade"
  depends_on "py2cairo"
  depends_on "pygobject"

  # Allow building with recent Pango, where some symbols were removed
  patch do
    url "https://raw.githubusercontent.com/Homebrew/formula-patches/85fa66a9/pygtk/2.24.0.diff"
    sha256 "ec480cff20082c41d9015bb7f7fc523c27a2c12a60772b2c55222e4ba0263dde"
  end

  def install
    ENV.append "CFLAGS", "-ObjC"
    system "./configure", "--disable-dependency-tracking",
                          "--prefix=#{prefix}"
    system "make", "install"

    # Fixing the pkgconfig file to find codegen, because it was moved from
    # pygtk to pygobject. But our pkgfiles point into the cellar and in the
    # pygtk-cellar there is no pygobject.
    inreplace lib/"pkgconfig/pygtk-2.0.pc", "codegendir=${datadir}/pygobject/2.0/codegen", "codegendir=#{HOMEBREW_PREFIX}/share/pygobject/2.0/codegen"
    inreplace bin/"pygtk-codegen-2.0", "exec_prefix=${prefix}", "exec_prefix=#{Formula["pygobject"].opt_prefix}"
  end

  test do
    (testpath/"codegen.def").write("(define-enum asdf)")
    system "#{bin}/pygtk-codegen-2.0", "codegen.def"
  end
end

$ git -C "$(brew --repo homebrew/core)" show fcfa254fc^:Formula/pygobject.rb > pygobject.rb

$ cat pygobject.rb 
class Pygobject < Formula
  desc "GLib/GObject/GIO Python bindings for Python 2"
  homepage "https://wiki.gnome.org/Projects/PyGObject"
  url "https://download.gnome.org/sources/pygobject/2.28/pygobject-2.28.7.tar.xz"
  sha256 "bb9d25a3442ca7511385a7c01b057492095c263784ef31231ffe589d83a96a5a"
  revision 2

  bottle do
    cellar :any
    sha256 "2dbdab3cd94b10eae121c1e8460085b84c1908b487150e486005dd125f99890d" => :catalina
    sha256 "caf4b79e8454b58bb67e73a6f06853d7a410c1fa9b31478c6ac389424ca690bb" => :mojave
    sha256 "04550d558f335fd6431ee3c124ba19011ec4284e7584eff343ad6b78483472a5" => :high_sierra
    sha256 "fbe187ff2aa28f4e9f57e1e3f8f69df8e69da6406833b3dd9a976f5bae267ee7" => :sierra
  end

  depends_on "pkg-config" => :build
  depends_on "glib"
  depends_on "python@2"

  patch do
    url "https://raw.githubusercontent.com/Homebrew/formula-patches/85fa66a9/pygobject/2.28.7.diff"
    sha256 "ada3da43c84410cc165d8547ad3c7809435e09c9e8539882860d97cd1ce922b2"
  end

  def install
    system "./configure", "--disable-dependency-tracking",
                          "--prefix=#{prefix}",
                          "--disable-introspection"
    system "make", "install"
    (lib/"python2.7/site-packages/pygtk.pth").append_lines <<~EOS
      #{HOMEBREW_PREFIX}/lib/python2.7/site-packages/gtk-2.0
    EOS
  end

  test do
    system Formula["python@2"].opt_bin/"python2.7", "-c", "import dsextras"
  end
end

$ brew install pygobject3.rb pygtk.rb 
Error: No available formula with the name "pygobject3.rb" 
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.
```

**Comment by saeid-h** [comment]
> Same problem here. The reason seems to be indeed the recent removal of the pygtk formula from homebrew/core. Looks like the team maintining the core formulae has decided pygtk is "deprecated".
> 
> I guess a long term solution will have to be found to remove the dependency for pygtk from the osgeo-qgis and osgeo-qgis-ltr fromulae.
> 
> If you are in an urgent rush (like me), you can install the relevant missing packages by retrieving the deleted formulae via git, saving them as local formulae and then installing them with brew (see below).
> 
> ```
> # Retrieve old pygtk formula and save as temporary file in active folder
> git -C "$(brew --repo homebrew/core)" show 6258719db^:Formula/pygtk.rb > pygtk.rb
> # Retrieve old pygobject formula (pygtk dependency) 
> git -C "$(brew --repo homebrew/core)" show fcfa254fc^:Formula/pygobject.rb > pygobject.rb
> # Install local formulae from files
> brew install pygobject.rb pygtk.rb
> # Remove temporary formulae files (if needed)
> rm pygobject.rb pygtk.rb
> ```
> 
> Just as a warning: Messing around with package mangers in unorthodox ways is never a good idea! So unless you're happy to take that risk, I would recommend waiting for a proper fix.
> 
> After that brew install osgeo/osgeo4mac/osgeo-qgis-ltr or brew install osgeo/osgeo4mac/osgeo-qgis should hopefully work like before.

It depends on python@2. I can't find it either :(
