### ISSUE TITLE
qt5-webkit outdated

### ISSUE THREAD

**Issue by frankli0324** [OSGeo/homebrew-osgeo4mac#1295]
qt5-webkit once again outdated
#1292 

temporary fix:
replace `find_dependency_with_major_and_minor\(Qt5.* 5 13\)` with `5 14` in 
`/usr/local/Cellar/osgeo-qt-webkit/5.13.0/lib/cmake/*/*Config.cmake`

**Comment by frankli0324** [comment]
since the formula is called "**qt5**-webkit", why bother checking the minor version number?

**Comment by 3nids** [comment]
see #1296

**Comment by frankli0324** [comment]
thanks
