### ISSUE TITLE
orfeo-42 fails on El Captain with Cmake 3.5.1

### ISSUE THREAD

**Issue by mbalcilar** [OSGeo/homebrew-osgeo4mac#130]
Is there workaround to this error:

CMake Error at /usr/local/Cellar/cmake/3.5.1/share/cmake/Modules/CMakeExportBuildSettings.cmake:17 (message):
  The functionality of this module has been dropped as of CMake 2.8.  It was
  deemed harmful (confusing users by changing their compiler).  Please remove
  calls to the CMAKE_EXPORT_BUILD_SETTINGS macro and stop including this
  module.  If this project generates any files for use by external projects,
  remove any use of the CMakeImportBuildSettings module from them.
Call Stack (most recent call first):
  CMakeLists.txt:362 (include)

Here is the gist log: https://gist.github.com/f0dab939f32313a34c411a2b50266a08

**Comment by pjduplooy** [comment]
Hi yes, revert to cmake 2.8 for orfeo.  You can get cmake.rb for 2.8 at homebrew's github, just do a history view for cmake.

Basically, uninstall cmake 3.5.1, install cmake 2.8, brew orfeo, uninstall cmake 2.8, and reinstall cmake 3.5.1.

You will have to move rb files in and out of the Formula folder.  What I did was uninstall cmake, move cmake's .rb out to a tmp folder, move cmake 2.8's .rb into the Formula folder, install cmake, orfeo, then uninstall cmake, move the .rb out of formula, and move 3.5's .rb back in, and reinstall cmake.

Works for me on El Capitan.

Pieter

**Comment by dakcarto** [comment]
Closing as related to deprecated formulae. Reopen if necessary.

Try `orfeo5` formula.
