### ISSUE TITLE
Adding Python support to Postgresql requires $PYTHON be set

### ISSUE THREAD

**Issue by bahoo** [OSGeo/homebrew-osgeo4mac#1304]
Adding support for [PL/Python](https://www.postgresql.org/docs/10/plpython.html) requires $PYTHON environment variable to be set.

From when [options were stripped out of many / most-all repos](https://github.com/Homebrew/homebrew-core/issues/31510), they simply cut this line:

https://github.com/Homebrew/homebrew-core/commit/c55743ce2e993d3407a7f7932abfe4910a25f953#diff-c290cd53a44f82f9ba1f4d59d9f90140L57

I've tested and adding it back in works in for me. `--with-python` is already set.

Is `which("python3")` a reasonable approach here? I can get a PR together if so. But thought I'd kick it around for feedback before submitting it.

Thank you!

**Comment by fjperini** [comment]
@bahoo There I added that line, you check it #1306
