### ISSUE TITLE
CREATE EXTENSION postgis fails with Symbol not found: _AllocSetContextCreateExtended

### ISSUE THREAD

**Issue by kevinstadler** [OSGeo/homebrew-osgeo4mac#1335]
I've... 
- I read
	- [ ] the [reporting issues](https://github.com/OSGeo/homebrew-osgeo4mac/docs/reporting-issues) (broken link)
	- [ ] the [troubleshooting](https://github.com/OSGeo/homebrew-osgeo4mac/docs/troubleshooting) (broken link)
- [X] I checked the documentation and found no answer
- [X] I tried to install after following the suggestions
- [X] I am running the latest version (`brew update` twice?)
- [X] I checked to make sure that this issue has not already been filed
- [X] I uploaded logs: `brew gist-logs formula`

**Describe the bug**

After a *fresh install* of the latest versions of `osgeo-postgresql`(v12.1) and `osgeo-postgis` (v2.5), `CREATE EXTENSION postgis` on a completely new database fails. This is presumably because of some version mismatch, but I haven't been able to get the postgis extension to work with any other postgres installation either (in particular not `osgeo-postgresql@10`).

This is *not* the same as #1124, #1174, but may be related to #1283?

```
2020-02-05 12:43:40.125 CET [42967] ERROR:  could not load library "/usr/local/lib/postgresql/postgis-2.5.so": dlopen(/usr/local/lib/postgresql/postgis-2.5.so, 10): Symbol not found: _AllocSetContextCreateExtended
	  Referenced from: /usr/local/lib/postgresql/postgis-2.5.so
	  Expected in: /usr/local/Cellar/osgeo-postgresql/12.1/bin/postgres
	 in /usr/local/lib/postgresql/postgis-2.5.so
2020-02-05 12:43:40.125 CET [42967] STATEMENT:  CREATE EXTENSION postgis;
ERROR:  could not load library "/usr/local/lib/postgresql/postgis-2.5.so": dlopen(/usr/local/lib/postgresql/postgis-2.5.so, 10): Symbol not found: _AllocSetContextCreateExtended
  Referenced from: /usr/local/lib/postgresql/postgis-2.5.so
  Expected in: /usr/local/Cellar/osgeo-postgresql/12.1/bin/postgres
 in /usr/local/lib/postgresql/postgis-2.5.so
```

**To Reproduce**

```
brew install osgeo-postgresql osgeo-postgis
initdb -D dummy
pc_ctl -D dummy start
createdb dummydb
psql -d dummydb
```

```
CREATE EXTENSION postgis;
```

**Expected behavior**

The postgis extension should be installed on the current database, so that geodata can be impoted.

**Additional context**

This is my first installation of postgres and postgis, so it is not an issue with upgrading postgis.

**Comment by fjperini** [comment]
@kevinstadler We are updating the formulas, I fix this!

**Comment by fjperini** [comment]
@kevinstadler try after merging #1337

**Comment by alazarolop** [comment]
It should be fixed with the latest release (https://github.com/OSGeo/homebrew-osgeo4mac/pull/1354), could you confirm @kevinstadler ?
