### ISSUE TITLE
error while upgrading osgeo-vkt

### ISSUE THREAD

**Issue by 3nids** [OSGeo/homebrew-osgeo4mac#1338]
No available formula with the name "python2" (dependency of osgeo/osgeo4mac/osgeo-vtk)

**Comment by Joshgallagher** [comment]
Currently experiencing this issue - Python@2 reached its EOL at the beginning of this year.

Error occurring when performing: `brew install https://raw.githubusercontent.com/OSGeo/homebrew-osgeo4mac/master/Formula/osgeo-grass.rb`

**Comment by 3nids** [comment]
yes, but I don't have grass installed!

**Comment by fjperini** [comment]
@3nids @Joshgallagher Today I will update all these dependencies, we are working in another branch, so as not to break the dependencies in the future.
For the new version of QGIS, everything will be updated.

**Comment by fjperini** [comment]
Fix #1357
