### ISSUE TITLE
Cannot install osgeo-gdal-python due to dependency on python2

### ISSUE THREAD

**Issue by donCarlosOne** [OSGeo/homebrew-osgeo4mac#1340]
I've been trying unsuccesfully to install osgeo-gdal-python on MacOS Catalina using Homebrew.

I previously had python@2 installed, and it complained:

```
brew install --verbose osgeo/osgeo4mac/osgeo-gdal-python  
==> Installing osgeo-gdal-python from osgeo/osgeo4mac
Error: No available formula with the name "python2" (dependency of osgeo/osgeo4mac/osgeo-gdal-python)
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.
```

I thought perhaps that by uninstalling python@2, this installer would do it for me.  I believe it tried to install it, however Homebrew is no longer supporting python@2 at all (and I cannot even reinstall it via Homebrew manually):

```
brew install --verbose osgeo/osgeo4mac/osgeo-gdal-python 
==> Installing osgeo-gdal-python from osgeo/osgeo4mac
Error: No available formula with the name "python@2" (dependency of osgeo/osgeo4mac/osgeo-gdal-python)
==> Searching for a previously deleted formula (in the last month)...
python@2 was deleted from homebrew/core in commit 028f11f9e4:
  python@2: delete (https://github.com/Homebrew/homebrew-core/issues/49796)
  EOL 1 January 2020.
  We gave it 1 month more to live so that people had time to migrate.
  All in all, developers had 11 years to do their migration.
  You can use the `brew extract` command and maintain python@2 in your own
  tap if necessary:
  https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

To show the formula before removal run:
  git -C "$(brew --repo homebrew/core)" show 028f11f9e4^:Formula/python@2.rb

If you still use this formula consider creating your own tap:
  https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap
```

So, Homebrew has indicated how to do this above - but somewhere the installer is still looking for "python2", not "python@2" as per my initial attempts.

Any workaround would be most appreciated as this is now restricting us in a dev project.

**Comment by alazarolop** [comment]
Currently the tap is under revision to upgrade all dependencies, not just to Python 3, but to new releases of GDAL and Proj, and it should be finished in the following days. In the meantime, a bundle version of QGIS can be downloaded with `brew cask install qgis`.

**Comment by alazarolop** [comment]
The formula accepts an option `--without-python@2`, can you successfully build it adding that?

**Comment by aniruhil** [comment]
same boat as @donCarlosOne 

Tried the --without-python@2 option but to no avail. 

> Upgrading 1 outdated package:
osgeo/osgeo4mac/osgeo-gdal-python 3.0.2 -> 3.0.4
Error: No available formula with the name "python2" (dependency of osgeo/osgeo4mac/osgeo-gdal-python)

**Comment by alazarolop** [comment]
I see. Unfortunately, I guess there isn't a simple workaround (e.g. editing the formula locally) and you will probably find the same error in formulas that depend on this GDAL version too. You'd better wait a bit for the update, which is on his way. It shouldn't take longer.

**Comment by aniruhil** [comment]
Thank you for looking into it @alazarolop, much appreciated. I'll wait for the update.

**Comment by alazarolop** [comment]
You are welcome. I'll let you know when everything is rightly set up

**Comment by fjperini** [comment]
@donCarlosOne @aniruhil Today I will update all these dependencies, we are working in another branch, so as not to break the dependencies in the future.
For the new version of QGIS, everything will be updated.

**Comment by alazarolop** [comment]
It should be fixed in the latest release (https://github.com/OSGeo/homebrew-osgeo4mac/pull/1354).

**Comment by aniruhil** [comment]
thank you @alazarolop and @fjperini

**Comment by atsokol** [comment]
Thank you @alazarolop  
Do you plan to fix osgeo-grass and other installations that depend on python@2 as well?

**Comment by fjperini** [comment]
@atsokol Yes, I already have `osgeo-grass` working. I will update it in a few hours!

**Comment by davidraleigh** [comment]
In the last hour I just tried
```shell
brew install osgeo-gdal
brew install osgeo-gdal-python
brew install osgeo-qgis
```
and I still got the error:
```
brew install osgeo-qgis
==> Installing osgeo-qgis from osgeo/osgeo4mac
Error: No available formula with the name "python@2" (dependency of osgeo/osgeo4mac/osgeo-qgis)
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

python@2 was deleted from homebrew/core in commit 028f11f:
  python@2: delete (https://github.com/Homebrew/homebrew-core/issues/49796)
  EOL 1 January 2020.
  We gave it 1 month more to live so that people had time to migrate.
  All in all, developers had 11 years to do their migration.
  You can use the `brew extract` command and maintain python@2 in your own
  tap if necessary:
  https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

To show the formula before removal run:
  git -C "$(brew --repo homebrew/core)" show 028f11f^:Formula/python@2.rb

If you still use this formula consider creating your own tap:
  https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap
```

`--without-python@2` does not seem to be an option.
