### ISSUE TITLE
Cannot install osgeo-qgis due to dependency on python2

### ISSUE THREAD

**Issue by davidraleigh** [OSGeo/homebrew-osgeo4mac#1362]
**Please answers the following**

I've... 
- I read
	- [ x] the [reporting issues](https://github.com/OSGeo/homebrew-osgeo4mac/docs/reporting-issues)
	- [ x] the [troubleshooting](https://github.com/OSGeo/homebrew-osgeo4mac/docs/troubleshooting)
- [ x] I checked the documentation and found no answer
- [ x] I tried to install after following the suggestions
- [ x] I am running the latest version (`brew update` twice?)
- [ x] I checked to make sure that this issue has not already been filed
- [ x] I uploaded logs: `brew gist-logs formula`

**Describe the bug**

seems to be the same issue as https://github.com/OSGeo/homebrew-osgeo4mac/issues/1340
 and https://github.com/OSGeo/homebrew-osgeo4mac/issues/1353 but for osgeo-qgis

```shell
$ brew install --verbose osgeo/osgeo4mac/osgeo-qgis
==> Installing osgeo-qgis from osgeo/osgeo4mac
Error: No available formula with the name "python@2" (dependency of osgeo/osgeo4mac/osgeo-qgis)
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

python@2 was deleted from homebrew/core in commit 028f11f:
  python@2: delete (https://github.com/Homebrew/homebrew-core/issues/49796)
  EOL 1 January 2020.
  We gave it 1 month more to live so that people had time to migrate.
  All in all, developers had 11 years to do their migration.
  You can use the `brew extract` command and maintain python@2 in your own
  tap if necessary:
  https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

To show the formula before removal run:
  git -C "$(brew --repo homebrew/core)" show 028f11f^:Formula/python@2.rb

If you still use this formula consider creating your own tap:
  https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap
```

My setup:
```shell
brew config 
HOMEBREW_VERSION: 2.2.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4493f27db28be7f083737424cecd8edb863ec3f6
Last commit: 2 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c1af875e08a1092483b244fe35ae28abd732175b
Core tap last commit: 85 minutes ago
HOMEBREW_PREFIX: /usr/local
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.25.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 11.0.6, 1.8.0_241
macOS: 10.15.3-x86_64
CLT: 11.3.1.0.1.1576735732
Xcode: 11.3.1

```

**Comment by fjperini** [comment]
@davidraleigh we are updating all the formulas. Wait for the update process to finish.

**Comment by peop81** [comment]
Any ETA on this issue ? Thanks

**Comment by alazarolop** [comment]
No at this moment. We are facing some issues building QGIS without Python@2 and because some updates in macOS. As for now, cask version is the only available option. It should works even in a system with osgeo-formulas installed in parallel.
