### ISSUE TITLE
osgeo-grass depends on quartz but is not in dependencies and installed automatically

### ISSUE THREAD

**Issue by rkrug** [OSGeo/homebrew-osgeo4mac#1367]
**Please answers the following**

I've... 
- I read
	- [X] the [reporting issues](https://osgeo.github.io/homebrew-osgeo4mac/docs/reporting-issues/)
	- [X] the [troubleshooting](https://osgeo.github.io/homebrew-osgeo4mac/docs/troubleshooting/)
- [X] I checked the documentation and found no answer
- [X] I tried to install after following the suggestions
- [X] I am running the latest version (`brew update` twice?)
- [X] I checked to make sure that this issue has not already been filed
- [ ] I uploaded logs: `brew gist-logs formula`

**Describe the bug**

the Formula osgeo-grass depends on quartz (which is in cask). The formula asks for it to be installed. Would it be possible to add it to the dependencies?

**Comment by alazarolop** [comment]
Thanks for the comment. We'll check it. I'm not sure whether cask formulas can be force to be installed in the same manner as standard formulas.

**Comment by rkrug** [comment]
@alazarolop Any news on this?

**Comment by alazarolop** [comment]
A new system it's under development in order to address dependencies issues. It's mainly focused on QGIS, but it would include also GRASS GIS. News will be posted in the tap as soon as it's ready.

**Comment by alazarolop** [comment]
A new system it's under development in order to address dependencies issues. It's mainly focused on QGIS, but it would include also GRASS GIS. As soon as it's ready, indications will be posted in the tap.

**Comment by alazarolop** [comment]
@rkrug  Information will be added to GRASS GIS caveats when the installation is completed for the next release.

**Comment by rkrug** [comment]
OK - thanks.
