### ISSUE TITLE
Trying to install sf package in my New Mac.

### ISSUE THREAD

**Issue by bijeshmishra** [OSGeo/homebrew-osgeo4mac#1371]
**Please answers the following**

I've... 
- I read
	- [ Yes] the [reporting issues](https://osgeo.github.io/homebrew-osgeo4mac/docs/reporting-issues/)
	- [Yes ] the [troubleshooting](https://osgeo.github.io/homebrew-osgeo4mac/docs/troubleshooting/)
- [ ] I checked the documentation and found no answer
- [ Yes ] I tried to install after following the suggestions
- [ ] I am running the latest version (`brew update` twice?)
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I uploaded logs: `brew gist-logs formula`

**Describe the bug**
I am trying to install sf package in fresh Macbook running macOS Catalina Version 10.15.4. Seems like I have to install several packages. I went through a tutorial [https://medium.com/@jinwujour/mapping-with-r-on-mac-installation-8c8ef997c6c2] but did not work somewhere in the middle. I got some error message on my R. I have attached screenshot if that is helpful.
![image](https://user-images.githubusercontent.com/11329730/78583906-14588c00-77fd-11ea-9cb6-a7c2ed79a6c5.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

`brew doctor` output: 

```shell
# paste here the output of your brew doctor output. Delete this line please. 
```

**Logs**

**Comment by ateucher** [comment]
If you can live with working (for now) with sf` one version behind the most current (0.8-1 vs 0.9), just install the binary: `install.packages("sf", type = "binary")`. Binaries for the v0.9 should be built shortly and then you can update again.

If you must build from source, see [here](https://github.com/r-spatial/sf#macos).

**Comment by bijeshmishra** [comment]
Does this work as same as sf package?

**Comment by ateucher** [comment]
Sorry I'm not sure I understand the question. The instructions I posted/linked to are for the `sf` package. 

Also, I'm not sure this is the place to discuss `sf` installation issues, please look through the issues at the [sf](https://github.com/r-spatial/sf) repo as a version of this question has been asked there many times recently (and please don't post another one there).
