### ISSUE TITLE
Failure: CREATE EXTENSION postgis

### ISSUE THREAD

**Issue by mhazeley** [OSGeo/homebrew-osgeo4mac#1372]
I've tried doing a clean reinstall of postgis and postgresql and I am still unable to create the postgis extension in a new database.

`ERROR:  could not load library "/usr/local/lib/postgresql/postgis-3.so": dlopen(/usr/local/lib/postgresql/postgis-3.so, 10): Library not loaded: /usr/local/opt/osgeo-proj/lib/libproj.15.dylib
  Referenced from: /usr/local/lib/postgresql/postgis-3.so
  Reason: image not found`

**Comment by alazarolop** [comment]
Which code have you run to install the formulas? Have you tried to built it from source adding the flag `--build-from-source`?

**Comment by alazarolop** [comment]
This commit https://github.com/OSGeo/homebrew-osgeo4mac/commit/d84f38b63da91053f61b2569a9e741546b8c9473 should fix it.
