### ISSUE TITLE
GDAL installs but fails with jpeg errors

### ISSUE THREAD

**Issue by RWhite-EDR** [OSGeo/homebrew-osgeo4mac#1373]
**Please answers the following**

I've... 
- I read
	- [x] the [reporting issues](https://osgeo.github.io/homebrew-osgeo4mac/docs/reporting-issues/)
	- [x] the [troubleshooting](https://osgeo.github.io/homebrew-osgeo4mac/docs/troubleshooting/)
- [x] I checked the documentation and found no answer
- [x] I tried to install after following the suggestions
- [x] I am running the latest version (`brew update` twice?)
- [x] I checked to make sure that this issue has not already been filed
- [] I uploaded logs: `brew gist-logs formula`

**Describe the bug**
I'm able to install osgeo-gdal, but gdalinfo --formats or --version fails with the following error:

dyld: Symbol not found: __cg_jpeg_resync_to_restart
Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
Expected in: /usr/local/lib/libjpeg.9.dylib
in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO

**To Reproduce**

1. brew install osgeo-gdal
2. test installation with gdalinfo --formats

**Expected behavior**

I expect to see a list of installed formats or version.

**Additional context**

I believe there is an issue with osgeo-jpeg and the ImageIO.framework.  I'm able to test the jpeg install with djpeg and a random jpeg file.

This is also an issue with the brew gdal formula.

**Comment by RWhite-EDR** [comment]
If I unlink a few installed libraries I'm at least able to get gdalinfo --formats to run:
```
brew unlink libpng
brew unlink libtiff
brew unlink libjpeg
brew unlink giflib
```
Still testing if anything needing these libraries will still work.

**Comment by alazarolop** [comment]
Hi @RWhite-EDR it seems a problem from `libjpeg` rather than `osgeo-gdal` then. Have you try to reinstall `libjpeg`? Could you post your `brew doctor` output?

**Comment by RWhite-EDR** [comment]
brew doctor is ready to brew before I unlink and is now showing the unlinked libraries.

I have tried multiple reinstalls of libjpeg, gdal, and osgeo-gdal.  I have not tried to brew reinstall jpeg after installing GDAL.

Unlinking the libraries above is working for my specific gdal problem.

brew install jpeg by itself appears to be working.  Meaning that the djpeg program installed with the libraries is working by itself.

DYLD_LIBRARY_PATH isn't set in my .zshrc and appears to be the default /usr/local/bin .

If I had to guess, there is a version or path conflict between the JPEG libraries in the system image io framework, JPEG, and GDAL.

**Comment by alazarolop** [comment]
Yes, I think so. I don’t exactly know the `libjpeg` case, but it seems weird you have picked something from within Frameworks directory when using a formula from HomeBrew. You can close this issue if you think you’ve solved it and check what happens with the next update of GDAL formula.
