### ISSUE TITLE
Geo .PDF to .tiff has a transparent background colour

### ISSUE THREAD

**Issue by JanC** [OSGeo/homebrew-osgeo4mac#1374]
**Please answers the following**

I've... 
- I read
	- [x] the [reporting issues](https://osgeo.github.io/homebrew-osgeo4mac/docs/reporting-issues/)
	- [x] the [troubleshooting](https://osgeo.github.io/homebrew-osgeo4mac/docs/troubleshooting/)
- [x] I checked the documentation and found no answer
- [x] I tried to install after following the suggestions
- [x] I am running the latest version (`brew update` twice?)
- [x] I checked to make sure that this issue has not already been filed
- [x] I uploaded logs: `brew gist-logs formula`

**Describe the bug**
Converting a .pdf to .tiff using `gdal_translate` creates a .tiff with transparent background

**To Reproduce**

1. Download this [00989I11.PDF](https://www.dropbox.com/s/7nw82o89cjew3zl/00989I11.PDF?dl=0)
2. run `gdal_translate 00989I11.PDF 00989I11.tiff`
3. Open the resulting [00989I11.tiff](https://www.dropbox.com/s/o3bx8gi5rd8blae/00989I11.tiff?dl=0)

**Expected behavior**
I would expect the .tiff to have a white color as background as the source PDF does not contain any `NoData` value

**Screenshots**
**Source PDF:**
![Screenshot 2020-04-23 at 18 55 44](https://user-images.githubusercontent.com/707703/80300086-dadec500-8799-11ea-8fa9-a4d97d4bf620.png)

**Generated .tiff**

![Screenshot 2020-04-23 at 18 59 51](https://user-images.githubusercontent.com/707703/80300094-eaf6a480-8799-11ea-92b3-e39c019c7c81.png)

**Additional context**
- gdal version"

```
gdalinfo --version
GDAL 3.0.4, released 2020/01/28
```

- The `gdalinfo` of the .pdf is:
```
    gdalinfo 00989I11.PDF
    Driver: PDF/Geospatial PDF
    Files: 00989I11.PDF
    Size is 806, 1237
    Coordinate System is:
    PROJCRS["",
        BASEGEOGCRS["NAD83",
            DATUM["North American Datum 1983",
                ELLIPSOID["GRS 1980",6378137,298.2572221,
                    LENGTHUNIT["metre",1]],
                ID["EPSG",6269]],
            PRIMEM["Greenwich",0,
                ANGLEUNIT["Degree",0.0174532925199433]]],
        CONVERSION["unnamed",
            METHOD["Lambert Conic Conformal (2SP)",
                ID["EPSG",9802]],
            PARAMETER["Latitude of false origin",35.2372777777778,
                ANGLEUNIT["Degree",0.0174532925199433],
                ID["EPSG",8821]],
            PARAMETER["Longitude of false origin",-120.642611111111,
                ANGLEUNIT["Degree",0.0174532925199433],
                ID["EPSG",8822]],
            PARAMETER["Latitude of 1st standard parallel",45,
                ANGLEUNIT["Degree",0.0174532925199433],
                ID["EPSG",8823]],
            PARAMETER["Latitude of 2nd standard parallel",33,
                ANGLEUNIT["Degree",0.0174532925199433],
                ID["EPSG",8824]],
            PARAMETER["Easting at false origin",0,
                LENGTHUNIT["Inch",0.0254000508001],
                ID["EPSG",8826]],
            PARAMETER["Northing at false origin",0,
                LENGTHUNIT["Inch",0.0254000508001],
                ID["EPSG",8827]]],
        CS[Cartesian,2],
            AXIS["(E)",east,
                ORDER[1],
                LENGTHUNIT["Inch",0.0254000508001]],
            AXIS["(N)",north,
                ORDER[2],
                LENGTHUNIT["Inch",0.0254000508001]]]
    Data axis to CRS axis mapping: 1,2
    Origin = (-1807172.000000000000000,2042985.000000000000000)
    Pixel Size = (3334.000000000000000,-3335.000000000000000)
    Metadata:
      AUTHOR=
      CREATION_DATE=D:20190718071421-04'00'
      CREATOR=MicroStation 8.11.9.867 by Bentley Systems, Incorporated
      NEATLINE=POLYGON ((-1487388.02470535 -1654179.3669621,563048.661741154 -1654193.12139478,563073.777508997 1615063.22966106,-1487370.34966788 1615075.17034221,-1487388.02470535 -1654179.3669621))
      PRODUCER=Adobe PDF Library 9.0
      TITLE=00989I11
    Corner Coordinates:
    Upper Left  (-1807172.000, 2042985.000) (121d 9' 6.29"W, 35d42'19.70"N)
    Lower Left  (-1807172.000,-2082410.000) (121d 8'43.15"W, 34d45'28.56"N)
    Upper Right (  880032.000, 2042985.000) (120d23'40.84"W, 35d42'22.90"N)
    Lower Right (  880032.000,-2082410.000) (120d23'52.11"W, 34d45'31.72"N)
    Center      ( -463570.000,  -19712.500) (120d46'20.58"W, 35d13'57.63"N)
    Band 1 Block=806x1 Type=Byte, ColorInterp=Red
      Overviews: 403x619, 202x310, 101x155
      Mask Flags: PER_DATASET ALPHA 
      Overviews of mask band: 403x619, 202x310, 101x155
    Band 2 Block=806x1 Type=Byte, ColorInterp=Green
      Overviews: 403x619, 202x310, 101x155
      Mask Flags: PER_DATASET ALPHA 
      Overviews of mask band: 403x619, 202x310, 101x155
    Band 3 Block=806x1 Type=Byte, ColorInterp=Blue
      Overviews: 403x619, 202x310, 101x155
      Mask Flags: PER_DATASET ALPHA 
      Overviews of mask band: 403x619, 202x310, 101x155
    Band 4 Block=806x1 Type=Byte, ColorInterp=Alpha
      Overviews: 403x619, 202x310, 101x155
```

- The same command with the same input file creates a .tiff with a white color when using the Linux version of gdal:

```
docker run -ti --rm  osgeo/gdal  gdalinfo --version
GDAL 3.1.0dev-2fde97fd57bbd892781f89323499528c5821dea4, released 2020/04/25

docker run -ti --rm -v $(pwd):/data osgeo/gdal  gdal_translate /data/00989I11.PDF /data/00989I11_linux.tiff
```

**Linux output:**
<img width="707" alt="Screenshot 2020-04-26 at 08 54 03" src="https://user-images.githubusercontent.com/707703/80300275-84728600-879b-11ea-9ced-6c736b32fc1b.png">

`brew doctor` output: 

```shell
brew doctor
Your system is ready to brew.
```

**Comment by alazarolop** [comment]
Hi @JanC thank you for thoroughly describing your problem. Within Docker you are using a different GDAL version (3.1.0dev > 3.0.4), could you reproduce the issue using the same GDAL version?

**Comment by JanC** [comment]
hi,
I've just tried with Ubuntu docker where I manually installed the gdal 3.0.4 and the result there is the same (correct white background)

```
gdalinfo --version
GDAL 3.0.4, released 2020/01/28

gdal_translate 00989I11.PDF 00989I11_linux_3.0.4.tiff

Input file size is 807, 1237
proj_uom_get_info_from_database: unit of measure not found
0...10...20...30...40...50...60...70...80...90...100 - done.
```

![Screenshot 2020-04-27 at 11 03 37](https://user-images.githubusercontent.com/707703/80354234-c02e4e00-8876-11ea-8257-c406aa9f26f9.png)

**Comment by alazarolop** [comment]
@JanC I can't reproduce it at this moment. I think you could get a better support from GDAL repository https://github.com/OSGeo/gdal/issues as it's related to the tool itself.

**Comment by JanC** [comment]
> I can't reproduce it at this moment. 
Do you mean that the same input .pdf file produces a .tiff with a white background on your side?

ok, I'll open a ticket in that repo

**Comment by alazarolop** [comment]
No, unfortunately I can't try the example at this moment because I don't have access to my testing installation. Could you please link the new issue you open, so anyone con follow up the thread?

**Comment by JanC** [comment]
See link above.

**Comment by alazarolop** [comment]
Great, thank you. `osgeo-gdal is built with both Pdfium and Poppler, so the behavior would be the expected considering the answer.

**Comment by JanC** [comment]
yeah the `GDAL_PDF_BANDS` config options works.

`gdal_translate 00989I11.PDF 00989I11.tiff --config GDAL_PDF_BANDS 3`

👍
