### ISSUE TITLE
QGIS brew install requires pygobject which is not available. 

### ISSUE THREAD

**Issue by jeabraham** [OSGeo/homebrew-osgeo4mac#1375]
**Please answers the following**

I've... 
- I read
	- [X ] the [reporting issues](https://osgeo.github.io/homebrew-osgeo4mac/docs/reporting-issues/)
	- [ ] the [troubleshooting](https://osgeo.github.io/homebrew-osgeo4mac/docs/troubleshooting/)
- [ X] I checked the documentation and found no answer
- [ X] I tried to install after following the suggestions
- [ X] I am running the latest version (`brew update` twice?)
- [ X] I checked to make sure that this issue has not already been filed
- [ X] There are no uploaded logs from `brew gist-logs qgis` because it failed looking for a dependency and never started installing qgis

**Describe the bug**

There is a dependency on pygobject but it seems that no longer exists.  Perhaps it's been renamed to pygobject3?

**To Reproduce**

1. type brew install qgis
2. watch the error

**Expected behavior**

I expect QGIS to install with the dependencies

**Screenshots**

`==> Installing osgeo-qgis from osgeo/osgeo4mac
Error: No available formula with the name "pygobject" (dependency of osgeo/osgeo4mac/osgeo-qgis)
`
**Additional context**

I tried this on two Mojave systems, both gave the same error

**Logs**

There are no logs, as it can't find the dependency

**Comment by jeabraham** [comment]
If I comment out `pygobject` dependency in `osgeo-qgis-res.rb` it then complains about `pygtk`, which is also no longer available.  If I comment both out, it starts installing...

**Comment by alazarolop** [comment]
Thank you for posting the issue. I'm linking you an issue with an alternative approach to install QGIS and an explanation https://github.com/OSGeo/homebrew-osgeo4mac/issues/1376.
