### ISSUE TITLE
Postgresql linking requirement unclear

### ISSUE THREAD

**Issue by kiendang** [OSGeo/homebrew-osgeo4mac#1380]
**Please answers the following**

I've... 
- I read
	- [x] the [reporting issues](https://osgeo.github.io/homebrew-osgeo4mac/docs/reporting-issues/)
	- [x] the [troubleshooting](https://osgeo.github.io/homebrew-osgeo4mac/docs/troubleshooting/)
- [x] I checked the documentation and found no answer
- [x] I tried to install after following the suggestions
- [x] I am running the latest version (`brew update` twice?)
- [x] I checked to make sure that this issue has not already been filed
- [ ] I uploaded logs: `brew gist-logs formula`

**Describe the bug**

I've been using the `osgeo-gdal` formula for a while now. `osgeo-gdal` depends on `osgeo-postgresql`. However as my usecase does not involve postgres integration I was already using the `postgresql` from `homebrew-core` and didn't want to change that I instead installed `osgeo-postgresql@11` keg-only. Everything was fine until I upgraded to `3.1.0` version, failed and realized now all `osgeo-postgresql` formulas, including `@10` and `@11` require linking and my setup of linked `homebrew-core/postgresql` + keg-only `osgeo-postgresql@11` doesn't work anymore. May I ask what prompted the change and is it possible to revert it so that keg-only installation of `osgeo-postgresql@10/@11` is enough because if I'm not wrong originally that was the intended behavior as seen in the caveat section of these formulas

https://github.com/OSGeo/homebrew-osgeo4mac/blob/77e7c268577f4f0895e4a0dcda6c81ab8c07514a/Formula/osgeo-postgresql%4011.rb#L234-L245

**Comment by alazarolop** [comment]
Hi @kiendang. I'm not sure what "I upgraded and failed" mean in this case, do you mean the upgrade process failed or some function of GDAL did? As far as I know, it's done this way to ensure compatibility between PostgreSQL and the GDAL driver. However, you could unlinking it after the GDAL installation and link again your desired version, whether core or osgeo.

**Comment by kiendang** [comment]
> However, you could unlinking it after the GDAL installation and link again your desired version, whether core or osgeo.

Yes that's what I did. But considering 1. the package works fine without linking `osgeo-postgres` and 2. `homebrew-core/postgresql` is one of the most commonly installed [formulae](https://formulae.brew.sh/analytics/install-on-request/365d/) is it better to not require linking? Or at least change the caveat message which implies linking is not required

https://github.com/OSGeo/homebrew-osgeo4mac/blob/77e7c268577f4f0895e4a0dcda6c81ab8c07514a/Formula/osgeo-postgresql%4011.rb#L234-L245

**Comment by alazarolop** [comment]
`osgeo-postgresql` formulas are also thought as companions to `osgeo-postgis` formulas or `osgeo-grass`, so it'd make sense to link all of them and keep them working together as the standard. 

There is an open debate though whether we should use core formulas again instead. At this moment the main advantages are finer control to upgrades and python extensions in osgeo formulas.

I agree caveats message could be adjust, perhaps with this explanation https://github.com/OSGeo/homebrew-osgeo4mac/issues/1380#issuecomment-633206747. Would you suggest something different?
