### ISSUE TITLE
New osgearth-qt5 warning

### ISSUE THREAD

**Issue by mjsteinbaugh** [OSGeo/homebrew-osgeo4mac#1386]
**Please answers the following**

I've... 
- I read
	- [X] the [reporting issues](https://osgeo.github.io/homebrew-osgeo4mac/docs/reporting-issues/)
	- [X] the [troubleshooting](https://osgeo.github.io/homebrew-osgeo4mac/docs/troubleshooting/)
- [X] I checked the documentation and found no answer
- [X] I tried to install after following the suggestions
- [X] I am running the latest version (`brew update` twice?)
- [X] I checked to make sure that this issue has not already been filed
- [ ] I uploaded logs: `brew gist-logs formula`

**Describe the bug**

```
Warning: Calling depends_on :macos => :mavericks is deprecated! There is no replacement.
Please report this issue to the osgeo/osgeo4mac tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/osgearth-qt5.rb:38

```

**To Reproduce**

```sh
brew upgrade
```

**Expected behavior**

Clean update without a warning.

**Comment by alazarolop** [comment]
Thank you for the warning. This formula hasn't been updated in a year, so it's probably broken for updates and new installs. I'll try to rebuild bottles, so it'll be ready to install and without that message popping up.
