### ISSUE TITLE
rgdal: `Symbol not found: ___addtf3`

### ISSUE THREAD

**Issue by pat-s** [OSGeo/homebrew-osgeo4mac#1390]
When installing R package `rgdal` from source, I get the following with `osgeo-gdal` and `osgeo-proj` linked.

Might be related to #301 

Everything is fine when using homerew-core `gdal` and `proj`.

```
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘rgdal’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Users/pjs/Library/R/4.1/library/00LOCK-rgdal/00new/rgdal/libs/rgdal.so':
  dlopen(/Users/pjs/Library/R/4.1/library/00LOCK-rgdal/00new/rgdal/libs/rgdal.so, 6): Symbol not found: ___addtf3
  Referenced from: /usr/local/opt/gcc/lib/gcc/10/libquadmath.0.dylib
  Expected in: /usr/lib/libSystem.B.dylib
 in /usr/local/opt/gcc/lib/gcc/10/libquadmath.0.dylib
Error: loading failed
Backtrace:
1: stop("loading failed", call. = FALSE)
2: tools:::.test_load_package("rgdal", "/Users/pjs/Library/R/4.1/library/00LOCK-rgdal/00new")
ERROR: loading failed
* removing ‘/Users/pjs/Library/R/4.1/library/rgdal’
* restoring previous ‘/Users/pjs/Library/R/4.1/library/rgdal’

```

**Comment by alazarolop** [comment]
From a previous post, I assume you've already got `rgdal` compiled from source in R 4.0 and you are trying to do it again in  4.1, right? Have you set a Makevars file to define compile and flags?

**Comment by alazarolop** [comment]
From a previous post, I assume you've already got rgdal compiled from source in R 4.0 and you are trying to do it again in 4.1, right?

Have you tried to recompile GDAL from source as it's suggested in the issue you linked? Have you set a Makevars file to define compile and flags? https://stackoverflow.com/questions/61103104/ld-unknown-option-platform-version-when-building-r-packages-from-source
