### ISSUE TITLE
Oracle connectivity in QGIS 3.14

### ISSUE THREAD

**Issue by therealgisarchitect** [OSGeo/homebrew-osgeo4mac#1391]
Requesting implementation of the option --with-oracle  

All our data is in Oracle databases and we are unable to load it into QGIS on Mac

https://osgeo.github.io/homebrew-osgeo4mac/docs/installing-QGIS-3/

Thx

**Comment by alazarolop** [comment]
QGIS formula is no longer available within the tap. I suggest you take a look at the GDAL plugin for Oracle from the tap or from another source in order to read this type of data.
