### ISSUE TITLE
Enable PDAL for GRASS 7.8.3

### ISSUE THREAD

**Issue by nilason** [OSGeo/homebrew-osgeo4mac#1392]
Problems with compiling failure of PDAL support with GRASS has been addressed with https://github.com/OSGeo/grass/commit/73b37a7dfb2d068e0734ca858e1f330a74f094e7, which is included with 7.8.3.
I believe it is now safe to enable PDAL in osgeo-grass.rb.

**Comment by alazarolop** [comment]
Thanks for letting us know. I'll try to include it.
