### ISSUE TITLE
osgeo-gdal brew install fails

### ISSUE THREAD

**Issue by alejandrofcarrera** [OSGeo/homebrew-osgeo4mac#1396]
**Describe the bug**

For Mac OS Catalina.

After these commands the URL is not the same than the official download repository. Seems like it is a misspelling on the configuration or Formula script file.

The URL to be downloaded is the following one: https://bottle.download.osgeo.org/osgeo-gdal-3.1.2_2.catalina.bottle.1.tar.gz but it is trying to download https://bottle.download.osgeo.org/osgeo-gdal-3.1.2_2.catalina.bottle.tar.gz

**Steps to reproduce the behavior**

brew unlink gdal
brew tap osgeo/osgeo4mac && brew tap --repair
brew install osgeo-gdal

**Comment by JesusFdezDav** [comment]
Just subscribing to what my colleague said and adding a correction, the steps to reproduce the behavior are as follows:

brew unlink gdal
brew tap osgeo/osgeo4mac && brew tap --repair
brew install gdal2

**Comment by alazarolop** [comment]
Hi @JesusFdezDav , the formula you are trying to install no longer exists. The new one is `osgeo-gdal`, have you tried it?

**Comment by alejandrofcarrera** [comment]
Yes.

I copied and pasted badly, but the one is failing is that one `osgeo-gdal`.

Thanks for the quick reply

**Comment by alazarolop** [comment]
I think it was my mistake 6ed262e811bf1934e9102acebd7daebe4bc82dc7. Can you try again?

**Comment by JesusFdezDav** [comment]
Brilliant! It did the trick. Thanks again for the quick reply
