### ISSUE TITLE
GRASS GIS 7.8.4 released, some mac specific news

### ISSUE THREAD

**Issue by nilason** [OSGeo/homebrew-osgeo4mac#1397]
GRASS GIS 7.8.4 has just been released (https://github.com/OSGeo/grass/releases/tag/7.8.4).

Now wxPython 4.1 is supported, failures such as: `wx._core.wxAssertionError: C++ assertion "!(flags & wxALIGN_CENTRE_HORIZONTAL)"` (as reported in #1377) have been fixed.

I'd like to inform you of some changes that relates to mac and potentially to Homebrew, to simplify the process of bumping version.

- configure:L1544 `SHLIB_LD` is set through CC variable, instead of previously hardcoded `cc`
- the app icon (previously `app.icns`) has been renamed to `AppIcon.icns`
- a GRASS document (gxw) file icon has been added: `macosx/app/GRASSDocument_gxw.icns`
- the `macosx/app/Info.plist.in` has been updated
- pdal should now compile (see #1392)
- GRASS terminal prompt now fully supports Z shell (zsh) as well as Bash

If you do consider using the updated `Info.plist.in`, the following strings needs to be replaced:
- `@GRASS_VERSION_MAJOR@` -> "7"
- `@GRASS_VERSION_MINOR@` -> "8"
- `@GRASS_VERSION_DATE@` -> "2020" (or read from `include/VERSION:L4`)
- `@BUNDLE_VERSION@` -> "7.8.4"
- `@DEPLOYMENT_TARGET@` -> e.g. "10.15"

**Comment by alazarolop** [comment]
Thanks a lot for the thorough description and the information. I should take a look at this and this https://github.com/OSGeo/homebrew-osgeo4mac/issues/1392 soon, it's in my task list.
