### ISSUE TITLE
Missing lib armadillo

### ISSUE THREAD

**Issue by milosimr** [OSGeo/homebrew-osgeo4mac#1399]
**Please answers the following**

I've... 
- I read
	- [x] the [reporting issues](https://osgeo.github.io/homebrew-osgeo4mac/docs/reporting-issues/)
	- [x] the [troubleshooting](https://osgeo.github.io/homebrew-osgeo4mac/docs/troubleshooting/)
- [x] I checked the documentation and found no answer
- [x] I tried to install after following the suggestions
- [x] I am running the latest version (`brew update` twice?)
- [x] I checked to make sure that this issue has not already been filed
- [ ] I uploaded logs: `brew gist-logs formula`

**Describe the bug**

When trying to use gdal functions, with the gdal `3.1.2`, I get this issue.

```
dyld: Library not loaded: /usr/local/opt/armadillo/lib/libarmadillo.9.dylib
  Referenced from: /usr/local/opt/osgeo-gdal/lib/libgdal.27.dylib
  Reason: image not found
```

**Comment by ryandatanerds** [comment]
Also experiencing the same issues as OP.

When I check the links of the `osgeo-gdal` formula (`brew linkage osgeo/osgeo4mac/osgeo-gdal`), I get the following broken dependencies:
```
Broken dependencies:
  /usr/local/opt/armadillo/lib/libarmadillo.9.dylib (armadillo)
```

Looks like `armadillo` pushed out version 10.11 [over the weekend](https://github.com/Homebrew/homebrew-core/commit/7d498bf148dcf49f2d248dadde640ca71499842e#diff-744c07ac6963cc0f8715cfea5cedc40f0f81a681524bf3b6c10c66a70399915e) which caused this formula to break.

If anyone could explain how to circumvent this issue for the time being, I'd greatly appreciate it. Also happy to help resolve the issue, but will need some hand holding as I am very new to homebrew.

**Comment by alazarolop** [comment]
In general, building the formula from source would workaround this kind of issue. 
```
brew install osgeo-gdal `--build-from-source
```
Some formulas need to be updated in the repository to avoid this.

**Comment by pat-s** [comment]
Unfortunately building from source errors for me and I am stuck with a broken GDAL installation.

Is there a fix coming in soon or do I need to switch to `gdal` for the moment?

Curios: Shouldn't the CI notice such issues in some way?

**Comment by alazarolop** [comment]
I'm sorry for that. I'm currently involved in a move and taking up a new position, so I think I won't be able to fix it in a short time. I would suggest using the core formulas instead as for now.  

In this regard, now that `gdal` and `proj` from core are up-to-date, I have been considering to use them within the repo, while keeping the capabilities. For example, building the GDAL extensions as a complement to the core formula. I need to spend some time on it though.

**Comment by pat-s** [comment]
Sounds good 👍 Thanks for the quick reply.

**Comment by pomadchin** [comment]
It is also possible to fix GDAL via symlinking the new armadillo:

```bash
ln -s /usr/local/opt/armadillo/lib/libarmadillo.10.dylib /usr/local/opt/armadillo/lib/libarmadillo.9.dylib
```

/cc @pat-s

**Comment by lseelenbinder** [comment]
I can confirm this issue. Thanks for the fix @pomadchin!
