### ISSUE TITLE
Question: How do I join Slack ?

### ISSUE THREAD

**Issue by bahoo** [OSGeo/homebrew-osgeo4mac#1412]
I'd like to get up to speed and hopefully / ideally contribute on a few repos ( particularly in adding more support for M1 / Apple Silicon ).

I see found the Slack link on the docs, but it won't let me create a new account unless I have a certain email address. And I didn't see any other way in, so I made a ticket. :D

If you can drop me an invite, amazing — jon.c.culver@gmail.com

And if this org is hoping to open up access to Slack a bit, I've also built some inviter / automation sort of tools I can offer if there is interest.

Thank you !

**Comment by alazarolop** [comment]
Thank you a lot for reaching out, I really appreciate your interest and I think your contribution could be very helpful. 

No worries, the ticket did its job. You should have received an invitation to the Slack. 

See you!
