### ISSUE TITLE
Move to homebrew-geospatial

### ISSUE THREAD

**Issue by dakcarto** [OSGeo/homebrew-osgeo4mac#142]
Hi @jctull, @nickrobison, @hobu, @rkrug, @cspanring, @m-kuhn, @fphilipe, @zitterbewegung,

I have started the migration today, so that [upstream `grass` can be removed](https://github.com/Homebrew/homebrew-core/pull/676) and `gcc` upgraded to 6.1.

Note that the license switch (PR #131) should be addressed prior to any commit to homebrew-geospatial.

For everything to work right, I'd like to take this approach:
- main formulae keep with Homebrew naming convention: `gdal` is 2.x
- older versions that still need to stick around get versioned: `gdal111` is 1.11.x, where older versions match naming convention and acceptable formulae specs of https://github.com/Homebrew/homebrew-versions. However, the versioned formula _stay_ in the homebrew-geospatial tap, not in homebrew-versions.

This way formulae in main taps that need `gdal2` can migrate to 2.x, but those that can't still have the `gdal111` formula to utilize. Many formulae can not be moved to homebrew-geospatial until `gdal` is bumped to 2.x.

Similarly, `grass6` is versioned because it is still a viable option for algorithms in QGIS's Processing framework. So, QGIS will become `qgis` and `qgis-ltr` and probably no older versions.

Opinions on any of that?

**Comment by jctull** [comment]
This is encouraging. It appears the Homebrew lead had another idea about migrating the existing repo, but you will see those comments over there. What will the process be to migrate various geospatial formulae that are in core now, e.g., gdal, postgis, etc.? Do we request that those get placed in the boneyard and with a PR referencing a revised version in the new repo? This will make more sense soon, I'm sure, but thanks for getting this underway!

**Comment by zitterbewegung** [comment]
This is good that is getting integrated with homebrew. Thanks for informing
me and good luck with the effort!

**Comment by zitterbewegung** [comment]
Why are all the links in your issue 404?

**Comment by dakcarto** [comment]
@zitterbewegung wrote:
> Why are all the links in your issue 404?

Thanks for noticing. Because that repo was removed in favor of fixing this repo up, then migrating it whoesale over to homebrew-geospatial. I'll edit the main description.
