### ISSUE TITLE
gdal-20 v2.1.0 not building under 10.11.5 (15F34)

### ISSUE THREAD

**Issue by rkrug** [OSGeo/homebrew-osgeo4mac#144]
Hi

I don't manage to install gdal-20 v2.1.0 under OS X 10.11.5 (15F34).

I can't see a real error message so I tried 

brew install --debug grad-20

which than gave me in the shell, when trying to execute ```make```:

```
make[2]: Nothing to be done for `install-obj'.
make[2]: Nothing to be done for `install-obj'.
make[2]: Nothing to be done for `install-obj'.
make[2]: Nothing to be done for `install-obj'.
make[2]: Nothing to be done for `install-obj'.
make[2]: Nothing to be done for `install-obj'.
delaunay.c:66:10: fatal error: 'libqhull.h' file not found
#include "libqhull.h"
         ^
1 error generated.
make[1]: *** [delaunay.lo] Error 1
make: *** [core-target] Error 2
```

Here is the gist of the logs:

https://gist.github.com/ee4a9db7a8ad219bea81a056838c3eca

Let me know if you need further info / help

Rainer

**Comment by rkrug** [comment]
Can anybody confirm this, or is it something with my installation of brew? Any suggestions?

**Comment by rkrug** [comment]
OK - i have the file which is missing at

```
/usr/local/include/libqhull
```
So I assume there is an include path wrong / missing in gdal-20

I don't know enough of brew and make to help here.

**Comment by mankoff** [comment]
I got it to compile with

    cd /usr/local/include
    ln -s libqhull qhull

And then, `brew install gdal-20 --with-complete`

**Comment by rkrug** [comment]
Worked - thanks. But this does not solve the issue - only circumvents it.

**Comment by claudiodsf** [comment]
Have the same issue on 10.11.5 and can confirm that the workaround works (even if, as @rkrug says, this just circumvents the issue).

**Comment by claudiodsf** [comment]
By the way, the formula needs `qhull` to compile, but doesn't formally depend on it.

**Comment by dakcarto** [comment]
Hi,

Thanks for reporting. See if e9ea72f fixes this issue. It skips external `qhull` dependency (for now) until it can be determined that the newer version available in Homebrew is as compatible as the internal one.

This **qhull** support is an optional configure option by default, so having a default formula dependency on `qhull` (at this time) does not quite make sense.

**Comment by MatzFan** [comment]
Just built GDAL v2.1.0 successfully on 10.11.6 - no problems.

**Comment by dakcarto** [comment]
Closing as per fix. Reopen if necessary.
