### ISSUE TITLE
QGIS-2.14 won't start after cfitsio have been updated to 3.390

### ISSUE THREAD

**Issue by jannefleischer** [OSGeo/homebrew-osgeo4mac#147]
After switching back to 3.370 everything worked again.

<code>brew switch cfitsio 3.370</code>

From the Crash Report:

```
Dyld Error Message:
     Library not loaded: /usr/local/opt/cfitsio/lib/libcfitsio.2.dylib
     Referenced from: /usr/local/opt/gdal-20/lib/libgdal.20.dylib
     Reason: image not found
```

**Comment by dakcarto** [comment]
@jannefleischer, thanks for reporting! You will need to build from source to remove dylib loading error, until the bottle can be rebuilt.

**Comment by dakcarto** [comment]
That is, you will need to rebuild `gdal-20` from source, not `qgis-214`.

**Comment by jannefleischer** [comment]
Well, since I can't [tap into](https://github.com/OSGeo/homebrew-osgeo4mac/issues/152) osgeo4mac anymore, I can't test this. Also: Working with 3.370 was fine enough for me.

**Comment by dakcarto** [comment]
Closing, as related to deprecated formulae. Please reopen if necessary.
