### ISSUE TITLE
Homebrew sha1 warnings

### ISSUE THREAD

**Issue by earthflat** [OSGeo/homebrew-osgeo4mac#148]
Dears,

Since yesterday homebrew gives the following warnings for some of your formulae (e.g. hexer and nitro). As you can see, they refer to an depreciated sha1 issue. Concerning the sha1 to sha256 conversion, information is provided here:
https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Checksum_Deprecation.md

Warning messages from homebrew when upgrading formulae:

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/hexer.rb:4:in `<class:Hexer>'

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/hexer.rb:4:in `<class:Hexer>'

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/hexer.rb:4:in `<class:Hexer>'

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/nitro.rb:6:in `<class:Nitro>'

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/nitro.rb:6:in `<class:Nitro>'

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/nitro.rb:6:in `<class:Nitro>'

**Comment by MatzFan** [comment]
Same issue here with gdal-grass64 formula:
```
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/gdal-grass64.rb:6:in `<class:GdalGrass64>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/gdal-grass64.rb:6:in `<class:GdalGrass64>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/gdal-grass64.rb:6:in `<class:GdalGrass64>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling BottleSpecification#sha1 is deprecated!
Use BottleSpecification#sha256 instead.
/usr/local/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/gdal-grass64.rb:11:in `block in <class:GdalGrass64>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling BottleSpecification#sha1 is deprecated!
Use BottleSpecification#sha256 instead.
/usr/local/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/gdal-grass64.rb:12:in `block in <class:GdalGrass64>'
Please report this to the osgeo/osgeo4mac tap!
```

**Comment by jctull** [comment]
This is from a change in policy for homebrew whereby all validations are required to have a sha256 checksum. You can ignore it despite how annoying the warnings may be.

Cheers,
John

**Comment by MatzFan** [comment]
Understand it is possible to safely ignore the warnings, but I'm interested to know if the OSGeo maintainers plan to change the checksum algorithms for their Homebrew formulae to sha256 - either now or at some time in the future. Like many Homebrew users, I guess, I rely on ```brew doctor``` warnings to check my installation is OK and it is nice to keep the output free from false positives

**Comment by rkrug** [comment]
Is there any chance that this will be addressed? Deprecated means that it will not be deleted soon and I don't want to get error messages. Also: this does not put the tap in a good light.

It would be easy to change the source from sha1 to sha256, but I have absolutely no idea about the bottles.

**Comment by jctull** [comment]
It is actually quite tedious to change the checksums, but I did it on the formulae that are in my fork. Unfortunately, I have moved from homebrew to macports because of growing frustration about the slow pace of updates to key dependencies, changes to requirements like qscintilla2 (requires qt5 without a qt4 option), etc. 

On the flip side, I'm not in love with macports. Basically the state of mac support for osgeo ease of use is in a rough state currently.

John

**Comment by jmunowitch** [comment]
I took a stab at this in my Pull Request:
https://github.com/OSGeo/homebrew-osgeo4mac/pull/153

Can anybody confirm this works?

**Comment by rkrug** [comment]
@jmunowitch haven't tried it, but it looks good. What we would need is CI to check the pull requests.

@jctull I know - and one can't change all at the same tie, especially the ones for the bottles. But changing the ones for source could be done by a search-replace (sha1 -> sha256) and than trying to install will give you the correct sha256 checksums which one can than paste into the formulas. Ha - look at [https://github.com/Homebrew/legacy-homebrew/issues/40877](https://github.com/Homebrew/legacy-homebrew/issues/40877) and this might work?

By the way - who has write access to this repo? It is sometimes very quiet for a long time...

**Comment by MatzFan** [comment]
Made a dent in this today (see above!). Couldn't build the remaining formulae for various reasons.

One comment & question (as a newcomer to OSGeo): This repo maintains a large number of formulae & seems to be relied upon by a large number of users. Has anyone asked Homebrew if they would host these formulae themselves under a dedicated tap; Homebrew/Geospatial or similar, or does Homebrew still consider this too "niche"? The reason I ask is that Homebrew's own taps benefit from the [brew test bot](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/dev-cmd/test-bot.rb) verifying all PR's automatically. Alternatively - has anyone looked at the possibility of running a version of the test bot on this repo - perhaps using Travis CI? Big plus for the maintainers would be the bot weeding out build failures before any time is wasted checking them manually. I used Travis CI myself to generate the bottle build sha256 hashes on OS X 10.9 & 10.10, as I run 10.11.

**Comment by dakcarto** [comment]
SHA hashes updated. Thanks to everyone who contributed! Please reopen if needed.

**Comment by dmwelch** [comment]
FYI: @dakcarto, I'm still getting errors with `orfeo-40`, `orfeo-42`, and `orfeo-ice` after pull.

```
Formula (master=) $ brew search orfeo
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/orfeo-40.rb:8:in `<class:Orfeo40>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/orfeo-40.rb:8:in `<class:Orfeo40>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/orfeo-40.rb:8:in `<class:Orfeo40>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling BottleSpecification#sha1 is deprecated!
Use BottleSpecification#sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/orfeo-40.rb:14:in `block in <class:Orfeo40>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/orfeo-40.rb:43:in `block in <class:Orfeo40>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/orfeo-40.rb:43:in `block in <class:Orfeo40>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/orfeo-40.rb:43:in `block in <class:Orfeo40>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/orfeo-42.rb:4:in `<class:Orfeo42>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/orfeo-42.rb:4:in `<class:Orfeo42>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/orfeo-42.rb:4:in `<class:Orfeo42>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling BottleSpecification#sha1 is deprecated!
Use BottleSpecification#sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/orfeo-42.rb:8:in `block in <class:Orfeo42>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/orfeo-42.rb:39:in `block in <class:Orfeo42>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/orfeo-42.rb:39:in `block in <class:Orfeo42>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/orfeo-42.rb:39:in `block in <class:Orfeo42>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/orfeo-ice.rb:12:in `<class:OrfeoIce>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/orfeo-ice.rb:12:in `<class:OrfeoIce>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/orfeo-ice.rb:12:in `<class:OrfeoIce>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling BottleSpecification#sha1 is deprecated!
Use BottleSpecification#sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/orfeo-ice.rb:16:in `block in <class:OrfeoIce>'
Please report this to the osgeo/osgeo4mac tap!

homebrew/boneyard/orfeo           osgeo/osgeo4mac/orfeo-32          osgeo/osgeo4mac/orfeo-40          osgeo/osgeo4mac/orfeo-42          osgeo/osgeo4mac/orfeo-54 ✔        osgeo/osgeo4mac/orfeo-ice
```

**Comment by dakcarto** [comment]
Hi @dmwelch, thanks for reporting. Note, `orfeo-40` and `orfeo-42` will soon be deprecated (in favor of only one `orfeo` formula), though `orfeo-ice` will be updated for use in an update `monteverdi3` formula.

Do you _need_ the older OTB 4.x support?

**Comment by dmwelch** [comment]
Nope, just an FYI.  ty!
