### ISSUE TITLE
gdal failed to build on 10.x

### ISSUE THREAD

**Issue by peteWT** [OSGeo/homebrew-osgeo4mac#149]
I'm getting an error when trying to upgrade gdal on OSX 10.11.6 (15G31) . Something about:

`glibtoolize: line 3771: /usr/local/Library/ENV/4.3/sed: No such file or directory` 

Here is the gist of it:

https://gist.github.com/peteWT/3f00640e172d2f41bb7faee5e1db594f

**Comment by dakcarto** [comment]
Hi @peteWT, thanks for reporting.

Please report upstream issues with the `gdal` formula, as it is from the homebrew-core, not this tap.
