### ISSUE TITLE
openjpeg21 Removed from homebrew-versions

### ISSUE THREAD

**Issue by iheffernan** [OSGeo/homebrew-osgeo4mac#150]
gdal-20 using the --with-complete option requires homebrew/versions/openjpeg21

As of 2 August, this openjpeg21 formula has been removed from the versions repo "in favour of updated core openjpeg" which has now been updated to v2.1.1 in homebrew-core.

https://github.com/Homebrew/homebrew-versions/commit/188498169d47185267e82796d39a8d15bff094a6#openjpeg21.rb

Can you update the gdal-20 formula to reflect this change? Thanks...

**Comment by iheffernan** [comment]
FYI - you can overcome this by running brew edit and changing the openjpeg21 dependency to just openjpeg (assuming you've upgraded core/openjpeg to 211). Still would be nice to have this fixed in the official formula, though.

**Comment by dschneiderch** [comment]
worked for me. thanks!

**Comment by dakcarto** [comment]
@iheffernan Thanks for reporting!
