### ISSUE TITLE
qgis-214 fails to install on 10.11, looking for Qt 4.x

### ISSUE THREAD

**Issue by EconGeo** [OSGeo/homebrew-osgeo4mac#151]
just upgraded to El Capitan.  QGIS was working on 10.9 before.  Trying to reinstall after if wouldn't open after the upgrade.  It fails with an error saying that it is looking for Qt4.  I have both the qt and qt5 formulae installed.  I tried uninstalling qt5 and then installing qgis-214, but it installed qt5 as a dependency.  Tried to build from source by issuing command --without-grass also gave same error.

```
`Warning: Calling Formula.path is deprecated!
Use Formulary.core_path instead.
/usr/local/Library/Taps/osgeo/homebrew-osgeo4mac/Requirements/qgis_requirements.rb:25:in `block in no_linked_qgis'
Please report this to the osgeo/osgeo4mac tap!

==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG
Last 15 lines from /Users/bluebird/Library/Logs/Homebrew/qgis-214/01.cmake:
-- Looking for gaiaDropTable in /usr/local/lib/libspatialite.dylib
-- Looking for gaiaDropTable in /usr/local/lib/libspatialite.dylib - found
-- Looking for gaiaStatisticsInvalidate in /usr/local/lib/libspatialite.dylib
-- Looking for gaiaStatisticsInvalidate in /usr/local/lib/libspatialite.dylib - found
-- Looking for spatialite_init_ex in /usr/local/lib/libspatialite.dylib
-- Looking for spatialite_init_ex in /usr/local/lib/libspatialite.dylib - found
CMake Error at /usr/local/Cellar/cmake/3.6.1/share/cmake/Modules/FindQt4.cmake:1328 (message):
  Found unsuitable Qt version "5.6.1" from /usr/local/opt/qt5/bin/qmake, this
  code requires Qt 4.x
Call Stack (most recent call first):
  CMakeLists.txt:272 (FIND_PACKAGE)


-- Configuring incomplete, errors occurred!
See also "/tmp/qgis-214-20160822-55008-x1uhv0/QGIS-final-2_14_3/build/CMakeFiles/CMakeOutput.log".`
```

**Comment by akx** [comment]
Yup, just bumped into this too. I have the `qt4` formula installed.

**Comment by jctull** [comment]
Have you tried running 'brew link qt' or 'brew link --force qt'? That may help. It looks like the cmake configuration process is picking up qmake from qt5. There isn't a formula for qt4, at least not in homebrew-core.

**Comment by bianchimro** [comment]
Same problem here, log message is exactly the same as @EconGeo .
I have both qt and qt5 formulae installed.
I'm running El Capitan v.10.11.4

@jctull you are right, seems like wrong version of qmake is picked up. 
I tried re-linking qt but no luck. qt5 is not linked.

**Comment by EconGeo** [comment]
the formula for Qt4 is qt.

**Comment by iandees** [comment]
I'm running into this as well. I `brew uninstall qt5` and noticed that `brew install osgeo/osgeo4mac/qgis-214` has a dependency on `qt5`, so it's getting installed instead over `qt`?

```
==> Installing dependencies for osgeo/osgeo4mac/qgis-214: qt5
==> Installing osgeo/osgeo4mac/qgis-214 dependency: qt5
```

**Comment by iandees** [comment]
Relevant StackOverflow question: http://gis.stackexchange.com/questions/207640/qgis-installation-error-qt-versions-osx

**Comment by UH-60** [comment]
Looks like this may be qscintilla2's fault: 

    commit a88f5f4cf83911c9c5b4e7aa7b8d6caab1c95138
    Author: Sebastian Schöps <schoeps@temf.tu-darmstadt.de>
    Date:   Sun Aug 14 13:01:35 2016 +0200

        qscintilla2: use Qt5 not Qt4.

Prior to this I had no problem building qgis. Now, my previously built version segfaults and the build dies like others have encountered. 

Reverting to the previous qscintilla2 formula seems to fix the problem. But since the version numbers didn't change between qscintilla2 commits, a _brew pin_ doesn't prevent the package from being upgraded (and therefore reintroducing the qt5 dependency) each time.

**Comment by jctull** [comment]
In light of the fact that it is qscintilla2 that is causing this problem, an issue should be filed against qscintilla2 on homebrew-core requesting an option for --with-qt4 that would build qscintilla2 against qt4 only.

**Comment by oeon** [comment]
I goofed and `brew update`d today, which upgraded qscintilla2 & sip and gave me qt5 & pyqt5...breaking my `qgis-214` 👎 .

After uninstalling the offenders above and running:

`brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/c630d7bdd17530799fc5fce69a92312da6e2bf08/Formula/qscintilla2.rb`

...I had my QGIS back 👍. 

Wanted to share if this can help anyone. Also `brew pin` looks potentially helpful https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/FAQ.md#how-do-i-stop-certain-formulae-from-being-updated

**Comment by warpedgeoid** [comment]
Running `brew switch qscintilla2 2.9.3` seems to have done the business for me.

**Comment by iandees** [comment]
Even after removing `qscintilla2` and installing 2.9.3 as recommended above I still see homebrew trying to install pyqt5 and qt5 along with a new qscintilla2:

```
$ brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/c630d7bdd17530799fc5fce69a92312da6e2bf08/Formula/qscintilla2.rb
######################################################################## 100.0%
==> Downloading https://homebrew.bintray.com/bottles/qscintilla2-2.9.3.el_capitan.bottle.1.tar.gz
Already downloaded: /Users/iandees/Library/Caches/Homebrew/qscintilla2-2.9.3.el_capitan.bottle.1.tar.gz
==> Pouring qscintilla2-2.9.3.el_capitan.bottle.1.tar.gz
🍺  /usr/local/Cellar/qscintilla2/2.9.3: 130 files, 6.2M
$ brew install qgis-214
==> Installing qgis-214 from osgeo/osgeo4mac
Warning: Calling Formula.path is deprecated!
Use Formulary.core_path instead.
/usr/local/Library/Taps/osgeo/homebrew-osgeo4mac/Requirements/qgis_requirements.rb:25:in `block in no_linked_qgis'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling Formula.path is deprecated!
Use Formulary.core_path instead.
/usr/local/Library/Taps/osgeo/homebrew-osgeo4mac/Requirements/qgis_requirements.rb:25:in `block in no_linked_qgis'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling Formula.path is deprecated!
Use Formulary.core_path instead.
/usr/local/Library/Taps/osgeo/homebrew-osgeo4mac/Requirements/qgis_requirements.rb:25:in `block in no_linked_qgis'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling Formula.path is deprecated!
Use Formulary.core_path instead.
/usr/local/Library/Taps/osgeo/homebrew-osgeo4mac/Requirements/qgis_requirements.rb:25:in `block in no_linked_qgis'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling Formula.path is deprecated!
Use Formulary.core_path instead.
/usr/local/Library/Taps/osgeo/homebrew-osgeo4mac/Requirements/qgis_requirements.rb:25:in `block in no_linked_qgis'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling Formula.path is deprecated!
Use Formulary.core_path instead.
/usr/local/Library/Taps/osgeo/homebrew-osgeo4mac/Requirements/qgis_requirements.rb:25:in `block in no_linked_qgis'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling Formula.path is deprecated!
Use Formulary.core_path instead.
/usr/local/Library/Taps/osgeo/homebrew-osgeo4mac/Requirements/qgis_requirements.rb:25:in `block in no_linked_qgis'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling Formula.path is deprecated!
Use Formulary.core_path instead.
/usr/local/Library/Taps/osgeo/homebrew-osgeo4mac/Requirements/qgis_requirements.rb:25:in `block in no_linked_qgis'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling Formula.path is deprecated!
Use Formulary.core_path instead.
/usr/local/Library/Taps/osgeo/homebrew-osgeo4mac/Requirements/qgis_requirements.rb:25:in `block in no_linked_qgis'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling Formula.path is deprecated!
Use Formulary.core_path instead.
/usr/local/Library/Taps/osgeo/homebrew-osgeo4mac/Requirements/qgis_requirements.rb:25:in `block in no_linked_qgis'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling Formula.path is deprecated!
Use Formulary.core_path instead.
/usr/local/Library/Taps/osgeo/homebrew-osgeo4mac/Requirements/qgis_requirements.rb:25:in `block in no_linked_qgis'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling Formula.path is deprecated!
Use Formulary.core_path instead.
/usr/local/Library/Taps/osgeo/homebrew-osgeo4mac/Requirements/qgis_requirements.rb:25:in `block in no_linked_qgis'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling Formula.path is deprecated!
Use Formulary.core_path instead.
/usr/local/Library/Taps/osgeo/homebrew-osgeo4mac/Requirements/qgis_requirements.rb:25:in `block in no_linked_qgis'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling Formula.path is deprecated!
Use Formulary.core_path instead.
/usr/local/Library/Taps/osgeo/homebrew-osgeo4mac/Requirements/qgis_requirements.rb:25:in `block in no_linked_qgis'
Please report this to the osgeo/osgeo4mac tap!

==> Installing dependencies for osgeo/osgeo4mac/qgis-214: qt5, pyqt5, qscintilla2
```

**Comment by oeon** [comment]
@iandees did you ever have a working version of `qgis-214`, or is this a new install? Maybe that's the difference. Sorry to hear you're having issues. Looks like this is going to be quite a challenge: https://github.com/qgis/QGIS/blob/master/INSTALL#L325 & https://github.com/Homebrew/homebrew-core/issues/4365

**Comment by iandees** [comment]
Nope, this is on a brand new machine that I never got homebrew going on. I ended up just falling back to Kyng Chaos, which is annoying.

**Comment by iandees** [comment]
It looks like even though I have `qscintilla2` installed and pinned at the specified version above running `brew install qgis-214` wants to bring in a newer `qscintilla2`. I'm looking for a way to let me specify which version of `qscintilla2` can be used in the `qgis-214` package.

**Comment by iandees** [comment]
I solved it on my end by editing the `qgis-214.rb` Formula to `depends_on` a specific URL instead of `qscintilla2`:

```diff
diff --git a/Formula/qgis-214.rb b/Formula/qgis-214.rb
index a1898c6..2b4edfe 100644
--- a/Formula/qgis-214.rb
+++ b/Formula/qgis-214.rb
@@ -70,7 +70,7 @@ class Qgis214 < Formula
   depends_on SipBinary
   depends_on PyQtConfig
   depends_on "qca"
-  depends_on "qscintilla2" # will probably be a C++ lib deps in near future
+  depends_on "https://raw.githubusercontent.com/Homebrew/homebrew-core/c630d7bdd17530799fc5fce69a92312da6e2bf08/Formula/qscintilla2.rb" # will probably be a C++ lib deps in near future
   depends_on "qwt"
   depends_on "qwtpolar"
   depends_on "gsl"
```

After that, `brew install qgis-214` seems to be progressing without a problem.

**Comment by oeon** [comment]
hmmm, after pinning - mine gives me:
```
➜  ~ brew update
Already up-to-date.

➜  ~ brew outdated
qscintilla2 (2.9.3) < 2.9.3_1

➜  ~ brew upgrade

==> No packages to upgrade
==> Not upgrading 1 pinned package:
qscintilla2 2.9.3_1
```

**Comment by pat-s** [comment]
Is it possible to update the `depends_on` change @iandees did in his post into the official `qgis-214.rb` so that this fix works for everyone?

**Comment by dakcarto** [comment]
Try building with latest commits (tested on 10.11.6), which introduce a `qscintilla2-qt4` formula to fix this, since upstream at Homebrew seems to not be interested in maintaining Qt4 support once macOS 10.12 lands (a reasonable point to fully deprecate Qt4).

**Comment by pat-s** [comment]
Tested with the latest commits (on 10.11.6). `make install` of `QGIS 2.14.6` took 36 minutes on my MBP to complete. In the end I get the [Missing psycopg2 dependency](https://github.com/OSGeo/homebrew-osgeo4mac/issues/5) error. However, `psycopg2`lib was installed a priori.

**Comment by ecerrillo** [comment]
I don't know if I should start another threat, but due to the new actualization of qgis-214 formula after the present failure there is a new error. I think that a simple editing of the formula should solve it. Here it is:

```
Error: /usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/qgis-214.rb:73: syntax error, unexpected <<, expecting keyword_end
<<<<<<< Updated upstream
  ^
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/qgis-214.rb:75: syntax error, unexpected ===, expecting keyword_end
=======
   ^
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/qgis-214.rb:77: syntax error, unexpected >>, expecting keyword_end
>>>>>>> Stashed changes
  ^
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:42:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:94:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:85:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:81:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:179:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:219:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:246:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:229:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1243:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1241:in `map'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1241:in `installed'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:27:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:99:in `<main>'

```

**Comment by dakcarto** [comment]
@ecerrillo, yes you should start another thread, as `brew audit --strict qgis-214` does not show any errors after most recent commit. Nothing I fixed is related to your error however. I can only assume you are using a newer version of Ruby that is supported by Homebrew. Check your `brew doctor` output.

**Comment by christianbraun** [comment]
I do get exactly the same error as ecerrillo.
`brew audit --strict qgis-214` is also throwing back the error...
Any ideas here?

**Comment by dakcarto** [comment]
@ecerrillo and @christianbraun you are receiving those errors because your tap repo is in an incomplete merging state, e.g.:

```
<<<<<<< Updated upstream
...
>>>>>>> Stashed changes
```
are indications that either Homebrew has failed at auto-updating your `brew` install or you have custom changes in your working tree (like edits to `qgis-214`) that could not be auto-merged.

With latest Homebrew go to `$(brew --prefix)/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac` then issue `git status` and `git diff` to see what state your tap repo is in. (NOTE: latest Homebrew adds `Homebrew` subdirectory to that path before `Library` now.)

**Comment by dakcarto** [comment]
@christianbraun what is the error that `brew audit --strict qgis-214` is throwing? Nothing here on 10.11.6. Have you done a `brew update`?

**Comment by christianbraun** [comment]
@dakcarto I solved it by getting the QGIS formula from the repo. Thanks for your help!

**Comment by dakcarto** [comment]
Please reopen if necessary.

**Comment by xav34** [comment]
Hi all,
I read all comments about the QT5 dependency issues with the qgis-214.rb

Using the last qgis-214.rb a still get the error : 

CMake Error at /usr/local/Cellar/cmake/3.6.1/share/cmake/Modules/FindQt4.cmake:1328 (message):
  Found unsuitable Qt version "5.6.1" from /usr/local/opt/qt5/bin/qmake, this
  code requires Qt 4.x
Call Stack (most recent call first):
  CMakeLists.txt:272 (FIND_PACKAGE)

It appears that the qca package was using Qt5 libraries (qt5 recommended but in fact needed)
"Brewing" the qca with the --without-qt5 option does not work.
I found that using the brew --tree qgis-214
 
Supposing that the issue comes from this package, Is there any formula referencing an old version of qca  ?
I'm in the fog...

Thanks in advance
