### ISSUE TITLE
Tapping into won't work  :using => CacheDownloadStrategy - returns error

### ISSUE THREAD

**Issue by jannefleischer** [OSGeo/homebrew-osgeo4mac#152]
Hi,

I recently untapped osgeo/osgeo4mac and now trying to tap into again. I am getting these errors:

```
invalid attribute for formula 'osgeo/osgeo4mac/filegdb-api': url ("file:///Volumes/1000er Intern/Users/Janne/Library/Caches/Homebrew/FileGDB_API_1_3-64.zip")
invalid attribute for formula 'osgeo/osgeo4mac/mrsid-sdk': url ("file:///Volumes/1000er Intern/Users/Janne/Library/Caches/Homebrew/MrSID_DSDK-9.5.1.4427-darwin14.universal.clang60.tar.gz")
invalid attribute for formula 'osgeo/osgeo4mac/oracle-client-sdk': url ("file:///Volumes/1000er Intern/Users/Janne/Library/Caches/Homebrew/instantclient-basiclite-macos.x64-11.2.0.4.0.zip")
```

With the result of:

```
Error: Cannot tap osgeo/osgeo4mac: invalid syntax in tap!
```

Prior to the untap I was able to work with this tap. I am guessing something in homebrew itself changed while the tap was already tapped. I think 

```
:using => CacheDownloadStrategy
```

is causing this error on tap (because this is only used in all the formulas that report that invalid attribute error and it is not native to homebrew).

Sadly, I do not know enough about ruby or homebrew to fix it myself...

**Comment by PaoloC68** [comment]
I am running in the same issue.

**Comment by dakcarto** [comment]
Hi @jannefleischer and @PaoloC68, thanks for reporting.

Can you verify that the same happens when the cache has a path _without_ spaces in it, and ideally, the cache is not on an external drive?

**Comment by dakcarto** [comment]
Ok, looks like the `url` attribute for a `formula` will error if its string contains a space:

From `$(brew --prefix)/Homebrew/Library/Homebrew/formula.rb`
```
242    url = active_spec.url
243    if url.nil? || url.empty? || url =~ /\s/
244      raise FormulaValidationError.new(full_name, :url, url)
245    end
```

Specifically, the `url =~ /\s/` bit will raise that error if the URL contains a space.

If you have a volume with a space in its name, you can try creating a no-space-in-name symlink to it and assign the symlink path to `HOMEBREW_CACHE`:

```
export HOMEBREW_CACHE=symlink/path
```

**Comment by dakcarto** [comment]
Closing. Please reopen if necessary.
