### ISSUE TITLE
QGIS searches for proj libraries in wrong path after proj update

### ISSUE THREAD

**Issue by ecerrillo** [OSGeo/homebrew-osgeo4mac#170]
I got an error when launching qgis-214 after updating to Mac OS X Sierra and later upgrading proj libraries. QGIS searches for the proj lib in /usr/local/opt/proj/lib/libproj.9.dylib, but the location of the library has changed.

Here is the  report of error:

`Dyld Error Message:
  Library not loaded: /usr/local/opt/proj/lib/libproj.9.dylib
  Referenced from: /usr/local/Cellar/qgis-214/2.14.3/QGIS.app/Contents/MacOS/QGIS
  Reason: image not found`

and a quick solution:

`sudo ln /usr/local/Cellar/proj/4.9.2/lib/libproj.9.dylib /usr/local/opt/proj/lib/`

**Comment by pwt-nf** [comment]
Same experience here..

**Comment by dakcarto** [comment]
Hi @ecerrillo, thanks for reporting.

You have upgraded a dependency (`proj` 4.9.2 -> 4.9.3, libproj.9.dylib -> libproj.12.dylib), so QGIS can no longer find the older library. You need to re-compile `qgis-214` whenever you change its underlying linked libraries and there is not an appropriate bottle available. Symlinking the older lib is _not recommended_.
