### ISSUE TITLE
Qgis won't launch on El Capitan

### ISSUE THREAD

**Issue by nikjft** [OSGeo/homebrew-osgeo4mac#173]
Successfully built qgis using homebrew, but now it won't open. Report is as follows:

`Process:               QGIS [97464]
Path:                  /usr/local/Cellar/qgis-214/2.14.6/QGIS.app/Contents/MacOS/QGIS
Identifier:            org.qgis.qgis2-hb
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           QGIS [97464]
User ID:               1170174668

Date/Time:             2016-10-07 16:29:48.343 -0600
OS Version:            Mac OS X 10.11.6 (15G1004)
Report Version:        11
Anonymous UUID:        FEEA7DB5-FB1F-9405-A0FF-1FA506BB9998

Sleep/Wake UUID:       02C653D8-83D8-44F4-9931-A0942D61D7CE

Time Awake Since Boot: 140000 seconds
Time Since Wake:       6500 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/lib/libpng15.15.dylib
  Referenced from: /usr/local/lib/QtGui.framework/Versions/4/QtGui
  Reason: image not found

Binary Images:
    0x7fff6b3cf000 -     0x7fff6b406a47  dyld (360.22) <DC81CC9D-651A-3A45-8809-928282052BD3> /usr/lib/dyld
    0x7fff87640000 -     0x7fff88269ff7  com.apple.AppKit (6.9 - 1404.47) <F3411F6E-DD87-34D0-8C68-C69B2205E41D> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff88822000 -     0x7fff88c98fff  com.apple.CoreFoundation (6.9 - 1258.1) <943A1383-DA6A-3DC0-ABCD-D9AEB3D0D34D> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff8904d000 -     0x7fff890c2fff  com.apple.framework.IOKit (2.0.2 - 1179.50.2) <A509D3AE-9D48-31B7-89C7-326A7A2007B2> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff8b565000 -     0x7fff8b573fff  com.apple.opengl (12.1.0 - 12.1.0) <0718DB60-BA4F-3CF7-A117-10A2515D931F> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
    0x7fff90571000 -     0x7fff90571fff  com.apple.Carbon (154 - 157) <8F6ED602-5943-3E29-A793-BC331E2C183D> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
    0x7fff92a70000 -     0x7fff92ac3ff7  libc++.1.dylib (120.1) <8FC3D139-8055-3498-9AC5-6467CB7F4D14> /usr/lib/libc++.1.dylib
    0x7fff96c63000 -     0x7fff96c74ff7  libz.1.dylib (61.20.1) <B3EBB42F-48E3-3287-9F0D-308E04D407AC> /usr/lib/libz.1.dylib
    0x7fff96e20000 -     0x7fff96e21ffb  libSystem.B.dylib (1226.10.1) <012548CD-614D-3AF0-B3B1-676F427D2CD6> /usr/lib/libSystem.B.dylib
    0x7fff991e9000 -     0x7fff991e9fff  com.apple.CoreServices (728.13 - 728.13) <E3DFECD2-ECEA-3242-972D-95B9646B57B8> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff9b41a000 -     0x7fff9b41afff  com.apple.ApplicationServices (48 - 48) <ADD57D3A-142F-3EF5-BFD8-EACD82164884> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices

Model: MacBookAir6,2, BootROM MBA61.0099.B22, 2 processors, Intel Core i7, 1.7 GHz, 8 GB, SMC 2.13f15
Graphics: Intel HD Graphics 5000, Intel HD Graphics 5000, Built-In
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1600 MHz, 0x80AD, 0x483943434E4E4E384A544D4C41522D4E544D
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1600 MHz, 0x80AD, 0x483943434E4E4E384A544D4C41522D4E544D
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x117), Broadcom BCM43xx 1.0 (7.21.95.175.1a6)
Bluetooth: Version 4.4.6f1 17910, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0512F, 500.28 GB
USB Device: USB 3.0 Bus
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Air, Apple Inc., 23.6
`

**Comment by dakcarto** [comment]
@nikjft thanks for reporting:

```
Dyld Error Message:
Library not loaded: /usr/local/lib/libpng15.15.dylib
Referenced from: /usr/local/lib/QtGui.framework/Versions/4/QtGui
Reason: image not found
```

This is unrelated to QGIS, per se. The `qt` formula is referencing a `libpng` that no longer exists. You will need to upgrade `qt`, then try launching QGIS. If it still does not launch, you may need to re-compile it.

If upgrading `qt` is not available, you can try searching Homebrew-core repo for issues related to this.

**Comment by dakcarto** [comment]
@nikjft this should be addressed with the new `qgis2-ltr` formula, specifically refer to https://github.com/OSGeo/homebrew-osgeo4mac/issues/177#issuecomment-253993786.

Please verify install when you have a chance (note, all new formulae require compiling). Successfully tested on 10.11.6 and 10.12.0.

**Comment by christianurich** [comment]
Thanks for upgrading the package!
I have qgis2 (2.16.3) running on 10.12.0

**Comment by dakcarto** [comment]
Closing due to lack of response. Please reopen if necessary.
