### ISSUE TITLE
Depricated SHA1 usage

### ISSUE THREAD

**Issue by cLupus** [OSGeo/homebrew-osgeo4mac#179]
When brew is updating, and when I run ```brew doctor```, I get the following warnings:

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/gdal-110.rb:6:in `<class:Gdal110>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/gdal-110.rb:6:in `<class:Gdal110>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/gdal-110.rb:6:in `<class:Gdal110>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/gdal-110.rb:75:in `block in <class:Gdal110>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/gdal-110.rb:75:in `block in <class:Gdal110>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/gdal-110.rb:75:in `block in <class:Gdal110>'
Please report this to the osgeo/osgeo4mac tap!

Are you planing to fix this "issue" in the near future, or would it be too much work for too little gain?

**Comment by apjanke** [comment]
It looks like this was already fixed in https://github.com/OSGeo/homebrew-osgeo4mac/commit/1423202588218eabc281a97076c48eaa5d538ccf and you shouldn't see the warning any more once you're up to date. Is it still happening on each `brew update`? And if so, do you have a branch or old version of the `osgeo4mac` tap checked out?

**Comment by dakcarto** [comment]
Please reopen if this persists.
