### ISSUE TITLE
qgis2 "Error: can't modify frozen Array"

### ISSUE THREAD

**Issue by bdon** [OSGeo/homebrew-osgeo4mac#187]
During ```brew install -v qgis2``` the install fails with:

```
...
==> Verifying qgis2--pyqgis-startup-2.0.0.py checksum
Error: can't modify frozen Array
```

This is on a fresh MacOS 10.12.1 machine

**Comment by bdon** [comment]
Found the line:

```
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/qgis2.rb:319:in `insert'
RuntimeError: can't modify frozen Array
```

**Comment by bdon** [comment]
I was able to work around this by adding ```.dup``` to ```ORIGINAL_PATHS```

**Comment by dakcarto** [comment]
@bdon, thanks for reporting and providing a fix! Updated both `qgis2` and `qgis2-ltr`.

**Comment by dakcarto** [comment]
Closing, please reopen if necessary.
