### ISSUE TITLE
hexer SHA256 mismatch on 10.12.1

### ISSUE THREAD

**Issue by earthflat** [OSGeo/homebrew-osgeo4mac#188]
Dears,

when trying to install hexer on macOS 10.12.1 the follow error is thrown:

brew install hexer
==> Installing hexer from osgeo/osgeo4mac
==> Downloading https://github.com/hobu/hexer/archive/1.3.0.tar.gz
==> Downloading from https://codeload.github.com/hobu/hexer/tar.gz/1.3.0
######################################################################## 100,0%
Error: SHA256 mismatch
Expected: 132f574682a45d67dd276ff9d274b71ec843262edf6101d85aa03b52ccd2cea3
Actual: 826789332b26aa8bc2d766e3732362d11374ed2df45f9194459cfc3d32123d05
Archive: /Users/mac/Library/Caches/Homebrew/hexer-1.3.0.tar.gz
To retry an incomplete download, remove the file above.

I've emptied ~/Library/Caches/Homebrew and also tried it on a freshly installed machine - but always the same error.

Here the brew config from the machine:
$ brew config
HOMEBREW_VERSION: 1.1.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: edf042ee97f80955b077724119e717a51eb25e29
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 75a59a2795510f67883ed1c87e659c073ebad0da
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.9.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_111, 1.8.0_101, 1.6.0_65-b14-468
macOS: 10.12.1-x86_64
Xcode: 8.1
CLT: 8.1.0.0.1.1476494586
X11: 2.7.9 => /opt/X11

And here brew doctor:
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/ublio.h

Hope somebody can help.

**Comment by cm325** [comment]
Same problem here, except I get it for this file - oracle-client-sdk-11.2.0.4.0.zip

**Comment by dakcarto** [comment]
Hi @earthflat, thanks for reporting.

Should be fixed in b5773ee. Reopen issue if necessary.
