### ISSUE TITLE
grass 7.0.5 on macOS 10.12.1 failed with system python

### ISSUE THREAD

**Issue by fxi** [OSGeo/homebrew-osgeo4mac#189]
Grass 7.0.5 did not compile on 10.12.1 with system python.

I had to `brew install python` to get it work.

`depends_on "python"` instead of `depends_on :python` ? 
 
Thanks !

**Comment by dakcarto** [comment]
Hi @fxi, thanks for reporting! Please retry `grass7` install after `brew update`. GRASS is now at 7.2.0.

**Comment by dakcarto** [comment]
Also, if it fails to compile using the system Python again, please provide [Troubleshooting](https://github.com/Homebrew/brew/blob/master/docs/Troubleshooting.md) logs.
