### ISSUE TITLE
gdal2-python Formula not working

### ISSUE THREAD

**Issue by gbataille** [OSGeo/homebrew-osgeo4mac#194]
Hey guys,

2 issues:
* in the message method, some method are not properly namespace and it fails at runtime
```
  def message
    s = "`gdal2` formula already installed with Python 2 or 3 bindings:\n"
    s += "  #{gdal2_python("python")}\n" if Gdal2Python.gdal2_py2_exist?
    s += "  #{gdal2_python("python3")}\n" if Gdal2Python.gdal2_py3_exist?
    s += "`gdal2` install options:\n"
    s += "  gdal2 #{gdal2_opts.to_a.join(" ")}\n"
    s += "Install latest `gdal2`, which installs no Python bindings:\n"
    s + "  `brew reinstall gdal2` or `brew upgrade gdal2`"
  end
```
`gdal2_python` should be `Gdal2Python.gdal2_python`. Same for `gdal_opts`

* The package refuses to install if gdal2 is already there. it says that gdal2 is there *with* python bindings where gdal2 is indeed there, but not the python bindings

**Comment by gbataille** [comment]
I have not investigated it (the formula are a bit more complicated than what I'm used to).

For point 2 maybe I should have followed the hint to reinstall the latest gdal2. but since I installed gdal2 2 weeks ago, I figured it was rather broken

(FYI, what I did was uninstall gdal2 and install gdal2-python which pulled gdal2 as a dependency)

**Comment by dakcarto** [comment]
Hi @gbataille, thanks for reporting. Please `brew update` and try again. Should be fixed with 9e40748.

**Comment by gbataille** [comment]
thanks. I'll try to do some tests next week.

**Comment by dakcarto** [comment]
Closing. Please reopen if necessary.
