### ISSUE TITLE
A request for gdal2/gdal2-python to support general network model

### ISSUE THREAD

**Issue by kkdd** [OSGeo/homebrew-osgeo4mac#195]
A request for the gdal2 formula to support an option of its general network model (GNM).
See also https://github.com/OSGeo/homebrew-osgeo4mac/pull/192 and https://github.com/OSGeo/homebrew-osgeo4mac/pull/171.

**Comment by dakcarto** [comment]
Hi @kkdd, thanks for your contributions. GNM support added in 237d193 and fa6d8e0.

Reopen this issue or the others if needed.
