### ISSUE TITLE
GRASS GIS needs numpy dependency

### ISSUE THREAD

**Issue by wenzeslaus** [OSGeo/homebrew-osgeo4mac#202]
Executing the following works:

```
brew tap osgeo/osgeo4mac
brew install grass7
```

but to get GRASS GIS working, numpy was needed as well. Numpy is not a mandatory dependency (although now it looks like one) but it is needed to get many of the features. I don't know how exactly numpy was installed (not my computer), if it was through pip or brew.

**Comment by mutolisp** [comment]
Got your message

**Comment by mutolisp** [comment]
I'm sorry for sent wrong message!

On Thu, Jan 12, 2017 at 12:20 AM,  <mutolisp@gmail.com> wrote:
> Got your message



-- 
Lin, Cheng-Tao, Ph.D. Assistant Professor
Department of Biological Resources,
National Chiayi University, Chiayi, Taiwan.
Tel: +886-5-2717829
Mob: +886-9-19172708

**Comment by dakcarto** [comment]
Hi @wenzeslaus, thanks for reporting! Should be fixed in 2651eb5. Reopen if necessary.
