### ISSUE TITLE
Invalid domain certificate for sourceforge download of pyqt-qt4

### ISSUE THREAD

**Issue by matadorcode** [OSGeo/homebrew-osgeo4mac#204]
Download link for pyqt-qt4 formula has an invalid ssl certificate for the sourceforge subdomain for the file at "https://downloads.sf.net/project/pyqt/PyQt4/PyQt-4.11.4/PyQt-mac-gpl-4.11.4.tar.gz"

**Comment by dakcarto** [comment]
Hi @matadorcode, thanks for reporting!

I think this is a temporary issue (I can't replicate here). Also, may related to the mirror domain that SourceForge offloaded the download to.

Please try again.

**Comment by m-kuhn** [comment]
Closing as a (possibly local) temporary issue. If this happens again, please reopen.
