### ISSUE TITLE
build `liblas` with `gdal2`?

### ISSUE THREAD

**Issue by pat-s** [OSGeo/homebrew-osgeo4mac#205]
> Error: You must `brew link gdal` before liblas can be installed

I have `gdal2` installed from the `osgeo4mac` tap. 
Is there a way to build liblas with `gdal2` or completely change to `gdal2`?

**Comment by dakcarto** [comment]
Hi @pat-s, thanks for reporting.

The only way to do this is to `brew edit liblas` and change the dependency to `gdal2`, or create a local copy and install via `brew install <path/to/your/liblas.rb>`.

**Comment by pat-s** [comment]
Thanks, simple solution which works like a charm :smiley:
