### ISSUE TITLE
wxpython won't launch GUI for GRASS 7.2

### ISSUE THREAD

**Issue by chase-dwelle** [OSGeo/homebrew-osgeo4mac#207]
I installed GRASS via the instructions on [this page](https://grasswiki.osgeo.org/wiki/Compiling_on_MacOSX_using_homebrew), but am unable to get the GUI for GRASS to launch. When I am in my (default) Python 3 environment I get an error from `wxpython`. Switching to my Python 2.7 environment I get the following:

```
>>> (python2)$ grass72
Starting GRASS GIS...
This program needs access to the screen.
Please run with a Framework build of python, and only when you are
logged in on the main display of your Mac.
ERROR: Error in GUI startup. See messages above (if any) and if necessary, please report this error to the GRASS developers.
On systems with package manager, make sure you have the right GUI package, probably named grass-gui, installed.
To run GRASS GIS in text mode use the -text flag.
Use '--help' for further options
     grass72 --help
See also: https://grass.osgeo.org/grass72/manuals/helptext.html
Exiting...
```

This seems to be an error related to `wxpython` and I thought I would be able to run in the text mode but when I get the following:

```
>>> (python2)$ grass72 -text
ERROR: Unable to start GRASS GIS. You have the choice to:
 - Launch the graphical user interface with the '-gui' switch
     grass72 -gui
 - Launch with path to the location/mapset as an argument
     grass72 /path/to/location/mapset`
 - Create a location with '-c' and launch in its PERMANENT mapset
     grass72 -c EPSG:number /path/to/location
     grass72 -c geofile /path/to/location
 - Create manually the GISRC file (/Users/chase/.grass7/rc)
 - Use '--help' for further options
     grass72 --help
See also: https://grass.osgeo.org/grass72/manuals/helptext.html
Exiting...
```

Is this known behavior, and if so, is there any known fix?

**Comment by dakcarto** [comment]
Hi @chase-dwelle, thanks for reporting. Which formula did you install? That page references an older one. it should be `grass7` (though there is an alias for `grass-70` to it I think).

I'm not sure what you mean by "Python 2.7 environment," or what your `>>> (python2)$` prompt indicates. Seems like you should try running `grass72` from a "normal" Terminal session, or at least from a standard macOS bash environ, as a baseline.

@rkrug, do you mind updating that GRASS page to be current with the latest OSGeo4Mac formulae?

**Comment by chase-dwelle** [comment]
Thank you for the quick response. I figured out part of the issue. I did go back and reinstall GRASS with the `grass7` instead of `grass-70`.

The main issue was that my Anaconda environment was the first in my `PATH`, where
'''
> echo $PATH
/Users/chase/anaconda/envs/python2/bin:/Users/chase/anaconda/bin:/usr/local/opt/coreutils/libexec/gnubin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/MacGPG2/bin:/Library/TeX/texbin
'''

If I move anaconda to the end of `PATH`, GRASS starts as expected. However, I thought that this wasn't supposed to make a difference. I would prefer to have Anaconda at the beginning of my PATH. Is there still a way I can do that and start GRASS normally? According to the wiki on the GRASS page:

> NOTES:
> 1. PATH adjustments are only needed during installation. After installation, the PATH can return to its default value and GRASS works fine.

**Comment by dakcarto** [comment]
There are a couple of things you can try (in order of recommendation):

* Globally set the GRASS_PYTHON environment variable to `/usr/local/bin/python2`. This is the 'official' setup for using a [different python interpreter for wxpython at runtime](https://grasswiki.osgeo.org/wiki/GRASS_and_Python#Using_a_version_of_Python_different_from_the_default_installation). However, "only used for components which use wxPython." So, it may only work for direct launching of `grass72` wrapper script.
* Run with `PATH=<custom/path:for/grass7:to/use> grass72 <options>` - this localizes the PATH variable to the execution of GRASS. You could set an `alias` in your BASH profile, e.g. `alias grass7-hb="<noted command>"` for easy launching.
* Change the `!#` line in `/usr/local/opt/grass7/bin/grass72` from `#!/usr/bin/env python` to `#!/usr/local/bin/python2`. However, this changes the install, and will be reverted on next upgrade or upon reinstall.

**Comment by dakcarto** [comment]
If you want `grass7` to _always_ use your Anaconda setup, you can try compiling from source with `brew install --build-from-source grass7`, ensuring your Anaconda's `python` is first on PATH. There are other considerations, like `gdal2-python` etc, which are built against Homebrew's Python. If there is 2.7.x version parity between the C-extension module compilations, then things should work. Obviously, Python 3 won't. Also, mixing Python installs is an unsupported task. Personally, I am limited to how complex or non-standard user's runtime setups can be and still support issues related to such setups.

**Comment by chase-dwelle** [comment]
Setting `GRASS_PYTHON=/usr/local/bin/python2` in `~/.bash_profile` did the trick for me. Now that I have it working, probably best not to mess with using Anaconda, etc.

Thanks for your help and I consider this issue closed.
