### ISSUE TITLE
gdal1-mrsid and gdal2-mrsid fails to build

### ISSUE THREAD

**Issue by pjduplooy** [OSGeo/homebrew-osgeo4mac#213]
Hi guys

As you can see, from my title. mrsid for gdal1 and gdal2 refuses to build, and gives an error:

No such file or directory - liblaslib.dylib

I also see that there is a new version of the sdk out namely MrSID_DSDK-9.5.4.4703-darwin16.universal.clang80.tar.gz built for clang 8.0, which is the clang on my machine.

Also, why does the sdk build against gdal2, even if i specify gdal1?

Could you please investigate?

Regards

Pieter

**Comment by dakcarto** [comment]
@pjduplooy, thanks for reporting! Please provide [Troubleshooting](https://github.com/Homebrew/brew/blob/master/docs/Troubleshooting.md) logs.

I can not reproduce the issue, nor do I understand:
> Also, why does the sdk build against gdal2, even if i specify gdal1?

**Comment by pjduplooy** [comment]
Ok first of all, brew gist-logs gdal1-mrsid or brew gist-logs mrsid-sdk does not provide any output, or I dont know how to use it.

When I first did a brew -v install gdal1-mrsid, gdal2 got built.  In the formula mrsid-sdk is a dependency, and when I do a brew edit mrsid-sdk, I see that there was a dependency of gdal2.  This is a bit strange, but as you said in another post, gdal1 and gdal2 can co-exist, so I was not to worried.

The fail comes in after extracting of the "source".

The only output is:

Pieters-Mac-mini:~ pieterduplooy$ brew -v install mrsid-sdk 
==> Installing mrsid-sdk from osgeo/osgeo4mac
==> Downloading file:///Users/pieterduplooy/Library/Caches/Homebrew/MrSID_DSDK-9.5.1.4427-darwin14.universal.clang60.tar.gz
Already downloaded: /Users/pieterduplooy/Library/Caches/Homebrew/mrsid-sdk-9.5.1.4427.tar.gz
==> Verifying mrsid-sdk-9.5.1.4427.tar.gz checksum
tar xzf /Users/pieterduplooy/Library/Caches/Homebrew/mrsid-sdk-9.5.1.4427.tar.gz
Error: No such file or directory - liblaslib.dylib

**Comment by dakcarto** [comment]
When `/Users/pieterduplooy/Library/Caches/Homebrew/MrSID_DSDK-9.5.1.4427-darwin14.universal.clang60.tar.gz` is decompressed, does it actually have `MrSID_DSDK-9.5.1.4427-darwin14.universal.clang60/Lidar_DSDK/lib/liblaslib.dylib`? Or, is it a download that was renamed to match the expected name?

I noticed that on https://www.lizardtech.com/developer/retired-sdks the macOS and iOS downloads are reversed.

If the base archive looks right, like this (expanding just `bin` and `lib` contents):
```
├── LICENSE.pdf
├── Lidar_DSDK
│   ├── Copyrights_Trademarks_and_Credits.pdf
│   ├── LICENSE.pdf
│   ├── README.txt
│   ├── bin
│   │   ├── lidardecode
│   │   └── lidarinfo
│   ├── contributions
│   ├── doc
│   ├── examples
│   ├── include
│   └── lib
│       ├── liblaslib.dylib
│       ├── liblti_lidar_dsdk.1.dylib
│       ├── liblti_lidar_dsdk.dylib -> liblti_lidar_dsdk.1.dylib
│       └── libtbb.dylib
├── README.txt
├── Raster_DSDK
│   ├── 3rd-party
│   ├── Copyrights_Trademarks_and_Credits.pdf
│   ├── LICENSE.pdf
│   ├── README.txt
│   ├── bin
│   │   ├── mrsiddecode
│   │   └── mrsidinfo
│   ├── doc
│   ├── examples
│   ├── include
│   └── lib
│       ├── libgeos.2.2.3.dylib
│       ├── libgeos.2.dylib -> libgeos.2.2.3.dylib
│       ├── libgeos.dylib -> libgeos.2.2.3.dylib
│       ├── libgeos_c.1.1.1.dylib
│       ├── libgeos_c.1.dylib -> libgeos_c.1.1.1.dylib
│       ├── libgeos_c.dylib -> libgeos_c.1.1.1.dylib
│       ├── libltidsdk.9.dylib
│       ├── libltidsdk.dylib -> libltidsdk.9.dylib
│       └── libtbb.dylib
└── examples
```

Then check `/Users/pieterduplooy/Library/Caches/Homebrew/mrsid-sdk-9.5.1.4427.tar.gz `. If it is different, delete it and try again.

**Comment by pjduplooy** [comment]
Hi, 

The contents of the archive is exactly according to the structure you gave
