### ISSUE TITLE
grass7 configuration in qgis2 not working

### ISSUE THREAD

**Issue by dschneiderch** [OSGeo/homebrew-osgeo4mac#214]
I installed gdal2, grass7, and qgis2 yesterday but I can't get grass7 to work in the processing toolbox. It seems to work fine when I start it from the command line with `grass72`

> Missing dependency. This algorithm cannot be run :-( 
> It seems that GRASS GIS 7 is not correctly installed and configured in your system. Please install it before running GRASS GIS 7 algorithms.

I set up the options in processing:
<img width="537" alt="screen shot 2017-02-28 at 9 44 44 am" src="https://cloud.githubusercontent.com/assets/7461221/23397906/a67e8aca-fd9a-11e6-98a3-1ffc43fefa96.png">

I installed gdal2 with netcdf, hdf4 and hdf5 support. grass7 with netcdf support. I built qgis2
--with-isolation --with-saga-gis --with-grass --with-gpsbabel-qt4

I'm on 10.11.6 el capitan

Is there something else I need to do?
Thank you

**Comment by dakcarto** [comment]
Hi @dschneiderch, thanks for reporting!

Hmm, that is the right Options config; so, if `grass72` launches, there might be an issue with QGIS 2.18 code upstream. I'll check into this today.

**Comment by dschneiderch** [comment]
they are working now.
I realized I was suffering from [this qgis bug](https://hub.qgis.org/issues/15265). I resolved this by removing my processing folder inside .qgis/python/plugins and the grass7 algorithms now appear to work.
