### ISSUE TITLE
Qgis 2.18.4 fails to upgrade (GRASS related error)

### ISSUE THREAD

**Issue by ecerrillo** [OSGeo/homebrew-osgeo4mac#217]
I'm trying to upgrade to qgis 2.18.4 without success. The error seems to be related to GRASS GIS installation and the location of headers version.h and gis.h, since I'm getting the following error during the compilation:

` 1 error generated.
make[2]: *** [src/plugins/grass/7/CMakeFiles/grassplugin7.dir/__/qgsgrassselect.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /tmp/qgis2-20170309-18798-1uigbab/QGIS-final-2_18_4/src/plugins/grass/qgsgrasstools.cpp:18:
In file included from /tmp/qgis2-20170309-18798-1uigbab/QGIS-final-2_18_4/src/plugins/grass/qgsgrassmodule.h:25:
In file included from /tmp/qgis2-20170309-18798-1uigbab/QGIS-final-2_18_4/src/plugins/grass/qgsgrassmoduleoptions.h:30:
/tmp/qgis2-20170309-18798-1uigbab/QGIS-final-2_18_4/src/plugins/grass/qgsgrassmoduleparam.h:45:10: fatal error: 'grass/gis.h' file not found
#include <grass/gis.h>
         ^
1 error generated.
make[2]: *** [src/plugins/grass/7/CMakeFiles/grassplugin7.dir/__/qgsgrasstools.cpp.o] Error 1
In file included from /tmp/qgis2-20170309-18798-1uigbab/QGIS-final-2_18_4/src/plugins/grass/qgsgrasseditrenderer.cpp:31:
In file included from /tmp/qgis2-20170309-18798-1uigbab/QGIS-final-2_18_4/src/plugins/grass/../../providers/grass/qgsgrassprovider.h:23:
In file included from /tmp/qgis2-20170309-18798-1uigbab/QGIS-final-2_18_4/src/plugins/grass/../../providers/grass/qgsgrassvectormap.h:25:
/tmp/qgis2-20170309-18798-1uigbab/QGIS-final-2_18_4/src/plugins/grass/../../providers/grass/qgsgrass.h:27:10: fatal error: 'grass/version.h' file not found
#include <grass/version.h>`

grass7 package is installed and working fine. Current version of grass7 is: osgeo/osgeo4mac/grass7-7.2.0. I've also installed osgeo/osgeo4mac/grass6-6.4.6.

Thanks in advance!

**Comment by pat-s** [comment]
Did you do a clean install, i.e. first `brew remove qgis2` and then `brew install qgis2`?

Also check what `brew doctor` shows. No problems on my side currently with `qgis2`

**Comment by ecerrillo** [comment]
Thanks, pat-s. I forgot to mention that `brew doctor` was doing fine. I removed the previous version of qgis2 and I get it working again.

**Comment by dakcarto** [comment]
Btw, the GRASS linking error should be fixed in 126fdf7.
