### ISSUE TITLE
qgis2-ltr: libgeos-3.5.1.dylib not found when building --with-qspatialite

### ISSUE THREAD

**Issue by pat-s** [OSGeo/homebrew-osgeo4mac#218]
```
/usr/local/Cellar/qgis2-ltr/2.14.12 (8,097 files, 195.6MB)
  Built from source on 2017-03-09 at 12:07:53 with: --with-saga-gis --with-grass --with-isolation --with-qspatialite --with-gpsbabel-qt4
```

During startup:

```
File "/usr/local/Cellar/qgis2-ltr/2.14.12/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 572, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			ImportError: dlopen(/usr/local/lib/python2.7/site-packages/pyspatialite/_spatialite.so, 2): Library not loaded: /usr/local/opt/geos/lib/libgeos-3.5.1.dylib
			  Referenced from: /usr/local/lib/python2.7/site-packages/pyspatialite/_spatialite.so
			  Reason: image not found
```

`libgeos-3.5.1.dylib` does not exist -> current installed version is 3.6.1

**Comment by pat-s** [comment]
When I remove `geos` v3.6.1 and install v3.5.1, I get the warning 

> dyld: Library not loaded: /usr/local/opt/geos/lib/libgeos_c.1.dylib
>   Referenced from: /usr/local/opt/qgis2-ltr/QGIS.app/Contents/MacOS/QGIS
>   Reason: Incompatible library version: QGIS requires version 12.0.0 or later, but libgeos_c.1.dylib provides version 11.0.0
> /usr/local/opt/qgis2-ltr/bin/qgis2-ltr: line 12: 59772 Abort trap: 6           /usr/local/opt/qgis2-ltr/QGIS.app/Contents/MacOS/QGIS "$@"

The only approach that is working is to 

1. have `geos` v3.6.1 installed
2. manually copy `libgeos-3.5.1.dylib` to `/usr/local/Cellar/geos/3.6.1/lib`

This problem also applies to `qgis-ltr` build **without** `qspatialite`.

**Comment by dakcarto** [comment]
Hi @pat-s, thanks for reporting again!

`/usr/local/lib/python2.7/site-packages/pyspatialite/_spatialite.so` is not the same as `qspatialite`, which is a Qt driver for Spatialite.

The issue is that your `pyspatialite/_spatialite.so` module is outdated, referencing an older GEOS lib.

Try:
* Revert your GEOS changes and ensure the latest is installed
* `brew rm pyspatialite` (as many times as necessary)
* `brew install pyspatialite`

**Comment by pat-s** [comment]
@dakcarto 

Thanks, worked! I saw the reference to v.3.5.1 in `_spatialite.so`. 
Shouldn't this link in `pyspatialite` get updated when `geos` is updated? 

Or was something wrong in my brew setup? Wondering because it seems I'm the first reporting this issue of the outdated `geos` link (which should have happened to way more if there is no automatic update). 

Thanks also for clarification between `qspatialite` and `pyspatialite`.

**Comment by dakcarto** [comment]
@pat-s wrote:
> Shouldn't this link in pyspatialite get updated when geos is updated?
>
> Or was something wrong in my brew setup? Wondering because it seems I'm the first reporting this issue of the outdated geos link (which should have happened to way more if there is no automatic update).

There is no reverse dependency lookup support in Homebrew. Basically, `pyspatialite` needs its `revision` bumped to force a rebuild when GEOS is updated. For formulae like this, if the build can configured to use the `/usr/local/opt` path for linking, incremental dependent formulae updates can be transparently supported; however, any dependency that _exceeds_ its supported version may not be checked and may cause runtime API or ABI failures.
