### ISSUE TITLE
TauDEM Throwing Error After Good Install

### ISSUE THREAD

**Issue by vanhoesenj** [OSGeo/homebrew-osgeo4mac#219]
After installing 2.14ltr successfully I've been slowly adding in the Processing plugins (my first attempt at installing them all at once failed). However  I have yet to get TauDEM working and that was one of the primary reasons to go this route. I think it was a successful install (no errors) and the Install_Receipt seems 'happy':

`{"homebrew_version":"1.1.11","used_options":[],"unused_options":[],"built_as_bottle":false,"poured_from_bottle":false,"installed_as_dependency":false,"installed_on_request":true,"changed_files":null,"time":1489369362,"source_modified_time":1475773042,"HEAD":"394f9fa0aaa5854aa52bc589708a079665dcf462","stdlib":null,"compiler":"clang","runtime_dependencies":[{"full_name":"libpng","version":"1.6.28"},{"full_name":"jpeg","version":"8d"},{"full_name":"giflib","version":"4.2.3"},{"full_name":"libtiff","version":"4.0.7"},{"full_name":"lzlib","version":"1.8"},{"full_name":"proj","version":"4.9.3"},{"full_name":"libgeotiff","version":"1.4.1"},{"full_name":"geos","version":"3.6.1"},{"full_name":"sqlite","version":"3.17.0"},{"full_name":"freexl","version":"1.0.2"},{"full_name":"libspatialite","version":"4.3.0a"},{"full_name":"osgeo/osgeo4mac/gdal2","version":"2.1.3"},{"full_name":"open-mpi","version":"2.0.2"}],"source":{"path":"/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/taudem.rb","tap":"osgeo/osgeo4mac","spec":"stable","versions":{"stable":"5.3.6-dev","devel":null,"head":"HEAD","version_scheme":0}}}`

However no matter what algorithm I run, I get the same odd message:
 
<img width="836" alt="screenshot 2017-03-12 22 28 10" src="https://cloud.githubusercontent.com/assets/2807706/23839964/ff73d3c4-0777-11e7-9581-796cb4faf9aa.png">

I haven't changed the Processing | Options | Providers | TauDEM folder. I was also under the impression I didn't need to install OpenMPI to make this run but perhaps that is part of the issue but I don't think I need to? Thanks in advance for thoughts.

**Comment by nickrobison** [comment]
@vanhoesenj We've updated tandem to the latest version  in #349.

Perhaps you could try this again using both the new tandem and the `qgis2` formula? If the error is still occurring, you might want to try filing an issue either with the Taudem project, or QGIS.
