### ISSUE TITLE
Please add --without-pdfium option to gdal2 formula

### ISSUE THREAD

**Issue by nextstopsun** [OSGeo/homebrew-osgeo4mac#220]
Or better add `pdfium` formula to this repo, because [this one](https://raw.githubusercontent.com/knowtheory/homebrew/f0efc3d0bb6aeba08bd112d5ad6625149dac8dbb/Library/Formula/pdfium.rb) doesn't work.

Otherwise, it's not possible to build gdal2 `--with-complete` option.

**Comment by oeon** [comment]
I'm not having any luck upgrading to the latest gdal2. I noticed https://github.com/OSGeo/homebrew-osgeo4mac/blob/master/Formula/gdal2.rb#L34 specifies `"Build with PDFium support (non-Homebrew install required)"` and gave this route a try https://github.com/klokantech/pdfium/blob/build/build-mac.sh.

I then had to change https://github.com/OSGeo/homebrew-osgeo4mac/blob/master/Formula/gdal2.rb#L205 to be `"--with-pdfium=/usr/local"` to find pdfium. 

But I still didn't have any luck. [gist-log](https://gist.github.com/oeon/e91a1ee9c468eb53b27a164707263e7e) here, FWIW.

**Comment by oeon** [comment]
Not sure if https://github.com/OSGeo/homebrew-osgeo4mac/commit/524a5f71820efcf9b21b60f70283dc1b9cae4b94 fully addresses this particular issue, but I'm able to upgrade to gdal2 now. Thanks, @dakcarto !!

**Comment by eugeneYWang** [comment]
@oeon which command do you use to install gdal? I still cannot get it done

**Comment by oeon** [comment]
@eugeneYWang I ran `brew upgrade gdal2 --with-complete --with-libkml`

**Comment by dakcarto** [comment]
Beyond 524a5f7, I've added [`pdfium`](https://github.com/OSGeo/homebrew-osgeo4mac/blob/master/Formula/pdfium.rb) and [`pdfium-gdal2`](https://github.com/OSGeo/homebrew-osgeo4mac/blob/master/Formula/pdfium-gdal2.rb), the latter based upon https://github.com/rouault/pdfium 

However, `pdfium` is 2 years newer and the GDAL driver does not compile against it (needs updated upstream in source). Then, the `pdfium-gdal2` formula has the right install for the GDAL driver, but it ends up needing an older C++ std lib. So, `pdfium-gdal2` needs to be incorporated into a standalone C++ plugin, to minimize the affects of mixing std C++ libs.

Closing issue. Please reopen if needed.
