### ISSUE TITLE
Linuxbrew support?

### ISSUE THREAD

**Issue by pat-s** [OSGeo/homebrew-osgeo4mac#225]
Since a few days I use linuxbrew on a machine - any linuxbrew support planned for this tap? 

AFAIK a lot of people use the ubuntugis repo for Linux to install various geospatial stuff. However, it often comes with undesired version (e.g. SAGA 2.2.7). I would love to see (bottle) support for some main formulas like `qgis2` and `gdal2` etc. 

While some formulas install fine, e.g. `gdal2` builds fine on my Debian server but fails on my local Ubuntu 16.04, formulas do not account for Linuxbrew at all atm.
Already started patching some formulas ;) Let's see how far I'll get..

**Comment by dakcarto** [comment]
Hi @pat-s, thanks for contributing!

> Since a few days I use linuxbrew on a machine - any linuxbrew support planned for this tap?

I do not intend to do any work towards supporting linuxbrew. There is already enough work just to keep the macOS side of things up-to-date.

> AFAIK a lot of people use the ubuntugis repo for Linux to install various geospatial stuff. However, it often comes with undesired version (e.g. SAGA 2.2.7). I would love to see (bottle) support for some main formulas like qgis2 and gdal2 etc.

Generally, the UbuntuGIS PPA is the preferred method for QGIS development on Ubuntu, or power users looking for more up-to-date dependencies. I don't see the need to duplicate efforts using a non-standard Linux methodology (linuxbrew) compared to more flexible approaches like [snap](https://snapcraft.io/) or [flatpack](http://flatpak.org/) like some [QGIS devs have embarked upon](http://lists-archives.com/kde-devel/34706-kde-qt-flatpak-sdk-runtime.html).

**Comment by m-kuhn** [comment]
I also once looked into linuxbrew but just very briefly.
What I like about it is its cross-distribution nature. Unfortunately it hasn't been widely spread...

What kind of patches are expected? Are these trivial non-invasive patches or more complex things?
