### ISSUE TITLE
can't find wxpython after installing from homebrew

### ISSUE THREAD

**Issue by bolliger32** [OSGeo/homebrew-osgeo4mac#228]
I followed the instructions available [here](https://grasswiki.osgeo.org/wiki/Compiling_on_MacOSX_using_homebrew) for compiling via homebrew and I can start text-based grass, but when I try to launch the GUI, I get the following error:

```Traceback (most recent call last):
  File "/usr/local/Cellar/grass7/7.2.0/grass-7.2.0/gui/wxpython/core/globalvar.py", line 69, in CheckForWx
    import wxversion
ImportError: No module named 'wxversion'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/grass7/7.2.0/grass-7.2.0/gui/wxpython/core/globalvar.py", line 71, in CheckForWx
    raise ImportError(e)
ImportError: No module named 'wxversion'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/grass7/7.2.0/grass-7.2.0/gui/wxpython/gis_set.py", line 31, in <module>
    from core import globalvar
  File "/usr/local/Cellar/grass7/7.2.0/grass-7.2.0/gui/wxpython/core/globalvar.py", line 95, in <module>
    CheckForWx()
  File "/usr/local/Cellar/grass7/7.2.0/grass-7.2.0/gui/wxpython/core/globalvar.py", line 84, in CheckForWx
    print >> sys.stderr, 'ERROR: wxGUI requires wxPython. %s' % str(e)
TypeError: unsupported operand type(s) for >>: 'builtin_function_or_method' and '_io.TextIOWrapper'
ERROR: Error in GUI startup. See messages above (if any) and if necessary, please report this error to the GRASS developers.
On systems with package manager, make sure you have the right GUI package, probably named grass-gui, installed.```

When I tried to import wx in an instance of the frameworks python (the one that I set GRASS_PYTHON to for the homebrew installation) it did not recognize the module either. I reinstalled wxpython via brew, making sure that my anaconda path was not in my PATH environment variable. Now when I start up the frameworks python, it does recognize "import wx" however I still get the same error when trying to start grass. Any thoughts on how to get GRASS to recognize wxpython?

**Comment by xzcvczx** [comment]
is grass using python2 or python3? wxpython doesn't support python3

**Comment by nickrobison** [comment]
@bolliger32 We recently updated the various grass7 formulas and improved our handling of python dependencies. Would you be able to try again and see if the error is still occurring?

**Comment by bolliger32** [comment]
will do! gimme a few days to get back into this.

**Comment by nickrobison** [comment]
@bolliger32 The links looks ok to me. If you simply do `brew install grass7 --with-netcdf` that should automatically download the required dependencies. If you don't need `netcdf` support, simply doing `brew install grass7` should be sufficient.

**Comment by rdinman** [comment]
I am having a similar issue. Installed grass7.4.0 with brew install grass7 --with-netcdf, and am unable to launch the gui. Works fine in with -text mode. 

Is there a fix to this?

GRASS 7.4.0 (Sinusoidal):~ > g.gui
Launching <wxpython> GUI in the background, please wait...
ERROR: wxGUI requires wxPython. No module named wx
You can still use GRASS GIS modules in the command line or in Python.

Thanks!!

**Comment by nickrobison** [comment]
@rdinman Sorry to hear you're having issues.

here are a couple of things you can try (in order of recommendation):

- Globally set the GRASS_PYTHON environment variable to /usr/local/bin/python2. This is the 'official' setup for using a different python interpreter for wxpython at runtime. However, "only used for components which use wxPython." So, it may only work for direct launching of grass72 wrapper script.
- Run with PATH=<custom/path:for/grass7:to/use> grass72 <options> - this localizes the PATH variable to the execution of GRASS. You could set an alias in your BASH profile, e.g. alias grass7-hb="<noted command>" for easy launching.

Do you have Anaconda installed, or another python distribution?

Can you post the output of `ls $(brew --prefix)/lib/python2.7/site-packages | grep wx`

**Comment by bolliger32** [comment]
OK I reinstalled grass from homebrew. I first got a pretty basic error:

```  File "/usr/local/Cellar/grass7/7.4.0/libexec/bin/grass74", line 1671
    sys.stdout.write("%s\n" % grass_version)
                                           ^
TabError: inconsistent use of tabs and spaces in indentation```

Looks like there was a weird tab added into that file for some reason. I tried removing that weird tab but it didn't seem to recognize that this change had happened, as it is still giving me the same error. Any thoughts?

**Comment by nickrobison** [comment]
@bolliger32 That's a really strange error, I can see the incorrect indenting in my `grass74` file, but no error in thrown.

Which version of python are you using?

If you remove the tabs at the beginning on the line, and ensure that the indentation is lined up correctly, does the error still occur?

**Comment by bolliger32** [comment]
Ah ok I realized I had fixed one of the tabs, but not all of the tabs. I corrected that and indeed that error went away but then I arrived at this error:
```
Traceback (most recent call last):
  File "/usr/local/Cellar/grass7/7.4.0/libexec/bin/grass74", line 2003, in <module>
    main()
  File "/usr/local/Cellar/grass7/7.4.0/libexec/bin/grass74", line 1900, in main
    grass_gui = check_gui(expected_gui=grass_gui)
  File "/usr/local/Cellar/grass7/7.4.0/libexec/bin/grass74", line 735, in check_gui
    stdout=nul, stderr=nul)
  File "/usr/local/Cellar/grass7/7.4.0/libexec/bin/grass74", line 252, in Popen
    return subprocess.Popen(cmd, **kwargs)
  File "/Users/ianbolliger/anaconda/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/Users/ianbolliger/anaconda/lib/python3.5/subprocess.py", line 1289, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'python2'
```

I had installed grass following the homebrew instructions I linked in my original post, so not sure why it's trying to call my anaconda python. The only step from the instructions that I modified was when it asked me to reset my path with
```
PATH=/usr/local/bin:/usr/bin/sbin
```
I instead did
```
PATH=/usr/local/bin:/usr/bin/sbin:$PATH
```
because otherwise a lot of the helper functions needed for `brew install` didn't work and I couldn't install anything.

Do I need to set the PATH variable each time before calling GRASS? That is what I used to do in earlier versions, but my interpretation was if I had the PATH and GRASS_PYTHON environment variables set correctly during installation that I wouldn't need to reset PATH when calling grass74

**Comment by nickrobison** [comment]
Glad that fix worked!

Environment variables are scoped to the terminal session, so as soon as you close your terminal they'll be reset. You'll need to set them each time you open a new session, though you can do this automatically in your `.bash_profile` file, which is what I do.

**Comment by bolliger32** [comment]
I don't want to change my PATH in my `.bash_profile` file, since typically I want to be using anaconda python and not the frameworks python. I thought this line in the instructions meant that I wouldn't have to change my env variables after installation

> PATH adjustments are only needed during installation. After installation, the PATH can return to its default value and GRASS works fine.

Regardless, I tried changing my PATH and GRASS_PYTHON environment variables and calling grass74 again, but got the same error.

**Comment by nickrobison** [comment]
If you type `which python2` what's the output?

Can you paste the output of `brew info python@2`?

**Comment by nickrobison** [comment]
With the updated `GRASS_PYTHON` variable, can you paste the error output, I know it's the same, but I'm curious if the paths are different, or if it's still calling anaconda python3.

**Comment by bolliger32** [comment]
I get no output for `which python2` (I tried both with my standard PATH variable and after prepending /usr/local/bin:/usr/bin/sbin).

For `brew info python@2` I get the following output:
```
python@2: stable 2.7.15 (bottled), HEAD
Interpreted, interactive, object-oriented programming language
https://www.python.org/
/usr/local/Cellar/python@2/2.7.15 (4,677 files, 82.8MB)
  Poured from bottle on 2018-06-10 at 11:36:06
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/python@2.rb
==> Dependencies
Build: pkg-config ✔, sphinx-doc ✘
Required: gdbm ✔, openssl ✔, readline ✔, sqlite ✔
Optional: tcl-tk ✔
==> Options
--with-tcl-tk
	Use Homebrew's Tk instead of macOS Tk (has optional Cocoa and threads support)
--HEAD
	Install HEAD version
==> Caveats
Pip and setuptools have been installed. To update them
  pip install --upgrade pip setuptools

You can install Python packages with
  pip install <package>

They will install into the site-package directory
  /usr/local/lib/python2.7/site-packages

See: https://docs.brew.sh/Homebrew-and-Python
```

After updating `GRASS_PYTHON`, grass74 is still calling my anaconda installation and I'm getting the same error:
```
Traceback (most recent call last):
  File "/usr/local/Cellar/grass7/7.4.0/libexec/bin/grass74", line 2003, in <module>
    main()
  File "/usr/local/Cellar/grass7/7.4.0/libexec/bin/grass74", line 1900, in main
    grass_gui = check_gui(expected_gui=grass_gui)
  File "/usr/local/Cellar/grass7/7.4.0/libexec/bin/grass74", line 735, in check_gui
    stdout=nul, stderr=nul)
  File "/usr/local/Cellar/grass7/7.4.0/libexec/bin/grass74", line 252, in Popen
    return subprocess.Popen(cmd, **kwargs)
  File "/Users/ianbolliger/anaconda/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/Users/ianbolliger/anaconda/lib/python3.5/subprocess.py", line 1289, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'python2'
```

Thanks so much for troubleshooting with me!

**Comment by nickrobison** [comment]
Well that's something!

Looks like the homebrew python installed correctly, but didn't link, probably because of some conflicts with Anaconda. 2 things to try.

1. `export GRASS_PYTHON=$(brew --prefix)/opt/python2/bin/python2` and see if that resolves the issue, that's the python binary installed by Homebrew, that is usually linked into `user/local/bin`

2. Try to run `brew link python@2 --dry-run` and see if that generates any errors.

**Comment by nickrobison** [comment]
Also, congrats on finding a bug in grass! The indentation issue should be resolved at some point. I'm working on getting a patch put together, if you'd like, I can send it over to you for you to submit, and get credit for it!

**Comment by bolliger32** [comment]
haha sure! but not a big deal if it's easier for you to just submit.

I tried the new `GRASS_PYTHON` path but it still seems to be calling my anaconda python b/c it comes up with the same error again. I did verify that `/usr/local/bin/python2` does not exist (although `usr/local/bin/python2-32` does, for some reason). And I confirmed that `/usr/local/opt/python2/bin/python2` does exist (my brew prefix is `/usr/local`).

The dry run did not seem to generate any errors:
```
/usr/local/bin/2to3-2
/usr/local/bin/2to3-2.7
/usr/local/bin/idle
/usr/local/bin/idle2
/usr/local/bin/idle2.7
/usr/local/bin/pydoc
/usr/local/bin/pydoc2
/usr/local/bin/pydoc2.7
/usr/local/bin/python
/usr/local/bin/python-config
/usr/local/bin/python2
/usr/local/bin/python2-config
/usr/local/bin/python2.7
/usr/local/bin/python2.7-config
/usr/local/bin/pythonw
/usr/local/bin/pythonw2
/usr/local/bin/pythonw2.7
/usr/local/bin/smtpd.py
/usr/local/bin/smtpd2.7.py
/usr/local/bin/smtpd2.py
/usr/local/share/doc/python@2
/usr/local/share/man/man1/python.1
/usr/local/share/man/man1/python2.1
/usr/local/share/man/man1/python2.7.1
/usr/local/share/python@2
/usr/local/lib/pkgconfig/python-2.7.pc
/usr/local/lib/pkgconfig/python.pc
/usr/local/lib/pkgconfig/python2.pc
/usr/local/Frameworks/Python.framework/Headers
/usr/local/Frameworks/Python.framework/Python
/usr/local/Frameworks/Python.framework/Resources
/usr/local/Frameworks/Python.framework/Versions/2.7
/usr/local/Frameworks/Python.framework/Versions/Current
```

Should I try linking that and then calling grass74 again? Or do you think it still won't work if exporting the new GRASS_PYTHON path didn't seem to do the trick...

**Comment by nickrobison** [comment]
You can try linking it, and then seeing if `which python2` outputs anything.

**Comment by bolliger32** [comment]
that did the trick, thanks! `grass74` now opens without me having to mess with the GRASS_PYTHON variable. I get this warning, but I'm assuming it's not going to cause problems?:
```
/usr/local/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/_core.py:16633: UserWarning: wxPython/wxWidgets release number mismatch
```

**Comment by nickrobison** [comment]
Awesome!

That warning shouldn’t mean anything, it’s an artifact of the build process.

**Comment by peteWT** [comment]
Hi,
I'm not sure if this should be a new issue, its wxPython related and results in no wx GUI. I have installed the `osgeo4mac/osgeo/grass` which results in `grass76`.  I get the following error when attempting to use the wxgui:

```> g.gui wxpython
Launching <wxpython> GUI in the background, please wait...
ERROR: wxGUI requires wxPython. No module named _core_```

Tried setting the GRASS_PYTHON variable to the homebrew Python with no luck:

`export GRASS_PYTHON=/usr/local/bin/python2`

**Comment by fjperini** [comment]
@peteWT you should not have this problem. Try again after reinstalling `wxmac`, `wxpython`  and `osgeo-grass`. Remember to verify that they are linked.

**Comment by peteWT** [comment]
@fjperini  Thanks for the reply! I've reinstalled everything as you suggest and still the same result.

**Comment by SPAMLab** [comment]
Hi, after a clean install of homebrew and osgeo-grass, I started getting teh same errors:

`ERROR: wxGUI requires wxPython. No module named _core_`

I tried reinstalling and links wxmac, wxpython and grass.

running python2 and importing wx works fine.

Note: grass was working fine until I decided to run a brew upgrade. It all broke after wx 4 was installed

**Comment by fjperini** [comment]
@peteWT @SPAMLab It may be related to a problem in your homebrew.

`brew doctor`

also send me the result of `$PATH`

**Comment by SPAMLab** [comment]
sorry for the late reply

brew doctor shown nothing wrong

PATH: /usr/local/opt/gdal2-python/lib/python2.7/site-packages:/Library/Frameworks/GDAL.framework/Programs/:/usr/local/opt/osgeo-liblas/bin:/usr/local/opt/gdal2/bin:/usr/local/opt/osgeo-laszip@2/bin:/usr/local/sbin:/usr/local/bin:

PYTHONPATH
/usr/local/lib/python2.7/site-packages:/usr/local/lib/python2.7/site-packages/wx-3.0-osx_cocoa

**Comment by fjperini** [comment]
@SPAMLab  try after deleting those paths from PATH AND PYTHONPATH.

Remember that if Frameworks GDAL is used it will cause problems with the OSGeo-Homebrew version, and the others should make references to `osgeo- *` (eg, `gdal2-python`: `osgeo-gdal-python`)

My advice is that there is no reference to these paths.

**Comment by SPAMLab** [comment]
Got it. I fond an old file wxversion.pyc in /usr/local/lib/python2.7/site-packages/ and removed it, Now it works as before.
