### ISSUE TITLE
Oracle driver SHA256 mismatch

### ISSUE THREAD

**Issue by ngiuliani-netbel** [OSGeo/homebrew-osgeo4mac#240]
Hi, I'm getting this error trying to install oracle instant client:

brew install instantclient-basic
==> Installing instantclient-basic from instantclienttap/instantclient
==> Downloading http://download.oracle.com/otn/mac/instantclient/121020/instantclient-ba
Already downloaded: /Users/na/Library/Caches/Homebrew/instantclient-basic-macos.x64-12.1.0.2.0.zip
Error: SHA256 mismatch
**Expected: ecbf84ff011fcd8981c2cd9355f958ee42b2e452ebaad2d42df7b226903679cf
Actual: 71aa366c961166fb070eb6ee9e5905358c61d5ede9dffd5fb073301d32cbd20c**
Archive: /Users/na/Library/Caches/Homebrew/instantclient-basic-macos.x64-12.1.0.2.0.zip
To retry an incomplete download, remove the file above.

**Comment by taylorwilliams** [comment]
Also experiencing this issue

**Comment by eivindhammers** [comment]
Same issue with qgis2 and qgis2-ltr.

**Comment by dakcarto** [comment]
Hi. Thanks for everyone reporting, but formulae from https://github.com/InstantClientTap/homebrew-instantclient are not supported here.

Closing this issue. Please reopen if necessary.

@eivindhammers, please provide more information on how installing `qgis2` or `qgis2-ltr` is throwing an error for this other third-party tap.

---

This tap does provide [oracle-client-sdk](https://github.com/OSGeo/homebrew-osgeo4mac/blob/master/Formula/oracle-client-sdk.rb), which is utilized by the GDAL/OGR driver formula [gdal2-oracle](https://github.com/OSGeo/homebrew-osgeo4mac/blob/master/Formula/gdal2-oracle.rb); however, there appears to be issues with it inside QGIS (see #200). I don't generally have access to any Oracle geospatial-enabled database connections, so any help on debugging issue with the Oracle-related formulae here would be much appreciated.

**Comment by dakcarto** [comment]
@ngiuliani-netbel, @taylorwilliams and @eivindhammers, please review https://github.com/OSGeo/homebrew-osgeo4mac/issues/200#issuecomment-340229764 for updates on the `oracle-client-sdk` formula in this tap.
