### ISSUE TITLE
Alternative QGIS bottle repository 

### ISSUE THREAD

**Issue by pat-s** [OSGeo/homebrew-osgeo4mac#242]
Because we need them for testing of the R package [RQGIS](https://github.com/jannes-m/RQGIS), we are building our own `qgis2` and `qgis2-ltr` bottles. 

Currently, there is not bottle for `qgis2` available from `osgeo4mac` and hence our Travis CI build fails. Also, we need to check the latest versions of QGIS to make sure that QGIS changes do not break package functionality. 

If you want to use them, just install the bottle directly. Example for QGIS 2.18.10:

`brew install http://www.geoinf.uni-jena.de/~bi28yuv/bottles/qgis2-2.18.10.sierra.bottle.tar.gz`. 

### Note:

- Installation will only work if your local `osgeo4mac` formula has the same version, i.e. here `2.18.10`. Currently `qgis2-ltr` from `osgeo4mac` has v2.14.14 and our bottle v2.14.16. If you want to install it, you need to do `brew edit qgis2-ltr` and manually edit the version. Otherwise you will get a version mismatch  error. 

- There is no guarantee that the bottles are working properly as we just change the version and will not do changes to the compiling steps. So use them at your own risk ;) 

- If you want to update, you need to manually redo all the steps. So think twice if its worth to do all the fuzz for minor version updates ;)

**Comment by dakcarto** [comment]
Please do not recommend people who use this tap install a bottle from an outside source.
