### ISSUE TITLE
QGIS2  2.18.10 fails to build on OSX Sierra 10.12.5

### ISSUE THREAD

**Issue by jyutzler** [OSGeo/homebrew-osgeo4mac#243]
Related to #227 I guess but different versions.
Logs here: https://gist.github.com/jyutzler/fad86f4eb09cf555c8dfe7cd52ce5b68

**Comment by dakcarto** [comment]
Hi @jyutzler, thanks for reporting!

Please try with latest `qgis2` updates. Thanks!

**Comment by lcoandrade** [comment]
Hi there!
Now the problem changed. 
As soon as I try to begin the install process the following error occurs:
Error: osgeo/osgeo4mac/qgis2 contains conflicting version recursive dependencies:
  qwt-qt4, qwt-qt4@5.2

**Comment by lcoandrade** [comment]
Problem solved!!!!

**Comment by dakcarto** [comment]
Closing. Please reopen if needed.

Note the current recommendations against using `--with-orfeo5` in #265.
