### ISSUE TITLE
Update GRASS Formula to 7.2.1?

### ISSUE THREAD

**Issue by 3DTOPO** [OSGeo/homebrew-osgeo4mac#246]
I would be happy to put the work in to update the grass7.rb formula to 7.2.1 (I imagine its a simple update), but I have never updated a brew formula before. Do I just make changes and do a pull request?

How would I test it before pulling? 

Thanks!

**Comment by dakcarto** [comment]
Hi @3DTOPO, thanks for reporting!

This has been done in 81423db.
