### ISSUE TITLE
error while Installing qgis-ltr in mac using terminal

### ISSUE THREAD

**Issue by Sagar036** [OSGeo/homebrew-osgeo4mac#259]
Installing osgeo/osgeo4mac/qgis2-ltr
==> Downloading https://github.com/qgis/QGIS/archive/final-2_14_17.tar.gz
==> Downloading from https://codeload.github.com/qgis/QGIS/tar.gz/final-2_14_17
######################################################################## 100.0% 
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/qgis2-ltr/2.14.17 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_V
Last 15 lines from /Users/sagardhiman/Library/Logs/Homebrew/qgis2-ltr/01.cmake:
-- Found Proj: /Library/Frameworks/proj.framework
-- Found GEOS: /usr/local/Cellar/geos/3.6.2/lib/libgeos_c.dylib (3.6.2)
-- Found GDAL: /usr/local/opt/gdal2/lib/libgdal.dylib (2.2.1)
-- Found Expat: /usr/local/opt/expat/lib/libexpat.dylib
-- Found Qwt: /usr/local/opt/qwt-qt4/lib/qwt.framework/qwt (6.1.3)
-- Found Sqlite3: /usr/local/opt/sqlite/lib/libsqlite3.dylib
-- Found PostgreSQL: /usr/local/lib/libpq.dylib
CMake Error at cmake/FindSPATIALITE.cmake:79 (MESSAGE):
  Could not find SpatiaLite
Call Stack (most recent call first):
  CMakeLists.txt:220 (FIND_PACKAGE)

-- Configuring incomplete, errors occurred!
See also "/tmp/qgis2-ltr-20170813-35609-rthbcr/QGIS-final-2_14_17/build/CMakeFiles/CMakeOutput.log".

**Comment by dakcarto** [comment]
Hi @Sagar036, thanks for reporting!

Should be fixed with c629054. Also, 3c1aaea adds a Sierra bottle; so, if you are building from source on that macOS version, you will need to specify `brew install --build-from-source ...` to skip the bottled install (assuming you want to test the fix).

**Comment by dakcarto** [comment]
Closing. Please reopen if needed.
