### ISSUE TITLE
Can not tap into osgeo/homebrew-osgeo4mac

### ISSUE THREAD

**Issue by jannefleischer** [OSGeo/homebrew-osgeo4mac#266]
Hi, I reported this a year or more ago, and can't find it now, but for my uneducated eye this seem to be an issue to be reported again:

I can't tap into this tap because of syntax error:

```
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/mrsid-sdk.rb
invalid attribute for formula 'osgeo/osgeo4mac/mrsid-sdk': url ("file:///Volumes/1000er Intern/Users/Janne/Library/Caches/Homebrew/MrSID_DSDK-9.5.1.4427-darwin14.universal.clang60.tar.gz")
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/oracle-client-sdk.rb
invalid attribute for formula 'osgeo/osgeo4mac/oracle-client-sdk': url ("file:///Volumes/1000er Intern/Users/Janne/Library/Caches/Homebrew/instantclient-basiclite-macos.x64-12.1.0.2.0.zip")
Error: Cannot tap osgeo/osgeo4mac: invalid syntax in tap!
```

**Comment by dakcarto** [comment]
Hi @jannefleischer, thanks for reporting!

It looks like an issue with a space in the volume path to your Homebrew.

**Comment by dakcarto** [comment]
If it is the same space in URL issue, as noted previously in #152, then it is an upstream issue that I don't think needs fixed. Try the symlink workaround noted in #152.

Closing. Please reopen if needed.
