### ISSUE TITLE
libkml-dev SHA256 mismatch

### ISSUE THREAD

**Issue by cmarmstrong** [OSGeo/homebrew-osgeo4mac#271]
Hi,

When I attempt to install libkml-dev using the following steps I recieve a SHA256 mismatch error:

    brew tap osgeo/osgeo4mac && brew tap --repair
    brew install libkml-dev

Which gives error:

    Error: SHA256 mismatch
    Expected: 5661de8d1f662e5ee117543ffb325bad36bc6a2ac6f2d16f02a4d8acf4bb936e
    Actual: 667cd86b7e66e38c71c054526e49c6ee9558b506c9ddec9e6de14b87e18c0072

I am able to repair this problem by cloning the repo, updating the libkml-dev formula to the actual sha256, and installing with

    brew install libkml-dev.rb

I am on an older MacPro running El-Capitan.  I'm not sure if this is specific to me or an actual problem with the formula, but it seems like it could be the formula, so there ya go.

**Comment by pat-s** [comment]
Can you provide a PR to quickly fix this?

**Comment by cmarmstrong** [comment]
certainly. I'll do it tonight.

**Comment by cmarmstrong** [comment]
PR submitted.
