### ISSUE TITLE
numpy and requests are not installed on fresh QGIS2 install

### ISSUE THREAD

**Issue by 3nids** [OSGeo/homebrew-osgeo4mac#278]
these are missing packages when launching QGIS for the first time:

* numpy
* requests
* jinja2

**Comment by 3nids** [comment]
also jinja2 is missing

**Comment by dakcarto** [comment]
Hi Denis,

Installing non-Homebrew Python packages to a shared `site-packages` location is strictly forbidden in formulae, i.e. `pip install requests`.

There are several ways to get around this:
1. Manually install the packages from source into `<formulae prefix>/libexec/(vendored)?`, then reference the path in your formula.
2. Make the packages into formula, i.e. `matplotlib` and `numpy` (which should have [already been installed by `gdal2-python`](https://github.com/OSGeo/homebrew-osgeo4mac/blob/master/Formula/gdal2-python.rb#L68) ??)
3. Use `pip` to do a localized PYTHONUSERBASE tweak install to `<formulae prefix>/libexec/(vendored)?`, as I have [now done in the `qgis3-dev` formula](https://github.com/qgis/homebrew-qgisdev/blob/master/Formula/qgis3-dev.rb#L154-L174).
4. Just notify users that these runtime requirements are their responsibility to manually install (as seen currently in the caveats of `brew info qgis2`).

The best solution is to place accurate `runtime_requirements.txt` and `dev_requirements.txt` files in the `<qgis src>/python` directory, so packagers/devs can readily tell `pip` what's need to be installed in a vendored or virtualenv location. Then 3 above is a simple operation.

**Comment by 3nids** [comment]
Hi Larry,
Thanks a lot for your reply.
I wasn't aware of brew info working dynamically with my current setup.
