### ISSUE TITLE
QGIS2 2.18.14 upgrade. Error on install

### ISSUE THREAD

**Issue by cbertelli** [OSGeo/homebrew-osgeo4mac#285]
==> Upgrading 1 outdated package, with result:
osgeo/osgeo4mac/qgis2 2.18.14
==> Upgrading osgeo/osgeo4mac/qgis2 --with-grass --with-qspatialite
==> Downloading https://github.com/qgis/QGIS/archive/final-2_18_14.tar.gz
Already downloaded: /Users/carlo/Library/Caches/Homebrew/qgis2-2.18.14.tar.gz
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/qgis2/2.18.14 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAME
==> make
==> make install
Error: No such file or directory @ rb_file_s_symlink - (../../../../lib/qt-4/plugins/sqldrivers, /usr/local/Cellar/qgis2/2.18.14/QGIS.app/Contents/Plugins/qgis/)

Looking into qt-4 I find:
ls /usr/local/opt/qt-4/plugins/sqldrivers/
libqsqlite.dylib  libqsqlodbc.dylib libqsqlpsql.dylib libqsqltds.dylib

Is does not seem to be missing or empty. Any suggestion?

**Comment by dakcarto** [comment]
Hi @cbertelli, thanks for reporting!

Please provide [Troubleshooting](https://github.com/Homebrew/brew/blob/master/docs/Troubleshooting.md) logs.

Also note that the compilation error _may be missing_ from any uploaded `brew gits-logs`. See: [Finding-a-parallel-job-compilation-error](https://github.com/OSGeo/homebrew-osgeo4mac/wiki/Finding-a-parallel-job-compilation-error)

---

Note: `../../../../lib/qt-4/plugins/sqldrivers` and `/usr/local/opt/qt-4/plugins/sqldrivers/` are not the same thing here. Also, this is actually a core coding issue that I am currently working on, i.e. QT_PLUGIN_PATH is not properly being honored by QGIS. Should have a fix today.

**Comment by cbertelli** [comment]
By now, here is the gist:
https://gist.github.com/cbertelli/66ba91e2f64450daf35a2de8306c7f86
I hope it does not hide something subtly happened in parallel compilation. I think it could be a missing requirement…
I compiled yesterday on ArchLinux 32bits and it worked well, so I may hope (fairly unreasonably) that is not an upstream bug. Thanks for looking to problems of a 10.9 user.

**Comment by dakcarto** [comment]
@cbertelli I've removed the symlink command and opted for leveraging QT_PLUGIN_PATH in 4058b5c. However, this needs merged and backported to `release-2_18` before it will actually work for the `qgis2*` formulae, i.e. `qt4-mysql` and `qt4-oracle` will not have their Qt database drivers recognized in QGIS 2 for now.

Regardless, `qgis2*` formulae _should_ compile fine now.
