### ISSUE TITLE
GRASS 72 build fails `--with-postgresql`

### ISSUE THREAD

**Issue by peteWT** [OSGeo/homebrew-osgeo4mac#292]
Hi,

I can build GRASS 72 without errors by not asking for PostgreSQL. However I get the following when I `brew reinstall grass7 --with-postgresql`:

```
Last 15 lines from /Users/pete/Library/Logs/Homebrew/grass7/02.make:
--------------------------------------------------
Started compilation: Thu Nov 16 09:45:13 PST 2017
--
Errors in:
/private/tmp/grass7-20171116-95904-1fbc0f4/grass-7.2.2/lib/db/sqlp
/private/tmp/grass7-20171116-95904-1fbc0f4/grass-7.2.2/db/drivers/dbf
/private/tmp/grass7-20171116-95904-1fbc0f4/grass-7.2.2/raster
--
In case of errors please change into the directory with error and run 'make'.
If you get multiple errors, you need to deal with them in the order they
appear in the error log. If you get an error building a library, you will
also get errors from anything which uses the library.
--
Finished compilation: Thu Nov 16 09:48:13 PST 2017
make: *** [default] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/osgeo/homebrew-osgeo4mac/issues

These open issues may also help:
Update grass7 to use aqua gui, dump XQuartz https://github.com/OSGeo/homebrew-osgeo4mac/pull/267

```

I've updated and doctored, removed a couple un-brewed dylibs that seemed unrelated: `/usr/local/lib/libtk8.6.dylib`

postgresql is installed from homebrew:

```
brew info postgresql
postgresql: stable 10.1 (bottled), HEAD
Object-relational database system
https://www.postgresql.org/
Conflicts with:
  postgres-xc (because postgresql and postgres-xc install the same binaries.)
/usr/local/Cellar/postgresql/10.1 (3,372 files, 38.8MB) *
  Poured from bottle on 2017-11-13 at 09:54:17
```

as is PostGIS

```
brew info postgis
postgis: stable 2.4.0 (bottled), HEAD
Adds support for geographic objects to PostgreSQL
https://postgis.net/
/usr/local/Cellar/postgis/2.3.2 (196 files, 75.2MB)
  Poured from bottle on 2017-07-19 at 16:32:19
/usr/local/Cellar/postgis/2.4.0_1 (228 files, 91.0MB) *
  Poured from bottle on 2017-10-27 at 14:11:05
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/postgis.rb
```

Thanks,

Peter

**Comment by dakcarto** [comment]
Hi @peteWT, thanks for reporting!

Guessing GRASS 7.2.2 may not yet support compilation against `postgres` version 10.1. You can try installing an older version of `postgres` formula by directly installing a previous bottle, as noted in a previous version of the `postgres.rb`, but it will be tricky to get newer `postgis` to install as well.

Please provide [Troubleshooting](https://github.com/Homebrew/brew/blob/master/docs/Troubleshooting.md) logs.

Also note that the compilation error _may be missing_ from any uploaded `brew gits-logs`. See: [Finding-a-parallel-job-compilation-error](https://github.com/OSGeo/homebrew-osgeo4mac/wiki/Finding-a-parallel-job-compilation-error)

**Comment by nickrobison** [comment]
@peteWT Is this error still occurring? I was able to successfully build `grass7` against Postgres 10 on on High Sierra machine.

It looks like there's a `postgres@9.6` formula in the homebrew repo that we could potentially link against, but I want to make sure this is still an issue before I do so.

**Comment by peteWT** [comment]
@nickrobison Still getting the following error:

```
==> Installing osgeo/osgeo4mac/grass7 --with-postgresql
==> Downloading https://grass.osgeo.org/grass72/source/grass-7.2.2.tar.gz
Already downloaded: /Users/pete/Library/Caches/Homebrew/grass7-7.2.2.tar.gz
==> Patching
patching file include/Make/Install.make
Hunk #1 succeeded at 116 (offset 2 lines).
==> ./configure --prefix=/usr/local/Cellar/grass7/7.2.2 --enable-shared --with-cxx --with-python --with-blas --w
==> make GDAL_DYNAMIC=
Last 15 lines from /Users/pete/Library/Logs/Homebrew/grass7/02.make:
--------------------------------------------------
Started compilation: Tue Apr 17 17:54:40 PDT 2018
--
Errors in:
/private/tmp/grass7-20180417-29875-15kumjv/grass-7.2.2/lib/db/sqlp
/private/tmp/grass7-20180417-29875-15kumjv/grass-7.2.2/db/drivers/dbf
/private/tmp/grass7-20180417-29875-15kumjv/grass-7.2.2/raster
--
In case of errors please change into the directory with error and run 'make'.
If you get multiple errors, you need to deal with them in the order they
appear in the error log. If you get an error building a library, you will
also get errors from anything which uses the library.
--
Finished compilation: Tue Apr 17 17:57:19 PDT 2018
make: *** [default] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/osgeo/homebrew-osgeo4mac/issues

These open issues may also help:
grass7 fails to build --with-liblas option https://github.com/OSGeo/homebrew-osgeo4mac/issues/299
Update grass7 to use aqua gui, dump XQuartz https://github.com/OSGeo/homebrew-osgeo4mac/pull/267
NF-ptittmann:~ pete$ brew update
Updated Homebrew from 5a2817cb0 to 714bf5152.
Updated 3 taps (homebrew/core, osgeo/osgeo4mac, caskroom/cask).
```

**Comment by nickrobison** [comment]
@peteWT 

Sorry to hear this this still happening. The error log you posted doesn't seem to point to the underlying issue. Would you mind providing some more detailed errors by following the below links:

Providing [Troubleshooting](https://github.com/Homebrew/brew/blob/master/docs/Troubleshooting.md) logs.

Also note that the compilation error _may be missing_ from any uploaded `brew gits-logs`. See: [Finding-a-parallel-job-compilation-error](https://github.com/OSGeo/homebrew-osgeo4mac/wiki/Finding-a-parallel-job-compilation-error)

Also, you might want to post the entirety of your Make file output.

**Comment by nickrobison** [comment]
@peteWT I'm going to close this issue, feel free to re-open if you're still having trouble.
