### ISSUE TITLE
gdal2 MDB configure error

### ISSUE THREAD

**Issue by nextstopsun** [OSGeo/homebrew-osgeo4mac#293]
When trying to build gdal2 `--with-mdb` I get a configure error:
```
checking whether we should include MDB support... configure: error: "--with-jvm-lib must be specified."
```

**Comment by nickrobison** [comment]
@nextstopsun I believe I've resolved this issue via changes to the `gdal2-mdb` formula. We've been slowly moving the various drivers out of the main GDAL backend and into their own formulae, so MDB support in the main `gdal2` formula is pretty much deprecated. Let us know if you're still running into issues.
