### ISSUE TITLE
Request for gdal2-db2 formula

### ISSUE THREAD

**Issue by nextstopsun** [OSGeo/homebrew-osgeo4mac#296]
@dakcarto Can you please provide a `gdal2-db2` formula similar to i.e. `gdal2-oracle` one? GDAL has r/w capabilities in DB2 driver, so this would be a great feature for os x gdal users.

**Comment by dakcarto** [comment]
Hi @nextstopsun,

I don't think this is possible on macOS. The [GDAL/OGR DB2 driver](http://www.gdal.org/drv_db2.html) mentions it utilizes the ODBC driver:

> "This [GDAL] driver is currently supported only in the Windows environment."

Also, the [pre-compiled ODBC DB2 driver](https://www-01.ibm.com/marketing/iwm/iwm/web/reg/pick.do?source=swg-idsoc97&lang=en_US) from IBM (requires account signup) appears to only be for Windows or Linux.

Do you know of an open source DB2 client ODBC library for macOS?

**Comment by nextstopsun** [comment]
I've used it with GDAL on Linux and `unixodbc` lib. 
I thought that linux DB2 driver could be used here also.

**Comment by dakcarto** [comment]
The Linux binary client would be ABI-incompatible on macOS.
