### ISSUE TITLE
Caveats for qgis2

### ISSUE THREAD

**Issue by pat-s** [OSGeo/homebrew-osgeo4mac#297]
I just installed `qgis2` on a new `high_sierra` VM. 

To get it starting after installation without throwing python errors, I needed to install the following python modules via `pip2`:

* psycopg2
* pygments
* jinja2
* gdal
* requests

This does partly match with what I need to do on travis. There its `psycopg2`, `matplotlib` and `pyparsing`. Maybe the others are installed as dependencies (have not checked in detail yet).

Would it be worth adding this information to `qgis2` and `qgis2-ltr`? Not sure if its the same for `qgis-ltr` though.

**Comment by dakcarto** [comment]
Hi @pat-s, thanks for reporting!

The Python runtime requirements are [parsed upon each run of `brew info qgis2`](https://github.com/OSGeo/homebrew-osgeo4mac/blob/master/Formula/qgis2.rb#L512). Any dependencies that are missing are listed, i.e. a listing may not show up if you have everything is already installed.

However, `gdal` should _not_ be a requirement, as the `gdal2-python` formulae is already a dependency and properly handled in both the `Info.plist` for the QGIS.app and in the `qgis2` binary wrapper script. What error prompted you to do `pip2 install gdal`?

**Comment by pat-s** [comment]
> However, gdal should not be a requirement, as the gdal2-python formulae is already a dependency and properly handled in both the Info.plist for the QGIS.app and in the qgis2 binary wrapper script. What error prompted you to do pip2 install gdal?

To use QGIS with a 3rd party software, we do besides others (see below) `from osgeo import ogr`

```
  py_run_string("import os, sys, re, webbrowser")
  py_run_string("from qgis.core import *")
  py_run_string("from osgeo import ogr")
  py_run_string("from PyQt4.QtCore import *")
  py_run_string("from PyQt4.QtGui import *")
  py_run_string("from qgis.gui import *")
```
The mentioned step failed without having `gdal` installed via pip and an re-installation of `qgis2`. 

Maybe this only relates to the use of QGIS in a 3rd party software (wild guess) as QGIS launched without errors AFAIR.

**Comment by dakcarto** [comment]
@dakcarto wrote:
> However, gdal should not be a requirement, as the gdal2-python formulae is already a dependency and properly handled in both the Info.plist for the QGIS.app and in the qgis2 binary wrapper script. What error prompted you to do pip2 install gdal?

What I mean here is that keg-only formulae that install to a custom prefix will never have their Python modules installed to the main Homebrew `site-packages`, i.e. look at `gdal2-python` caveats, or at the env vars listed in `/usr/local/Cellar/qgis2/2.18.14/QGIS.app/Contents/Info.plist` or `/usr/local/Cellar/qgis2/2.18.14/bin/qgis2`.

Unless your third-party solution sets up a similar environ to `qgis2*` apps, it will fail to find certain keg-only Python modules.

**Comment by dakcarto** [comment]
@pat-s, hi. Any updates here?

**Comment by pat-s** [comment]
did not do further investigations here - but as travis builds are fine without `pip2 install gdal`, it seems to be related to the third party app only.
