### ISSUE TITLE
qt5-webkit needs upgrade to qt 5.10 repo

### ISSUE THREAD

**Issue by nextstopsun** [OSGeo/homebrew-osgeo4mac#303]
Homebrew `qt` version is now `5.10`. 
I couldn't rebuild `qgis3-dev` due to `qt5-webkit` package, which still relies on qt 5.9.1 submodule.
@dakcarto Can you please upgrade `qt5-webkit` formula to clear the way for a `qgis3-dev` build?

These `qt5-webkit` and `pyqt5-webkit` formulas look quite hacky. Are they still needed in addition to recent `qt 5.10` lib?

**Comment by nickrobison** [comment]
@nextstopsun It looks like the qt-webkit module isn't built for 5.10. The latest version I can find on the qt site is 5.9.2. Am I understanding that correctly?

Is there a community maintained version that we can build against?

**Comment by 3nids** [comment]
also, there is a --without-webkit or similar in qgis3-dev formula from memory

**Comment by nickrobison** [comment]
This has been resolved in #404
