### ISSUE TITLE
Cannot Install GRASS-7 from Homebrew on Mac 10.13.3

### ISSUE THREAD

**Issue by dheerajchand** [OSGeo/homebrew-osgeo4mac#310]
Hi, no clue what's going on here.

--

➜  ~ brew install grass-70 --with-netcdf --with-postgresql

Warning: Calling 'depends_on :python' is deprecated!
Use 'depends_on "python"' instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/grass7.rb:47:in `<class:Grass7>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling 'depends_on :postgresql' is deprecated!
Use 'depends_on "postgresql"' instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/grass7.rb:50:in `<class:Grass7>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling 'depends_on :mysql' is deprecated!
Use 'depends_on "mysql"' instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/grass7.rb:51:in `<class:Grass7>'
Please report this to the osgeo/osgeo4mac tap!

==> Installing grass7 from osgeo/osgeo4mac
Error: no implicit conversion of Symbol into String
Please report this bug:
  https://docs.brew.sh/Troubleshooting.html
/usr/local/Homebrew/Library/Homebrew/formulary.rb:363:in `extname'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:363:in `loader_for'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:280:in `factory'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:33:in `to_formula'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:96:in `block in expand'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/delegate.rb:341:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/delegate.rb:341:in `block in delegating_block'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:83:in `expand'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1478:in `recursive_dependencies'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1490:in `runtime_dependencies'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:419:in `runtime_requirements'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:432:in `expand_requirements'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:376:in `compute_dependencies'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:133:in `verify_deps_exist'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:126:in `prelude'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:336:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:227:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:225:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:225:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'

**Comment by aleksandrmelnyk** [comment]
yep, facing same issue.

**Comment by nickrobison** [comment]
@dheerajchand @aleksandrmelnyk Can you try installing again? We just cleaned up some of the formula and I'm unable to replicate this error on my High Sierra machine.

**Comment by aleksandrmelnyk** [comment]
I installed fine.
