### ISSUE TITLE
Homebrew warnings report to osgeo4mac tap

### ISSUE THREAD

**Issue by kikislater** [OSGeo/homebrew-osgeo4mac#313]
I got these warnings : 

> 
> $ brew update
> Updating Homebrew...
> Warning: Calling 'depends_on :python' is deprecated!
> Use 'depends_on "python"' instead.
> /usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/gdal2-python.rb:66:in `<class:Gdal2Python>'
**> Please report this to the osgeo/osgeo4mac tap!**
> 
> Warning: Calling 'depends_on :python3' is deprecated!
> Use 'depends_on "python3"' instead.
> /usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/gdal2-python.rb:67:in `<class:Gdal2Python>'
**> Please report this to the osgeo/osgeo4mac tap!**
> 
> Warning: Calling 'depends_on :python' is deprecated!
> Use 'depends_on "python"' instead.
> /usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/pyspatialite.rb:29:in `<class:Pyspatialite>'
**> Please report this to the osgeo/osgeo4mac tap!**
> 
> Warning: Calling 'depends_on :gpg' is deprecated!
> Use 'depends_on "gnupg"' instead.
> /usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/qca-qt4.rb:43:in `<class:QcaQt4>'
**> Please report this to the osgeo/osgeo4mac tap!**
> 
> Warning: Calling 'depends_on :postgresql' is deprecated!
> Use 'depends_on "postgresql"' instead.
> /usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/grass7.rb:50:in `<class:Grass7>'
**> Please report this to the osgeo/osgeo4mac tap!**
> 
> Warning: Calling 'depends_on :mysql' is deprecated!
> Use 'depends_on "mysql"' instead.
> /usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/grass7.rb:51:in `<class:Grass7>'
**> Please report this to the osgeo/osgeo4mac tap!**
> 
> Warning: Calling Requirement.default_formula is deprecated!
> There is no replacement.
> /usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Requirements/qgis_requirements.rb:33:in `<class:SipBinary>'
**> Please report this to the osgeo/osgeo4mac tap!**
> 
> Warning: Calling Requirement.default_formula is deprecated!
> There is no replacement.
> /usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Requirements/qgis_requirements.rb:48:in `<class:PyQtConfig>'
**> Please report this to the osgeo/osgeo4mac tap!**

**Comment by dd-a** [comment]
The 6 first warnings can be fixed like this, considering the first one as an example :
type `brew edit /usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/gdal2-python.rb` 
then on line 66 (and everywhere else) replace `depends_on :python` with `depends_on "python"` as it is stated in the message.  For the 2 last warnings (with `Calling Requirement.default_formula`) I don't know but on my system it works anyway.

**Comment by nickrobison** [comment]
Thanks for reporting. I believe this has been resolved in #308.
