### ISSUE TITLE
"from osgeo import gdal" fails

### ISSUE THREAD

**Issue by BuddyVolly** [OSGeo/homebrew-osgeo4mac#316]
Dear osgeo team, 
I installed the gdal2-python formulae. The commands however do not run. They exit with the error that module osgeo is not found. If I launch the brew python version and type it manually, same error. 
Any help is appreciated to get this working. 
Thanks in advance!

**Comment by pat-s** [comment]
Hi Andreas,

does [that](https://github.com/OSGeo/homebrew-osgeo4mac/issues/312) help?

**Comment by nickrobison** [comment]
@BuddyVolly Is this issue still affecting you?

If so, can you try to reinstall with the latest versions of `gdal2` and `gdal2-python`?

If the error's still occurring, could you post some additional logs?

**Comment by shubhawasthi123** [comment]
I am trying to 	from	osgeo import	gdal in anaconda python3 environment, but it is showing the error

In [2]: from osgeo import gdal
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-61e0eefce4de> in <module>()
----> 1 from osgeo import gdal

~/anaconda3/lib/python3.6/site-packages/osgeo/__init__.py in <module>()
     19                 fp.close()
     20             return _mod
---> 21     _gdal = swig_import_helper()
     22     del swig_import_helper
     23 else:

~/anaconda3/lib/python3.6/site-packages/osgeo/__init__.py in swig_import_helper()
     15         if fp is not None:
     16             try:
---> 17                 _mod = imp.load_module('_gdal', fp, pathname, description)
     18             finally:
     19                 fp.close()

~/anaconda3/lib/python3.6/imp.py in load_module(name, file, filename, details)
    241                 return load_dynamic(name, filename, opened_file)
    242         else:
--> 243             return load_dynamic(name, filename, file)
    244     elif type_ == PKG_DIRECTORY:
    245         return load_package(name, filename)

~/anaconda3/lib/python3.6/imp.py in load_dynamic(name, path, file)
    341         spec = importlib.machinery.ModuleSpec(
    342             name=name, loader=loader, origin=path)
--> 343         return _load(spec)
    344 
    345 else:

ImportError: libncurses.so.6: cannot open shared object file: No such file or di
