### ISSUE TITLE
brew install qgis2-ltr fails on 10.12.6/macOS Sierra

### ISSUE THREAD

**Issue by tfr42** [OSGeo/homebrew-osgeo4mac#325]
Trying to install qgis2-ltr with `brew install osgeo/osgeo4mac/qgis2-ltr` on 10.12.6/macOS Sierra. Command is failing due to:
```
Could NOT find PythonInterp: Found unsuitable version "1.4", but required is at least "2" (found /usr/local/Cellar/python@2/2.7.14_2/Frameworks/Python.framework/Versions/Current/bin/python)
CMake Error at cmake/FindSIP.cmake:54 (MESSAGE):
  Could not find SIP
```

SIP was installed with:
```
> pip install sip
Collecting sip
  Downloading sip-4.19.8-cp36-cp36m-macosx_10_6_intel.whl (51kB)
    100% |████████████████████████████████| 61kB 1.2MB/s 
Installing collected packages: sip
Successfully installed sip-4.19.8
```

The trouble shooting logs are here: https://gist.github.com/anonymous/60b553920d4e1f616224022b40628b68

Any ideas what to try next? https://github.com/qgis/homebrew-qgisdev/issues/2 didn't help.

**Comment by nickrobison** [comment]
@tfr42 We just made a number of changes to the way formulas handle python dependencies. Can you try to reinstall again and see if the issue persists?

I don't have a Sierra machine, but the latest `qgis2-ltr` installed for me on High Sierra.


Also, unless you need the QGIS 2.14 branch, you might be better served by the `qgis2` formula, which uses the newer 2.18 version of QGIS.

**Comment by tfr42** [comment]
I can confirm that build from source worked for `qgis2-ltr` with QGIS 2.14.20 on macOS Sierra.

`brew install osgeo/osgeo4mac/qgis2` works on macOS Sierra but running the application is failing:

```
> /usr/local/opt/qgis2/bin/qgis2
dyld: Library not loaded: /usr/local/opt/json-c/lib/libjson-c.2.dylib
  Referenced from: /usr/local/opt/gdal2/lib/libgdal.20.dylib
  Reason: image not found
/usr/local/opt/qgis2/bin/qgis2: line 10:  7694 Abort trap: 6           /usr/local/opt/qgis2/QGIS.app/Contents/MacOS/QGIS "$@"
```

**Comment by nickrobison** [comment]
@tfr42  Can you try `brew reinstall gdal2` and see if that resolves the issue?

the `libjson` library was recently updated in Home-brew and has been causing some breakages in gdal.
