### ISSUE TITLE
faulty gdalwarp install on OSX 10.13.3

### ISSUE THREAD

**Issue by erictheise** [OSGeo/homebrew-osgeo4mac#333]
The standard brew version of gdal wasn't doing what I needed so I followed [Bhaskar V. Karambelkar's outline](https://www.karambelkar.info/2016/10/gdal-2-on-mac-with-homebrew/) to install 2.2.3. Using `gdalwarp` on a pair of NetCDF files failed, then some others, and I finally tried it on a Natural Earth II geotiff per an old [Mapbox tutorial](https://tilemill-project.github.io/tilemill/docs/guides/reprojecting-geotiff/). Every attempt failed with a `Too many points (10201 out of 10201) failed to transform, unable to compute output bounds.` error.

Always 10201.

Finally switched to compiling on an Ubuntu 16.04 VM and the operation sails through with out a hitch.

Here's the OSX output if it helps.

```
$ gdalwarp --debug ON -s_srs EPSG:4326 -t_srs EPSG:3857 -of GTIFF -te -20037508.34 -20037508.34 20037508.34 20037508.34  NE2_LR_LC_SR_W.tif NE2_LR_LC_SR_W.merc.tif

GNM: GNMRegisterAllInternal
GNM: RegisterGNMFile
GNM: RegisterGNMdatabase
GDAL: GDALOpen(NE2_LR_LC_SR_W.tif, this=0x7fdf92c2ae30) succeeds as GTiff.
OGRCT: PROJ >= 4.8.0 features enabled
OGRCT: Using locale-safe proj version
OGRCT: Wrap source at -1.80194e-11.
OGRCT: Source: +proj=longlat +ellps=WGS84 +no_defs
OGRCT: Target: +proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +no_defs
OGRCT: Wrap target at -1.80194e-11.
OGRCT: Source: +proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +no_defs
OGRCT: Target: +proj=longlat +ellps=WGS84 +no_defs
OGRCT: Wrap source at -1.80194e-11.
OGRCT: Source: +proj=longlat +ellps=WGS84 +no_defs
OGRCT: Target: +proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +no_defs
OGRCT: Wrap target at -1.80194e-11.
OGRCT: Source: +proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +no_defs
OGRCT: Target: +proj=longlat +ellps=WGS84 +no_defs
WARP: At least one point failed after direct transform
ERROR 1: Too many points (10201 out of 10201) failed to transform, unable to compute output bounds.
GDAL: GDALClose(NE2_LR_LC_SR_W.tif, this=0x7fdf92c2ae30)
```

**Comment by nickrobison** [comment]
@erictheise Thanks for reporting this. I think if you're experiencing the issue using multiple drivers, with the same compilation flags between Linux and MacOS, that it's an issue with GDAL itself and not the packaging for MacOS.

Looking at the installation formula, there aren't any changes to the source or additional patches being applied, so you'd probably be best served by reporting the issue to the GDAL bug tracker [here](https://github.com/OSGeo/gdal/issues).

Hopefully then can get you up and running again.
