### ISSUE TITLE
Formulae bottles are not being updated correctly.

### ISSUE THREAD

**Issue by nickrobison** [OSGeo/homebrew-osgeo4mac#346]
As mentioned in #342, there's an issue with some of the latest bottle (gdal2 specifically). It looks like when the formula is updated in travis that the `bottle do` block in the formula isn't being updated with the latest values. The CI script merely outputs the updated block to the screen, but doesn't merge the changes with the old script. 

Looking at the commit history, it seems like @dakcarto was manually updating the bottle block, after pushing new versions (see 73c972b, 3605b02).

Seems like we have a couple of options going forward.

1. We can keep the manual process:
That would require doing the manual update as soon as we push a new version, because the new version would be including the wrong bottle hash.

2. Setup Travis to automatically update the bottle block.
This is definitely possible, the `brew bottle` command has the option to automatically merge the bottle changes into the formula. We would then have travis create a new commit and push the changes back up to GitHub. This would require creating a Travis oauth token in Github and adding it as an encrypted variable to the travis.yml file. It would also require allowing that oauth token to make commits to the repo.

3. Switch to using the `brew pull` command.
Homebrew has a special command for merging pull requests and doing the bottle updating. I'm not sure if this is fully compatible with using s3 to store the bottles, it mentions bintray a couple of times, but we could definitely look into that more.

@3nids Thoughts? Happy to help figure out the best option going forward. I'm leaning towards 2, simply because it reduces the burden on the maintainer, they only have to approve a clean PR and the CI system will handle the rest, but it definitely requires the most up front work.

**Comment by 3nids** [comment]
good summary.

see https://gist.github.com/maelvalais/068af21911c7debc4655cdaa41bbf092

I have no strong opinion. I tend to like the idea of having an extra PR with the updated bottle. But I think this makes the workflow much more complicated.

We could go for 2.
We would just need a way of re-triggering bottle builds (by manually creating build on travis with a defined env variable to say which package must be bottled).

Would you have some time to work on this?

**Comment by nickrobison** [comment]
Resolved in #347.
