### ISSUE TITLE
Travis hangs if no formula are updated

### ISSUE THREAD

**Issue by nickrobison** [OSGeo/homebrew-osgeo4mac#351]
[See](https://travis-ci.org/OSGeo/homebrew-osgeo4mac/builds/365859693). If `changed_formula.sh` returns an empty string, Travis hangs and eventually gets killed. Perhaps `travis_terminate 0` isn't working correctly?

Maybe we can just call `exit 0`?

Seems to work fine if at least 1 formula was modified.

**Comment by fjperini** [comment]
I think the solution for this is to add `[skip ci]` to the commit message when the change doesn't require a build.

**Comment by fjperini** [comment]
Fixed with `exit 0 || true;`
