### ISSUE TITLE
qgis2 : syntax error, unexpected <<

### ISSUE THREAD

**Issue by dd-a** [OSGeo/homebrew-osgeo4mac#355]
trying to install qgis2 I get this error:

```
Error: qgis2: /usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/qgis2.rb:61: syntax error, unexpected <<, expecting keyword_end
<<<<<<< Updated upstream
  ^
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/qgis2.rb:64: syntax error, unexpected ===, expecting keyword_end
=======
   ^
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/qgis2.rb:66: syntax error, unexpected >>, expecting keyword_end
>>>>>>> Stashed changes
```

same after with qgis_requirements.rb

**Comment by nickrobison** [comment]
@dd-a Sorry to hear this. Looking at the formula, I can't see the error mentioned in the output and the formula installed fine for me.

Perhaps it's an issue with your local tap? Have you tried running `brew update` and `brew doctor` to see if any errors have been reported.

**Comment by dd-a** [comment]
Strange ...  I'm on another mac right now (10.13.4), so I tried it again with the same result.  I did exactly:

1. brew update (which announces `osgeo/osgeo4mac/qgis2` among the update formulae)
2. brew install qgis2
Plus now, I ran `brew doctor` which gave me this:

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6m-config
  /Library/Frameworks/Python.framework/Versions/3.6/bin/python3-config
  /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6-config

Warning: You have MacPorts or Fink installed:
  /opt/local/bin/port

This can cause trouble. You don't have to uninstall them, but you may want to
temporarily move them out of the way, e.g.

  sudo mv /opt/local ~/macports

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  gdal2-python
  python@2
  python
  qgis2-ltr

Warning: Your XQuartz (2.7.9) is outdated.
Please install XQuartz 2.7.11 (or delete the current version).
XQuartz can be updated using Homebrew-Cask by running
  brew cask reinstall xquartz
```

I hope it makes more sense to you.  I'm not a dev so I don't edit the formulas myself except for the mentioned errors this morning which I commented (and it solved the issue but then produced the ones about `qgis_requirements.rb`).  Tell me if there's any additional information I can give you.

**Comment by dd-a** [comment]
According to the error message I did:
`brew edit /usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/gdal2-python.rb`
and doing this I realised that _this time_ it was gdal2-python.rb ... Sorry I didn't pay attention.  Anyway here are the requested lines from `gdal2-python.rb` , just in case:


```
  bottle do
    root_url "https://osgeo4mac.s3.amazonaws.com/bottles"
    cellar :any
    rebuild 1
    sha256 "ca2844b0de49cd966f5b484ce74e9b6b5e10f388564792f778cff002ccaddf05" => :high_sierra
    sha256 "ca2844b0de49cd966f5b484ce74e9b6b5e10f388564792f778cff002ccaddf05" => :sierra
  end

  keg_only "older version of gdal is in main tap and installs similar components"

  depends_on "swig" => :build
  depends_on "gdal2"
  depends_on NoGdal2Python
<<<<<<< Updated upstream
  depends_on "python@2" => :recommended
  depends_on "python" => :recommended
=======
  depends_on "python" => :recommended
  depends_on "python3" => :recommended
>>>>>>> Stashed changes
  depends_on "numpy"

  resource "autotest" do
    url "http://download.osgeo.org/gdal/2.2.4/gdalautotest-2.2.4.tar.gz"
    sha256 "0d3bb1362f86507b255d8e2000b58824b32e9602af893135de549262833bd6aa"
  end

```

This morning it was in `qgis2.rb` but unfortunately I can't check that computer now (still, I did exactly the same this morning than now, `brew update` first, the `qgis2.rb` formula was 3 hours old)

And `brew info qgis2` gives `osgeo/osgeo4mac/qgis2: stable 2.18.18 (bottled), HEAD`
`brew info gdal2-python` simply gives the same error message, no version info

**Comment by nickrobison** [comment]
@dd-a It sounds like there's something strange going on with your local tap. If you look at the current version of `gdal2-python` [here](https://github.com/OSGeo/homebrew-osgeo4mac/blob/master/Formula/gdal2-python.rb), you can see that it doesn't have any of the extra characters you're reporting on your end.

Those `Updated upstream` messages usually indicate a conflict with trying to merge changes on your local machine with the latest homebrew updates.

Not sure what would be causing that issue, but you might want to try to remove the tap and try again.

```
brew untap osgeo/homebrew-osgeo4mac
brew tap osgeo/homebrew-osgeo4mac
brew update
```

When you run the `brew update` command, do you see any changes in red, or any messages that would indicate a conflict?

**Comment by dd-a** [comment]
This solved the issue, Thanks !

qgis2 installation failed afterward for some other reasons but I guess these are part of the other problems that are currently being addressed.

**Comment by nickrobison** [comment]
@dd-a Good news!

Sorry `qgis2` didn't compile for you. If you don't see the problem you encountered currently described in an open issue, feel free to create a new one and we'll try to get it resolved as quickly as possible.
