### ISSUE TITLE
QGIS: brew linkapps doesn't exist anymore

### ISSUE THREAD

**Issue by grischard** [OSGeo/homebrew-osgeo4mac#362]
QGIS is built as an application bundle. Installing it recommends running `brew linkapps` to symlink it into /Applications, but `linkapps` is gone from the latest versions of homebrew. Using brew casks is now the recommended way of achieving this.

See https://github.com/macvim-dev/macvim/issues/450 for more details.

**Comment by nickrobison** [comment]
@grischard Thanks for reporting this. We're currently trying to figure out how best to handle moving QGIS to a cask (see #353), do you know of any projects that have successfully move from Formulae to casks?

**Comment by grischard** [comment]
Thank you for your explanation. Unfortunately I don't know any such projects. I'm closing this as a duplicate of #353.
