### ISSUE TITLE
Building qgis2 fails after 'brew upgrade' recently.

### ISSUE THREAD

**Issue by Gwang-Jin** [OSGeo/homebrew-osgeo4mac#371]
Hello. 
I succeeded `brew install qgis2 --with-grass --with-saga-gis-lts` last week. But after 'brew upgrade', qgis2 didn't work and rebuilding qgis2 failed.

`brew reinstall -v qgis2 --with-grass --with-saga-gis-lts`

The error message is
`ImportError: dlopen(/tmp/qgis2-20180511-47072-8unxdn/QGIS-final-2_18_19/build/output/python/qgis/_core.so, 2): Library not loaded: /usr/local/opt/json-c/lib/libjson-c.2.dylib
  Referenced from: /usr/local/opt/gdal2/lib/libgdal.20.dylib
  Reason: image not found
make[2]: *** [python/plugins/GdalTools/tools/ui_dialogAbout.py] Error 1
make[1]: *** [python/plugins/GdalTools/tools/CMakeFiles/zzz-GdalTools-2-depend.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
`

In the directory of /usr/local/opt/json-c/lib, there is no libjson-c.2.dylib file but libjson-c.4.dylib.

[https://gist.github.com/4e855a87db299bb702e041f7c89010ba](https://gist.github.com/4e855a87db299bb702e041f7c89010ba)

Thank you.

**Comment by 3nids** [comment]
I just triggered a new build for gdal2, let's see if it solves the issue

**Comment by nickrobison** [comment]
@Gwang-Jin You might want to try `brew reinstall gdal2`, now that we've rebuilt the bottle. Sometimes GDAL breaks if the underlying libraries get updated, let us know if you're still having issues.

**Comment by Gwang-Jin** [comment]
After `brew reinstall gdal2`, I also met the same problem. 
So I tried to symbolic-link`ln -s libjson-c.4.dylib libjson-c.2.dylib`. And I solved the problem.

**Comment by Jmuccigr** [comment]
FWIW on May 10 I started getting this error that `brew reinstall gdal2` seems to have fixed:

```
dyld: Library not loaded: /usr/local/opt/json-c/lib/libjson-c.2.dylib
  Referenced from: /usr/local/opt/gdal2/bin/ogr2ogr
  Reason: image not found
Abort trap: 6
```

**Comment by Gwang-Jin** [comment]
Thank you. After retrying `brew reinstall gdal2`, I can find that the problem has solved.

**Comment by 3nids** [comment]
glad to read so! 
Thanks for reporting
