### ISSUE TITLE
saga-gis-lts: add liblas support

### ISSUE THREAD

**Issue by nickrobison** [OSGeo/homebrew-osgeo4mac#383]
In `saga-gis-lts` liblas support is disabled due to incompatible versions. We should investigate whether or not the latest version (6.3.0) supports liblas, and if so, add some optional support.

**Comment by luisspuerto** [comment]
@nickrobison do you think this is related to #463?

**Comment by fjperini** [comment]
This is solved in https://github.com/OSGeo/homebrew-osgeo4mac/pull/768 https://github.com/OSGeo/homebrew-osgeo4mac/pull/770
