### ISSUE TITLE
GDAL 2.3.0 No Longer Building Java JNI Libraries

### ISSUE THREAD

**Issue by agxs** [OSGeo/homebrew-osgeo4mac#397]
After upgrading from 2.2.3 to 2.3.0 the Java JNI libraries no longer seem to be included in the build in the `/lib` directory.

The command I'm using to build is:
`brew install osgeo/osgeo4mac/gdal2 --with-complete --with-libkml --with-java --with-opencl --with-postgresql --with-swig-java`

There is a warning about `with-java` being deprecated, however I've tried with and without this parameter, and also including `--with-swig-java`.

**Comment by nickrobison** [comment]
@agxs Thanks for reporting this. Sorry that you're having issues.

Which version of Java are you running on your machine?

**Comment by nickrobison** [comment]
It looks like the `gdal.jar` library is being built on my machine. Can you provide some more system details, such as the output of `brew config`?

**Comment by agxs** [comment]
1.8.0.171 and 1.8.0.102. `gdal.jar` gets built fine, but the JNI `so` file isn't, I think it's called `libgdaljni.so.<version>`.

**Comment by agxs** [comment]
If I revert the commit back to the 2.2.4 version then the library gets built fine. Not sure if this is an issue with GDAL itself maybe.

**Comment by nickrobison** [comment]
@agxs Thanks for the extra info! Sounds like something changed internally with gdal as we didn't modify the formula when bumping the version. I'll dig around and see what I can come up with.

Glad you have a work around for now.

**Comment by nickrobison** [comment]
@agxs I believe I've resolved this issue with #402. Thanks for reporting! Should be fixed in GDAL 2.3.2, until then, I've applied a temporary patch.

Can you try again (after running `brew update`) and let me know if this issue is still occurring?

**Comment by agxs** [comment]
Wow thanks for the fast turnaround!

Works fine!
