### ISSUE TITLE
Error when installing qgis3

### ISSUE THREAD

**Issue by nextstopsun** [OSGeo/homebrew-osgeo4mac#434]
I'm installing qgis3 with
```
brew install --with-3d --with-gpsbabel --with-grass --with-isolation --with-oracle --with-qspatialite --with-r --with-saga-gis-lts qgis3
```

and etting an error: 
```
/usr/local/Cellar/qgis3/3.2.1/libexec/vendor/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tm
Error: No such file or directory @ rb_sysopen - src/providers/spatialite/qspatialite/CMakeLists.txt
```

What does `rb_sysopen` contain?

**Comment by fjperini** [comment]
@nextstopsun The `--with-qspatialite` option is causing that problem.

I will review the lines in question:

```
# install db plugins to local qt plugins prefix
if build.with? "qspatialite"
  mkdir lib_qt/"plugins/sqldrivers"
  inreplace "src/providers/spatialite/qspatialite/CMakeLists.txt",
                  "${QT_PLUGINS_DIR}/sqldrivers", lib_qt/"plugins/sqldrivers".to_s
end
```

**Comment by fjperini** [comment]
@nextstopsun I already apply the change, it must be `src/providers/spatialite/CMakeLists.txt` instead of `src/providers/spatialite/qspatialite/CMakeLists.txt`.

**Comment by nextstopsun** [comment]
@fjperini new error now:
```
==> /usr/local/Cellar/qgis3/3.2.1/libexec/vendor/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tm
Error: inreplace failed
src/providers/spatialite/CMakeLists.txt:
  expected replacement of "${QT_PLUGINS_DIR}/sqldrivers" with #<Pathname:/usr/local/Cellar/qgis3/3.2.1/lib/qt/plugins/sqldrivers>
```

**Comment by nextstopsun** [comment]
@fjperini Could you please bump up formula version for Homebrew to mark old one as outdated?

**Comment by fjperini** [comment]
@nextstopsun Ok! I will to revise it.

**Comment by fjperini** [comment]
@nextstopsun I think it is already solved. Building!

There was not a reference of `${QT_PLUGINS_DIR}/sqldrivers` in `src/providers/spatialite/qspatialite/CMakeLists.txt
`

Checking I found

```
qsqlspatialite
external/qspatialite/CMakeLists.txt
${QT_PLUGINS_DIR}/sqldrivers

spatialiteprovider
src/providers/spatialite/CMakeLists.txt
${QGIS_PLUGIN_DIR}
```

**Comment by fjperini** [comment]
@nextstopsun Ready! Build correctly, with the only option that I did not use was that of `--with-oracle`, it is necessary to download a file and copy it into `HOMEBREW CACHE`.

For more information check this: [cache-download.rb](homebrew-osgeo4mac/Strategies/cache-download.rb)|[oracle-client-sdk.rb](homebrew-osgeo4mac/Formula/oracle-client-sdk.rb)

**Comment by nextstopsun** [comment]
@fjperini Thanks, I'll try rebuilding qgis3 and get back to you here. 
Both links are broken, can you please point to that info once again?

**Comment by fjperini** [comment]
@nextstopsun fixed the links. It works with `--with-qspatialite`.

I think it's an extra configuration or something installed that makes it work correctly on my computer and does not present the pop-up window.

**Comment by fjperini** [comment]
@nextstopsun confirm that you can use `--with-qspatialite`, to close this issue.

**Comment by nextstopsun** [comment]
@fjperini A bit offline now. Will get back here asap.

**Comment by nextstopsun** [comment]
@fjperini Great work!! Closing.
