### ISSUE TITLE
Giant cursors in Qgis3 on retina display.

### ISSUE THREAD

**Issue by nextstopsun** [OSGeo/homebrew-osgeo4mac#447]
I don't know if that's related to a formula or upstream, but I've got giant cursors for tools like zoom in/out, identify etc. on a retina display. Anyone else? @luisspuerto @fjperini @nickrobison ?

**Comment by luisspuerto** [comment]
@nextstopsun I don't have a retina display so... I can help. 😕

**Comment by fjperini** [comment]
@nextstopsun Using retina, without that problem.

**Comment by nickrobison** [comment]
@nextstopsun I'm seeing the same issue, seems like an upstream problem. Since the other icons seem to be sized correctly, I don't think there's an issue with our formula, but maybe opening a ticket with the QGIS project could help identify if it's a problem on our end.

**Comment by nextstopsun** [comment]
@nickrobison It's quite hard to take a screenshot with a cursor on:)

**Comment by luisspuerto** [comment]
You can take a small screencast or a photo with your phone 😉

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by 3nids** [comment]
before running QGIS, can you try to do:
```
export QT_AUTO_SCREEN_SCALE_FACTOR=0
export QT_DEVICE_PIXEL_RATIO=1
```

**Comment by nextstopsun** [comment]
@3nids that didn't help. 
In general, map content looks quite low-res in comparison to UI elements.
Look how pixelated polygon border is compared to i.e. pan icon.

![image](https://user-images.githubusercontent.com/966321/44728387-1288fb80-aae5-11e8-913f-c640cc615f3f.png)

**Comment by fjperini** [comment]
@nextstopsun @nickrobison This can be closed?

**Comment by nextstopsun** [comment]
@fjperini seems ok to close. This can be reopened if needed.

**Comment by 3nids** [comment]
yes, this has been fixed
