### ISSUE TITLE
orfeo6: error when building --with: mapnik

### ISSUE THREAD

**Issue by spicysardine** [OSGeo/homebrew-osgeo4mac#449]
the problem is caused by the --with-mapnik option

Last 15 lines from /Users/Library/Logs/Homebrew/orfeo6/01.cmake:
-- Found GLUT: /usr/local/opt/freeglut/lib/libglut.dylib  
-- Found LTDL: /usr/local/lib/libltdl.dylib  
-- Found ICUUC: /usr/local/opt/icu4c/lib/libicuuc.dylib  
CMake Error at /usr/local/Cellar/cmake/3.12.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Agg (missing: AGG_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.12.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  CMake/FindAgg.cmake:39 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  Modules/ThirdParty/Mapnik/otb-module-init.cmake:23 (find_package)
  CMake/OTBModuleEnablement.cmake:394 (include)
  CMakeLists.txt:349 (include)

-- Configuring incomplete, errors occurred!
See also "/tmp/orfeo6-20180812-12730-1dbg2u7/OTB-release-6.6/build/CMakeFiles/CMakeOutput.log".

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/osgeo/homebrew-osgeo4mac/issues

**Comment by nickrobison** [comment]
@spicysardine Sorry to hear that you're having issues. I've created a patch to add the missing `libagg` library when compiling with the `--with-mapnik` flag, but it seems there are more issues going on. The compilation is failing for me. I'll dig into this a bit more and let you know what I find.

**Comment by spicysardine** [comment]
Thanks.

**Comment by fjperini** [comment]
@spicysardine @nickrobison I checked this, and it is necessary to build `mapkit` with the updated submodules.

We should have this formula in this repository since the homebrew-core version will not work without these changes.

```
git submodule update --init
./configure
make
make install
```
