### ISSUE TITLE
QGIS3 save fails and corrupts app

### ISSUE THREAD

**Issue by ozak** [OSGeo/homebrew-osgeo4mac#455]
Hi all...first of all thanks for the upgraded formula for qgis3! It's great!

I have the following issue on ``El Capitan``...I tried to create an output file after a process (in this case ``points on surface``), but when I click the ``Save to file..`` option it just freezes and gets stuck. Moreover, after killing QGIS I cannot restart the application using the symbolic link. I have to use ``/usr/local/opt/qgis3/bin/qgis3`` in the terminal. I have deleted the profile and its still the same. Any pointers?

I tried saving a shapefile after opening it and got the same issue of it never showing the window. Interestingly, using ``/usr/local/opt/qgis3/bin/qgis3`` in the terminal reopens QGIS without the need to delete the profile. Still, in order to quit the process I had to ``kill PID``. Looking at the output of ``ps`` I see that there are usually two processes, one ``/usr/local/opt/qgis3/bin/qgis3`` and another ``(QGIS)`` . The first I can kill to quit, I could not kill the latter.

This behavior occurs both when I have installed ``--with-r`` and also ``--with-r --with-grass`` (after reinstalling it worked again, but had the same issue when trying to save a file).

**Comment by ozak** [comment]
One more thing I noticed, which I guess should be a different issue is the following. Even after giving the option ``--without-qt5-webkit`` on has to use ``--no-sabdbox``. Why?

```bash
brew install osgeo/osgeo4mac/qgis3 --without-qt5-webkit --with-r --with-grass --with-saga-gis-lts
Updating Homebrew...
==> Installing qgis3 from osgeo/osgeo4mac
qt5-webkit: Must be built with `brew install --no-sandbox ...`, or install steps will fail.
Error: An unsatisfied requirement failed this build.
```

**Comment by nickrobison** [comment]
@ozak Sorry to hear that you're having problems. The first issue you reported sounds like an issue with QGIS itself, and not the Homebrew formula, you might want to try reporting the issue to them.

Regarding the the sandbox requirement. The `--without-qt5-webkit` flag has been removed from the latest version of the formula, if you want to skip the webkit dependency, you should use the `--without-pyqt5-webkit` flag.

**Comment by ozak** [comment]
I am reinstalling with ``brew install --no-sandbox osgeo/osgeo4mac/qgis3 --with-r --with-grass --with-saga-gis-lts``. Let's see what happens.

**Comment by ozak** [comment]
Ok...finally finished...the only concerning message I see is 

```bash
Warning: osgeo/osgeo4mac/qgis3 dependency gcc was built with a different C++ standard
library (libstdc++ from clang). This may cause problems at runtime.
```

Any way to ensure this is created with the same one?

**Comment by ozak** [comment]
And any operation that requires to access to the window to choose a directory or file freezes the app.

**Comment by fjperini** [comment]
@ozak You should not have any of these problems. If they persist, maybe it's best to clean your Homebrew environment and install everything again.
It is not necessary to use the option `--no-sandbox` to install QGIS.

**Comment by fjperini** [comment]
@nickrobison this issue could be closed.
