### ISSUE TITLE
armadillo, gdal2 and thus qgis3 problems

### ISSUE THREAD

**Issue by luisspuerto** [OSGeo/homebrew-osgeo4mac#456]
I've rebuilt qgis3 with the last formula and it doesn't starts. 

```
$ qgis3                                                                                   
dyld: Library not loaded: /usr/local/opt/armadillo/lib/libarmadillo.8.dylib
  Referenced from: /usr/local/opt/gdal2/lib/libgdal.20.dylib
  Reason: image not found
/usr/local/bin/qgis3: line 11: 74284 Abort trap: 6           /usr/local/opt/qgis3/QGIS.app/Contents/MacOS/QGIS "$@"
```
I've noticed that armadillo was update a couple of days ago so... I've decided to rebuild `gdal2` to check if it solved the problem. 
```
$ brew reinstall gdal2 \                       
    --with-armadillo --with-complete --with-libkml \
    --with-opencl --with-postgresql --with-unsupported
```
However in my first try I got the following [error](
https://gist.github.com/luisspuerto/5522b748dc3dc93a2ee1dd722534392b#file-gdal2-error-building-with-armadillo)

I've noticed the mentions to armadillo, so I try to reinstall it, yield the same error. 

So I tried without armadillo: 
```
$ brew reinstall gdal2 \                                                       
    --with-complete --with-libkml \
    --with-opencl --with-postgresql --with-unsupported
```

And I got the following [error](
https://gist.github.com/luisspuerto/5522b748dc3dc93a2ee1dd722534392b#file-gdal2-error-building-without-armadillo). 

I finally decided to install the bottle and now qgis3 start.

**Comment by luisspuerto** [comment]
without `armadillo` and without `unsuppoerted` I got [this](https://gist.github.com/luisspuerto/b4ca194bb8ec80295161a51e3489400c)

**Comment by rdornas** [comment]
Unfortunately I am facing the exact same problem:

> Last 15 lines from /Users/rubemdornas/Library/Logs/Homebrew/gdal2/02.make:
_LIBCPP_CONSTEXPR typename enable_if<!is_floating_point<_A1>::value, bool>::type
                                                            ~~^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[3]: *** [../o/ogrbnadriver.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
20 errors generated.
make[3]: *** [../o/ogrbnaparser.lo] Error 1
20 errors generated.
make[3]: *** [../o/ogrbnadatasource.lo] Error 1
20 errors generated.
make[3]: *** [../o/ogrbnalayer.lo] Error 1
make[2]: *** [bna-target] Error 2
make[1]: *** [sublibs] Error 2
make: *** [ogr-target] Error 2

I am running  a macOS 10.13.6 (17G65) Kernel version Darwin 17.7.0

**Comment by nickrobison** [comment]
@luisspuerto @rdornas looks like this is the same failure reported in #276. I'm not entirely sure how to get around it.

It's odd that everything would be working correctly, and then suddenly fail to compile. Did anything else change on your systems? Such as upgrading Xcode or installing the Xcode CLTs?

Do any other formulae fail to compile?

**Comment by nickrobison** [comment]
@luisspuerto It looks like you're using the Xcode 10 version of the CLT, but version 9.4 of Xcode. Is there a reason for that?

@rdornas Can you post the output of `brew config`?

**Comment by luisspuerto** [comment]
@nickrobison I really don't know, but perhaps [this](https://apple.stackexchange.com/questions/327115/beta-command-line-tools-offered-as-update-why) is the reason. I recall updating CLT a while ago and perhaps I didn't read it was a beta, or perhaps I didn't even care. I'll install the 9.4 version and I'll try again.

**Comment by luisspuerto** [comment]
I installed it and

```shell
$ brew config                                                     
HOMEBREW_VERSION: 1.7.1-308-gc9aa25e
ORIGIN: https://github.com/Homebrew/brew
HEAD: c9aa25e6d220baa65bd4c0377af9442212e8636b
Last commit: 15 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 02f39f80abf241d560b1a089a3a46116e423c566
Core tap last commit: 77 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
CPU: octa-core 64-bit sandybridge
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 9.1 build 902
Git: 2.18.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 10.0.2, 10.0.1
macOS: 10.13.6-x86_64
CLT: 9.4.1.0.1.1528165917
Xcode: 9.4.1
XQuartz: 2.7.11 => /opt/X11
```

**Comment by luisspuerto** [comment]
Now build without error 🙂

**Comment by rdornas** [comment]
@luisspuerto this is really strange because I didn't update anything recently other than by homebrew. I did what you said, now my CLT is the same as yours, however I'm still not able to open QGIS. The error is still the same as @luisspuerto reported in the initial post of this issue.

**Comment by rdornas** [comment]
Ok, now! I did `brew reinstall --force-bottle gdal2`, as a modified suggestion from [#276](https://github.com/OSGeo/homebrew-osgeo4mac/issues/276) and now I am able to open QGIS!

Thank you @luisspuerto and @nickrobison!
