### ISSUE TITLE
QGIS 3 install fails with `ModuleNotFoundError: No module named 'setuptools'`

### ISSUE THREAD

**Issue by cnowzohour** [OSGeo/homebrew-osgeo4mac#465]
When doing `brew install osgeo/osgeo4mac/qgis3` I get the following error message:
```
==> Installing osgeo/osgeo4mac/qgis3
==> Downloading https://github.com/qgis/QGIS/archive/final-3_2_2.tar.gz
Already downloaded: /Users/cnowzohour/Library/Caches/Homebrew/qgis3--3.2.2.tar.gz
==> Downloading https://files.pythonhosted.org/packages/33/bc/fa0b5347139cd9564f0d44ebd2b147ac97c36b2403943dbee8a25fd74012/virtualenv-16.0.0.tar.gz
Already downloaded: /Users/cnowzohour/Library/Caches/Homebrew/qgis3--homebrew-virtualenv--16.0.0.tar.gz
==> python3 -c import setuptools... --no-user-cfg install --prefix=/private/tmp/qgis3--homebrew-virtualenv-20180824-64552-1qrs7k0/target --single-version-externally-managed --record=installed.txt
Last 15 lines from /Users/cnowzohour/Library/Logs/Homebrew/qgis3/01.python3:
python3
-c
import setuptools, tokenize
__file__ = 'setup.py'
exec(compile(getattr(tokenize, 'open', open)(__file__).read()
  .replace('\r\n', '\n'), __file__, 'exec'))
--no-user-cfg
install
--prefix=/private/tmp/qgis3--homebrew-virtualenv-20180824-64552-1qrs7k0/target
--single-version-externally-managed
--record=installed.txt

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'setuptools'

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/osgeo/homebrew-osgeo4mac/issues

These open issues may also help:
qgis3: integration with OTB6 https://github.com/OSGeo/homebrew-osgeo4mac/pull/462
QGIS3 save fails and corrupts app https://github.com/OSGeo/homebrew-osgeo4mac/issues/455
QGIS3/GRASS: error while executing a script https://github.com/OSGeo/homebrew-osgeo4mac/issues/452
Giant cursors in Qgis3 on retina display. https://github.com/OSGeo/homebrew-osgeo4mac/issues/447
```

So it seems that the setuptools package is not being found. However, I did `pip install -U pip setuptools` before and verified I can `import setuptools` from within a `python3` session.

**Comment by adiffer** [comment]
Same here. Leads to a broken pipe. setuptools directory is there, but I don't see 'setup.py' inside.

**Comment by markamccann** [comment]
Gah.  Same here.

**Comment by swaxolez** [comment]
sigh - Same here

**Comment by swaxolez** [comment]
The following series of steps finally worked:

Brew Doctor and brew config to get my bearings

I had to create /usr/local/Frameworks and /usr/local/sbin
sudo mkdir /usr/local/Frameworks
sudo chown $(whoami):admin /usr/local/Frameworks

sudo mkdir -p /usr/local/sbin
sudo chown -R $(whoami) /usr/local/sbin

brew uninstall --ignore-dependencies python3
brew install python3
pip3 install --upgrade pip setup tools wheel

Brew Doctor revealed some problems so:
deleted 
sudo rm  /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6m-configsudo 
sudo rm /Library/Frameworks/Python.framework/Versions/3.6/bin/python3-config
sudo rm /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6-config

Ran Brew Doctor again .. then brew prune

Finally I was able to run brew install qgis3 and it worked
