### ISSUE TITLE
[suggestion] Formulae renaming ?

### ISSUE THREAD

**Issue by Emic37** [OSGeo/homebrew-osgeo4mac#466]
Hello, 

I am not sure I can do it myself and open a pull request, so I make you this suggestion:

In my opinion, the name of the qgis' formulae no longer make sense : 
- "qgis2-ltr" formula = QGIS 2.14 = this version is no longer supported. 
- "qgis2" formula is now ltr version, but in the future, qgis3 probably will become ltr version.
- "qgis3" formula is now QGIS 3 standard version, but it will probably become the ltr version.

So, I think it would be better to rename formulae to correspond to the official QGIS packages like it's described [here](https://www.qgis.org/en/site/forusers/alldownloads.html) : 
- "qgis-ltr" = ltr version, actual formula "qgis2" = QGIS 2.18.x branch
- "qgis" = standard release = actual formula "qgis3" = QGIS 3.2.x branch
- evently "qgis-dev" = QGIS master branch

This would allow to update formulae without the need to create new formulae for each new QGIS' version and more clarity for user.

**Comment by 3nids** [comment]
I think we should avoid removing version numbers.
Doing a brew upgrade leading to a major version upgrade is a bad idea for me.
I would stick to version numbers.
qgis2-ltr => 2.18
qgis2 => deprecate
qgis3 => current release
qgis3-ltr => future ltr to come
qgis3-dev => master (also you can use -HEAD on current formula)

**Comment by fjperini** [comment]
@Emic37 I agree. It would be good to just leave `qgis2-ltr=2.18` and `qgis3=3.X.x`. The others are not necessary. And wait to make the change to `qgis3-ltr` when it reaches `3.4.4`.

**Comment by Emic37** [comment]
@3nids, @fjperini 
 > I think we should avoid removing version numbers.
Doing a brew upgrade leading to a major version upgrade is a bad idea for me.

I may be wrong but it's already arrived : `2.14`, `2.16`, `2.18` are all major versions installed and updated with `qgis2` formulae. And 2.14 and 2.18 are LTR version installed with `qgis2-ltr`. So doing a brew upgrade leads to a major version upgrade.

The next ltr version will be `3.4.5` but the next one? This will probably be `3.10.5` ; two different major versions and however installed with `qgis3-ltr` formulae. Or an other `qgis3.10-ltr` formulae will be created ? 

So, I understand your opinion but I stay convinced the easier way is to stick to the [qgis installers](https://www.qgis.org/en/site/forusers/alldownloads.html) : 

- qgis
- qgis-ltr

It's simple and standing solution. And it doesn't prevent to place `info` command before upgrade.

**Comment by fjperini** [comment]
@Emic37 I think it would be best to have

- `qgis2-ltr` => 2.18.28 (there are things that change in QGIS 3 that's why many will continue using it)
- `qgis3-ltr` => 3.4.x
- `qgis3` => current release

I am preparing this, soon `qgis2` (must be eliminated and only `qgis2-ltr` should be preserved) will arrive at FF (feature freeze, end of development phase).

What do you think @nickrobison?

**Comment by 3nids** [comment]
@fjperini I agree with your point of view!

**Comment by fjperini** [comment]
@3nids @Emic37 Maybe it would be better:
- `qgis2-ltr` => 2.18.28
- `qgis3-ltr` => 3.4.x
- `qgis` => current release

To not be eliminating every time a new LTR comes out.

For example, we will have to eliminate `qgis2`.

**Comment by fjperini** [comment]
@3nids @nickrobison If you can assign me as a Collaborator, so I help you a little more, I promise not to break anything :sweat_smile:

**Comment by Emic37** [comment]
@fjperini I like your latest proposition. And it gave me the idea to look for another formula to see how it made... 

In fact, you would that people who want use qgis 2.18 can install it with homebrew. So I looked for `python` formulae and it's organised like this : 

- `python` (for current release)
- `python@X` (for previous version)

So, maybe it would good to make like this for qgis : 

- `qgis-ltr` (for latest ltr)
- `qgis-ltr@2.14`, `qgis-ltr@2.18`, ... (for previous deprecated qgis-ltr)
- `qgis` (for current release)

`qgis` and `qgis-ltr` are standing. It's the permanent formula to simply install the latest qgis versions and the people wanting to use a deprecated version use `qgis-ltr@X.XX` formulae.

**Comment by fjperini** [comment]
@Emic37 @3nids Yes, I think it will be better that way. This will avoid rename or delete formulas in the future.

In minutes I apply these changes!

**Comment by Emic37** [comment]
Yes, like this, there are main formula for current releases and the others. And actuel `qgis2` is not deleted but become the new `qgis-ltr@2.14`. 
Thanks to you.

**Comment by fjperini** [comment]
@Emic37 Yes, `qgis2` become the new `qgis-ltr@2.18`.

**Comment by Emic37** [comment]
Yes sorry. I would say `qgis2-ltr` become `qgis-ltr@2.14`.

**Comment by fjperini** [comment]
In short, it would be like that:

```
qgis2-ltr => qgis-ltr@2.14
qgis2 => qgis-ltr@2.18
qgis3 => qgis (current release)
new => qgis-ltr (for latest ltr)

```

**Comment by fjperini** [comment]
@Emic37 @3nids There was a problem in Circle CI when renaming a formula or uploading/updating a file. Fixed!

The new formulas:

```
=> qgis-ltr@2.18
=> qgis-ltr (for latest ltr)
=> qgis (current release)
```

In this way only a new formula for QGIS will be added, for example: when QGIS 3 reaches its end of the development phase (FF) we will add `qgis-ltr@3.x`.

**Comment by fjperini** [comment]
@3nids @nickrobison You can put me as a collaborator, to help you with the updating of the formulas.

**Comment by nickrobison** [comment]
@jfperini, yup, adding you as a collaborator is long overdue.

**Comment by 3nids** [comment]
Hey, sorry I've done that already yesterday without further notice. Indeed long overdue. Thanks a lot for your work!

**Comment by fjperini** [comment]
@3nids The invitation has not arrived, can you do it again?

Thank you!

**Comment by fjperini** [comment]
@3nids Great! 🎉 
The formulas have already been renamed, we can close this issue.
@Emic37 Thanks for contributing!

**Comment by Emic37** [comment]
@fjperini  Thanks for your job. It's perfect ! 👍
