### ISSUE TITLE
QGIS3 Install issue Error: SHA256 mismatch

### ISSUE THREAD

**Issue by miguelangelperg** [OSGeo/homebrew-osgeo4mac#468]
When:
brew install qgis3 --with-3d --with-gpsbabel --with-grass --with-isolation --with-qspatialite --with-r --with-saga-gis-lts

Install QGIS3 fails and shows the following messages:

==> Installing qgis3 from osgeo/osgeo4mac
 ......./......
==> Downloading https://github.com/jswhit/pyproj/archive/master.zip
Already downloaded: /Users/miguelmbp/Library/Caches/Homebrew/qgis3--pyproj--1.9.5.1.zip
Error: SHA256 mismatch
Expected: 6611ca878ec6de71115f7705f7fcb3a900999ef1fa9616376c2de63edd3a7841
Actual: 8469e71591dd5171eedb21b127afeac127704280d6000088df16a1504299b62d
Archive: /Users/miguelmbp/Library/Caches/Homebrew/qgis3--pyproj--1.9.5.1.zip
To retry an incomplete download, remove the file above.

**Comment by luisspuerto** [comment]
for me is the same if I download the pyproj master: 

```
shasum -a 256 ~/Downloads/pyproj-master.zip                               
8469e71591dd5171eedb21b127afeac127704280d6000088df16a1504299b62d  /Users/lpuerto/Downloads/pyproj-master.zip
```

**Comment by miguelangelperg** [comment]
Gracias de nuevo

Este es mi correo habitual. Por eso tardé en ver tu respuesta. Al dirigirme
a ti desde tu web, adoptó mi cuenta de Apple

**Comment by luisspuerto** [comment]
@miguelangelperg you posted your message in github so everyone can see it, I really don't know if it is what you meant.

**Comment by fjperini** [comment]
@miguelangelperg @luisspuerto I already solve this!

**Comment by luisspuerto** [comment]
@PiotrKrosniak please update because it's fixed for me. 

```rb 
# fix for Python3.7
  resource "pyproj" do
    url "https://github.com/jswhit/pyproj/archive/40bc5389e7ee8212d9f5a790f582970007e367e1.zip"
    sha256 "d38ff62738460a6d986c132999fcb83256e35f3b649273304392f961613d731f"
    version "1.9.5.1"
  end
```

**Comment by luisspuerto** [comment]
Why don we implement something like this? https://probot.github.io/apps/stale/

**Comment by fjperini** [comment]
Always with good ideas @luisspuerto :smiley:
