### ISSUE TITLE
GDAL compile flag --with-openjpeg no longer takes parameter value

### ISSUE THREAD

**Issue by philvarner** [OSGeo/homebrew-osgeo4mac#469]
Somewhere between 2.1 and 2.3, the GDAL compile script changed so that the --with-openjpeg no longer takes a parameter value. E.g., `--with-openjpeg=HOMEBREW_PREFIX` should now just be `--with-openjpeg`.  

I believe the correct code change would be in `Formula/gdal2.rb` to move the entry `openjpeg` out of the `supported_backends` array, and instead add an entry `--with-openjpeg` to the `args` array in the `configure_args` method.

[https://trac.osgeo.org/gdal/ticket/7074]
[https://github.com/OSGeo/gdal/commit/3e762d9c94]

**Comment by nickrobison** [comment]
@philvarner Thanks for the suggestion, this change has been applied!
