### ISSUE TITLE
 brew install osgeo/osgeo4mac/mrsid-sdk fails

### ISSUE THREAD

**Issue by newmanw** [OSGeo/homebrew-osgeo4mac#475]
$ brew install osgeo/osgeo4mac/mrsid-sdk
==> Installing mrsid-sdk from osgeo/osgeo4mac
Error: Formula expects to locate the following archive:
  MrSID_DSDK-9.5.1.4427-darwin14.universal.clang60.tar.gz

in the HOMEBREW_CACHE directory:
  /Users/geouser/Library/Caches/Homebrew

Copy archive to cache or create a symlink in cache to archive:
  ln -sf /path/to/archive $(brew --cache)/
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:49:in `write': Broken pipe (Errno::EPIPE)
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:49:in `puts'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:49:in `rescue in block (3 levels) in safe_fork'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:31:in `block (3 levels) in safe_fork'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:30:in `fork'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:30:in `block (2 levels) in safe_fork'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:27:in `open'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:27:in `block in safe_fork'
	from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:26:in `safe_fork'
	from /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:719:in `build'
	from /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:311:in `install'
	from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:321:in `install_formula'
	from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:253:in `block in install'
	from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:251:in `each'
	from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:251:in `install'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
Error: An exception occured within a build process:
  SystemExit: exit

**Comment by fjperini** [comment]
@newmanw It seems necessary to download the file previously and place the file in `~/Library/Caches/Homebrew`: 

```
ln -sf /path/to/MrSID_DSDK-9.5.1.4427-darwin14.universal.clang60.tar.gz $(brew --cache)
```
