### ISSUE TITLE
brew install gdal2 fails on OSX Mojave

### ISSUE THREAD

**Issue by juanmayorgahenao** [OSGeo/homebrew-osgeo4mac#482]
Hi guys, 

I'm having trouble installing gdal2 on OSX Mojave. 
`brew install gdal2 --with-armadillo \
> --with-complete --with-libkml --with-unsupported`

returns 

`==> Downloading http://download.osgeo.org/gdal/2.3.1/gdal-2.3.1.tar.gz
Already downloaded: /Users/JuanMayorga/Library/Caches/Homebrew/downloads/0e52abbbcedfe1f9296bd5b0806416e7290c2cf96224125a7fbf387dc6fb97a3--gdal-2.3.1.tar.gz
==> Patching
patching file swig/java/GNUmakefile
==> ./configure --prefix=/usr/local/Cellar/gdal2/2.3.1 --mandir=/usr/local/Cella
==> make
Last 15 lines from /Users/JuanMayorga/Library/Logs/Homebrew/gdal2/02.make:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:563:63: error: definition or redeclaration of 'value' cannot name the global scope
_LIBCPP_CONSTEXPR typename enable_if<!is_floating_point<_A1>::value, bool>::type
                                                            ~~^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[1]: *** [gnmgenericnetwork.lo] Error 1
20 errors generated.
make[3]: *** [../o/gnmdbnetwork.lo] Error 1
make[2]: *** [db-install-obj] Error 2
make[1]: *** [sublibs] Error 2
20 errors generated.
make[1]: *** [gnmlayer.lo] Error 1
make: *** [gnm-target] Error 2
make[1]: *** [gxf-install-obj] Error 2
make: *** [frmts-target] Error 2

`

I have absolutely no idea what is going on. 

Any ideas?

thank you

**Comment by juanmayorgahenao** [comment]
This is my output from `brew doctor`
 `Juans-iMac:~ JuanMayorga$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Library/Frameworks/Python.framework/Versions/3.6/bin/python3-config
  /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6-config
  /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6m-config
  /Library/Frameworks/GDAL.framework/Programs/gdal-config

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/fakemysql.h
  /usr/local/include/fakepq.h
  /usr/local/include/fakesql.h
  /usr/local/include/geos/algorithm/ExtractLineByLocation.h
  /usr/local/include/geos/algorithm/LengthIndexOfPoint.h
  /usr/local/include/geos/algorithm/LengthIndexedLine.h
  /usr/local/include/geos/algorithm/LengthLocationMap.h
  /usr/local/include/geos/algorithm/LinearGeometryBuilder.h
  /usr/local/include/geos/algorithm/LinearIterator.h
  /usr/local/include/geos/algorithm/LinearLocation.h
  /usr/local/include/geos/algorithm/LocationIndexOfLine.h
  /usr/local/include/geos/algorithm/LocationIndexOfPoint.h
  /usr/local/include/itcl.h
  /usr/local/include/itcl2TclOO.h
  /usr/local/include/itclDecls.h
  /usr/local/include/itclInt.h
  /usr/local/include/itclIntDecls.h
  /usr/local/include/itclMigrate2TclCore.h
  /usr/local/include/itclTclIntStubsFcn.h
  /usr/local/include/mysqlStubs.h
  /usr/local/include/odbcStubs.h
  /usr/local/include/pqStubs.h
  /usr/local/include/tcl.h
  /usr/local/include/tclDecls.h
  /usr/local/include/tclOO.h
  /usr/local/include/tclOODecls.h
  /usr/local/include/tclPlatDecls.h
  /usr/local/include/tclThread.h
  /usr/local/include/tclTomMath.h
  /usr/local/include/tclTomMathDecls.h
  /usr/local/include/tdbc.h
  /usr/local/include/tdbcDecls.h
  /usr/local/include/tdbcInt.h
  /usr/local/include/tk.h
  /usr/local/include/tkDecls.h
  /usr/local/include/tkPlatDecls.h

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  gdal
  git
  python
  r
  texi2html

Warning: An outdated version (2.6.4) of Git was detected in your PATH.
Git 2.14.3 or newer is required for Homebrew.
Please upgrade:
  brew upgrade git`

**Comment by nickrobison** [comment]
@juanmayorgahenao We've made some changes to the GDAL formula and upgraded it to the latest version. Is this issue still occurring?

**Comment by fjperini** [comment]
@nickrobison @juanmayorgahenao I had the same problems in Mojave. I think we have to apply more changes (see #504 #505)

**Comment by PeterPetrik** [comment]
works for me on Mojave

**Comment by nickrobison** [comment]
@juanmayorgahenao Have you been able to resolve this issue? Hopefully the changes in #504 will resolve things.

**Comment by juanmayorgahenao** [comment]
@nickrobison Yes indeed. Thank you
