### ISSUE TITLE
oracle-client-sdk - update filenames and checksum

### ISSUE THREAD

**Issue by IvanLucena** [OSGeo/homebrew-osgeo4mac#486]
I am getting this error:

```
$ brew reinstall qgis3 --with-oracle
==> Reinstalling osgeo/osgeo4mac/qgis3 --with-grass --with-oracle
==> Installing dependencies for osgeo/osgeo4mac/qgis3: oracle-client-sdk
==> Installing osgeo/osgeo4mac/qgis3 dependency: oracle-client-sdk
==> Downloading https://osgeo4mac.s3.amazonaws.com/src/dummy.tar.gz
######################################################################## 100.0%
Error: Formula expects to locate the following archive:
  instantclient-basiclite-macos.x64-12.2.0.1.0.zip

Copy archive to cache or create a symlink in cache to archive:
  ln -sf /path/to/archive $(brew --cache)/
```
And I tried to apply the suggested workaround by downloading the files from oracle.com. The problem is that this particular filename (version) is not available anymore at:

https://www.oracle.com/technetwork/topics/intel-macsoft-096467.html

It seems like the solution would be to change the formula by updating the file names and checksum.

**Comment by nextstopsun** [comment]
Same issue here. 
I can update checksums and do a PR if those files are really outdated.

**Comment by nickrobison** [comment]
@IvanLucena @nextstopsun Sorry for the delayed response to this issue, if either of you would be willing to open a PR to resolve this, that would be great!

**Comment by IvanLucena** [comment]
I can do that. No problem.

**Comment by IvanLucena** [comment]
Here is the problem. My PR did not pass the CI tests.

The formula oracle-client-sdk intentionally downloads a dummy.tar.gz to gives the user an error message and a chance to go to Oracle website, sign in and download the files themselves.  

I don't see a problem with that. Actually, I don't see a solution to that error. 

The script cannot download directly from Oracle without user login-in and license would not allow homebrew-osgeo4mac (and GitHub ultimately) to be a distributor of those files.

So if you approve the PR I will merge it as it is.

That formula doesn't run automatically in all CI test? Does it?

**Comment by IvanLucena** [comment]
Should I got ahead and merge it?

**Comment by nickrobison** [comment]
@IvanLucena I merged #511 a couple of days ago. Are you still encountering the error?

**Comment by IvanLucena** [comment]
Thanks, Nick!

The installation works perfectly in regards to Oracle client SDK but I am afraid I didn't clean my previous attempts correctly. Any suggestion on how to start from fresh? Deleting some stuff maybe.

When I run QGIS is I am getting errors like that:

```
  File "/usr/local/Cellar/qgis3/3.4.1/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 219, in initInterface
    iface = wrapinstance(pointer, QgisInterface)
TypeError: wrapinstance() argument 2 must be sip.wrappertype, not sip.wrappertype

```

And 

```
Couldn't load plugin 'db_manager' due to an error when calling its initGui() method 

AttributeError: 'NoneType' object has no attribute 'mainWindow' 
Traceback (most recent call last):
  File "/usr/local/Cellar/qgis3/3.4.1/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 344, in startPlugin
    plugins[packageName].initGui()
  File "/usr/local/Cellar/qgis3/3.4.1/QGIS.app/Contents/MacOS/../Resources/python/plugins/db_manager/db_manager_plugin.py", line 41, in initGui
    self.iface.mainWindow())
AttributeError: 'NoneType' object has no attribute 'mainWindow'

```

And some other that doesn't seem to be related to Oracle, even though db_manager is mentioned.

Can you help with that, I mean any advice?

Thanks.

**Comment by IvanLucena** [comment]
Never mind. I figured out what was the problem. I had too many version of SIP installed. 2 From brew and one built from source. Now QGIS opens clean without any error but crashes when I open the About box. :(

**Comment by nickrobison** [comment]
Glad you hear that it's working for you, thanks for the contribution!
