### ISSUE TITLE
Error when installing saga-gis-lts --with-app

### ISSUE THREAD

**Issue by nextstopsun** [OSGeo/homebrew-osgeo4mac#509]
Seems like the app doen't get built.

My output looks like this
```
==> ./configure --prefix=/usr/local/Cellar/saga-gis-lts/2.3.2_1 --disable-openmp --disable-libfire --disable-triangle --enable-shared --enable-debug --disable-triangle --
==> make install
==> Downloading https://osgeo4mac.s3.amazonaws.com/src/saga_gui.icns
Already downloaded: ~/Library/Caches/Homebrew/downloads/0a8bcdf92c0b2329108ec0fb0a65415e4d4016f60e94b9fc953c1fa7f75fa892--saga_gui.icns
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory - SAGA.app
```

**Comment by fjperini** [comment]
@nextstopsun I had the same problem and @nickrobison told me at that moment:


> Regarding the saga-gis-lts issue, that formula no longer compiles on High Sierra due to its age and recent updates to the MacOS compiler, if you build it without the --with-app flag (the app isn't needed for QGIS integration) it should download a pre-built bottle that will work correctly.

**Comment by nextstopsun** [comment]
@fjperini I've built it from source - seems ok except that final bit with app itself

**Comment by fjperini** [comment]
@nextstopsun It will be built well, it just does not build `SAGA.app`

**Comment by fjperini** [comment]
@nextstopsun you can now use the option `--with-app`
