### ISSUE TITLE
QGIS 3.4? 

### ISSUE THREAD

**Issue by luispuerto** [OSGeo/homebrew-osgeo4mac#516]
Hey! 

There is any reason because we haven't update to QGIS 3.4? Just asking... I'm a little bit lost with all the branches and test we did the last two months so, I don't know if it's just as easy as change the version number in the formula or there are other problems we have to fix before. 

CC/ @fjperini @nickrobison 

PS/ This just came to my mind after reading [this thread](http://osgeo-org.1560.x6.nabble.com/QGIS-3-4-macOS-still-doesn-t-install-GRASS-properly-sigh-td5384037.html). I'm still wondering why QGIS isn't more involved is this tap so QGIS for macOS is easier to install.

**Comment by luispuerto** [comment]
well, to be honest, the confusion is also mine... I was in another branch of homebrew-osgeo4mac on my computer that used to update to a previous version of QGIS. 

I think I'll update everything in the next hour or so. Thanks and sorry to bother!!!

**Comment by fjperini** [comment]
@luispuerto Reading!

> PS/ This just came to my mind after reading this thread. I'm still wondering why QGIS isn't more involved is this tap so QGIS for macOS is easier to install.

They were missing sticks and it was a complete discussion. Ha!

@luispuerto, you gave a little calm. Ha! And yes, I think using Homebrew is the best option, although few know that QGIS is available.
