### ISSUE TITLE
Installing onto Mac OS El Capitan Xcode fail

### ISSUE THREAD

**Issue by dominijk** [OSGeo/homebrew-osgeo4mac#524]
On Mac El Capitan i run into trouble
qt5-webkit: A full installation of Xcode.app is required to compile this software. Installing just the Command Line Tools is not sufficient. Xcode can be installed from the App Store. but i can't use current version as not compatible with El Capitan, any other options..?

**Comment by PeterPetrik** [comment]
older XCode can be downloaded from Apple Developer Downloads if you have access. But other homebrew packages are not compatible with 10.11 either , so I was not able to make it work. Best to upgrade to 10.13 at least

**Comment by nickrobison** [comment]
@dominijk What @PeterPetrik suggested is correct. Unfortunately, we're not supporting El Cap at this time. If you run into some specific errors, we can try to provide some guidance, but I can't guarantee that anything will work, sorry.

**Comment by dominijk** [comment]
Thanks all, I couldn't find away round this. For other ending up here through google the QGIS official mac download (3.4) worked for me having followed the instructions to install the Python version required
