### ISSUE TITLE
gdal2 can't read xml file (expat missing)

### ISSUE THREAD

**Issue by Jmuccigr** [OSGeo/homebrew-osgeo4mac#526]
Right after I upgraded to the latest version of gdal2, I started getting the following error:

`ERROR 6: OGR/GeoRSS driver has not been built with read support. Expat library required`

This is the command that generates it:

`ogr2ogr -f csv sheet.csv sheet.xml`

Not sure where to go with this.

**Comment by fjperini** [comment]
@Jmuccigr Maybe you need to change the permissions to the file:

```
chmod 777 sheet.csv
```

To see the supported formats:
```
ogr2ogr --formats
```
