### ISSUE TITLE
missing bottle for saga-gis-lts

### ISSUE THREAD

**Issue by PeterPetrik** [OSGeo/homebrew-osgeo4mac#529]
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "saga-gis-lts"
Download failed: https://dl.bintray.com/homebrew-osgeo/osgeo-bottles/saga-gis-lts-2.3.2_2.mojave.bottle.tar.gz

**Comment by nickrobison** [comment]
@PeterPetrik @fjperini Done!
