### ISSUE TITLE
Proposal: Migrate CI builds from Travis to Circle CI

### ISSUE THREAD

**Issue by nickrobison** [OSGeo/homebrew-osgeo4mac#541]
I'd like to promise moving our current CI infrastructure from Travis to [Circle CI](https://circleci.com/). There are two main reasons for wanting to do so:

1. There have been multiple requests to start building against both newer compilers, as well as building OS native bottles, instead of simply duplicating the Sierra bottle across OSes.

2. Since `brew linkapps` is deprecated, we need some way to packaging up the GUI applications (primarily QGIS) into a more consumable format. Since `brew casks` are a different format and build process, we need a structured way of handling this.

Due to the way bottles are merged into formulae, we need to add everything in a single commit, otherwise the versions and revisions will get out of sync. That means we need a way to have a build pipeline which builds/tests the formulae on each OS, then in a subsequent step upload the new bottles to bintray and merge them into the formula. In addition, for specific GUI applications, we'll need to build/update the cask formulae as well.

In digging around, I've been unable to find a way to do this in Travis without resorting to uploading files to bintray and manually retrieving them in a later step. This is because Travis doesn't persist artifacts between stages. Likewise, build caches won't work because a different cache is generated for each OS, so we don't have the ability to merge all the bottles after building them.

It seems like Circle CI's [workflows](https://circleci.com/docs/2.0/workflows/) would be a perfect fit for this type of problem. Since you can persist files between stages, we can have a parallel build/test phase, followed by a single merge/upload stage.

While Travis has been working great for us, for a long time, it seems like the types of issues we're running into are not well supported in their current architecture. So I would propose creating a CI process, on CircleCI, and running it 'dark' (e.g. no bottle uploading or committing) for a couple of days/weeks to ensure we can successfully build some of our more popular and complicated formulae. Once we've tested that it works, we'll switch Travis dark and start uploading bottles from CircleCI. We'll leave both running for a while, that way if something goes wrong, we can always fall back to Travis and keep things working.

At this point, there are a couple of challenges that I foresee:

1. Lots of the formulae are old and most likely will not build on newer versions of Xcode (saga-gis-lts definitely won't), we have to decide how much effort we want to invest in keeping old formulae building against newer OSes. I for one would like to dump some of the really old stuff (e.g. gdal1, grass6, orfeo5, etc.), but things like QGIS2 we definitely need to keep working. I'm sure there's a way to keep the build pipeline running, even if one of the OS builds fails (e.g. use the Sierra bottles if High Sierra or Mojave fails to build), but we'll have to experiment a bit.

2. I'm not entirely sure if we're able to do the migration, primarily because we're part of the OSGEO organization (on both Github and Travis), and I'm not sure if there are any concerns or restrictions about setting up our own build account. Perhaps @rouault could offer some insights. I'm also not an owner of the repo, so some things I may not be able to move without help from folks like @3nids.

3. MacOS build slots are not, by default, available for OS projects, I'll need to reach out to the CircleCI folks to see if they'd be willing to allocate some for us.

The end result, from a user's perspective, should be completely transparent. We'll still serve the bottles from Bintray, but they should now have native bottles for their current OS. For developers, we'll hopefully be able to get more builds tested faster and perhaps add the capability to test custom flag operations, in order to help debug issues with custom source builds.

Any thoughts or concerns from anyone? @fjperini @3nids @luispuerto @dakcarto @nextstopsun @jonathanmccormack

**Comment by fjperini** [comment]
@nickrobison It is very good that you are working on it, I think it will solve what you have mentioned. Hopefully you can count on the account in CircleCI.
Once done we can go testing everything. And yes, there are formulas that must be removed.

**Comment by luispuerto** [comment]
Sounds great to me —from my lack of knowledge of some of those things, even more if we can get an OS slot for macOS on Circle CI. 

Just for clarification, what we pretend here is to build in Circle CI all bottles and then link those bottles on a cask? If that is the idea, and the bottles are going to have all the bells and whittles in the same way as the official build have, it's really AWESOME! 

I would love to have QGIS 3 with just `brew cask install qgis3` as a result of this workflow.

**Comment by luispuerto** [comment]
PS/ for sure we need to keep QGIS2, even more if grass is still faulty in QGIS3 —at least in our case here still is.

**Comment by nickrobison** [comment]
@luispuerto We're definitely NOT going to get rid of QGIS2, if we get rid of anything at all, it'll be really old versions that don't compile on Mac OS anymore, so fear not!

I haven't fully looked at what it'll take to setup QGIS as a bottle, but the goal would be to use the existing formulae and simply package it in cask format to simplify installation. It'll take some experimenting to get it right though.

**Comment by fjperini** [comment]
@nickrobison What is the time limit for Circle CI?

**Comment by fjperini** [comment]
I have completed the integration of Circle CI, now it is by default 🎉
