### ISSUE TITLE
brew install osgeo/osgeo4mac/qgis3 fails ... usr/local/Cellar/qgis3 folder is missing

### ISSUE THREAD

**Issue by rkalasek** [OSGeo/homebrew-osgeo4mac#553]
after serious troubles with the qgis.org version of 3.4.2 on mac os 10.14.1 i have just tried to install homebrew version using brew install osgeo/osgeo4mac/ with qgis3 formula. everything looked fine so far. but finally i couldn't find a qgis-folder in /Cellar. 
during a second attempt with bew install i was tracking the Cellar folder. the folder exists for most of the install process and the subfolders and files were modified during the process. at the end that folder is missing again.

**Comment by PeterPetrik** [comment]
@rkalasek not related to the ticket, but you can also try https://lutraconsulting.github.io/qgis-mac-packager/ which is based on homebrew dependencies?

**Comment by rkalasek** [comment]
had a look into tho logs with the konsole.app already. there are tons of logs unfortunately - and some of them prove that something has been created in /usr/local/Cellar/qgis3/3.4.2_1. but right now there is nothing left. @ fjperine: will try the way you suggested.

drwxr-xr-x  3 xxx  staff  96 10 Dez 11:35 python@2
drwxr-xr-x  3 xxx  staff  96 10 Dez 11:38 qca
drwxr-xr-x  3 xxx  staff  96 10 Dez 11:39 qhull
drwxr-xr-x  3 xxx  staff  96 10 Dez 11:39 qjson
drwxr-xr-x  3 xxx  staff  96 10 Dez 11:38 qscintilla2
drwxr-xr-x  3 xxx  staff  96 10 Dez 11:36 qt
drwxr-xr-x  3 xxx  staff  96 10 Dez 11:38 qt5-webkit
drwxr-xr-x  3 xxx  staff  96 10 Dez 11:38 qtkeychain
drwxr-xr-x  3 xxx  staff  96 10 Dez 11:38 qwt
drwxr-xr-x  3 x  staff  96 10 Dez 11:39 qwtpolar

**Comment by fjperini** [comment]
@rkalasek It really is a problem to have another version of Python installed outside of Homebrew. You could try installing Python v3.6.x, for example:

```
$ brew unlink python
```

```
$ brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/f2a764ef944b1080be64bd88dca9a1d80130c558/Formula/python.rb
```
For the use of 3.7.0:

```
$ brew switch python 3.7.1
```

And if need 3.6.5 switch with:

```
brew switch python 3.6.5_1
```


If you decide to do this: removed an orphaned Python version in `/Library/Frameworks/Python.framework`. Another thing to keep in mind is to make sure that there is no other version of Python (Anaconda installed?) in PATH: if during installation another Python installation is first in the path, it will use that one.

Try these changes, anyway ... if the installation is complete, you should have `qgis3` in `/Cellar`.

**Comment by rkalasek** [comment]
@PeterPetrik: not off topic at all ! ! !  
at some desperate moment i've been giving up my efforts with homebrew and swiched to https://lutraconsulting.github.io/qgis-mac-packager/  ... as you suggested. 
and ... it works ! !  at least as it concerns the initial problem i had ([https://gis.stackexchange.com/questions/301460/qgis-3-4-0-system-freeze-on-macos-10-14](url)o and [https://issues.qgis.org/issues/20381#change-95741](url)). 
but: now i ended up with the python 3.6 - 3.7 issue. 
@fjperini: thx for your posts ! ... i am not shure wether your suggestions cover my current situation. qgis is working - qgis python console says verion is 3.7.1. when opend in mac termina python version still is 3.6.1. both of them seem to work fine - each in it's own context. should i switch over to 3.7.1. via brew switch ? 
pretty confusing: `ls -l /usr/local/bin/python*`returns ../Cellar/python@2/2.7.15_1/bin/python - so there are three of them right now and within qgis 3.4.2 python seems to be there: Applications/QGIS3.4.2.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/.
 i couldn't figure out what the `brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/f2a764ef944b1080be64bd88dca9a1d80130c558/Formula/python.rb` migth cause in that situation.

**Comment by fjperini** [comment]
@rkalasek You only need one version of Python 3 (Homebrew), it does not matter which one.

The important thing is not to have another python as first in PATH, or some obsolete Python in /Library`/Frameworks/Python.framework`

**Comment by nickrobison** [comment]
@rkalasek Are you able to post a link to your `brew gist-lists qgis3`? It sounds like there's a probably with the installation process, which is causing homebrew to roll back the installation.

Also, could you post the output of `brew doctor` and `brew logs`?

**Comment by rkalasek** [comment]
@nickrobison - since i am pretty new to homebrew  i just can try my best. the output covers 32 files. the web interface provides different kinds of link types but just the "embedded" type is active ... the link:    https://gist.github.com/rkalasek/1e12498d547621cbeb1b58e436c5955e
as far as i can see this one covers doctor and config files as well. if there are additional brew logs i would need information about where to find them. thx in advance. 
the "rollback" seems to affect just some of the "modules" since f.i. gdal, postgis2, proj, qjson ... folders are still existing in /cellar.

**Comment by fjperini** [comment]
@rkalasek Now you can try the new revision of the formula.

Some useful suggestions.

In case you have installed another version of Python (Anaconda, Miniconda or if you used the installer provided by python.org).
QGIS will use the first Python that is in its PATH, so the installation may fail.

If the installation failed due to the problem reported in https://github.com/OSGeo/homebrew-osgeo4mac/issues/520

Try after doing:

       $ brew unlink python && brew link --force python

       $ $PATH (Check that there is no other version)

If the installation failed due to the problem reported in https://github.com/OSGeo/homebrew-osgeo4mac/issues/510

Try after doing:

       $ brew reinstall ninja gsl sip six bison flex pkg-config python qt pyqt qscintilla2

       $ brew link --overwrite pyqt

Other Notes:

An installation that failed previously may have created this link

       /usr/local/lib/python3.7/site-packages/PyQt5/uic/widget-plugins/qgis_customwidgets.py

you will need to delete it.

Also make sure that the folder `/usr/local/Cellar/qgis` does not exist if the installation fails.

It is also recommended remove the Homebrew Cache `$ rm -rf $(brew --cache)` (`~/Library/Caches/Homebrew`) and the temporary build files in `/tmp`.

**Comment by fjperini** [comment]
@rkalasek this issue is closed, the problem should no longer be.

If the problem persists after all the changes that were made, it is advisable to reinstall your Homebrew.
