### ISSUE TITLE
Who said that these holidays are not a problem?

### ISSUE THREAD

**Issue by fjperini** [OSGeo/homebrew-osgeo4mac#575]
Happy holidays people! :christmas_tree: :gift:

I hope there are not so many problems to solve, we need a vacation :smile: If we have solved many @nickrobison @luispuerto @3nids

Hug from a distance!

p/d: there will be so many issues, one more is not bad 😁

**Comment by luispuerto** [comment]
Yeah!!!

Happy holidays guys! 🎄🎁🎊🎉🎈📯

Wherever and whoever you are spending them with!

**Comment by luispuerto** [comment]
@fjperini I will open an issue. 😂
