### ISSUE TITLE
QGIS-26 on Yosemite can not find fcgi

### ISSUE THREAD

**Issue by ajshunter** [OSGeo/homebrew-osgeo4mac#58]
I have recently upgraded to Yosemite and QGIS 2.6 was working. However, following a brew update QGIS 2.6 failed. I have subsequently removed it and tried to reinstall.

I have upgraded XCode and the command line tools as suggested by a number of apple discussions.

Brew says it does not understand the kern.osversion:

brew gist-logs --config --doctor qgis-26
couldn't understand kern.osversion `14.0.0'
https://gist.github.com/2cc0ee54a1bba3a8aa97

My brew configuration is:

HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew.git
HEAD: 5366a374c5b4d1ffeff900c28ac78eb06a2a9714
Last commit: 6 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: dual-core 64-bit penryn
OS X: 10.10-x86_64
Xcode: 6.1
CLT: 6.1.0.0.1.1413057044
couldn't understand kern.osversion `14.0.0'
GCC-4.2: build 5666
Clang: 6.0 build 600
X11: 2.7.7 => /opt/X11
System Ruby: 2.0.0-481
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby

I'm not convinced it is a brew problem, but haven't been able to find anything via Apple that resolves this. Any suggestions you can offer would be appreciated.

Thanks
Andrew

**Comment by michaelkirk** [comment]
For what it's worth, I just built qgis-26 and qgis-26 --HEAD on yosemite without issue.

**Comment by dakcarto** [comment]
@michaelkirk Thanks for the update
