### ISSUE TITLE
Problem when running brew upgrade qGis3

### ISSUE THREAD

**Issue by miguelangelperg** [OSGeo/homebrew-osgeo4mac#581]
Problem when running brew upgrade qGis3
Brew fails in osx Mojave when it tries to install R as dependency.
I have R installed from the repository: sethfore on two computers.
When I run brew upgrade qgis3 on the first, with Osx hight saw the process ends without errors. 
In the second, with Osx Mojave, it fails. Homebrew says: first uninstall R.
Qgis3 does not work after trying the upgrade.

Any solution? Thank you

**Comment by luispuerto** [comment]
You can try... 

```shell
$ brew uninstall qgis3 && brew uninstall r 
$ brew install sethrfore/r-srf/r --with-openblas --with-java --with-libtiff --with-cairo
$ brew install qgis3 --with-r --with-grass --with-orfeo6 --with-saga-gis-lts
```

Or whatever flags you want to use. But that worked for me.

**Comment by fjperini** [comment]
@miguelangelperg Verified, this was resolved.

You can use the pull #585, or wait for it to merge.

**Comment by miguelangelperg** [comment]
Thank you so much guys. Qgis working in both OS

**Comment by fjperini** [comment]
Great! @miguelangelperg You can close this issue.
