### ISSUE TITLE
QGIS3 crashes when I click on QGIS → About QGIS & on Plugins → Manage and install plugins → click on some plugins

### ISSUE THREAD

**Issue by luispuerto** [OSGeo/homebrew-osgeo4mac#582]
When I run it on terminal it return this error: 

```shell
/usr/local/bin/qgis3: line 12: 27621 Segmentation fault: 11  /usr/local/opt/qgis3/QGIS.app/Contents/MacOS/QGIS "$@"
```

It's only me? Where it something wrong in my build or something ir wrong it general. The rest of the things seem to work fine. No crashing. 

It's quite a funny / stupid error. 😅

**Comment by fjperini** [comment]
@luispuerto I will check this!

**Comment by fjperini** [comment]
@luispuerto I did not have this problem, but I updated a more recent commit just in case. Everything worked fine.
Later I apply the changes!

**Comment by luispuerto** [comment]
Since I've suspected that perhaps the problem was related to my profile I moved `~/Library/Application Support/QGIS/QGIS3/profiles/default` and tried again. 

The outcome it's exactly the same... 

Seems that error is related to python. 

- https://github.com/geometalab/Vector-Tiles-Reader-QGIS-Plugin/issues/163
- https://stackoverflow.com/questions/19531969/segmentation-fault-11-in-os-x

**Comment by luispuerto** [comment]
After the last building with master + #450 + #585 + #586 I still have this bug in my build.

**Comment by fjperini** [comment]
I have built again, and I do not have that error.
@luispuerto maybe you're having a problem with Qt.

Test after:

```
export QT_QPA_PLATFORM_PLUGIN_PATH=/usr/local/Cellar/qgis3/3.4.3_2/QGIS.app/Contents/Plugins
```

**Comment by luispuerto** [comment]
@fjperini i really don't know where it's the problem exactly, but it seems to be out there... somewhere, like the [truth](https://youtu.be/Vpqffgak7To?t=39).

I've tried to run QGIS3 with those variables and the outcome is the same.

>p/d: @luispuerto you do not need that pull #450.

I take note of this.

**Comment by luispuerto** [comment]
I was able to capture the About screen before crashing.... I don't see anything fishy there. 

![screen shot 2019-01-15 at 10 30 18 3](https://user-images.githubusercontent.com/22882880/51168016-c29eab80-18b0-11e9-9a2c-012c0657da2d.png)

If it's a QT problem perhaps it's a problem related to just high sierra.

**Comment by fjperini** [comment]
@luispuerto It can be that, since I'm using Mojave and I do not have that problem.

**Comment by fjperini** [comment]
@nickrobison @luispuerto I'm preparing some changes for `qgis3`.

It will facilitate the installation and incorporate more Python Modules (see list in: https://lutraconsulting.github.io/qgis-mac-packager), which will be installed in another formula so that we do not have to be building them every time we build `qgis3`.

I have tried these changes, `qgis3` creates a link to use them:

```
(prefix/"QGIS.app/Contents/Resources/python").install_symlink Dir["#{Formula["qgis3-resources"].opt_libexec}/vendor/lib/python#{py_ver}/site-packages/*"]
```

Everything works perfectly 🎉 

Will solve the problems that some have with PyQt5 and SIP #510

I will incorporate the new formulas I have for `sip`, `pyqt` and `qscintilla2`. Updated to its latest version.

@luispuerto the formulas so you can try: [six.rb](https://gist.githubusercontent.com/fjperini/b39b1a54252d2e05c625e268be8bfa7c/raw/91a83bf8592d7cf6979faeea92fddc3c6f8ec44e/six.rb), [qgis3-resources.rb](https://gist.githubusercontent.com/fjperini/cbc2271a5559b1f790394b66c599b055/raw/b30be0ccd088ac693b372342294fe1db6a8de063/qgis3-resources.rb) and [qgis3](https://gist.githubusercontent.com/fjperini/85760fb695de6c3ead6ed11720a9e65a/raw/ea5f4818bb32bc663cac3d38f0b94b807356026d/qgis3.rb)

p/d: @luispuerto Maybe this solves the problem you have.

**Comment by luispuerto** [comment]
Great!! Can I merge this formulas with the LAStools' one? I can try to build everything together.

**Comment by fjperini** [comment]
@luispuerto yes, only that I have not yet applied the changes in `qgis3` to enable the new add-ons.

**Comment by fjperini** [comment]
@luispuerto I leave you the updated formulas: [six](https://gist.githubusercontent.com/fjperini/b39b1a54252d2e05c625e268be8bfa7c/raw/91a83bf8592d7cf6979faeea92fddc3c6f8ec44e/six.rb) | [qgis-res](https://gist.githubusercontent.com/fjperini/cbc2271a5559b1f790394b66c599b055/raw/e829c4a13fc130b62482275e8d049dcdbd6e1422/qgis-res.rb) | [qgis](https://gist.githubusercontent.com/fjperini/85760fb695de6c3ead6ed11720a9e65a/raw/4758b2c9c7dbb66b8d6894f646d8086d923a3bd0/qgis.rb)

LAStools, TauDEM and WTB are available!

Everything works very well 🎉 I will review them a few days before applying the changes.

The resource solves many things:

- installation time
- and conflicts with some PyQt and SIP modules (some have had this problem)

In addition, there will be more modules available, making things easier for the user.

**Comment by luispuerto** [comment]
@fjperini I've downloaded the three pull request (#591 #592 and #596) and installed the [six](url
https://gist.githubusercontent.com/fjperini/b39b1a54252d2e05c625e268be8bfa7c/raw/91a83bf8592d7cf6979faeea92fddc3c6f8ec44e/six.rb) | [qgis-res](url
https://gist.githubusercontent.com/fjperini/cbc2271a5559b1f790394b66c599b055/raw/e829c4a13fc130b62482275e8d049dcdbd6e1422/qgis-res.rb) | [qgis](url
https://gist.githubusercontent.com/fjperini/85760fb695de6c3ead6ed11720a9e65a/raw/4758b2c9c7dbb66b8d6894f646d8086d923a3bd0/qgis.rb) and I'm building with: 

```shell
brew install qgis \
	--with-grass --with-saga --with-r --with-orfeo6 --with-qspatialite \
	--with-isolation --with-lastools --with-liblas --with-szip \
	--with-taudem --with-whitebox --with-whitebox-tools
```

I don't know if all the flags are needed, but I have a couple of questions: 

- You mention in #596 that `--with-wine` can be added, but the formula doesn't have that flag. 
- I want to have `qgis-ltr` also, do I have to build both formulas `--with-insolation` or just one?  
- Will the resulting app from `qgis-ltr` going to be named `qgis-ltr.app` because that would have a lot of sense.

**Comment by fjperini** [comment]
@luispuerto Hey!

So I have it installed:

```
brew install qgis \
	--with-grass --with-saga --with-r --with-orfeo \
	--with-lastools --with-taudem --with-whitebox \
	--with-3d
```

You can also use: `--with-oracle`, `--with-gpsbabel`, `--with-qspatialite` and `--with-api-docs`.

Yes the flag `--with-wine` is not there, but you can still use it. Then I add it.

I will review the `--with-insolation` and apply the changes to have different `.app`. Suggestions?

**Comment by luispuerto** [comment]
Hey @3nids do you know if this is a general issue of QGIS in High Sierra? I've been trying to find something about it and I can't find anything. Thanks!

**Comment by luispuerto** [comment]
by the way... I just checked, by wife has in her computer 3.4.3 and was build with homebrew and it doesn't have this issue. That computer also has High Sierra.

**Comment by fjperini** [comment]
@luispuerto well, then try to eliminate and reinstall everything referred to Qt.

**Comment by luispuerto** [comment]
Interesting news... just build on my wife's computer, with Sigh Sierra and this bug isn't present... 

I've uninstalled some dependencies in my machine and now I'm rebuilding. Let's see, but it's pretty sure it's a isolate issue in my machine.

**Comment by luispuerto** [comment]
This is fixed reinstalling qt and other dependencies and forcing the link: 

```shell
$ brew reinstall ninja gsl sip six bison flex pkg-config python qt pyqt qscintilla2
$ brew link --overwrite pyqt
```

![screen shot 2019-02-06 at 09 50 42](https://user-images.githubusercontent.com/22882880/52327525-148caa00-29f5-11e9-91ca-4c6d0cb11664.png)
