### ISSUE TITLE
upgrade qgis and postgresql 

### ISSUE THREAD

**Issue by miguelangelperg** [OSGeo/homebrew-osgeo4mac#588]
When I run **brew upgrade qgis**, *Homebrew* also updates the installed postgresql version. If the update of postgresql implies an upgrade, then we will have problems, because **brew postgresql-upgrade-database** does not always work.

Is it possible to build Qgis against a specific version of postgresql and postgis to avoid an unwanted upgrade?

**Comment by luispuerto** [comment]
@fjperini do you know if qgis can be build against a previous version of postgresql?

**Comment by fjperini** [comment]
@miguelangelperg @luispuerto We could add a new formula `postgresql@10.6`? for this.

**Comment by luispuerto** [comment]
Core already has `postgresgl@10` 

```shell 
$ brew info postgresql@10                                          
postgresql@10: stable 10.6 (bottled) [keg-only]
Object-relational database system
https://www.postgresql.org/
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/postgresql@10.rb
==> Dependencies
Build: pkg-config ✔
Required: icu4c ✔, openssl ✔, readline ✔
==> Caveats
To migrate existing data from a previous major version of PostgreSQL run:
  brew postgresql-upgrade-database

postgresql@10 is keg-only, which means it was not symlinked into /usr/local,
because this is an alternate version of another formula.


To have launchd start postgresql@10 now and restart at login:
  brew services start postgresql@10
Or, if you don't want/need a background service you can just run:
  pg_ctl -D /usr/local/var/postgresql@10 start
==> Analytics
install: 6,960 (30 days), 9,675 (90 days), 9,678 (365 days)
install_on_request: 6,949 (30 days), 9,660 (90 days), 9,663 (365 days)
build_error: 0 (30 days)
```

The question is more if build agains that is possible or not. If he can install `postgresgl@10` and then pin the formula it's easier, I guess.

**Comment by miguelangelperg** [comment]
**@fjperini**, a great idea.
For those who postgresql-postgis has a relevant role in their workflow, allowing the selection of the postgresql version to install is an added value for the formula, in my opinion.

It would allow you to update Qgis without being forced to perform a *major upgrade* of the unwanted potgreslql cluster. Thanks.

Thanks, **@luispuerto** . I have installed postgresql @ 10 and postgresql 11, but for some reason ***brew postgresql-upgrade-database*** does not work for me.

Great job this tap!!!!

**Comment by miguelangelperg** [comment]
Probably my lack of knowledge makes me ask: if the user has a satisfied requirement, eg. postgresql or python3, why is it necessary to update the already available version when it is installed or updated, qgis?

**Comment by fjperini** [comment]
@miguelangelperg I think it is only updated if there is a new version of those packages at the time of installing `qgis`.

**Comment by miguelangelperg** [comment]
That's right, the update occurs if there is a higher version available. And this is not a problem, except when the version change requires updating the cluster.
  The update of the cluster in postgresql is necessary when a major version change occurs. For example, the change from posgresql 10.6 to 11.1 is a major update, while changing from version 10.1 to 10.6 is a minor update.
Any minor update will not be a problem for the postgresql user, but a major update requires upgrading the cluster data and this can be an expensive operation in time and is not always without problems. This is the origin of my cuestion.

If I understand your answer well, the update depends on homebrew. If so, should I find out if it is possible to prevent homebrew from updating a specific formula, in my case postgresql?

**Comment by luispuerto** [comment]
`brew pin postgresql` should do that job @miguelangelperg

**Comment by luispuerto** [comment]
Yes. But you already undated. If you want to downgrade you probably need to uninstall and install the Mersin you want

```
brew install postgresql@10
```

**Comment by fjperini** [comment]
@miguelangelperg @luispuerto We could implement a flag to choose one of the two versions in `qgis`.

**Comment by miguelangelperg** [comment]
I have both installed:
 brew services list
Name          Status  User      Plist
lighttpd      stopped           
postgresql    stopped           
postgresql@10 started miguelmbp /Users/miguelmbp/Library/LaunchAgents/homebrew.mxcl.postgresql@10.plist

**Comment by miguelangelperg** [comment]
@fjperini Good idea!

**Comment by fjperini** [comment]
@miguelangelperg I added the support!
