### ISSUE TITLE
New QGIS formula with LASTools, Whitebox, TauDEM, Six and qgis-res

### ISSUE THREAD

**Issue by luispuerto** [OSGeo/homebrew-osgeo4mac#607]
Hey! 

I just tried the new qgis formula that @fjperini and it's seems to work great! 

I've downloaded #596 and added the also the formulas [six](https://gist.githubusercontent.com/fjperini/b39b1a54252d2e05c625e268be8bfa7c/raw/91a83bf8592d7cf6979faeea92fddc3c6f8ec44e/six.rb), [qgis-res](https://gist.githubusercontent.com/fjperini/cbc2271a5559b1f790394b66c599b055/raw/e829c4a13fc130b62482275e8d049dcdbd6e1422/qgis-res.rb) and [qgis](https://gist.githubusercontent.com/fjperini/85760fb695de6c3ead6ed11720a9e65a/raw/4758b2c9c7dbb66b8d6894f646d8086d923a3bd0/qgis.rb). 

However, I feel I'm missing something here and don't know if it's because I added [qgis](https://gist.githubusercontent.com/fjperini/85760fb695de6c3ead6ed11720a9e65a/raw/4758b2c9c7dbb66b8d6894f646d8086d923a3bd0/qgis.rb) so I deleted something from the current qgis formula. 

## Whitebox 

It isn't working, at least in my build. It gives the following error when I turn it on. 

```
Couldn't load plugin 'whitebox' 

SyntaxError: invalid syntax 
Traceback (most recent call last):
  File "/usr/local/opt/qgis/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 309, in loadPlugin
    __import__(packageName)
  File "/usr/local/opt/qgis/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/local/opt/qgis/QGIS.app/Contents/MacOS/../Resources/python/plugins/whitebox/__init__.py", line 28, in 
    from whitebox.whiteboxProviderPlugin import WhiteboxProviderPlugin
  File "/usr/local/opt/qgis/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/local/opt/qgis/QGIS.app/Contents/MacOS/../Resources/python/plugins/whitebox/whiteboxProviderPlugin.py", line 30, in 
    from whitebox.whiteboxProvider import WhiteboxProvider
  File "/usr/local/opt/qgis/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/local/opt/qgis/QGIS.app/Contents/MacOS/../Resources/python/plugins/whitebox/whiteboxProvider.py", line 37, in 
    from whitebox.whiteboxAlgorithm import WhiteboxAlgorithm
  File "/usr/local/opt/qgis/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/local/opt/qgis/QGIS.app/Contents/MacOS/../Resources/python/plugins/whitebox/whiteboxAlgorithm.py", line 49, in 
    from whitebox import whiteboxUtils
  File "/usr/local/opt/qgis/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/local/opt/qgis/QGIS.app/Contents/MacOS/../Resources/python/plugins/whitebox/whiteboxUtils.py", line 45
    filePath = /usr/local/opt/whitebox-tools/bin/whitebox_tools
               ^
SyntaxError: invalid syntax


Python version: 3.7.2 (default, Jan 12 2019, 20:39:48) [Clang 10.0.0 (clang-1000.11.45.5)] 
QGIS version: 3.4.4-Madeira Madeira, 20a1d7ff 

Python Path:
/usr/local/opt/qgis/QGIS.app/Contents/MacOS/../Resources/python/plugins/lastools
/Users/lpuerto/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/gml_application_schema_toolbox/extlibs
/usr/local/opt/qgis/QGIS.app/Contents/MacOS/../Resources/python
/Users/lpuerto/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/lpuerto/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/usr/local/opt/qgis/QGIS.app/Contents/MacOS/../Resources/python/plugins
/usr/local/opt/gdal2-python/lib/python3.7/site-packages
/usr/local/opt/qgis/QGIS.app/Contents/Resources/python
/usr/local/opt/qgis/lib/python3.7/site-packages
/usr/local/opt/lib/python3.7/site-packages
/usr/local/Frameworks/Python.framework/Versions/3.7/lib/python37.zip
/usr/local/Frameworks/Python.framework/Versions/3.7/lib/python3.7
/usr/local/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload
/usr/local/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
/usr/local/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/geos
/usr/local/Cellar/matplotlib/2.2.3/libexec/lib/python3.7/site-packages
/usr/local/Cellar/numpy/1.16.0/libexec/nose/lib/python3.7/site-packages
/Users/lpuerto/Library/Application Support/QGIS/QGIS3/profiles/default/python
```
![screen shot 2019-01-20 at 12 02 48](https://user-images.githubusercontent.com/22882880/51442867-06971380-1cea-11e9-9856-b33c8edddc59.png)

## TauDEM

More or less the same as with Whitebox. 

```
Couldn't load plugin 'taudem' 

SyntaxError: invalid syntax 
Traceback (most recent call last):
  File "/usr/local/opt/qgis/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 309, in loadPlugin
    __import__(packageName)
  File "/usr/local/opt/qgis/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/local/opt/qgis/QGIS.app/Contents/MacOS/../Resources/python/plugins/taudem/__init__.py", line 28, in 
    from taudem.taudemProviderPlugin import TauDemProviderPlugin
  File "/usr/local/opt/qgis/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/local/opt/qgis/QGIS.app/Contents/MacOS/../Resources/python/plugins/taudem/taudemProviderPlugin.py", line 30, in 
    from taudem.taudemProvider import TauDemProvider
  File "/usr/local/opt/qgis/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/local/opt/qgis/QGIS.app/Contents/MacOS/../Resources/python/plugins/taudem/taudemProvider.py", line 37, in 
    from taudem.pitremove import PitRemove
  File "/usr/local/opt/qgis/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/local/opt/qgis/QGIS.app/Contents/MacOS/../Resources/python/plugins/taudem/pitremove.py", line 36, in 
    from taudem import taudemUtils
  File "/usr/local/opt/qgis/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/local/opt/qgis/QGIS.app/Contents/MacOS/../Resources/python/plugins/taudem/taudemUtils.py", line 47
    filePath = /usr/local/opt/taudem/bin
               ^
SyntaxError: invalid syntax


Python version: 3.7.2 (default, Jan 12 2019, 20:39:48) [Clang 10.0.0 (clang-1000.11.45.5)] 
QGIS version: 3.4.4-Madeira Madeira, 8871a589 

Python Path:
/Users/lpuerto/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/gml_application_schema_toolbox/extlibs
/usr/local/opt/qgis/QGIS.app/Contents/MacOS/../Resources/python
/Users/lpuerto/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/lpuerto/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/usr/local/opt/qgis/QGIS.app/Contents/MacOS/../Resources/python/plugins
/usr/local/opt/gdal2-python/lib/python3.7/site-packages
/usr/local/opt/qgis/QGIS.app/Contents/Resources/python
/usr/local/opt/qgis/lib/python3.7/site-packages
/usr/local/opt/lib/python3.7/site-packages
/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python37.zip
/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7
/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload
/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/geos
/usr/local/Cellar/matplotlib/2.2.3/libexec/lib/python3.7/site-packages
/usr/local/Cellar/numpy/1.16.0/libexec/nose/lib/python3.7/site-packages
/Users/lpuerto/Library/Application Support/QGIS/QGIS3/profiles/default/python
```
![screen shot 2019-01-20 at 19 34 33](https://user-images.githubusercontent.com/22882880/51442925-d8660380-1cea-11e9-8861-988e7b58eb96.png)

### With App Insolation

I tried `--with-insolation` and the app worked just fine, but I moved it from the `Cellar` location to `/Applications` no plugin worked. 

### Without App Insolation

I removed the flag and build again to check if I could moved the app to `/Applications` and I got this if I moved: 
![screen shot 2019-01-20 at 15 50 35](https://user-images.githubusercontent.com/22882880/51442985-9e493180-1ceb-11e9-87ec-3926ae616b56.png)

I know that move the app to `/Applications` isn't that important / big deal, but it's nice to be able to find it with Spotlight.

## Wine

`--with-wine` isn't working, at least in my case. It reply that the formula doesn't have a `--with-wine` flag and that's it. That was in my second build. It's funny because in the first build I didn't put the `--with-wine` flag and at some point during the building a message saying that I could add `--with-wine` if I wanted additional support. 

I've already have Wine installed so, perhaps I just have to give the plugin the path? I installed it with Homebrew. 

------

All the rest seems to work. I haven't tested LAStools that it doesn't produce any error when I try to use them, so I guess they are working. 

The idea of `gis-res` seems to work great and although the first time you build seems to take more time, then the building time is the same as before. Really great! 

**GREAT WORK!!!!!** 🎉

**Comment by fjperini** [comment]
@luispuerto The thing about `SyntaxError: invalid syntax` is already solved! I'll check the other.

The idea of `qgis-res` is that it is only built once (and updated from time to time, if necessary) in that way the time to build `qgis` is greatly reduced.

**Comment by luispuerto** [comment]
> Using Mojave and without that problem. Are you using High Sierra?
Yes I'm still in High Sierra (and in general I'm happy 😝 
> Perhaps it would be good to report this to the developers @3nids
Good idea, I'll mention him in the the issue.

**Comment by fjperini** [comment]
@luispuerto I built without  `--with-isolation` and moved `QGIS.app` to `/Applications` and all the plugins work!

**Comment by luispuerto** [comment]
If I try to see the plugins I get...

![screen shot 2019-01-20 at 21 38 02](https://user-images.githubusercontent.com/22882880/51444102-bcb72900-1cfb-11e9-9a5e-8c72b716a2fc.png)

And it's true that there is nothing there. There isn't `/usr/local/opt/qgis/QGIS.app/`

**Comment by fjperini** [comment]
Did you move `QGIS.app`, or did you make a link?
```
ln -Fs `find $(brew --prefix) -name "QGIS.app"` /Applications/QGIS.app
```

Then he sent you the updated formula!

**Comment by luispuerto** [comment]
I move the `QGIS.app` to `/Applications`. I don't like to make a link or symbolic link because those doesn't show up in Spotlight.

**Comment by fjperini** [comment]
@luispuerto There is the problem.

**Comment by luispuerto** [comment]
but... moving the app worked before. If it isn't possible isn't a problem. I was just wondering why the behavior changed.

**Comment by fjperini** [comment]
It must be for the links that are created to `qgis-res`

**Comment by luispuerto** [comment]
okidoki... taking into account the big advantage `qgis-res` is leave it like that... but if come to your mind how to solve it without compromise anything would be great. 

I think having the app in `/Applications` it's important for some users.

**Comment by luispuerto** [comment]
@fjperini don't waste your neurons in this... a simple alias show up in the spotlight just fine. 

Now I have to figure out how to create an Alias in terminal so I can automate that when I install / update QGIS

**Comment by luispuerto** [comment]
Just in case it's useful for someone. I created a script with this

```
qgis_location=$(find $(brew --prefix)/Cellar/qgis/ -name "3.*" -print -quit)/QGIS.app
osascript -e 'tell application "Finder"' -e 'make new alias to file (posix file "'$qgis_location'") at (posix file "/Applications")' -e 'end tell'
```

**Comment by fjperini** [comment]
@luispuerto Great!
You no longer have the problem?

**Comment by luispuerto** [comment]
![screen shot 2019-01-21 at 00 07 31](https://user-images.githubusercontent.com/22882880/51445664-92bc3180-1d10-11e9-988c-2f39298d7c84.png)

let's say it's a solution... leave the app in the cellar and create just an alias to it. As they say in academia "it is suboptimal", but it works.

**Comment by fjperini** [comment]
I'm testing the changes that I made, then I will apply them here.

**Comment by fjperini** [comment]
I do some more tests and I pass all the updated formulas. works perfectly!

**Comment by fjperini** [comment]
@luispuerto The new formulas are ready 🎉  before we must solve the problems that arose recently.

**Comment by fjperini** [comment]
@luispuerto ready to try the new formula?

**Comment by luispuerto** [comment]
>@luispuerto ready to try the new formula?

@fjperini is it already pulled?

**Comment by fjperini** [comment]
You give Ok before. Ha!  

[qgis-res.rb](https://gist.githubusercontent.com/fjperini/cbc2271a5559b1f790394b66c599b055/raw/87516b2b4469f2767f20d71f6d8dc75f7b78b5aa/qgis-res.rb) | [qgis.rb](https://gist.githubusercontent.com/fjperini/85760fb695de6c3ead6ed11720a9e65a/raw/95757e1560b3e2a9a30f3bd14d24767e0a8029df/qgis.rb)

After trying it for a few days, it's time to launch this new formula. It brings great changes.

Once the bottle for `qgis-res` is generated, we will save a lot of time in the construction of `qgis`. The user will compile `qgis-res` if he wants to install `r` and the associated modules or update the modules.

p/d: there is already a new version of `qt`, but it is not yet in `homebrew-core`.

**Comment by fjperini** [comment]
I added support for Microsoft ODBC Driver for SQL, is it being used?

**Comment by fjperini** [comment]
Note:

By default, LASTools will use the open source tools.

```
open source tools:

* laszip - compresses the LAS files in a completely lossless manner
* lasinfo - prints out a quick overview of the contents of a LAS file
* lasindex - creates a spatial index LAX file for fast spatial queries
* las2las - extracts last returns, clips, subsamples, translates, etc ...
* lasmerge - merges several LAS or LAZ files into a single LAS or LAZ file
* txt2las - converts LIDAR data from ASCII text to binary LAS format
* las2txt - turns LAS into human-readable and easy-to-parse ASCII
* lasprecision - analyses the actual precision of the LIDAR points
```
```
closed source tools:

* lastool.exe - is an old GUI for multiple LAStools (now each tool has its own GUI)
* lasground.exe - extracts the bare-earth by classifying all ground points
* lasground_new.exe - an improved version of lasground.exe for complex terrains
* lasoverlap.exe - checks overlap & vertical/horizontal alignment of flight lines
* lascontrol.exe - quality checks elevations for a list of control points 
* lasclassify.exe - finds buildings and the vegetation above the ground
* lascolor.exe - colors the LAS points based on ortho imagery in TIF format 
* lasgrid.exe - grids onto min/max/avg/std elevation, intensity, or counter rasters
* lascanopy.exe  - computes many raster and plot metrics for forestry applications
* lasboundary.exe - extracts a boundary polygon that encloses the points
* lasheight.exe - computes for each point its height above the ground
* lastrack.exe - classifies LiDAR point based on distance from a trajectory
* lasplanes.exe - finds planar patches in terrestrial, mobile, (airborne?) scans 
* lasclip.exe - clips points against building footprints / swath boundaries
* lastile.exe - tiles huge amounts of LAS points into square tiles
* lassplit.exe - splits points of LAS file(s) into flightlines or other criteria
* lassort.exe - sorts points by gps_time, point_source, or into spatial proximity
* lasduplicate.exe - removes duplicate points (with identical x and y, z optional) 
* lasthin.exe - thins lowest / highest / random LAS points via a grid
* las2tin.exe - triangulates the points of a LAS file into a TIN
* las2dem.exe - rasters (via a TIN) into elevation/slope/intensity/rgb DEMs
* las2iso.exe - extracts, optionally simplified, elevation contours
* lasview.exe visualizes a LAS file with a simple OpenGL viewer
* las2shp.exe - turns binary LAS into ESRI's Shapefile format
* shp2las.exe - turns an ESRI's Shapefile into binary LAS
```
If you want to use closed source tools, the user must [download](http://lastools.org/download/LAStools.zip) the closed source version, unzip it and manually assign (in Preferences - Processing -> Options: Providers -> LASTools) the new path for LASTools and define the path to `wine` (`/usr/local/opt/wine`). I left this like this, to make things easier. But it is possible to leave this by default.

By default it will only show the enabled tools, if it is changed to the closed source version, it will automatically show all the tools in the processing box.

**Comment by luispuerto** [comment]
>You give Ok before. Ha!
>
>[qgis-res.rb](https://gist.githubusercontent.com/fjperini/cbc2271a5559b1f790394b66c599b055/raw/87516b2b4469f2767f20d71f6d8dc75f7b78b5aa/qgis-res.rb) | [qgis.rb](https://gist.githubusercontent.com/fjperini/85760fb695de6c3ead6ed11720a9e65a/raw/95757e1560b3e2a9a30f3bd14d24767e0a8029df/qgis.rb)

Ok! I don't mind to download those... but if you have them in a branch in github, and you can point it out to me, it's a lot of easier. 

>I added support for Microsoft ODBC Driver for SQL, is it being used?

Sounds good to me. ODBC driver it's always needed to connect to old, and sometimes new, databases. It's not the first time I come across data in a old MS Access database format and I believe this driver would make it possible to get in the data.

**Comment by fjperini** [comment]
@luispuerto the [branch](https://github.com/fjperini/homebrew-osgeo4mac/tree/new). Sure, it's good to have mssql.

**Comment by luispuerto** [comment]
@fjperini I just tried. *It works* 🎊 . I have to rebuild grass7 and remove `insighttoolkit`. But all the rest went fine. Build time 40', which is the same as before.

**Comment by fjperini** [comment]
@luispuerto Great!

The insighttoolkit is because there is a reference to `brewsci/homebrew-science` in `orfeo6`, I will eliminate it.

As for `grass7`, you probably have a different version of the version that appears in the repository, so it asked you to rebuild it.

That we have a space to explain some things would be very good.

Yes, we hope that the problem in High Sierra related to Qt will be solved with the new version.

Apply a minor change in the TauDEM plugin, a fact with respect to this: open-mpi requires permission in the firewall to run.

**Comment by luispuerto** [comment]
In my quest to fix #582, I found up that I had my Qt pinned... I unpinned and updated everything and so... but now, I have a problem related to #510. This is last part of the terminal output: 

```shell
[2118/5113] Generating server/sip_serverpart0.cpp, server/sip_serverpart1.cpp, server/sip_serverpart2.cpp, server/sip_serverpart3.cpp
FAILED: python/server/sip_serverpart0.cpp python/server/sip_serverpart1.cpp python/server/sip_serverpart2.cpp python/server/sip_serverpart3.cpp
cd /tmp/qgis-20190206-98340-g1y85e/build/python && /usr/local/Cellar/cmake/3.13.4/bin/cmake -E echo && /usr/local/Cellar/cmake/3.13.4/bin/cmake -E touch /tmp/qgis-20190206-98340-g1y85e/build/python/server/sip_serverpart0.cpp /tmp/qgis-20190206-98340-g1y85e/build/python/server/sip_serverpart1.cpp /tmp/qgis-20190206-98340-g1y85e/build/python/server/sip_serverpart2.cpp /tmp/qgis-20190206-98340-g1y85e/build/python/server/sip_serverpart3.cpp && /usr/local/Cellar/sip/4.19.8_8/bin/sip -w -e -x TESTS -x ANDROID -x ARM -x MOBILITY_LOCATION -g -o -a /tmp/qgis-20190206-98340-g1y85e/build/python/qgis.server.api -y /tmp/qgis-20190206-98340-g1y85e/build/output/python/qgis/_server.pyi -j 4 -c /tmp/qgis-20190206-98340-g1y85e/build/python/server -I /tmp/qgis-20190206-98340-g1y85e/build/python/server -I /usr/local/share/sip -I /tmp/qgis-20190206-98340-g1y85e/python /tmp/qgis-20190206-98340-g1y85e/build/python/server/server.sip

sip: Unable to find file "QtCore/QtCoremod.sip"
[2119/5113] Linking C executable output/lib/qgis/grass/modules/qgis.d.rast7
[2120/5113] Building C object src/providers/grass/7/CMakeFiles/qgis.g.info7.dir/__/qgis.g.info.c.o
[2121/5113] Building CXX object src/app/dwg/libdxfrw/CMakeFiles/libdxfrw.dir/drw_classes.cpp.o
[2122/5113] Building CXX object src/crssync/CMakeFiles/crssync.dir/main.cpp.o
[2123/5113] Building CXX object src/core/CMakeFiles/qgis_core.dir/geometry/qgsgeometry.cpp.o
[2124/5113] Building CXX object src/app/dwg/libdxfrw/CMakeFiles/libdxfrw.dir/drw_entities.cpp.o
[2125/5113] Building CXX object src/app/dwg/libdxfrw/CMakeFiles/libdxfrw.dir/drw_header.cpp.o
ninja: build stopped: subcommand failed.
```

**Comment by luispuerto** [comment]
I fixed it... 

![screen shot 2019-02-06 at 09 50 42](https://user-images.githubusercontent.com/22882880/52327421-bbbd1180-29f4-11e9-9ef5-aa3043279176.png)

Get the champagne 🍾 @fjperini 😂

**Comment by fjperini** [comment]
@luispuerto Hip, hip, ¡hurra! 🎉

**Comment by luispuerto** [comment]
looking forward to your pull request.

**Comment by fjperini** [comment]
@luispuerto I verify that it builds in CI and will be available for all.

**Comment by fjperini** [comment]
@luispuerto to thank your great work :computer: :wrench:

<img width="1440" alt="qgis" src="https://user-images.githubusercontent.com/21315242/52372004-ba600900-2a35-11e9-8050-e89cda114473.png">

**Comment by luispuerto** [comment]
@fjperini I did nothing, just test and build your work. You did all the work! 

You already merged all the changes, didn't you?

**Comment by fjperini** [comment]
@luispuerto Much more than that!

Yes, it is available to everyone.

**Comment by luispuerto** [comment]
@fjperini by the way, I've reinstalled `--with-pdal` but I don't see anything new. How does one access to the pdal support, if any? 😛 

PS/ I write here because I don't have any way to contact you besides here
