### ISSUE TITLE
qgis fails to install due to RAlgorithmProvider.patch

### ISSUE THREAD

**Issue by alazarolop** [OSGeo/homebrew-osgeo4mac#611]
I was installing `qgis` after uninstalling old `qgis3` formula. At the beginning of the process I get the following messages: 
```
 -i
/private/tmp/qgis-20190121-8334-gx0oww/RAlgorithmProvider.patch

can't find file to patch at input line 3
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|--- a/python/plugins/r/processing/provider.py
|+++ b/python/plugins/r/processing/provider.py
--------------------------
File to patch: 
Skip this patch? [y] 
Skipping patch.
patch unexpectedly ends in middle of line
1 out of 1 hunk ignored
```

I was doing the process using some flags (--with-saga --with r), but even without them I get the same result.

**Comment by alazarolop** [comment]
Thank you a lot!

**Comment by fjperini** [comment]
@alazarolop Fixed up! You can use this pull #612.

**Comment by fjperini** [comment]
I meant that you can use the formula that is in that pull:

brew install https://raw.githubusercontent.com/OSGeo/homebrew-osgeo4mac/197f5ba37f0c54336cea232cd1e2f1afaec7ec41/Formula/qgis.rb

or wait for it to merge.

**Comment by alazarolop** [comment]
Thanks for the explanation and for the quick fix, I'll try it.
