### ISSUE TITLE
Error: We're doing an SSH key audit

### ISSUE THREAD

**Issue by fjperini** [OSGeo/homebrew-osgeo4mac#642]
Trying to solve a problem I found another.

```
ERROR: We're doing an SSH key audit.
Reason: unverified automatically (private key found in a public repository)
```
@nickrobison @3nids You will need to follow these steps: https://help.github.com/articles/error-we-re-doing-an-ssh-key-audit/

Maybe it's best to generate a new ssh key.

Note:
- For Travis CI: deploy_key

**Comment by fjperini** [comment]
Another thing I noticed that the ssh key in Circle CI did not work.

Here explain how to generate and apply the changes so that it works in both CI:
https://semantic-release.gitbook.io/semantic-release/recipes/recipes-1/git-auth-ssh-keys

Note:
- For Circle CI: ci_deploy_key

I regret the inconvenience!

**Comment by wildintellect** [comment]
Yes, I got the email too "SSH private deploy key found in commit", it referenced this commit as causing the issue
https://github.com/OSGeo/homebrew-osgeo4mac/blob/0064004044149ba3663d6e97cf6764131bef034a/deploy_key

The particular solution is to make a new private key for deployments, and not store it in git. Kind of a pain, when you need to share it amongst various CI tools. One option is to have a different deploy key per CI/Tool, and if we lose the private key to just make a new one. That way we don't need to share them typically.

**Comment by 3nids** [comment]
how come that the bot has pushed this file !?

**Comment by fjperini** [comment]
Solving another problem I could have pushed that file.
I took note so that it does not happen again. I'm sorry!

**Comment by fjperini** [comment]
@wildintellect @3nids If you need me to handle this, I can do it, I just need more permissions for this repository.

**Comment by fjperini** [comment]
@wildintellect @3nids I will solve this, the inconvenience that we have with Bintray and I will finish the implementation of Circle CI, for that I will need some of you to change the permissions to Admin.

**Comment by fjperini** [comment]
@wildintellect @3nids Sorry for the inconvenience, but this is necessary to publish the bottles.

**Comment by wildintellect** [comment]
@fjperini apologies I didn't realize only @3nids didn't have admin either. So in my role as safety net for access, I've bumped both of you up.

**Comment by fjperini** [comment]
@wildintellect Thank you! Now I will solve the problems.

**Comment by fjperini** [comment]
@wildintellect Can you generate a Token from the osgeo user?
https://github.com/settings/tokens
I will need it to publish the bottles!
Thank!

**Comment by wildintellect** [comment]
@fjperini Yes I have permissions, do you want a Github or Oauth token? Can you point me to the docs for the tool you are setting up so I make the right thing?

**Comment by fjperini** [comment]
@wildintellect https://docs.travis-ci.com/user/deployment/releases https://circleci.com/blog/publishing-to-github-releases-via-circleci/ https://developer.github.com/v3/auth/#basic-authentication

**Comment by fjperini** [comment]
@wildintellect I have solved this! and also the problem with Bintray 🎉 
Anyway, it would be nice to have the Token to have a backup in GitHub Release.

Note:

> ghr -t ${GITHUB_TOKEN} - Here we start the command and pass it a GitHub token for authentication. This is a GitHub Personal Access Token and not an OAuth token/key.

**Comment by wildintellect** [comment]
Github Personal Access Token's do not exist at the Org level, those are per user.

**Comment by fjperini** [comment]
@wildintellect I get it! Then let's use OAuth token. I will use it with `hub`.

**Comment by fjperini** [comment]
@wildintellect You can add it here:
https://travis-ci.com/OSGeo/homebrew-osgeo4mac/settings
https://circleci.com/gh/OSGeo/homebrew-osgeo4mac/edit#env-vars

**Comment by fjperini** [comment]
@wildintellect I close this issue, the problem is solved.
As for the Token, there is no hurry for that, do it at the moment you can.
