### ISSUE TITLE
change description and readme of the project

### ISSUE THREAD

**Issue by b4l** [OSGeo/homebrew-osgeo4mac#653]
STABLE is somehow inaccurate for the past three month. getting many errors in the constantly reoccurring installation/update process which is far from smooth and using a lot of ressources (4GB disk space, compilation)

**Comment by fjperini** [comment]
@b4l The formulas build stable packages. That users have configurations on their machines that cause problems, is another problem.
Anyway, if you think there is not something stable, you can make changes in the formulas, otherwise that issue does not contribute anything.

**Comment by fjperini** [comment]
@b4l By the way, we are working to solve the problem reported with Bintray.
And very soon we will distribute bottles with basic versions and others containing all the available options.

In this way it will no longer be necessary to build if it will be installed with all options or none.
