### ISSUE TITLE
cannot install perlmapscript on Yosemite 

### ISSUE THREAD

**Issue by dnltsk** [OSGeo/homebrew-osgeo4mac#66]
Hi,

brewing mapserver-64 on Yosemite aborts while [ 80%] Built target perlmapscript
Looking around turns out, Yosemite has changed something there:
http://stackoverflow.com/questions/26751927/perl-on-mac-os-10-10-yosemite-with-strange-inc-path

Disableing that module could be a workaround, but --without-perl or --without-perlmapscript doesn't work unfortunately. 

$ brew install mapserver-64
==> Installing mapserver-64 from osgeo/homebrew-osgeo4mac
==> Downloading http://download.osgeo.org/mapserver/mapserver-6.4.1.tar.gz
Already downloaded: /Library/Caches/Homebrew/mapserver-64-6.4.1.tar.gz
==> cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/mapserver-64/6.4.1 -DCMAKE_BUILD_TYPE=None -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=
==> make install
cd /tmp/mapserver-64-wBidxj/mapserver-6.4.1/build/mapscript/perl && /usr/local/Cellar/cmake/3.0.2/bin/cmake -E cmake_link_script CMakeFiles/perlmapscript.dir/link.txt --verbose=1
/usr/local/Library/ENV/4.3/clang    -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -bundle -Wl,-headerpad_max_install_names   -o mapscript.bundle CMakeFiles/perlmapscript.dir/mapscriptPERL5_wrap.c.o /System/Library/Perl/5.18/darwin-thread-multi-2level/CORE/libperl.dylib -Wl,-rpath,"/usr/local/opt/mapserver-64/lib" ../../libmapserver.6.4.1.dylib /usr/local/opt/libpng/lib/libpng.dylib /usr/lib/libz.dylib /usr/local/lib/libjpeg.dylib /usr/local/opt/freetype/lib/libfreetype.dylib /usr/local/lib/libproj.dylib /usr/local/lib/libfribidi.dylib /usr/lib/libiconv.dylib /usr/local/lib/libcairo.dylib /usr/local/lib/libgeos_c.dylib /usr/local/lib/libpq.dylib /usr/local/lib/libgdal.dylib /usr/lib/libcurl.dylib /usr/local/opt/libxml2/lib/libxml2.dylib /usr/local/opt/libxslt/lib/libxslt.dylib /usr/local/opt/libxslt/lib/libexslt.dylib /usr/local/lib/libgif.dylib -lm -Wl,-rpath,/tmp/mapserver-64-wBidxj/mapserver-6.4.1/build 
/usr/local/Cellar/cmake/3.0.2/bin/cmake -E cmake_progress_report /tmp/mapserver-64-wBidxj/mapserver-6.4.1/build/CMakeFiles  72
[ 80%] Built target perlmapscript
make: **\* [all] Error 2

Thats the $ brew --config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 87c75fd93cb545a9f2d8e462ced5064c36fdef4d
Last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: 8-core 64-bit ivybridge
OS X: 10.10-x86_64
Xcode: 6.1
Clang: 6.0 build 600
X11: 2.7.7 => /opt/X11
System Ruby: 2.0.0-481
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby

**Comment by nickrobison** [comment]
Closing this. @dnltsk, if this issue is still affecting you, feel free to open a new issue.
