### ISSUE TITLE
error when running gdal merge

### ISSUE THREAD

**Issue by GuiAlDuS** [OSGeo/homebrew-osgeo4mac#668]
Hi! 
I'm having issues when running the gdal merge tool from latest osgeo4mac QGIS 3.4.4 on MacOS Mojave. 
It's strange because other gdal tools run well, but when I run the mosaic I get this error:

```
2019-02-11T18:25:17     INFO    gdal_merge.py -ot Float32 -of GTiff -o /private/var/folders/fc/8d63rgj567954sphjm_18jxc0000gn/T/processing_b134aaed11d54580be7a0a55892749b4/852f65f2e4174785a1b7b8edc21053e9/OUTPUT.tif --optfile /private/var/folders/fc/8d63rgj567954sphjm_18jxc0000gn/T/processing_b134aaed11d54580be7a0a55892749b4/mergeInputFiles.txt
2019-02-11T18:25:17     INFO    GDAL execution console output
             Traceback (most recent call last):

              File "/usr/local/opt/gdal2-python/bin/gdal_merge.py", line 38, in 

              from osgeo import gdal

              File "/usr/local/opt/gdal2-python/lib/python3.7/site-packages/osgeo/__init__.py", line 21, in 

              _gdal = swig_import_helper()

              File "/usr/local/opt/gdal2-python/lib/python3.7/site-packages/osgeo/__init__.py", line 13, in swig_import_helper

              import _gdal

             ImportError: No module named _gdal
```

I already checked those directories and the .py files are there, so I'm wondering what can be causing this error.
Thanks!

**Comment by fjperini** [comment]
@GuiAlDuS I will check this!
I already know what may be happening.

using the revision 3.4.4_2?

**Comment by fjperini** [comment]
I am rebuilding bottles and applying changes in several formulas.

Just wait a couple of hours, I'll solve it.

**Comment by GuiAlDuS** [comment]
Thanks FJ!
I'll be checking for the updates.

Just in case it's important for the debugging, I had the same issue with the _Polygonize (raster to vector)_ tool:

```
GDAL command:
gdal_polygonize.py /private/var/folders/fc/8d63rgj567954sphjm_18jxc0000gn/T/processing_9c3099bdd4a542bcb0d85f965c021096/d23e2d00703b4770a7a155993d12ed56/WSHED.sdat /private/var/folders/fc/8d63rgj567954sphjm_18jxc0000gn/T/processing_9c3099bdd4a542bcb0d85f965c021096/eb1090891c8743b0964ac5bbbbc4bf7b/OUTPUT.shp -b 1 -f "ESRI Shapefile" OUTPUT DN
GDAL command output:
Traceback (most recent call last):

File "/usr/local/opt/gdal2-python/bin/gdal_polygonize.py", line 36, in <module>

from osgeo import gdal

File "/usr/local/opt/gdal2-python/lib/python3.7/site-packages/osgeo/__init__.py", line 21, in <module>

_gdal = swig_import_helper()

File "/usr/local/opt/gdal2-python/lib/python3.7/site-packages/osgeo/__init__.py", line 13, in swig_import_helper

import _gdal

ImportError: No module named _gdal
```

**Comment by fjperini** [comment]
What revision of `gdal2-python` and `qgis` are you using? The last one of `qgis` is `3.4.4_2` and `gdal2-python` is `2.4.0`.

if they are those, it must be because in resources there was also the `GDAL` module, I will remove it. It may be the problem with `gdal2-python`.

**Comment by GuiAlDuS** [comment]
Thanks!
Just in case it's needed, this is the info of the versions I have:
```
osgeo/osgeo4mac/gdal2-python: stable 2.4.0 (bottled), HEAD [keg-only]
Python bindings for GDAL: Geospatial Data Abstraction Library
https://pypi.python.org/pypi/GDAL
/usr/local/Cellar/gdal2-python/2.4.0 (141 files, 6.7MB)
  Poured from bottle on 2019-02-07 at 16:06:30
From: https://github.com/osgeo/homebrew-osgeo4mac/blob/master/Formula/gdal2-python.rb
```


```
osgeo/osgeo4mac/qgis: stable 3.4.4, HEAD
Open Source Geographic Information System
https://www.qgis.org
/usr/local/Cellar/qgis/3.4.4_2 (5,766 files, 246.3MB) *
  Built from source on 2019-02-07 at 21:40:50 with: --with-grass --with-saga
From: https://github.com/osgeo/homebrew-osgeo4mac/blob/master/Formula/qgis.rb
```

**Comment by fjperini** [comment]
@GuiAlDuS @saberraz I think the solution is to build `gdal2` with `swig-java`

**Comment by saberraz** [comment]
CC @PeterPetrik

**Comment by fjperini** [comment]
@GuiAlDuS @PeterPetrik @saberraz 🎉 I already found a solution for this, I will comment.
Before I need to see what happens in Travis, building bottles.

<img width="1440" alt="gdal" src="https://user-images.githubusercontent.com/21315242/52717509-06540600-2f80-11e9-902c-a291510b1c1e.png">

**Comment by PeterPetrik** [comment]
actually I think this is different problem I have in my bundle. What we do it https://github.com/lutraconsulting/qgis-mac-packager/blob/master/scripts/install_brew.bash#L55, so probably it is already with swig.

**Comment by fjperini** [comment]
@PeterPetrik yes, it is related to Python,  need to use `python3` in each script.

**Comment by GuiAlDuS** [comment]
> @GuiAlDuS @saberraz I think the solution is to build `gdal2` with `swig-java`

I'll then run `brew install osgeo/osgeo4mac/gdal2  --with-swig-java` and see how it goes.
Thanks for all your help! gracias!

**Comment by fjperini** [comment]
in the course of the day I will fix this!

**Comment by fjperini** [comment]
@GuiAlDuS I will implement the solution, verified and it works.

**Comment by fjperini** [comment]
@GuiAlDuSFormula updated, problems solved! 🎉

**Comment by fjperini** [comment]
@GuiAlDuS wait for the pull to merge.

**Comment by fjperini** [comment]
We closed this issue, I've been testing gdal and it works fine. If something fails, we can reopen it.

**Comment by GuiAlDuS** [comment]
Thanks! I'm having some issues with the update but I'll let you guys know if after all the recommendations (*) (**) and (***) I'm able to get it work again.

**Comment by fjperini** [comment]
@GuiAlDuS What kind of problems are you having? do you mean others?

If you are installing.

To rule out any problem you have in your homebrew installation:

```
$ brew unlink python && brew link --force python
$ brew reinstall ninja gsl python qt sip-qt5 pyqt-qt5 pyqt5-webkit qscintilla2-qt5 six bison flex pkg-config
$ brew link --overwrite pyqt-qt5
$ brew unlink gettext && brew link --force gettext
```
```
$ rm -rf $(brew --cache)
```
and the temporary build files in `/tmp`

An installation that failed previously may have created this link

```
   /usr/local/lib/python3.7/site-packages/PyQt5/uic/widget-plugins/qgis_customwidgets.py
```
you will need to delete it.

If you are going to use several flags, make sure that the system can open the necessary number of files.

```
$ ulimit -n 1024
```

If you only use `qgis` without flags, you do not need to build, will use the generated bottle.

p/d: keep in mind that if it is built in CI, it should be built on any other machine. If your installation fails, it is due to your Homebrew environment, review it.

**Comment by GuiAlDuS** [comment]
It worked great... thanks!!
