### ISSUE TITLE
grass-70 fails to build on OSX 10.10.1

### ISSUE THREAD

**Issue by max-nova** [OSGeo/homebrew-osgeo4mac#68]
I run:

    $ brew install osgeo/osgeo4mac/grass-70
    ==> Installing grass-70 from osgeo/homebrew-osgeo4mac
    ==> Downloading http://grass.osgeo.org/grass70/source/grass-7.0.0beta3.tar.gz
    Already downloaded: /Library/Caches/Homebrew/grass-70-7.0.0beta3.tar.gz
    ==> Patching
    patching file include/Make/Install.make
    ==> ./configure --prefix=/usr/local/Cellar/grass-70/7.0.0beta3 --enable-shared --with-cxx --with-python --with-blas --with-lapack --with-sqlite --with-odbc --with-geos=/usr/local/opt/geos/bin/geos-config --with-proj-share=/usr/local/opt/p
    ==> make GDAL_DYNAMIC=
    appear in the error log. If you get an error building a library, you will
    also get errors from anything which uses the library.
    --
    Finished compilation: Thu Dec  4 01:23:24 EST 2014
    make: *** [default] Error 1

gist here: https://gist.github.com/4cd2f6929700f85e664f

grass-64 is already installed on my computer from the osgeo4mac repo

When I run brew-doctor, I get:

    Warning: You have unlinked kegs in your Cellar
    Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
    those kegs to fail to run properly once built. Run `brew link` on these:
        gdal-grass

But gdal-grass64 is already linked, so I wasn't sure what to do.  When I run 

    brew link gdal-grass

I get:

    Linking /usr/local/Cellar/gdal-grass/1.4.3...
    Error: Could not symlink share/gdal/grass/driver/db/dbf
    Target /usr/local/share/gdal/grass/driver/db/dbf
    is a symlink belonging to gdal-grass64. You can unlink it:
      brew unlink gdal-grass64
    To force the link and overwrite all conflicting files:
      brew link --overwrite gdal-grass

**Comment by dakcarto** [comment]
Closing. Try latest `grass-70`. Reopen if necessary.
