### ISSUE TITLE
Upgrade to libspatialindex 1.9.0

### ISSUE THREAD

**Issue by saberraz** [OSGeo/homebrew-osgeo4mac#681]
See https://github.com/libspatialindex/libspatialindex/releases/tag/1.9.0

**Comment by fjperini** [comment]
@saberraz is in `homebrew-core`, I'll update it from there.

**Comment by fjperini** [comment]
@saberraz this is about to merge!

**Comment by songololo** [comment]
After reinstalling `qgis` via `brew` I'm getting this error:
```
dyld: Library not loaded: /usr/local/opt/spatialindex/lib/libspatialindex.4.dylib
  Referenced from: /usr/local/opt/qgis/QGIS.app/Contents/MacOS/QGIS
  Reason: image not found
/usr/local/bin/qgis: line 13: 14532 Abort trap: 6           /usr/local/opt/qgis/QGIS.app/Contents/MacOS/QGIS "$@"
```

Is this possibly related to the `libspatialindex` upgrade or is there something else going on?

**Comment by fjperini** [comment]
@songololo Yes, it must be that. I will rebuild the bottle, if you build with flags, you will need to rebuild `qgis`.

**Comment by fjperini** [comment]
@songololo Ready! Thanks for the warning.

**Comment by songololo** [comment]
awesome, thank you,
