### ISSUE TITLE
Unable to uninstall a package that has unsupported calling need

### ISSUE THREAD

**Issue by wrobelda** [OSGeo/homebrew-osgeo4mac#687]
I have a problem with mosh package that has a problem with :cxx11 not available anymore. However, since I don't really use it, after all, I wanted to uninstall it. This is, again, not possible due to the disabled calling need. I suppose *uninstalling* packages should not be blocked by it?

DawidsMcBookPro  ~  brew uninstall mosh                                                       
Uninstalling /usr/local/Cellar/mosh/1.3.2_4... (14 files, 878.4KB)
Error: Calling needs :cxx11 is disabled! There is no replacement.
Please report this to the homebrew/core tap:
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/mosh.rb:26

**Comment by fjperini** [comment]
@wrobelda I do not know where this comes from, but I give you some help. `needs :cxx11` (see https://github.com/OSGeo/homebrew-osgeo4mac/issues/626#issuecomment-460657787) is no longer in that, it must be removed from the formulas. It seems only a message, not an error.
If you have problems to uninstall, use:

```
brew uninstall --ignore-dependencies formula
brew uninstall formula --force
```

**Comment by wrobelda** [comment]
Thing is, using --force or --ignore-dependencies don't help at all:

`brew uninstall --ignore-dependencies mosh --force
Uninstalling mosh... (14 files, 878.4KB)
Error: Calling needs :cxx11 is disabled! There is no replacement.
Please report this to the homebrew/core tap:
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/mosh.rb:26

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/Homebrew/homebrew-core/issues`
