### ISSUE TITLE
qgis: can't connect to MS SQL

### ISSUE THREAD

**Issue by nextstopsun** [OSGeo/homebrew-osgeo4mac#691]
Qgis3 throws 
```Error opening connection: Driver not loaded Driver not loaded```
when trying to create a new MS SQL Server connection. 
Installed and configured `freetds` with brew and `tsql` client connects to the database just fine.
Seems like `libqt5sql5-tds` or something is missing in the build.
Can anyone please give a clue?
I can provide access to a MS SQL Server for testing if needed.

**Comment by fjperini** [comment]
@nextstopsun I'm preparing an update to the `qgis` formula.

Can you tell me what version you have installed? It would also be good for me to indicate the steps to error, so I can reproduce them. And access. Thank!

**Comment by nextstopsun** [comment]
Sure, I have installed qgis from `3.4.4_1` formula.
To access MS SQL Server, I've installed `unixodbc` and `freetds` formulas, added driver config to `odbcinst.ini` and DSN config to `odbc.ini` files.
I can access my DB with both cli and gdal. So I assume qgis MSSQL connection should work out of the box in this environment.
To reproduce this error you just have to try adding a new MSSQL connection. After filling all the params hit `List Databases` or `Test connection` and you'll get this error.
@fjperini Can I DM you an access?

**Comment by fjperini** [comment]
@nextstopsun Thanks for the data.
Regarding the version you are using, in 3.4.4_2 I added:

```
  if build.with? "mssql"
    depends_on "microsoft/mssql-release/msodbcsql17"
    depends_on "microsoft/mssql-release/mssql-tools"
  end
```
I think it incorporates the drivers that are needed.

just wait a bit, I'll be updating the formula, with the new version of `qt`.
With improvements and new supports.

**Comment by nextstopsun** [comment]
@fjperini Why don't you depend on `freetds` instead of `msodbcsql17`?

**Comment by fjperini** [comment]
@nextstopsun We replace?
```
msodbcsql17
mssql-tools
```

by

```
freetds
python-pymssql
```

**Comment by nextstopsun** [comment]
@fjperini Yep. I can test build with either option (btw if this can be set as option - could be great to test performance of both)

**Comment by fjperini** [comment]
Updated formula, `freetds` and `unixodbc` by default .. for python modules, you will need to build `qgis-res` with `--with-complete`.
Alternatively you can use `msodbcsql17`.

**Comment by nextstopsun** [comment]
@fjperini Wow!! Thanks a lot.
How can I dm you DB access if something goes wrong?

**Comment by fjperini** [comment]
@nextstopsun Can you send me a DM (Twitter)? @fjperini

**Comment by nextstopsun** [comment]
@fjperini Please accept follow request

**Comment by fjperini** [comment]
@nextstopsun I will try to see what happens with the MS SQL connection.

**Comment by fjperini** [comment]
@nextstopsun I already know what happens with this.
I will try to make a report to explain it.

**Comment by fjperini** [comment]
@nextstopsun Resolved 🎉  Later I will try to implement the solution.

**Comment by atumius** [comment]
> @nextstopsun Resolved 🎉 Later I will try to implement the solution.

I see that you somehow solved "Driver not loaded" issue on mac
Can you help by texting exact steps?

I tried to install odbc drivers through brew, but nothing happens

**Comment by fjperini** [comment]
It is something I solved a long time ago, it requires a manual fix.
I can gladly help you @atumius, send me your email.
![mssql](https://user-images.githubusercontent.com/21315242/76889841-1619da00-6865-11ea-8c11-468593ae6c85.png)

**Comment by MiroslavHrcan** [comment]
hi @fjperini ,
I have same issue on windows desktop, could you plesase send me this manual fixes?
tnx

**Comment by johlund** [comment]
@fjperini any chance you wanna send the manual fix to me as well? At work we have mssql and I'm stuck on a win machine but would be so much more happy to use qgis from my mac. 

ohlund.jonas@gmail.com

**Comment by mgarve** [comment]
@fjperini I would also be very happy if you share your solution :wink:
tomberlin54321@gmail.com

**Comment by juancarlos-rodriguez** [comment]
Hello @johlund, @mgarve, @catalinmiraute and @fjperini ,

Did you guys solve it?
I need it for a project but I'm stock trying to connect to a MSSQL database.
jkr.784@gmail.com
Thanks!

**Comment by PeterPetrik** [comment]
@fjperin @nextstopsun I would like to fix it in https://github.com/qgis/QGIS-Mac-Packager/issues/85, so at the end it was fixed by inclusion of which drivers?
```
freetds
python-pymssql
```

**Comment by nextstopsun** [comment]
@PeterPetrik @fjperini kindly did a manual fix on my machine some time ago. As far as I remember, drivers that this formula was referring to were sufficient and fix didn't involve rebuilding from source. Unfortunately, I gave up on building qgis with homebrew and installed recent version from your (official) bundle, so @fjperini can give you more detail on that.

It'd be great to have Mssql in official build, as It would be great to have a working homebrew qgis formula. Any chance it gets resurrected any time soon?

**Comment by cyberease** [comment]
@fjperini, I would also like to have the solution to this problem.  Have tried everything I can think of.  OpenSuse.  cyberease@gmail.com.  Thanks.

**Comment by shyicl** [comment]
@cyberease  @fjperini @PeterPetrik  thanks a lot! can you send me this solution please? I am struggling with this this issue since twoo months ago. My email is shyicl@yahoo.fr. Thanks a million!

**Comment by xsxWang** [comment]
> It is something I solved a long time ago, it requires a manual fix. I can gladly help you @atumius, send me your email. ![mssql](https://user-images.githubusercontent.com/21315242/76889841-1619da00-6865-11ea-8c11-468593ae6c85.png)
@fjperini 
i could connect MSSQL with FreeTDS [MSSQL database was installed on windows] ,but how to config with qgis ? see :
https://github.com/xsxWang/hello-world/blob/master/linux-MSSQL.png
https://github.com/xsxWang/hello-world/blob/master/linux-qgis-2.png

hknmtt426@gmail.com
thanks for help！

**Comment by shyicl** [comment]
Dear SirThanks a lot for your reaction. This is my email.
Regards
----------------------------------------------------------------------------------------------------------
Shyirambere Jean Claude
----------------------------------------------------------------------------------------------------------
