### ISSUE TITLE
Failure to install: PyQt5 and sipconfig modules not found

### ISSUE THREAD

**Issue by sasha-kap** [OSGeo/homebrew-osgeo4mac#692]
`brew install osgeo/osgeo4mac/qgis`
returns:

==> cmake -G Ninja -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/qgis/3.4.4_2 -DCMAKE_
Last 15 lines from /Users/.../Library/Logs/Homebrew/qgis/01.cmake:
    import PyQt5.QtCore
ModuleNotFoundError: No module named 'PyQt5'
Traceback (most recent call last):
  File "/tmp/qgis-20190214-12772-113kfk1/cmake/FindSIP.py", line 33, in <module>
    import sipconfig
ModuleNotFoundError: No module named 'sipconfig'
CMake Error at cmake/FindSIP.cmake:54 (MESSAGE):
  Could not find SIP
Call Stack (most recent call first):
  CMakeLists.txt:769 (FIND_PACKAGE)

(This is after I ran `brew reinstall ninja gsl sip six bison flex pkg-config python qt pyqt qscintilla2` & `brew link --overwrite pyqt`.)

Both sip and PyQt5 appear to be installed, so not sure what the problem is:

`brew info pyqt`
pyqt: stable 5.10.1 (bottled)
Python bindings for v5 of Qt
https://www.riverbankcomputing.com/software/pyqt/download5
/usr/local/Cellar/pyqt/5.10.1_1 (985 files, 45.0MB) *
  Poured from bottle on 2019-02-14 at 22:32:37
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/pyqt.rb
==> Dependencies
Required: python ✔, python@2 ✔, qt ✔, sip ✔

`brew info sip`
sip: stable 4.19.8 (bottled), HEAD
Tool to create Python bindings for C and C++ libraries
https://www.riverbankcomputing.com/software/sip/intro
/usr/local/Cellar/sip/4.19.8_9 (16 files, 1.1MB) *
  Poured from bottle on 2019-02-14 at 22:24:21
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/sip.rb
==> Dependencies
Required: python ✔, python@2 ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
The sip-dir for Python is /usr/local/share/sip.

`brew --config`
HOMEBREW_VERSION: 2.0.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: e32c1515432a938093d5ef1d8c4b4408991873df
Last commit: 9 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 8780bcc4cc70de26ca166098e2ecbd63aee18000
Core tap last commit: 8 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_LOGS: /Users/.../Library/Logs/Homebrew
HOMEBREW_NO_INSTALL_CLEANUP: 1
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.10.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_121
macOS: 10.14.1-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: 10.1

Would appreciate any assistance you can offer.  Thank you.

**Comment by fjperini** [comment]
@sasha-kap I'll check this, maybe this.
In the course of the day I will be updating the formula.

**Comment by fjperini** [comment]
@sasha-kap We will use our own packages of `sip`, `pyqt` and `qscintilla`. And before will clean `PATH` temporarily so there is no conflict with the configurations/installations that each user has on their machine.
I will apply a patch for FindSIP, FindQsci and FindPyQt5.

With this, the formula would have all the necessary restrictions to avoid this problem that you and others have #510.

<img width="504" alt="sip" src="https://user-images.githubusercontent.com/21315242/52908112-85319300-324d-11e9-9d5b-c98a03d41088.png">

**Comment by fjperini** [comment]
@sasha-kap updated formula. With all the restrictions there should no longer be any problem with these modules.
If it fails for the same reason, it is because you need to check your Homebrew. if it is compiled in Travis CI, it should be built on any machine.

A bottle will be built, if you only install qgis it without extra supports, you will not need to build.

**Comment by fjperini** [comment]
@sasha-kap now we use the formulas: `sip-qt5`, `pyqt-qt5` and `qscintilla2-qt5`.

To rule out any problem you have in your homebrew installation:

```
$ brew unlink python && brew link --force python
$ brew reinstall ninja gsl python qt sip-qt5 pyqt-qt5 pyqt5-webkit qscintilla2-qt5 six bison flex pkg-config
$ brew link --overwrite pyqt-qt5
$ brew unlink gettext && brew link --force gettext
```
```
$ rm -rf $(brew --cache)
```
and the temporary build files in `/tmp`

If you are going to use several flags, make sure that the system can open the necessary number of files.
```
$ ulimit -n 1024
```

If you only use `qgis` without flags, you do not need to build, will use the generated bottle.

**Comment by sasha-kap** [comment]
Thank you for getting this done quickly.  I just completed my installation (without any flags).  I just ran `$ brew link --overwrite` for sip-qt5, pyqt-qt5, qscintilla2-qt5, libiodbc, and psqlodbc after the installation.

**Comment by fjperini** [comment]
@sasha-kap Ok, it was advisable to do it before installation.
Either way, they are only recommendations, if your Homebrew environment is fine ... they will not be necessary.

Then confirm if everything works, to close this issue.

**Comment by sasha-kap** [comment]
Everything works, thank you!
