### ISSUE TITLE
grass7 perl dependency?

### ISSUE THREAD

**Issue by PeterPetrik** [OSGeo/homebrew-osgeo4mac#706]
https://github.com/OSGeo/homebrew-osgeo4mac/blob/master/Formula/grass7.rb#L474

but perl is not even in the required deps and even in ubuntu https://packages.ubuntu.com/cosmic/grass-gui it is not listed as dep. 

@neteler Do you know if PERL is dependency and if the environment variable is valid?

**Comment by fjperini** [comment]
You may I have added it unintentionally! I will review this and remove it if necessary.

**Comment by neteler** [comment]
Perl is not used, so it may be removed from the dependency list

**Comment by fjperini** [comment]
@neteler this is no longer used?

>   <dt>GRASS_PERL</dt>
>   <dd>[used during install process for generating man pages]<br>
>     set Perl with path.</dd>

**Comment by neteler** [comment]
Not sure what to found this but it is optionally possible to use Perl for own scripts.
On core level it is not used

**Comment by fjperini** [comment]
@neteler So we set it as optional? If you think it's better to remove it, I'll do it.
https://github.com/GRASS-GIS/grass-ci/blob/master/lib/init/variables.html#L231

**Comment by neteler** [comment]
I would not pack Perl as a dependency as most ppl write in C, C++ or Python in this context

**Comment by fjperini** [comment]
Fixed up!

**Comment by PeterPetrik** [comment]
thanks
