### ISSUE TITLE
Formula for Monteverdi1.x?

### ISSUE THREAD

**Issue by raughter** [OSGeo/homebrew-osgeo4mac#71]
Monteverdi2.0.8 is coming along but still lacks some important features from Monteverdi1 - like the Object Labeling functionality.

As was said over on the OTB Google Group, 
"Monteverdi2 has been developed 'from scracth' with different goals and a different architecture than Monteverdi 1.x. There is therefore no equivalency between the two softwares in terms of functionalities (best to think of them as 2 different software). We are still releasing Monteverdi 1.x for those needing it."

What are the prospects, if any, for a formula for the latest version of Monteverdi1?

Thank you for your work and time!

**Comment by dakcarto** [comment]
Well, certainly be nice for someone to do a pull request with that formula. :smile: I don't have any plans for adding that.

You can also try using the [DMG provided by OTB for Monteverdi1](http://sourceforge.net/projects/orfeo-toolbox/files/Monteverdi/), though it won't be integrated with all of the other Homebrew-based dependencies.

**Comment by raughter** [comment]
Thanks for your response and suggestion. :) 
I'll give the dmg  a try - though I'm leery of mixing brewed and unbrewed applications.
But maybe just this once... ;)
