### ISSUE TITLE
qgis-26 failed to build on Yosemite Syntax error

### ISSUE THREAD

**Issue by usabledata** [OSGeo/homebrew-osgeo4mac#72]
Hi there, 

I've been trying to install qgis-26 using:

brew install https://github.com/OSGeo/homebrew-osgeo4mac/tree/master/Formula

It's returning the following error:

Error: /Library/Caches/Homebrew/Formula/Formula:5: syntax error, unexpected '<'
<!DOCTYPE html>
 ^
/Library/Caches/Homebrew/Formula/Formula:6: syntax error, unexpected '<'
<html lang="en" class="">
 ^
/Library/Caches/Homebrew/Formula/Formula:6: syntax error, unexpected keyword_class, expecting end-of-input
<html lang="en" class="">
                     ^

Yosemite seems to be causing a few issues with qgis but is there anyway around this?

**Comment by jctull** [comment]
brew tap osgeo/osgeo4mac
brew install qgis-26
