### ISSUE TITLE
qgis-ltr@2: error when building --with: grass, saga-gis-lts and isolation

### ISSUE THREAD

**Issue by alazarolop** [OSGeo/homebrew-osgeo4mac#730]
Hi,

I'm trying to install QGIS 2.18.28 using formula `qgis-ltr@2` along with `qgis-ltr`. So far, I get `qgis-ltr` installed flawlessly and it works like a charm, but when I try to build `qgis-ltr@2`with some options, I get some errors.

Using this command `qgis-ltr@2 --with-grass --with-isolation --with-saga-gis-lts`, installation fails with this log:

```
Last 15 lines from /Users/alazaro/Library/Logs/Homebrew/qgis-ltr@2/26.make:
[  8%] Generating ui_qgsauthtrustedcasdialog.h
cd /tmp/qgis-ltr@2-20190225-59568-1g4iegh/QGIS-final-2_18_28/build/src/ui && /usr/local/Cellar/qt-4/4.8.7/bin/uic -o /tmp/qgis-ltr@2-20190225-59568-1g4iegh/QGIS-final-2_18_28/build/src/ui/ui_qgsauthtrustedcasdialog.h /tmp/qgis-ltr@2-20190225-59568-1g4iegh/QGIS-final-2_18_28/src/ui/auth/qgsauthtrustedcasdialog.ui
[  8%] Generating ui_qgshillshaderendererwidget.h
cd /tmp/qgis-ltr@2-20190225-59568-1g4iegh/QGIS-final-2_18_28/build/src/ui && /usr/local/Cellar/qt-4/4.8.7/bin/uic -o /tmp/qgis-ltr@2-20190225-59568-1g4iegh/QGIS-final-2_18_28/build/src/ui/ui_qgshillshaderendererwidget.h /tmp/qgis-ltr@2-20190225-59568-1g4iegh/QGIS-final-2_18_28/src/ui/raster/qgshillshaderendererwidget.ui
[  8%] Generating ui_qgsrastertransparencywidget.h
cd /tmp/qgis-ltr@2-20190225-59568-1g4iegh/QGIS-final-2_18_28/build/src/ui && /usr/local/Cellar/qt-4/4.8.7/bin/uic -o /tmp/qgis-ltr@2-20190225-59568-1g4iegh/QGIS-final-2_18_28/build/src/ui/ui_qgsrastertransparencywidget.h /tmp/qgis-ltr@2-20190225-59568-1g4iegh/QGIS-final-2_18_28/src/ui/raster/qgsrastertransparencywidget.ui
20 errors generated.
[  8%] Generating ui_qgsrenderercontainerbase.h
cd /tmp/qgis-ltr@2-20190225-59568-1g4iegh/QGIS-final-2_18_28/build/src/ui && /usr/local/Cellar/qt-4/4.8.7/bin/uic -o /tmp/qgis-ltr@2-20190225-59568-1g4iegh/QGIS-final-2_18_28/build/src/ui/ui_qgsrenderercontainerbase.h /tmp/qgis-ltr@2-20190225-59568-1g4iegh/QGIS-final-2_18_28/src/ui/styledock/qgsrenderercontainerbase.ui
make[2]: *** [src/app/dwg/libdxfrw/CMakeFiles/libdxfrw.dir/intern/dwgreader.cpp.o] Error 1
[  8%] Built target ui
20 errors generated.
make[2]: *** [src/app/dwg/libdxfrw/CMakeFiles/libdxfrw.dir/intern/dwgreader15.cpp.o] Error 1
make[1]: *** [src/app/dwg/libdxfrw/CMakeFiles/libdxfrw.dir/all] Error 2
make: *** [all] Error 2 
```

I haven't tried it without the options, as I understand I need QGIS 2 to be "isolated" to co-exist with QGIS 3, is this right? How could I make it? `qscintilla2-qt4` formula is already linked as mentioned in the formula note.

Thank you in advance!

**Comment by fjperini** [comment]
@alazarolop I will try to check this!

I will need before: `brew gist-logs qgis-ltr@2`

**Comment by alazarolop** [comment]
Thank you! This is the link:

https://gist.github.com/6ce0f4cb64f99a59ad583fe9e7f4ba4d

**Comment by fjperini** [comment]
Well, I think the problem is related to some dependency.

https://gist.githubusercontent.com/alazarolop/6ce0f4cb64f99a59ad583fe9e7f4ba4d/raw/bb9d102b44cc182fddcca089383c0fcf5cd4542f/26.make

Try after

```
$ brew unlink python@2 && brew link --force python@2

$ brew reinstall gsl sip-qt4 bison flex pkg-config python@2 qt-4 pyqt-qt4 qscintilla2-qt4

$ brew link --overwrite pyqt-qt4
```

these are the dependencies that may be in conflict with those that respect qt5.

```
sip-qt4, pyqt-qt4, qca-qt4, qscintilla2-qt4, qwt-qt4, qwtpolar-qt4, qjson-qt4, gpsbabel-qt4
```

**Comment by alazarolop** [comment]
I've tried the first three steps and I got the same message. So I unlinked every counterpart of qt5 version, relinked all of them and got again the error message:

https://gist.github.com/alazarolop/8f5a575cac88dccf52648b5baeb33072

**Comment by fjperini** [comment]
@alazarolop I will try to build on my machine, then I inform you.

**Comment by fjperini** [comment]
@alazarolop I've been completing the integration with Circle CI.
We will be creating bottles built with the most used flags until we have complete versions so that the user does not have to build if they want QGIS with additional supports and tools.

**Comment by alazarolop** [comment]
Cool! Thank you for your efforts! Shall I wait for an updated formula of `qgis-ltr@2` or an specific span of time? 

By the way, how will we be able to identify when a bottle will be used instead of compiling on the machine?

**Comment by fjperini** [comment]
When you build on your machine, it's because the bottle does not have any support you need, that's why you add it as flags.

I will try to start with the most used support/tools, in this case I will build the bottle with saga and lawn included.

So, little by little until we have everything included.

For each formula you can see the information with the formula of `brew info formula`

**Comment by fjperini** [comment]
I will try to do this as soon as possible, but keep in mind that I will have to review several formulas, so that all the dependencies are built with all the supports.
But if you need `qgis-ltr@2` as soon as possible, I can build tonight with `gdal2`, `saga` and `grass` without their additional supports.

**Comment by alazarolop** [comment]
Thank you very much for your concern! I understand what you mean. 

I want to work with RQGIS and right now its version for QGIS3, RQGIS3, doesn't work properly on Mac. That's why I wanted to try RQGIS with QGIS 2. So it would be great as soon as you get a chance. Could you include the `isolation` tag too when you do it? Thank you again, your support is awesome.

**Comment by fjperini** [comment]
Yes, just give me a couple of hours.

**Comment by alazarolop** [comment]
Great! Thank you a lot!

**Comment by fjperini** [comment]
I will need more time for this, something that is added is causing the problem, since without flags it was built well.

You could use the bottle and manually add the SAGA and GRASS plugins.

We could see the implementation of RQGIS in QGIS 3.

**Comment by fjperini** [comment]
Reviewing and rebuilding everything related to Qt4.

**Comment by alazarolop** [comment]
Hi, 
Sorry for the delay and thank you for your work and for the clue too. 

A doubt about the bottle, does it come isolated by default? Formula info says 
```
QScintilla Python module is needed by QGIS during run-time.
Ensure `qscintilla2-qt4` formula is linked."
```
and I've already got the qt5 version linked, and so I'm not sure how it can affect my current `qgis-ltr`.

**Comment by alazarolop** [comment]
About the implementation of RQGIS, I've test the “mac” branch of the project and it's already working with two main caveats: it demands for Python 3.6 (although it can be tricked with 3.7) and it crashes the R session when used within RStudio. This is the link to the issue https://github.com/jannes-m/RQGIS3/issues/3. I will comment in the bug thread but I'm not sure how I could give more support.

**Comment by fjperini** [comment]
@alazarolop I was reviewing this, it may be related to Qt4, I have reconstructed and improved a lot of those formulas ... but I'm missing some. When I have them ready I will apply the changes.

Yes, the quick solution for that is to link the ones you need, and unlink those that may come into conflict with those.

**Comment by alazarolop** [comment]
Ok! Great news. I'll keep an eye on updates.

I'll give it a try then. Thank you!

**Comment by fjperini** [comment]
Did you try to build with GRASS 7? test using GRASS 6.

Maybe the mistake is due to that.

**Comment by alazarolop** [comment]
I haven't actually. 

After your suggestion, I tried without `--with-grass` and it stopped with the same error message. As a side note, I kept GRASS 7 installed.

Then, I tried `brew install qgis-ltr@2 --with-grass6 --with-isolation --with-saga-gis-lts` in a VM without `qgis-ltr` and `grass-7` installed and it threw a new error message https://gist.github.com/a8e77fc4bf2880a70387bd0642428d12

**Comment by fjperini** [comment]
Try after uninstalling `grass7`. It seems that it uses it if it is installed

```
brew install qgis-ltr@2 --with-grass6 --with-isolation --with-saga-gis-lts 
```

**Comment by alazarolop** [comment]
My mistake, I thought I had uninstall everything from previous test. I've removed home-brew and installed everything from scratch, but it gets stop at the same point:

https://gist.github.com/3289fb779ef062efca848dd092d5b05b

**Comment by fjperini** [comment]
@alazarolop I will use the rest of the day to solve this at once.

**Comment by fjperini** [comment]
@alazarolop I solved the problem! 🎉

**Comment by fjperini** [comment]
@alazarolop I managed to build with GRASS and SAGA, but when I tried to do everything again with SAGA failed, some step is slipping away. I'll review it with more time.

Despite this, I have found a quick solution. You can use QGIS 2 with GRASS and SAGA without problems.

You can use the bottle (or build with isolation if you need it) ... then you just need to correctly configure the plugins and you can use GRASS and SAGA. Checked, it works!

The same for other plugins, you just need to configure the routes well and make sure you have the dependencies installed.

If you consider complex to configure everything, I can help you remotely.

You let me know when you are available. I will guide you.

**Comment by alazarolop** [comment]
Thank you! I did what you said and it works. Unfortunately I got it in my VM, but not in my main machine, probably because I keep installed GRASS 7 and SAGA as I need them for QGIS 3 and even though I just used the `--with-isolation` flag. Is it compulsory to use this flag in order to coexist with QGIS 3?

In the meantime I managed to get GRASS 7 to work with R, so I don't depend on QGIS 2 working with GRASS and SAGA and I can wait for a solution if there are more urgent matters.

**Comment by fjperini** [comment]
@alazarolop I really do not know if it is so necessary, I think that if there is nothing installed outside of homebrew it should work with or without isolation.

If you can try on your machine, I tried it together with QGIS 3 and both work without any conflict. I did it with the bottle of `qgis-ltr@2` and configuring the plugins' paths and everything worked perfectly. By doing this you will be able to use QGIS 2 with GRASS, SAGA, R, Taudem, and the others that are available.

**Comment by fjperini** [comment]
As a data: the flags is to install optional dependencies and/or extra configurations. If the ones you require are already installed and you can configure them in QGIS manually, it is not necessary to build with the flags.

**Comment by alazarolop** [comment]
That's great, I hadn't reckoned it. 

@fjperini TBH I have never manually configured QGIS. I took a look at the "Options" panel in QGIS 2, do I need to add plugins' path as "Environmental variables"? Could you give some indications perhaps?

**Comment by alazarolop** [comment]
> As a data: the flags is to install optional dependencies and/or extra configurations. If the ones you require are already installed and you can configure them in QGIS manually, it is not necessary to build with the flags.

BTW, does it mean I could avoid building QGIS 3 if I manually add paths to GRASS, SAGA, OTB later? Could 3D view be included in futures bottles?

**Comment by fjperini** [comment]
Of course, you can configure everything manually, adding "Environment variables" for the GDAL_DATA type, etc. and from Preferences/Prossesing to configure the plugins.

The bottle of `qgis` already has a large part of the flags by default, among them `3d`. We only leave those that require a manual intervention or consideration of the user.

**Comment by fjperini** [comment]
For plugins, for example GRASS:
<img width="1440" alt="captura de pantalla 2019-03-08 a la s 11 58 12" src="https://user-images.githubusercontent.com/21315242/54036268-f784fb80-4199-11e9-93e1-e199d6089339.png">
For the system environment:
<img width="1440" alt="captura de pantalla 2019-03-08 a la s 11 59 20" src="https://user-images.githubusercontent.com/21315242/54036165-a83ecb00-4199-11e9-9796-e53d365e1720.png">
In case you want to add others.

You can see that it works:
<img width="1440" alt="captura de pantalla 2019-03-08 a la s 12 04 20" src="https://user-images.githubusercontent.com/21315242/54036495-86921380-419a-11e9-8808-5ddfab5d749c.png">

**Comment by alazarolop** [comment]
@fjperini Thank you for the clues.

But I'm getting stuck again with `qgis-ltr@2`. I installed from bottle in my main machine and it didn't run from terminal nor from the .app throwing this message:

```
Dyld Error Message:
  Library not loaded: /usr/local/opt/spatialindex/lib/libspatialindex.4.dylib
  Referenced from: /usr/local/Cellar/qgis-ltr@2/2.18.28_1/QGIS.app/Contents/MacOS/QGIS
  Reason: image not found
```
So I repeated the process in a clean VM and I got the same message. Should I link something to fix the "libspatialindex.4.dylib" issue?

**Comment by fjperini** [comment]
Well, it is because the library was updated and it was built with the previous one.

Two options: rebuild `qgis-ltr@2` or create a temporary link with that name to the new one `ls -n ibspatialindex.4.dylib libspatialindex.X.dylib`

**Comment by alazarolop** [comment]
It works like a charm! 
Muchas gracias por toda la ayuda y disculpa por las molestias 👌🏼

**Comment by fjperini** [comment]
@alazarolop De nada!

We are working to solve all the problems.

What I suggested to you works, later I will try to reconstruct the bottle of `qgis-ltr@2` with all the options by default.
