### ISSUE TITLE
qgis 3.6 build fails

### ISSUE THREAD

**Issue by nextstopsun** [OSGeo/homebrew-osgeo4mac#744]
I'm building with:
```
brew install --with-3d --with-api-docs --with-gpsbabel --with-grass --with-isolation --with-lastools --with-mssql --with-oracle --with-orfeo --with-qspatialite --with-r --with-saga --with-server --with-taudem --with-whitebox --verbose qgis
```
I get an error when building `qgsfeaturerequest.cpp`
```
ninja: build stopped: subcommand failed:
```
Full `brew gist-logs` output [here](https://gist.github.com/c0c71c21b156c9ce222db80ca6611cd5)

**Comment by fjperini** [comment]
@nextstopsun option `--with-api-docs` is the one that fails, there must be some problem with those files.

You can remove `--with-api-docs`, then I'll review it. I think you have to report it to the developers.

**Comment by nextstopsun** [comment]
@fjperini Thanks, giving it a try without this option. I'll report here.

**Comment by nextstopsun** [comment]
@fjperini Now having another [one](https://gist.github.com/720e7bec1eb0cd014dca4d0b32ca3540)
`qsql_ocispatial.cpp`

**Comment by fjperini** [comment]
```
$ brew unlink python && brew link --force python
$ brew reinstall ninja gsl python qt sip-qt5 pyqt-qt5 pyqt5-webkit qscintilla2-qt5 six bison flex pkg-config
$ brew link --overwrite pyqt-qt5
$ brew unlink gettext && brew link --force gettext
```

**Comment by nextstopsun** [comment]
@fjperini Did all that already

**Comment by fjperini** [comment]
@nextstopsun ok, give me a few hours and I'll check this.

**Comment by nextstopsun** [comment]
Removing `--with-oracle` didn't help either

**Comment by fjperini** [comment]
is related to `sip`

$ brew unlink python && brew link --force python
$ brew uninstall --ignore-dependencies qt sip-qt5 pyqt-qt5 pyqt5-webkit qscintilla2-qt5
$ brew install qt sip-qt5 pyqt-qt5 pyqt5-webkit qscintilla2-qt5
$ brew link --overwrite qt sip-qt5 pyqt-qt5 pyqt5-webkit qscintilla2-qt5
$ brew unlink qt sip-qt5 pyqt-qt5 pyqt5-webkit qscintilla2-qt5 && brew link --force qt sip-qt5 pyqt-qt5 pyqt5-webkit qscintilla2-qt5

**Comment by nextstopsun** [comment]
Now it fails on install stage:
```
Error: An exception occurred within a child process:
  Errno::EPERM: Operation not permitted @ rb_file_s_symlink - (../../../../../../../opt/matplotlib/lib/python3.7/site-packages/__pycache__, /usr/local/Cellar/qgis/3.6.0/QGIS.app/Contents/Resources/python/__pycache__/__pycache__) 
```

**Comment by fjperini** [comment]
Well, I think I know what happens.

Probably changed `matplotlib`, you will need to regenerate qgis-res and then install qgis.

**Comment by nextstopsun** [comment]
No, haven't changed `matplotlib`.
I've reinstalled `qgis-res` and I'm getting the same error.
Full logs [here](https://gist.github.com/cdc951e3f15bcd8ce8870ad931763d4d)

**Comment by fjperini** [comment]
You should not have this problem, it can be something with your Homebrew installation.
Keep in mind that if you compile in CI then you should build on any other machine.
I am solving the integration with Circle CI, maybe we can build a bottle with all the options, so that nobody has to build on their machines.

**Comment by nextstopsun** [comment]
I've installed latest grass formula.
How can I solve a problem with grass?

**Comment by nextstopsun** [comment]
Regarding `matplotlib` : 
`/usr/local/opt/matplotlib/lib/python3.7/site-packages/__pycache__` is a folder, not a file.
Why does `rb_file_s_symlink` consider it a file?

**Comment by fjperini** [comment]
Are you still having the problem with matplotlib?

It seems to be a problem related to Qt and GRASS.

**Comment by nextstopsun** [comment]
I'm doing a complete rebuild of brew bundle now to make sure everything is installed from scratch. I'll get back with my results.

**Comment by fjperini** [comment]
@luispuerto I have managed to complete the integration with Circle CI :tada: This will allow us to have more build time to generate bottles of a given tool with all its flags.
In this way, a complete QGIS will be obtained and users will not have to build again and again.

I will dedicate the next hours to optimize formulas and scripts.

**Comment by nextstopsun** [comment]
@fjperini I've managed to build qgis at last! `matplotlib` formula doesn't compile from source, had to pour from bottle. Didn't see any problems with `Qt` and `GRASS`. 
Thanks a lot for your help.

**Comment by fjperini** [comment]
@nextstopsun Great! I'm glad to know what you managed to build 🎉 

We will be creating bottles built with the most used flags until we have complete versions so that the user does not have to build if they want QGIS with additional supports and tools.

p/d: I will try to create a report with respect to mmsql, so that the developers can review it.

**Comment by luispuerto** [comment]
@fjperini sounds really great!
