### ISSUE TITLE
Using homebrew recipe to develop QGIS?

### ISSUE THREAD

**Issue by michaelkirk** [OSGeo/homebrew-osgeo4mac#75]
Hi @dakcarto, I'm just starting working with developing QGIS, and am a bit turned off by the [official Mac build instructions](https://github.com/qgis/QGIS/blob/master/INSTALL#L936) which instruct you to manually fetch and compile several build dependencies. Whenever possible I prefer to use homebrew to install these sorts of dependencies in a uniform way.

I can get qgis-26 from your repository (thanks!) to download and build from source, so, in theory, I already have a working build environment for QGIS. I was wondering, do you have any advice for using homebrew to build QGIS for your local development purposes? e.g. can I point "head" at my local QGIS source directory, or can I export the build commands that homebrew issues?

I think that making it really easy to develop QGIS would be a good thing to encourage a casual committers like myself to get more involved.

**Comment by dakcarto** [comment]
Hi Michael,

Thank you for reporting and your interest in QGIS development. I have wrote
up a description on how to do use this tap to start QGIS dev work. See:

https://github.com/OSGeo/homebrew-osgeo4mac/wiki/Developing-on-QGIS-using-OSGeo4Mac

Please reply here if you have any issues with that setup.

Regards,

Larry

On Saturday, January 24, 2015, Michael Kirk <notifications@github.com>
wrote:

> Hi @dakcarto <https://github.com/dakcarto>, I'm just starting working
> with developing QGIS, and am a bit turned off by the official Mac build
> instructions <https://github.com/qgis/QGIS/blob/master/INSTALL#L936>
> which instruct you to manually fetch and compile several build
> dependencies. Whenever possible I prefer to use homebrew to install these
> sorts of dependencies in a uniform way.
>
> I can get qgis-26 from your repository (thanks!) to download and build
> from source, so, in theory, I already have a working build environment for
> QGIS. I was wondering, do you have any advice for using homebrew to build
> QGIS for your local development purposes? e.g. can I point "head" at my
> local QGIS source directory, or can I export the build commands that
> homebrew issues?
>
> I think that making it really easy to develop QGIS would be a good thing
> to encourage a casual committers like myself to get more involved.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OSGeo/homebrew-osgeo4mac/issues/75>.
>


-- 

Larry Shaffer
Dakota Cartography
Black Hills, South Dakota

**Comment by michaelkirk** [comment]
This is *exactly* what I was looking for. I'll follow through and submit updates to the documentation if I come across anything useful. Thanks so much Larry!

**Comment by michaelkirk** [comment]
One hangup I encountered was your [example of how to run tests in the wiki](https://github.com/OSGeo/homebrew-osgeo4mac/wiki/Developing-on-QGIS-using-OSGeo4Mac#run-unit-tests).

`HOMEBREW_PREFIX` wasn't defined in my local environment. Is this a standard env variable that all users of homebrew should be expected to have? I didn't have it.

Consider adding this to the top:
```
export HOMEBREW_PREFIX=`brew --prefix`
```

Your guide has been really helpful. Thanks Larry.

**Comment by michaelkirk** [comment]
Also, FYI, there are only 24 failures on Yosemite/[qgis master](https://github.com/qgis/qgis/tree/1eec3b9)/Qt 4.8.6.

Which is better than the 30 failing on [CDash (Lion) right now](http://dash.orfeo-toolbox.org/viewTest.php?onlyfailed&buildid=170432.)

```
 30 81% tests passed, 24 tests failed out of 125
 29 
 28 Total Test time (real) = 242.17 sec
 27 
 26 The following tests FAILED:
 25          16 - qgis_rendererstest (Failed)
 24          18 - qgis_blendmodestest (Failed)
 23          31 - qgis_composerutils (Failed)
 22          38 - qgis_composermapgridtest (Failed)
 21          40 - qgis_composereffectstest (Failed)
 20          42 - qgis_composerrotationtest (Failed)
 19          44 - qgis_atlascompositiontest (Failed)
 18          47 - qgis_composertablev2test (OTHER_FAULT)
 17          52 - qgis_composerscalebartest (Failed)
 16          57 - qgis_rasterfilltest (Failed)
 15          58 - qgis_shapebursttest (Failed)
 14          59 - qgis_invertedpolygontest (Failed)
 13          64 - qgis_legendrenderertest (Failed)
 12          78 - qgis_mapcanvastest (Failed)
 11          80 - qgis_openstreetmaptest (Failed)
 10          85 - PyQgsLocalServer (Failed)
  9          93 - PyQgsBlendModes (Failed)
  8         108 - PyQgsComposerMapGrid (Failed)
  7         109 - PyQgsComposerEffects (Failed)
  6         113 - PyQgsAtlasComposition (Failed)
  5         117 - PyQgsPalLabelingCanvas (Failed)
  4         118 - PyQgsPalLabelingComposer (Failed)
  3         119 - PyQgsPalLabelingServer (Failed)
  2         121 - PyQgsSpatialiteProvider (Failed)
```

**Comment by dakcarto** [comment]
On that page there is...

> Note: scripts expect the HOMEBREW_PREFIX environment variable to be set, e.g. in your .bash_profile:

If you do the following:

```sh
export HOMEBREW_PREFIX=`brew --prefix`
```
this assumes you already have `HOMEBREW_PREFIX/bin` on `PATH` in order to get an appropriate `brew` output, i.e. chicken-and-egg problem. :smile:  

Generally, I hard-code the `HOMEBREW_PREFIX` path in my bash (or build script) environment, which allows you to define a completely separate prefix than the one available via `brew --prefix` on `PATH`. For example, I have multiple Homebrew installs on one Mac for testing different build scenarios, without messing up my main Homebrew install in `/usr/local`.
