### ISSUE TITLE
orfeo-40 won't build (cmake error)

### ISSUE THREAD

**Issue by ashaw** [OSGeo/homebrew-osgeo4mac#76]
trying to install orfeo-40 --verbose and getting:

```
==> cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/orfeo-40/4.0.0_1 -DCMAKE_BUILD_TYPE=None -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DBUILD_APPLICATIONS=ON -DBUILD_TESTING=OFF -DOTB_USE_EXTERNAL_OPENTHREADS=OFF -DBUILD_SHARED_LIBS=ON -DOTB_WRAP_QT=ON -DOTB_USE_EXTERNAL_BOOST=OFF -DOTB_USE_EXTERNAL_ITK=OFF -DBUILD_EXAMPLES=OFF -DOTB_WRAP_JAVA=OFF -DOTB_USE_PATENTED=OFF -DOTB_WRAP_PYTHON=OFF -DITK_USE_FFTWF=OFF -DITK_USE_FFTWD=OFF -DITK_USE_SYSTEM_FFTW=OFF -DOTB_USE_OPENCV=OFF

[...]

CMake Error at /usr/local/Cellar/cmake/3.1.1/share/cmake/Modules/CMakeExportBuildSettings.cmake:17 (message):
  The functionality of this module has been dropped as of CMake 2.8.  It was
  deemed harmful (confusing users by changing their compiler).  Please remove
  calls to the CMAKE_EXPORT_BUILD_SETTINGS macro and stop including this
  module.  If this project generates any files for use by external projects,
  remove any use of the CMakeImportBuildSettings module from them.
Call Stack (most recent call first):
  CMakeLists.txt:355 (include)


-- Configuring incomplete, errors occurred!
See also "/tmp/orfeo-40-bAFzP0/OTB-b06793664fbc/build/CMakeFiles/CMakeOutput.log".
See also "/tmp/orfeo-40-bAFzP0/OTB-b06793664fbc/build/CMakeFiles/CMakeError.log".
/usr/libexec/java_home --failfast 
==> Formula
Tap: osgeo/homebrew-osgeo4mac
Path: /usr/local/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/orfeo-40.rb
==> Configuration
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: b968e5af296256e2e2c84177d1a00b44773e32c9
Last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: 8-core 64-bit haswell
OS X: 10.10.1-x86_64
Xcode: 6.1.1
CLT: 6.1.1.0.1.1416017670
Clang: 6.0 build 600
X11: 2.7.7 => /opt/X11
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/var/rbenv/shims/ruby => /usr/local/var/rbenv/versions/2.0.0-p598/bin/ruby
/usr/libexec/java_home --failfast 
Java: 1.6.0_65
==> ENV
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j8
CMAKE_PREFIX_PATH: /usr/local/opt/readline:/usr/local/opt/sqlite:/usr/local/opt/libxml2:/usr/local/opt/liblwgeom:/usr/local/opt/openssl:/usr/local
CMAKE_INCLUDE_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
CMAKE_FRAMEWORK_PATH: /usr/local/opt/qt/Frameworks:/usr/local/opt/python/Frameworks
PKG_CONFIG_PATH: /usr/local/opt/libpng/lib/pkgconfig:/usr/local/opt/libtiff/lib/pkgconfig:/usr/local/opt/proj/lib/pkgconfig:/usr/local/opt/sqlite/lib/pkgconfig:/usr/local/opt/freexl/lib/pkgconfig:/usr/local/opt/libxml2/lib/pkgconfig:/usr/local/opt/json-c/lib/pkgconfig:/usr/local/opt/libspatialite/lib/pkgconfig:/usr/local/opt/openssl/lib/pkgconfig:/usr/local/opt/postgresql/lib/pkgconfig:/usr/local/opt/gdal/lib/pkgconfig:/usr/local/opt/qt/lib/pkgconfig:/usr/local/opt/muparser/lib/pkgconfig:/usr/local/opt/minizip/lib/pkgconfig:/usr/local/opt/tinyxml/lib/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Library/ENV/pkgconfig/10.10
ACLOCAL_PATH: /usr/local/opt/libxml2/share/aclocal:/usr/local/share/aclocal
PATH: /usr/local/opt/python/bin:/usr/local/Library/ENV/4.3:/usr/local/opt/cmake/bin:/usr/local/opt/libpng/bin:/usr/local/opt/jpeg/bin:/usr/local/opt/giflib/bin:/usr/local/opt/libtiff/bin:/usr/local/opt/proj/bin:/usr/local/opt/libgeotiff/bin:/usr/local/opt/geos/bin:/usr/local/opt/sqlite/bin:/usr/local/opt/libxml2/bin:/usr/local/opt/openssl/bin:/usr/local/opt/postgresql/bin:/usr/local/opt/gdal/bin:/usr/local/opt/qt/bin:/usr/local/opt/python/bin:/usr/bin:/bin:/usr/sbin:/sbin

Error: orfeo-40 4.0.0 did not build
```

**Comment by rashadkm** [comment]
OTB is not compatible with CMake 3.0 right now.

**Comment by dakcarto** [comment]
@ashaw Could you try `orfeo-42` instead? Pretty sure I have been compiling it with CMake 3 (could be wrong about that).

**Comment by rashadkm** [comment]
@dakcarto, I was referring to this cmake policy - http://www.cmake.org/cmake/help/v3.0/policy/CMP0033.html
which earlier creates problem when using cmake 3.0. But this one seems to be new and need to reported on tracker. I can take care of reporting once the user confirms with orfeo-42

**Comment by ashaw** [comment]
@dakcarto getting the same error with `orfeo-42`

    CMake Error at /usr/local/Cellar/cmake/3.1.1/share/cmake/Modules/CMakeExportBuildSettings.cmake:17 (message):
      The functionality of this module has been dropped as of CMake 2.8.  It was
      deemed harmful (confusing users by changing their compiler).  Please remove
      calls to the CMAKE_EXPORT_BUILD_SETTINGS macro and stop including this
      module.  If this project generates any files for use by external projects,
      remove any use of the CMakeImportBuildSettings module from them.
    Call Stack (most recent call first):
      CMakeLists.txt:362 (include)


    -- Configuring incomplete, errors occurred!
    See also "/tmp/orfeo-42-NYclhx/OTB-4.2.1/build/CMakeFiles/CMakeOutput.log".
    See also "/tmp/orfeo-42-NYclhx/OTB-4.2.1/build/CMakeFiles/CMakeError.log".
    /usr/libexec/java_home --failfast 
    ==> Formula
    Tap: osgeo/homebrew-osgeo4mac
    Path: /usr/local/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/orfeo-42.rb
    ==> Configuration
    HOMEBREW_VERSION: 0.9.5
    ORIGIN: https://github.com/Homebrew/homebrew
    HEAD: b968e5af296256e2e2c84177d1a00b44773e32c9
    Last commit: 27 hours ago
    HOMEBREW_PREFIX: /usr/local
    HOMEBREW_CELLAR: /usr/local/Cellar
    CPU: 8-core 64-bit haswell
    OS X: 10.10.1-x86_64
    Xcode: 6.1.1
    CLT: 6.1.1.0.1.1416017670
    Clang: 6.0 build 600
    X11: 2.7.7 => /opt/X11
    System Ruby: 2.0.0-p481
    Perl: /usr/bin/perl
    Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/bin/python2.7
    Ruby: /usr/local/var/rbenv/shims/ruby => /usr/local/var/rbenv/versions/2.0.0-p598/bin/ruby
    /usr/libexec/java_home --failfast 
    Java: 1.6.0_65
    ==> ENV
    HOMEBREW_CC: clang
    HOMEBREW_CXX: clang++
    MAKEFLAGS: -j8
    CMAKE_PREFIX_PATH: /usr/local/opt/readline:/usr/local/opt/sqlite:/usr/local/opt/libxml2:/usr/local/opt/liblwgeom:/usr/local/opt/openssl:/usr/local
    CMAKE_INCLUDE_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
    CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
    CMAKE_FRAMEWORK_PATH: /usr/local/opt/qt/Frameworks:/usr/local/opt/python/Frameworks
    PKG_CONFIG_PATH: /usr/local/opt/libpng/lib/pkgconfig:/usr/local/opt/libtiff/lib/pkgconfig:/usr/local/opt/proj/lib/pkgconfig:/usr/local/opt/sqlite/lib/pkgconfig:/usr/local/opt/freexl/lib/pkgconfig:/usr/local/opt/libxml2/lib/pkgconfig:/usr/local/opt/json-c/lib/pkgconfig:/usr/local/opt/libspatialite/lib/pkgconfig:/usr/local/opt/openssl/lib/pkgconfig:/usr/local/opt/postgresql/lib/pkgconfig:/usr/local/opt/gdal/lib/pkgconfig:/usr/local/opt/qt/lib/pkgconfig:/usr/local/opt/muparser/lib/pkgconfig:/usr/local/opt/minizip/lib/pkgconfig:/usr/local/opt/tinyxml/lib/pkgconfig
    PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Library/ENV/pkgconfig/10.10
    ACLOCAL_PATH: /usr/local/opt/libxml2/share/aclocal:/usr/local/share/aclocal
    PATH: /usr/local/opt/python/bin:/usr/local/Library/ENV/4.3:/usr/local/opt/cmake/bin:/usr/local/opt/libpng/bin:/usr/local/opt/jpeg/bin:/usr/local/opt/giflib/bin:/usr/local/opt/libtiff/bin:/usr/local/opt/proj/bin:/usr/local/opt/libgeotiff/bin:/usr/local/opt/geos/bin:/usr/local/opt/sqlite/bin:/usr/local/opt/libxml2/bin:/usr/local/opt/openssl/bin:/usr/local/opt/postgresql/bin:/usr/local/opt/gdal/bin:/usr/local/opt/qt/bin:/usr/local/opt/python/bin:/usr/bin:/bin:/usr/sbin:/sbin

    Error: orfeo-42 4.2.1 did not build

**Comment by ashaw** [comment]
@dakcarto BTW, I got it to build by temporarily uninstalling cmake and installing cmake 2.8 from [this revision](https://github.com/Homebrew/homebrew/blob/716d4a9b75f7a3e28c7f5d15c5ab5f3beffe1e3b/Library/Formula/cmake.rb), then installing `orfeo-42`. Not a long-term solution, but OK in a pinch.

**Comment by rashadkm** [comment]
logged on otb bugtracker 
http://bugs.orfeo-toolbox.org/view.php?id=950#c2569

**Comment by grizonnetm** [comment]
FYI, I've pushed a patch in OTB trunk to provide support for cmake 3. Let me know if it works for you:

http://hg.orfeo-toolbox.org/OTB/rev/beb8272358c6

**Comment by ashaw** [comment]
@grizonnetm awesome, thank you!

**Comment by Abdel-razek** [comment]
@grizonnetm @ashaw May I ask, how to use install via the OTB trunk you mentioned? (on MacOS Yosmite)

**Comment by grizonnetm** [comment]
@ashaw @Abdel-razek  FYI there are ongoing refactoring in OTB trunk and the way that third parties are  handled. It will be released as OTB 5.0. It should lead to minor modifications to OTB packagers. More info on otb mailing list and blog soon.

Last stable release is 4.4

**Comment by Abdel-razek** [comment]
@grizonnetm @ashaw thanks for the clarification

**Comment by dakcarto** [comment]
Closing as related to deprecated formulae. Reopen if necessary.

Try `orfeo5` formula.
