### ISSUE TITLE
qt5-webkit: failed to download resource

### ISSUE THREAD

**Issue by juanfrans** [OSGeo/homebrew-osgeo4mac#762]
While trying to upgrade qgis through homebrew from version 3.4.4_4 to version 3.6.0 I hit the following error:
`Failed to download resource "qt5-webkit"`

The upgrade then tries to build from source but stalls at:
`==> cmake -G Ninja -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/qt5-webkit/5.12.1_1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DPORT=Qt -DENABLE_TOOLS=OFF -DCMAKE_MACOSX_RPATH=OFF -DEGPF_SET`
`==> cmake --build . --target all -- -j 12`

Any ideas?

**Comment by fjperini** [comment]
Building in Circle CI, wait for the bottle to be generated.

I updated the formula.

**Comment by fjperini** [comment]
@juanfrans Well, the `qt5-webkit` bottle is already generated. And the formula for `qgis` was updated. If you are not going to use `qgis` with additional supports, you do not need to build, just wait until the bottle is generated. If you are going to use flags, you can build `qgis`.

We close this problem, if another problem arises ... we can reopen it.

**Comment by fjperini** [comment]
@juanfrans Now you can install `qgis`, the bottles have already been generated.

**Comment by juanfrans** [comment]
@fjperini Great! Thank you.

**Comment by fjperini** [comment]
@juanfrans Once installed, we close this issue.
Will you use the bottles or will you install from source?

**Comment by juanfrans** [comment]
@fjperini Use the bottles. Just finished installing it. All good.

**Comment by fjperini** [comment]
@juanfrans You can confirm that you do not have this error https://github.com/OSGeo/homebrew-osgeo4mac/issues/767 I do not have it either.

**Comment by juanfrans** [comment]
@fjperini yes, I don't get that error.

**Comment by fjperini** [comment]
Thank you!
We close this issue.
