### ISSUE TITLE
qgis: processing isn't working - libopenblasp-r0.3.5.dylib not found

### ISSUE THREAD

**Issue by luispuerto** [OSGeo/homebrew-osgeo4mac#767]
I get the following messages when I open QGIS with the last formulae. 

![screen shot 2019-03-01 at 08 48 15](https://user-images.githubusercontent.com/22882880/53621740-33e7b300-3c00-11e9-96ba-eefe20322aec.png)
![screen shot 2019-03-01 at 08 48 18](https://user-images.githubusercontent.com/22882880/53621741-33e7b300-3c00-11e9-8267-a708119e31cf.png)
![screen shot 2019-03-01 at 08 48 31](https://user-images.githubusercontent.com/22882880/53621742-33e7b300-3c00-11e9-9673-bdd87c637bd8.png)

You can see the complete output in [this gist](https://gist.github.com/9ab2153f1008c3144ebe5bf43a534299).

**Comment by fjperini** [comment]
@luispuerto Is the latest version of the formula? I just updated it.

**Comment by luispuerto** [comment]
Both are the latest I just undated like an hour ago. I can recheck... 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fjperini** [comment]
The error is in this library
```
Library not loaded: /usr/local/opt/openblas/lib/libopenblasp-r0.3.5.dylib
```

**Comment by luispuerto** [comment]
I've tried to reinstall all the pip modules I have installed just in case... but it isn't working. 

is qgis-res in a bottle now? perhaps it's that? I don't know. 

by the way... I have to reinstall R from sethfore to be able to install qgis-res

**Comment by fjperini** [comment]
I have checked and on my machine this library is located.

A clarification on another topic:

`homebrew-core/r` is by default. to use the other version of R, the simplest thing will be to change the name of the folder when installing `qgis` and then restore it. It's because I generated the bottle of `qgis-res` with all the flags and it would require R.

**Comment by fjperini** [comment]
Yes, now it's an all-inclusive bottle.

**Comment by luispuerto** [comment]
no problem about R! It's easy to solve... 

About the res... I really don't know. I'll check it later again.

**Comment by fjperini** [comment]
Remember, first update `qgis-res` and then `qgis`.

**Comment by luispuerto** [comment]
Yeah I know. It was that way. I just undated so first updated res and then installed QGIS. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by luispuerto** [comment]
I've reinstalled both things... first rest and then qgis and the result is the same.

**Comment by luispuerto** [comment]
@fjperini this 
>`homebrew-core/r` is by default. to use the other version of R, the simplest thing will be to change the name of the folder (`/usr/local/Cellar/r-bk`) when installing `qgis` and then restore it. It's because I generated the bottle of `qgis-res` with all the flags and it would require R.

isn't working for me. I do: 

```sh
$ mv /usr/local/cellar/r /usr/local/cellar/r-back
# after qgis install finnish... 
$ trash /usr/local/cellar/r
$ mv /usr/local/cellar/r-back /usr/local/cellar/r
```
and doesn't work.

**Comment by luispuerto** [comment]
I think that perhaps this error it's due to the formula is bottled. I'll try later building it from source again, as I've done before. I haven't have this problem till now.

**Comment by fjperini** [comment]
Using the bottles and without that problem.

**Comment by fjperini** [comment]
@juanfrans recently installed using the bottles and it works properly https://github.com/OSGeo/homebrew-osgeo4mac/issues/762

**Comment by luispuerto** [comment]
openblas wasn't properly installed. 

```shell 
$ brew reinstall openblas 
```
fixed the issue... *stupid problems... stupid solutions*.

**Comment by Notoncebut2x** [comment]
Hi all, getting the same error, but with: `libopenblasp-r0.3.6.dylib`.  Happy to open a new issue but since it is so similar thought I would post here.  ```
ImportError: dlopen(/usr/local/opt/osgeo-qgis/QGIS.app/Contents/MacOS/../Resources/python/numpy/core/_multiarray_umath.cpython-37m-darwin.so, 2): Library not loaded: /usr/local/opt/openblas/lib/libopenblasp-r0.3.6.dylib
  Referenced from: /usr/local/Cellar/osgeo-qgis-res/3.8.0/libexec/vendor/lib/python3.7/site-packages/numpy/core/_multiarray_umath.cpython-37m-darwin.so
  Reason: image not found
```

**Comment by Notoncebut2x** [comment]
> Hi all, getting the same error, but with: `libopenblasp-r0.3.6.dylib`. Happy to open a new issue but since it is so similar thought I would post here. I tried reinstalling openblas and all that jazz...
> 
> ```
> ImportError: dlopen(/usr/local/opt/osgeo-qgis/QGIS.app/Contents/MacOS/../Resources/python/numpy/core/_multiarray_umath.cpython-37m-darwin.so, 2): Library not loaded: /usr/local/opt/openblas/lib/libopenblasp-r0.3.6.dylib
>   Referenced from: /usr/local/Cellar/osgeo-qgis-res/3.8.0/libexec/vendor/lib/python3.7/site-packages/numpy/core/_multiarray_umath.cpython-37m-darwin.so
>   Reason: image not found
> ```

Sorry didn't see: [issues 1245](https://github.com/OSGeo/homebrew-osgeo4mac/issues/1245).  @luispuerto fix in that worked for me.
