### ISSUE TITLE
Proposal to rename formulas

### ISSUE THREAD

**Issue by fjperini** [OSGeo/homebrew-osgeo4mac#769]
Proposal to rename all formulas that may conflict with those of `homebrew-core` and/or other tap.

For example: `gdal2` `postgis2`, `liblas-gdal2`, etc.

Or applying all the changes to `homebrew-core`, but the process would be slower and we would not have as much control over the updates or flags that they add or remove according to the criteria that the Homebrew people adopt.

That is why it is better to rename them and that the user only installs our versions.

Having two installed versions of the same package can be a problem. See: https://github.com/OSGeo/homebrew-osgeo4mac/issues/712

@luispuerto @3nids @miguelangelperg

**Comment by luispuerto** [comment]
In mi opinion applying the changes to the core isn't a solution. If you need options, they aren't going to provide them. Last time this popped up at the discurse forum, the answer was if you need option create your own tap. Literally. 

Renaming would be good, but I would love to not have more than one formula that do the same. In other words, if we have a create a gdal that have options —because we need it— I don't see the point of having another gdal for the core formulas that need it.

**Comment by fjperini** [comment]
Not only would it be necessary to change the name, but we could also generate the bottles with all the optional dependencies, in this way it would no longer be necessary for each of them to build on their machines.

Changing the name of the bottles would solve the problem of having two versions of the same package (there will only be one), resolving conflicts by linking it.

**Comment by miguelangelperg** [comment]
Hi. I think it's a good idea. But I can only substantiate it from a couple of observations from what seems logical to me:
-  It is evident that the formulas referring to the same version should be named in all the _tap_ in the same way.    
-  It would seem to me a good idea that in the tap the generic name for the current version of the formula is adopted. 

For example, if **Gdal** has the current version of 2, this is what should be in the tap **gdal**. Version 1 of gdal could be in **gdal1**.
This would be applicable also for **postgis**, if the current formula is version 2, this version will be the one stored under the tap **postgis**. While version 1 of postgis could be **postgis1**.

**Comment by luispuerto** [comment]
> For example, if **Gdal** has the current version of 2, this is what should be in the tap **gdal**. Version 1 of gdal could be in **gdal1**.
> This would be applicable also for **postgis**, if the current formula is version 2, this version will be the one stored under the tap **postgis**. While version 1 of postgis could be **postgis1**.

This... as far as I know is like this. Current version is the simple name and previous versions are marked with an `@`. For instance. `Python` and `Python@2`. So it should be `gdal` and `gdal@1` and `postgis` and `postgis@1` and so on and so forth. 

The gdal naming come from I really don't know why that homebrew core had for really long time outdated gdal in its formulae. They had just gdal 1 in their formula and they didn't update the formula to gdal 2. I'm sure that was for a really good reason, but I really don't know why. 

It seems that the best way to proceed is to have the same name and them pin the tap —this up to the user perhaps— so this tap formulae take precedence. Which I think it's wise.

**Comment by fjperini** [comment]
I agree.
We will proceed to use that logic when renaming the formulas.

**Comment by fjperini** [comment]
We will return to this later!

**Comment by miguelangelperg** [comment]
Hi @fjperini, @luispuerto 

I can not install postgis in any of the postgres versions (@ 10 and 11).

```
# select postgis_full_version() ;
ERROR:  could not access file "$libdir/postgis-2.4": No such file or directory
CONTEXT:  SQL statement "SELECT public.postgis_lib_version()"
PL/pgSQL function postgis_full_version() line 25 at SQL statement
```
```
# ALTER EXTENSION postgis UPDATE;
ERROR:  could not open extension control file "/usr/local/Cellar/postgresql@10/10.6_1/share/postgresql@10/extension/postgis.control": No such file or directory   
```

My postgis facilities for almost two years have been obtained from the tap osgeo4mac.

   1. Before the upgrade to qgis 3.4.2 I had in my Cellar: postgis and within postgis the different versions: 2.4.4_1 and the linked 2.5.0. Both versions built against gdal version 2.
My GDAL was in my Cellar in the gdal folder. Inside it, were the different versions that had been installed: 2.3.1_1 and 2.3.1_2 (linked).
Postgis without problems

I do not know if it's related, but:

2. After the upgrade, I keep the previous Cellar, which are still linked. But I also have:
postgis2 with version 2.5.1_1
gdal2 with version 2.4.0

If I request: `brew uninstall postgis`
I get:
```
$ brew uninstall postgis

Error: Refusing to uninstall /usr/local/Cellar/postgis/2.5.0
because it is required by postgis2, which is currently installed.
You can override this and force removal with:
  brew uninstall --ignore-dependencies postgis
```

I uninstalled postgis, and linked postgis2, but it does not solve anything. 
I can send details of the experience if it was useful

**Comment by luispuerto** [comment]
@miguelangelperg can you open new issue with this message? I mean... It's better if you create a new issue... because we really don't know if the renaming —that didn't happen yet, just a couple of formulae (none of those were postgis) and we reverted it— is related to your problem.

**Comment by luispuerto** [comment]
relevant: https://github.com/Homebrew/brew/issues/5796#issuecomment-470912951

**Comment by fjperini** [comment]
Then we have two options:

- 1 - rename the formulas so that only ours are installed, but with the warning of the secondary dependencies that come from core ... if we change the name, all the secondary ones must be in the repository.
- 2- use proper names and warn the user to link our versions so there is no conflict with the version from core.

2 is what we are currently doing.

**Comment by miguelangelperg** [comment]
I do not know anything about homebrew. In relation to PostgeSQL, Postgis, Gdal, I imagine that **PostGIS Support Matrix** (https://trac.osgeo.org/postgis/wiki/UsersWikiPostgreSQLPostGIS) is known.
The Homebrew-core formulas are not used because they do not correspond with the right ones?

**Comment by luispuerto** [comment]
> The Homebrew-core formulas are not used because they do not correspond with the right ones?

Homebrew core has stripped its formulae of options, to simplify maintenance.

**Comment by fjperini** [comment]
The main problem is not in the name, although if they were called the same and if only our version is installed, there would be no conflict. But it requires, if we rename everything, to bring all the secondary dependencies to the repo and that the user previously eliminates all the versions that he has installed in his homebrew.

**Comment by fjperini** [comment]
> Homebrew core has stripped its formulae of options, to simplify maintenance.

and it is the reason of our formulas, to have more support.

**Comment by fjperini** [comment]
What I can do:

link all the dependencies to be executed qgis in each session using `bin/qgis`, I'll try. With this everything will be correctly linked and the name will no longer matter.

But you must make a list of all dependencies to link.

And for what they install, make sure everything is properly linked beforehand.

**Comment by luispuerto** [comment]
In other words... we are thinking to rename, but rename into something that has more meaning, but doesn't conflict with core. 

@fjperini perhaps you can leave those formulae as keg only and make qgis call them to the cellar? just an idea!

**Comment by luispuerto** [comment]
I think we need to think this through and perhaps even ask to homebrew maintainers what is in their opinion the best solution... R could have a similar problem.

**Comment by fjperini** [comment]
calling them from Cellar would be somewhat more complicated, since you would have to apply patches to qgis to indicate from where to run the binaries. Although it would be a good solution if we implemented it.
With that we would make sure that everything that is executed within what refers to the paths we want.

linking, seems simpler.

**Comment by fjperini** [comment]
And works:
![link](https://user-images.githubusercontent.com/21315242/54032303-fea70c00-418f-11e9-96e6-c2d9cb1b6ad1.gif)


with this we make sure that the dependencies in conflict are correctly linked when executing qgis.

The file would look something like this:

```
#!/bin/sh

brew unlink qt sip-qt5 pyqt-qt5 qca qscintilla2-qt5 qwt qwtpolar qjson && brew link qt sip-qt5 pyqt-qt5 qca qscintilla2-qt5 qwt qwtpolar qjson --force --overwrite

export PATH=/usr/local/opt/saga-gis-lts/bin:/usr/local/opt/gpsbabel/bin:/usr/local/opt/qt/bin:/usr/local/opt/sip/bin:/usr/local/opt/pyqt/bin:/usr/local/opt/qca/bin:/usr/local/opt/gdal2-python/bin:/usr/local/opt/gdal2/bin:/usr/local/opt/libxml2/bin:/usr/local/opt/gdal2/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/fjperini/bin:/opt/X11/bin:$PATH
export QGIS_BUNDLE=/usr/local/opt/qgis/QGIS.app/Contents
export QGIS_PREFIX_PATH=/usr/local/opt/qgis/QGIS.app/Contents/MacOS
export GDAL_DRIVER_PATH=/usr/local/lib/gdalplugins
export GDAL_DATA=/usr/local/opt/gdal2/share/gdal
export CHECK_DISK_FREE_SPACE=FALSE
export PYTHONPATH=/usr/local/opt/gdal2-python/lib/python3.7/site-packages:/usr/local/opt/qgis/QGIS.app/Contents/Resources/python:/usr/local/opt/qgis/lib/python3.7/site-packages:/usr/local/opt/lib/python3.7/site-packages:$PYTHONPATH
export QT_PLUGIN_PATH=/usr/local/opt/qgis/lib/qt/plugins:/usr/local/opt/qt/plugins:/usr/local/lib/qt/plugins
export QT_AUTO_SCREEN_SCALE_FACTOR=1
export GRASS_PREFIX=/usr/local/opt/grass7/grass-base
export GRASS_SH=/bin/sh
export GRASS_PROJSHARE=/usr/local/opt/proj/share
export GRASS_VERSION=7.6.0
export GRASS_LD_LIBRARY_PATH=/usr/local/opt/grass7/grass-7.6.0/lib
export PROJ_LIB=/usr/local/opt/proj/lib
export GEOTIFF_CSV=/usr/local/opt/libgeotiff/share/epsg_csv
export OSG_LIBRARY_PATH=/usr/local/lib/osgPlugins-3.6.3
/usr/local/opt/qgis/QGIS.app/Contents/MacOS/QGIS "$@"
```

would have to add the other dependencies in conflict

This would work, but we also have to make sure they are the ones used when building and/or installing.

The solution goes through there, that everything is linked correctly, so at the time of installing or running qgis use our versions.

p/d: we have to identify the dependencies that need to be generated with our versions, for example: `pdal`.
