### ISSUE TITLE
Unmet requirements in GQIS 3.6.0_2

### ISSUE THREAD

**Issue by davidorme** [OSGeo/homebrew-osgeo4mac#777]
Hi,

I'm trying to `brew upgrade` qgis from 3.4.4 to 3.6.0-2 and keep getting errors like this:

    Error: An exception occurred within a child process:
      RuntimeError: /usr/local/opt/saga-gis-lts not present or broken

I can `brew install` each of these manually (so far, `opencv@2`, `libharu`, `laszip@2.2`, `liblas-gdal2`, `hdf4`) but it seems odd that the formula isn't installing these as required packages. I suspect I'm missing something simple!

Cheers,
David

**Comment by fjperini** [comment]
@davidorme Recently I updated `saga-gis-lts` to correct the support of liblas. And the bottle was generated correctly.

It seems that it is not linked.

Uninstall `saga-gis-lts`

```
brew uninstall --ignore-dependencies laszip@2.2
brew uninstall --ignore-dependencies liblas-gdal2
brew uninstall --ignore-dependencies saga-gis-lts

brew install saga-gis-lts

brew unlink saga-gis-lts && brew link --force saga-gis-lts
```

and then try again.

**Comment by davidorme** [comment]
Hi,

That solved the issue with the unmet dependencies. The build fails, with messages about some sip files:

sip: Unable to find file "QtCore/QtCoremod.sip"
sip: Unable to find file "QtXml/QtXmlmod.sip"

Full gist here: https://gist.github.com/5f0a2853771d1e26aafa648b36aa94cc

Cheers,
David

**Comment by fjperini** [comment]
To rule out any problem you have in your homebrew installation:

```
$ brew unlink python && brew link --force python
$ brew reinstall ninja gsl python qt sip-qt5 pyqt-qt5 pyqt5-webkit qscintilla2-qt5 six bison flex pkg-config
$ brew link --overwrite pyqt-qt5
$ brew unlink gettext && brew link --force gettext
```
```
$ rm -rf $(brew --cache)
```
and the temporary build files in `/tmp`

An installation that failed previously may have created this link

```
   /usr/local/lib/python3.7/site-packages/PyQt5/uic/widget-plugins/qgis_customwidgets.py
```
you will need to delete it.

If you are going to use several flags, make sure that the system can open the necessary number of files.

```
$ ulimit -n 1024
```

If you only use `qgis` without flags, you do not need to build, will use the generated bottle.

p/d: keep in mind that if it is built in CI, it should be built on any other machine. If your installation fails, it is due to your Homebrew environment, review it.

**Comment by fjperini** [comment]
@davidorme It is likely that you have linked another version of those packages, you need to use the one in this repository.

**Comment by fjperini** [comment]
From logs:

```
Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  gdal
  pyqt-qt5
  r
  numpy
  sip-qt5
  six
  scipy
qscintilla2-qt5
```
Try after doing
```
$ brew unlink python && brew link --force python
$ brew reinstall ninja gsl python qt sip-qt5 pyqt-qt5 pyqt5-webkit qscintilla2-qt5 six bison flex pkg-config
$ brew link --overwrite sip-qt5 pyqt-qt5 qscintilla2-qt5 pyqt5-webkit
$ brew unlink gettext && brew link --force gettext
```

**Comment by davidorme** [comment]
That's done it. Successfully installed. Many thanks.
