### ISSUE TITLE
qgis fails to install on MacOS Mojave

### ISSUE THREAD

**Issue by deg4uss3r** [OSGeo/homebrew-osgeo4mac#789]
```
> brew --version
Homebrew 2.0.3-8-gdb68e7e
Homebrew/homebrew-core (git revision 3d3341; last commit 2019-03-05)
Homebrew/homebrew-cask (git revision 7a1355; last commit 2019-03-05)
```

```
> system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.14.2 (18C54)
      Kernel Version: Darwin 18.2.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
```

Steps taken: 

```
> brew tap OSGeo/homebrew-osgeo4mac
> brew install qgis 
```

Error produced

```
> brew install qgis
==> Installing qgis from osgeo/osgeo4mac
Error: Operation already in progress for sip.formula
Another active Homebrew process is already using sip.formula.
Please wait for it to finish or terminate it to continue.
```

**Comment by fjperini** [comment]
We are renaming the formulas to avoid problems when you have another version of the same package installed.

We recommend that you wait a few hours and that you previously remove these dependencies
```
brew uninstall --ignore-dependencies sip-qt5 pyqt-qt5 qscintilla2-qt5 pyqt5-webkit gdal postgis liblas
```

and then do
```
brew tap-pin osgeo/osgeo4mac
```

We regret the inconvenience, but we believe that it will be the best for the future.

We need to use our versions and that the user does not have another installed.

**Comment by fjperini** [comment]
@deg4uss3r Given that the process is too slow and unexpected problems arose, we will do so later.
We regret the moleesties, they can install everything as they came doing it.

**Comment by deg4uss3r** [comment]
Thanks for the update @fjperini

**Comment by fjperini** [comment]
@deg4uss3r generating the bottles, if you use flags you can install from the source.

**Comment by deg4uss3r** [comment]
@fjperini Installed! Thanks for looking into this. I did have a few errors to work around (linking `sip-qt5` and `pyqt-qt5`, and the known error of 'libintl.h' not found, but the fixes listed worked). 

Thanks!!!
