### ISSUE TITLE
osgearth failed to build on OS X 10.9.5

### ISSUE THREAD

**Issue by Azimoth** [OSGeo/homebrew-osgeo4mac#79]
I tried to install QGIS 2.6 via Homebrew and ran into an error during the install of osgEarth.
Since I have hardly any experience (yet), I don't know where to start to fix this problem.

The output of "brew gist-log" can be found here:
https://gist.github.com/anonymous/cec50bd1a5b78d1a0a54

Homebrew is updated && upgraded, Xcode as well as the CLT are also up to date.
So far I tried reinstalling "geos" and made sure open-scene-graph was built using "--with-qt".

Does anybody have an idea what might cause the problem or has seen this problem solved elsewhere?
Thanks in advance, any help would be appreciated.

**Comment by dakcarto** [comment]
Yes, this is an incompatibility between `osgearth` 2.5 or 2.6 with `open-scene-graph` 3.3.x.

The only solution right now, until `osgearth` is updated, is to install `qgsi-26` using the `--without-globe` option. I am working on updating the formula to make that the default.

I don't think it is worth trying to install a localized or keg-only copy of `open-scene-graph` 3.2.1 to fix this.

**Comment by Azimoth** [comment]
Thank you for your answer. On the upside: It was not only my lack of experience that prevented a successful install.
Is there a way to notice a non-installed formula (or the code that it's supposed to build) was updated, except for seeing it being listed when I run "brew update"?

**Comment by dakcarto** [comment]
> Is there a way to notice a non-installed formula (or the code that it's supposed to build) was updated, except for seeing it being listed when I run "brew update"?

No. You have to pay attention to that `brew update` output. This is the main drawback of Homebrew: having the latest versions for all formulae do not always work for all other formulae builds. Though it does help move development forward across all coding projects for Mac.

Also, note that `osgearth` is in [Homebrew/homebrew-science](https://github.com/Homebrew/homebrew-science) and the incompatibility with `open-scene-graph` should be reported there. I believe the current master branch version for `osgearth` will work with `open-scene-graph` 3.3.x.

**Comment by dakcarto** [comment]
Closing, as an upstream issue.
