### ISSUE TITLE
gdal-filegdb.rb tested on mavericks?

### ISSUE THREAD

**Issue by smnorris** [OSGeo/homebrew-osgeo4mac#8]
I don't see any reference to gcc version in gdal-filegdb.rb, but have no experience with Ruby or setup scripts - is this tested on Mavericks?

I've tried a few things to get filegdb api to work with homebrew gdal on Mavericks but haven't had any luck:

[esri forum](http://forums.arcgis.com/threads/95958-OS-X-Mavericks)
[stack exchage](http://gis.stackexchange.com/questions/81783/file-geodatabase-api-on-osx-mavericks-via-brewed-gdal)

**Comment by smnorris** [comment]
I've happily been using the OpenFileGDB for the past couple of years but now have the requirement to write to .gdb files. Rather than open up arcgis it would be nice to use ogr2ogr and the FileGDB driver. ESRI has updated the api (1.4) and there are now two files for Mac (clang and gcc) http://www.esri.com/apps/products/download/.  

Has anyone tried using these latest with homebrew on El Captain 10.11?

**Comment by smnorris** [comment]
I've just tried the 1.4 clang version and it seems to be fine so far.

Rather than update this formula, I just went back to the copy api files into `/usr/local/include` `/usr/local/lib` method noted (here)[http://blog.burhum.com/post/34851795066/installing-gdalogr-with-filegdb-support-on-osx].

I'd update the formula but learning ruby is out of scope for the moment :)

**Comment by dakcarto** [comment]
Closing as related to deprecated formulae. Reopen if necessary.

Try `gdal1-filegdb` or `gdal2-filegdb`.
