### ISSUE TITLE
qgis-26 fails to build on OS X 10.9.5

### ISSUE THREAD

**Issue by Azimoth** [OSGeo/homebrew-osgeo4mac#81]
After I learned that the only option to install QGIS 2.6 is to "--without-globe" I tried to do just that.
But even if "--without-globe" is the only option used, QGIS cannot be built correctly (it fails at annoying 97%). My experience still is rather limited, so, once again, I don't know how to fix this problem.

The output of "brew gist-logs" can be found here:
https://gist.github.com/anonymous/6b69762d2d9d45da251d

During the build-process, python "exits unexpectedly" (this is displayed in a separate window, not within the shell). I don't know why this happens nor whether it affects the build-process. 

Homebrew is updated && upgraded, Xcode as well as the CLT are also up to date.

Does anybody have an idea what might cause the problem or has seen this problem solved elsewhere?
Thanks in advance, any help would be appreciated.
__________________________________________
Edit:
What I found by looking through the gist-logs output was the following errors.
During the step labeled "[ 81%] Generating ui_frmEliminate.py":

Fatal Python error: Py_Initialize: unable to load the file system codec
ImportError: No module named 'encodings'

later on:

make[2]: *** [python/plugins/fTools/tools/ui_frmEliminate.py] Error 134
make[1]: *** [python/plugins/fTools/tools/CMakeFiles/fTools-tools.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

and finally:

[ 97%] Built target QGIS
make: *** [all] Error 2

I hope this helps a little…

**Comment by dakcarto** [comment]
@Azimoth Thanks for reporting.

I did not have this issue when updating the `qgis-26` formula and rebuilding the bottle for 10.9 (see 855ebca note: typo of qgis-24 in commit message).

Try `brew update` and `brew install qgis-26` (`--without-globe` is now default). Since you are on 10.9, it should just pull the bottle binary, unless you set other install options.

The `Fatal Python error: Py_Initialize: unable to load the file system codec` error usually indicates an [issue with having multiple Python packages installed](http://stackoverflow.com/questions/5694706) and a flaw in your build environment setup, e.g. wrong PYTHONPATH, etc. Do you have Python 3 installed, or some other Python 2, that you are referencing in your bash profile, etc.?

**Comment by Azimoth** [comment]
First of all: Thanks again for your help.
Yes, Python 3 is installed and I must admit I'm always a little confused when it comes to PYTHONPATH. Often when I set python3 first in PYTHONPATH (PYTHONPATH=python3:python), homebrew is complaining when a formula requires python. The other way round (PYTHONPATH=python:python3) seems to be just as "wrong" for other formulas. Which way is "better"? Or is there a way to dynamically set PYTHONPATH according to the version of python the formula requires?

**Comment by Azimoth** [comment]
First of all: Thanks again for your help.
Pouring the bottle worked. 

Regarding your question: Yes, Python3 is installed. And PYTHONPATH always has confused me: When it points to Python as many formulas seem to complain as do when it points to Python3 (and "unset PYTHONPATH" is recommended). 

Where should it point to? 
And is there a way to set this dynamically, depending on the version of Python required by a formula? (PYTHONPATH=python3:python did not work so far…)

**Comment by dakcarto** [comment]
Any environment variables you have statically set in a bash profile may be overridden or possibly screw up a build. It is recommended to start with a clean or specific profile when building formulae.

Generally, when I build Homebrew formulae, I have a specific environment that I load: [osgeo4mac.env](https://github.com/OSGeo/homebrew-osgeo4mac/blob/master/enviro/osgeo4mac.env). This in turn sources any custom ~/**.**osgeo4mac.env, where I set custom environment variables or override existing ones.

Formulae will generally manage things based upon what Python is found first on your PATH, or whether the formula in question requires a specific version of 2 or 3. You do have to be careful not to mix extra environment variables between [Python 2](https://docs.python.org/2/using/cmdline.html#environment-variables) or [Python 3](https://docs.python.org/3.4/using/cmdline.html#environment-variables).
