### ISSUE TITLE
formula_renames.json is invalid

### ISSUE THREAD

**Issue by smellman** [OSGeo/homebrew-osgeo4mac#839]
**Please answers the following**

I've... 
- I read
	- [x] the [reporting issues](https://github.com/OSGeo/homebrew-osgeo4mac/docs/reporting-issues)
	- [x] the [troubleshooting](https://github.com/OSGeo/homebrew-osgeo4mac/docs/troubleshooting)
- [x] I checked the documentation and found no answer
- [ ] I tried to install after following the suggestions
- [x] I am running the latest version (`brew update` twice?)
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I uploaded logs: `brew gist-logs formula`

**Describe the bug**

`formula_renames.json` is not invalid json and raise error now.

**To Reproduce**

1. `brew tap osgeo/osgeo4mac`
2. `brew upgrade`
3. See log

**Logs**

```
$ brew upgrade
Error: 784: unexpected token at '{
  "qgis3": "qgis",
  "qgis2": "qgis-ltr@2",
  "libkml-dev": "osgeo-libkml",
  "hdf4": "osgeo-hdf4",
  "gdal2": "osgeo-gdal",
}
'
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/json/common.rb:156:in `parse'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/json/common.rb:156:in `parse'
/usr/local/Homebrew/Library/Homebrew/tap.rb:554:in `formula_renames'
/usr/local/Homebrew/Library/Homebrew/formula.rb:406:in `oldname'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1161:in `migration_needed?'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1174:in `block in outdated_kegs'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1178:in `outdated_kegs'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1257:in `outdated?'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:67:in `block in upgrade'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:66:in `select'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:66:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

**Comment by fjperini** [comment]
@smellman fixed up. Thank you!
