### ISSUE TITLE
grass-70 on 10.10.2 build failure

### ISSUE THREAD

**Issue by retsofaj** [OSGeo/homebrew-osgeo4mac#86]
https://gist.github.com/1658e625a84e732c54c5

Unfortunately it doesn't seem like an "obvious" error:

> Errors in:
> /private/tmp/grass-7020150327-2423-bl6gxk/grass-7.0.0/gui/wxpython/iclass

I did reinstall `wxmac` and `wxpython` in the hope that it was a simple dependency problem. 

I am using virtualenv which might be part of the issue. Are there any best practices for using Grass in an environment where virtualenv is present?

Thanks for any suggestion on how to debug the error!

**Comment by dakcarto** [comment]
Hi, thanks for reporting!

Closing this issue. `grass-70` builds on 10.10 now. Reopen if you find this not to be the case.
