### ISSUE TITLE
QGIS Update to 2.8.1

### ISSUE THREAD

**Issue by pjduplooy** [OSGeo/homebrew-osgeo4mac#88]
Could QGIS be updated to 2.8.1 please?

Just built it on two boxes, using an adapted formula. Changed file name and sha1 in .rb.  Compiled flawlessly.

QGIS works perfectly for me. Although I havent compiled with --with-globe (globe compile fails everytime, but no hassle.  Grass64 and 7 is in, as well as orfeo.

I suppose there is not much difference between 2.8 and 2.8.1, so this might be pretty straight forward.

Cheers
Pieter

And by the way, thanks for keeping Mac GIS'ers happy with this subproject!! 

Thanks in advance

**Comment by jkopera** [comment]
Would also love this, as I rely heavily on QGIS and y'all's great work on the homebrew version.  Pain in the butt to run Kyngchaos's version.   Not ruby savvy so can't do a similar solution to above.  Let me know what I could do to help.

**Comment by dakcarto** [comment]
Thanks! Fixed in d0d87f5. Bottles to be added shortly.
