### ISSUE TITLE
qgis-28 bottle cannot find dylib

### ISSUE THREAD

**Issue by ozak** [OSGeo/homebrew-osgeo4mac#91]
Hi, 

after doing ``brew update && brew upgrade`` and then running ``brew install qgis-28`` without any errors I get the following error message

    yld: Library not loaded: /usr/local/lib/libproj.0.dylib
    Referenced from: /usr/local/opt/qgis-28/QGIS.app/Contents/MacOS/QGIS
    Reason: image not found

I have proj4-9-1 installed (after upgrade originally had 4.8). Searching the directory ``/usr/local/lib/``  I see that there are the following files

    /usr/local/lib/libproj.9.dylib /usr/local/lib/libproj.a       /usr/local/lib/libproj.dylib   /usr/local/lib/libproj.la

After renaming ``/usr/local/lib/libproj.9.dylib`` to ``/usr/local/lib/libproj.0.dylib`` it worked. Should I have built it from scratch for it to work directly? Any other way this could have been done?

**Comment by pjduplooy** [comment]
Hi ozak

If you look at my answer in the previous issue you would have seen that I had the same problem. I have built from source though.  It is the update to proj 4.9.1 that causes this.  However you shouldn't have renamed it (might break something in the future), but made a link using ln -sf.

Pieter

**Comment by ozak** [comment]
Sorry...actually what I meant was that I copied the file, not renamed it, otherwise obviously everything else could fail. Indeed it is basically the same solution you proposed.

**Comment by ozak** [comment]
In case anyone else has similar issues, see issue #90 
On another computer GDAl complained for a similar reason...same solution, cp or ln -sf the missing dylib.

Thanks Pieter.

**Comment by oeon** [comment]
Thank you @pjduplooy :+1: `ln -sf /usr/local/lib/libproj.9.dylib /usr/local/lib/libproj.0.dylib` fixed for me.
