### ISSUE TITLE
QGIS 2.8.2

### ISSUE THREAD

**Issue by pjduplooy** [OSGeo/homebrew-osgeo4mac#93]
Any news on 2.8.2?

Tried my previous trick where I changed the filename and checksum in the .rb, but the patch files did not want to patch the source code.

Pieter

**Comment by hollandjg** [comment]
I've opened a pull request (#97) to point the --head option for the qgis_28 to the release-2_8 branch (rather than master)

**Comment by dakcarto** [comment]
Thanks! Fixed in d0d87f5. Bottles to be added shortly.
