### ISSUE TITLE
A licence for a fork

### ISSUE THREAD

**Issue by kaukas** [OSGeo/homebrew-osgeo4mac#96]
Hello.

I was looking for a formula to install the Oracle Instant Client and found [yours](https://github.com/OSGeo/homebrew-osgeo4mac/blob/master/Formula/oracle-client-sdk.rb). Because the instant client can not be freely downloaded it takes a very interesting approach to require the user to cache the downloads.

I liked the formula very much since it solves the other problems besides downloads. However, the formula does not do everything I need.

I would like to use your code or at least ideas in my own project but your repository is licensed under GPL while I'd like to have it under MIT or BSD (not really good at licensing). Would that be a problem?

Thank you!

**Comment by dakcarto** [comment]
See #131

**Comment by nickrobison** [comment]
Closing this, as #131 switched the license to BSD.

**Comment by kaukas** [comment]
Thank you!
