### ISSUE TITLE
saga_gui: Library not loaded

### ISSUE THREAD

**Issue by perrygeo** [OSGeo/homebrew-osgeo4mac#99]
I just installed `saga-gis` and get this error

```
$ saga_gui
dyld: Library not loaded: /usr/local/lib/libhpdf-2.2.1.dylib
  Referenced from: /usr/local/bin/saga_gui
  Reason: image not found
Trace/BPT trap: 5
```

Ideas to fix?

**Comment by pjduplooy** [comment]
Hi do a search on your machine like so (yoy need to be in root directory) 
cd /
sudo find . -name libhpdf*.dylib

link that file in /usr/local/lib to libhpdf-2.2.1.dylib

Hope this helps

**Comment by perrygeo** [comment]
That did the trick. The command, for reference:
```
sudo ln -s /usr/local/Cellar/libharu/2.2.1_1/lib/libhpdf-2.2.1.dylib /usr/local/lib/libhpdf-2.2.1.dylib
```
Any idea why this doesn't work out of the box?
