### ISSUE TITLE
qgis mismatch with proj 6.0.0

### ISSUE THREAD

**Issue by jonathanmccormack** [OSGeo/homebrew-osgeo4mac#997]
The bottled version of qgis is linked to proj 5.2.0 (libproj.13.dylib), but both proj and osgeo-proj are now at 6.0.0 (libproj.15.dylib).  After upgrading proj, libspatialite, and others, the bottled QGIS crashes:

```
Dyld Error Message:
  Library not loaded: /usr/local/opt/proj/lib/libproj.13.dylib
  Referenced from: /usr/local/Cellar/qgis/3.6.0_4/QGIS.app/Contents/MacOS/QGIS
  Reason: image not found
```

It may be as simple as triggering a rebuild of the bottle, as it looks like qgis has not be updated in 3 weeks.

**Comment by fjperini** [comment]
Hi Jona!

Creates a link temporarily, we are working to solve a problem with the hosting of the bottles.
Once solved this I will apply all the missing updates.

`ln -s libproj.15.dylib libproj.13.dylib`

I regret the inconveniences, working to make everything simpler in the future.

**Comment by fjperini** [comment]
we are working to migrate the bottles to osgeo, bintray already caused many problems.

**Comment by fjperini** [comment]
I have already built qgis on my machine, I just need to fix something in orfeo. Later I apply all the changes.
![Captura de Pantalla 2019-03-31 a la(s) 12 16 04](https://user-images.githubusercontent.com/21315242/55292646-c0ce8980-53c3-11e9-838f-6a854f252f9b.png)

**Comment by fjperini** [comment]
@jonathanmccormack the bottles for qgis are ready!

**Comment by Notoncebut2x** [comment]
Not sure if this is a related issue but I am now getting the error:  

```
Dyld Error Message:
  Library not loaded: /usr/local/opt/osgeo-proj/lib/libproj.15.dylib
  Referenced from: /usr/local/Cellar/osgeo-qgis/3.6.2/QGIS.app/Contents/MacOS/QGIS
  Reason: image not found
```

**Comment by fjperini** [comment]
@Notoncebut2x we are updating all the formulas, in some hours `osgeo-qgis` will be updated.

**Comment by danVnest** [comment]
I initially had the above error, followed the linking instructions above, and am now getting the following error:
`dyld: Library not loaded: /usr/local/opt/osgeo-proj/lib/libproj.15.dylib
  Referenced from: /usr/local/opt/osgeo-qgis/QGIS.app/Contents/MacOS/QGIS
  Reason: Incompatible library version: QGIS requires version 16.0.0 or later, but libproj.15.dylib provides version 15.0.0
/usr/local/opt/osgeo-qgis/bin/osgeo-qgis: line 21: 80256 Abort trap: 6           /usr/local/opt/osgeo-qgis/QGIS.app/Contents/MacOS/QGIS "$@"`

Any advice?

**Comment by fjperini** [comment]
@danVnest we are updating the formulas, in a few hours I will update `osgeo-qgis`.
